### ISSUE TITLE
Update : 20151021 

### ISSUE THREAD

**Issue by duckietm** [ccrisan/motioneyeos#10]
Hello,

When i go to the MotionEyeos and hit Software Update <CHECK> i do not get the update ......
It keeps saying : motionEye is up to date (current version:: 20151011)

**Comment by ccrisan** [comment]
Have you enabled prereleases in Expert Settings? The motionEyeOS image is still a pre-release as it needs to be tested.

**Comment by duckietm** [comment]
That solved it, Nice : PreRelase on +1:
