### ISSUE TITLE
Orange Pi IOT Support Coming?

### ISSUE THREAD

**Issue by kiteboy** [ccrisan/motioneyeos#1000]
Hi...would love to see support for the orange pi with the sim capability.....would be great for low cost remote cameras able to ftp files to a server.

**Comment by rkarlsba** [comment]
So would I. I have a few orange pi zero boards. I tried the raspbian for raspi zero, but no luck. Any idea if this will be supported at some time?

**Comment by rradar** [comment]
**orange pi one** is already supported with the newest release. Should not be a real problem now to support all other H3 (or H2+) based orange pi boards.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-motioneyeos-be-ported-to-insert-your-board-here
