### ISSUE TITLE
no system access per ssh only sdcard and storage

### ISSUE THREAD

**Issue by TheKitro** [ccrisan/motioneyeos#1001]
Hi 
I try to access the watch.conf file and the /home folder on the motioneye per ssh.
But I can only see the folders sdcard an storage. 
I know in the last months I was able to access the whole foldersystem.

How can I access it again?

**Comment by ccrisan** [comment]
You're probably accessing it using ftp instead of ssh.

**Comment by huvarda** [comment]
Are you using samba/ftp?

**Comment by jasaw** [comment]
No response from OP, closing issue.
