### ISSUE TITLE
After update 20170611

### ISSUE THREAD

**Issue by duckietm** [ccrisan/motioneyeos#1005]
Hello,

After updated the motioneyeos to 20170611 it keeps saying that there is an update avalible : 20170611
When i install the update i see that the version hasn't changed : 

motionEye Version 0.36 
Motion Version 4.0.1+git37b3595 
OS Version motionEyeOS 20170610

Looks like a small bug :)

**Comment by ccrisan** [comment]
It's a small bug in the version string. It'll go away with the stable release :) Sorry about that.

**Comment by duckietm** [comment]
Nice thanks !
