### ISSUE TITLE
No more pictures are send by email after a few days

### ISSUE THREAD

**Issue by azu19** [ccrisan/motioneyeos#1007]
I have installed motionseye os on raspberry pi 2 3 and 0 and have always the same issue. At the begining everything works fine but  after a few days , I still receive the email motion notification but no picture with the email.

**Comment by ccrisan** [comment]
After a while, the media directory has too many media files and they can't be parsed within a reasonable time. Make sure to configure your system so that it removes old pictures after a short while.
