### ISSUE TITLE
E-Mail notification with holdoff time

### ISSUE THREAD

**Issue by netding** [ccrisan/motioneyeos#1008]
Thank you verry much for this great sofware. I run motionEyeOS on a Raspberry Zero W - it works nearly perfect!
There is only one fuction I am slightly missing or I did not find the right settings:

I want motionEyeOS to send me an E-Mail motion notification for example to inform me when my cat has returned in my house. So, I only want to have an email with a picture of my cat entering the room. The following 60 minutes I am not interestest anymore in any detected motion.

Is it possible to set a holdoff time before a next motion event and hence a notification email will be triggered?
If I set "Motion Gap" to e.g. 3600 s a motion event will be at least 3600 s = 1 h long. But emails are triggert repeatedly during this time if any momentary motion is detected.

Is there any setting, where an email is only triggered at the start of a new motion event?
Or is there any other work around settings to make motionEyeOS send me a maximum of only one email per hour?

Thanks again for this great work!

**Comment by ccrisan** [comment]
I don't think that is possible with the currently available motion options. Sorry.
