### ISSUE TITLE
Cannot use SSD disk

### ISSUE THREAD

**Issue by rjalexa** [ccrisan/motioneyeos#101]
Dear friends,
I have connected a 120GB SSD disk to my RPi2 USB port and created one partition with an ext4 filesystem on it.

The disk appears to be recognized and defined as /dev/sda and the /dev/sda1 partition is found as mounted by the df command twice:
/dev/sda1 /data/media/sda1
/dev/sda1 /home/ftp/storage/sda1

but when I select sda1 as the storage in the configuration panel I get an error and it is not used.

I see the following error in the console messages:

EXT4-fs (sda1) couldn't mount as ext2 dur to feature incompatibilities

What can I do to fix this ? Thank you.

**Comment by ccrisan** [comment]
You can ignore that warning.
