### ISSUE TITLE
Android app unavaliable in Brazil

### ISSUE THREAD

**Issue by hpicelli** [ccrisan/motioneyeos#1014]
Hi there.
I can't install the android app, in my country it is unavaliable.
But, i can install directly the .APK.
What version is the latest?
Best regards,
Henrique
![screenshot from 2017-06-29 10-43-00](https://user-images.githubusercontent.com/3333923/27690470-ca00806c-5cb7-11e7-8762-065d27ac3dad.png)

**Comment by ccrisan** [comment]
We don't have an android APK.

**Comment by hpicelli** [comment]
Thanx. I guessed tha have a client.
![screenshot from 2017-06-29 15-44-39](https://user-images.githubusercontent.com/3333923/27704754-01944b92-5ce2-11e7-9765-7864f268ac3d.png)

**Comment by Garskecom** [comment]
Hi! We've made a completely new version - Please search for MotionEyeOS on the App Store again to find it.
