### ISSUE TITLE
Camera stopping. "Unable to open video device).

### ISSUE THREAD

**Issue by hpicelli** [ccrisan/motioneyeos#1015]
Hi there,
My camera is losing signal several times (+-2 times per minute).
Happening only to Camera2 (Microsoft VX-1000). Camera1 (Microsoft VX-500) is ok.
Can someone help me?
Best regards,
Henrique

![screenshot from 2017-06-29 15-35-11](https://user-images.githubusercontent.com/3333923/27704348-be8074bc-5ce0-11e7-95dd-fa36a42c4199.png)

**Comment by ccrisan** [comment]
It might be a power issue, a bad camera/driver issue, a USB bandwidth limitation or some other kind of hardware fault. In any case, there's nothing motionEyeOS can do to fix it.
