### ISSUE TITLE
Encryption issue 

### ISSUE THREAD

**Issue by ben19871987** [ccrisan/motioneyeos#102]
Dear 
Thank you for answering my last question. I have problem with local encryption of data frame of video stream. I am going to encrypt each JPEG with asymmetric key and digital signature but how can I do that? Should I work on stream.py?
Thanks

**Comment by ccrisan** [comment]
I don't think that's going to be possible with motionEye. At least I wouldn't know how to implement it.

**Comment by ben19871987** [comment]
thanks dear
