### ISSUE TITLE
Record in Grayscale?

### ISSUE THREAD

**Issue by TheAmazingJarvis** [ccrisan/motioneyeos#1020]
I'm wondering if it's possible to switch a camera to black and white (grayscale)?

I'm using the NoIR Picam with IR illumination so all the color data is useless to me anyway. I would also think black and white images are smaller easier of the Pi too.

I thought it might be in the "Extra Motion Options" under "Video Device" but I'm not finding any info in the Motion documentation or here.

**Comment by ccrisan** [comment]
This is not something that can be done with motionEye(OS) and nor with motion I think. Also it wouldn't make any significant performance change.
