### ISSUE TITLE
1080 video is cropped

### ISSUE THREAD

**Issue by livium2000** [ccrisan/motioneyeos#1023]
Hello. First congratulations for your work. The software is stunning. I have a little problem. Just bought the Noir V2 camera and everything works perfect out of the box except de 1920x1080 resolution. I have o huge crop on the image. 
I've put 2 images here : 
http://s.go.ro/3exk21jf
 First is 1600x1200 px, second is 1920x1080.
Can I fix that?
Thanks.

**Comment by ccrisan** [comment]
This might be related to the video mode vs stills mode that is specific to the Raspberry Pi camera module. I honestly don't know how to fix that.

**Comment by livium2000** [comment]
Thanks, No problem. 1600x1200 it's perfect.
