### ISSUE TITLE
Can't change hostname

### ISSUE THREAD

**Issue by phibes4000** [ccrisan/motioneyeos#103]
I have tried setting at /etc/hostname, /data/etc/hostname, via the hostname command, and the hosts file (per board/common/overlay/etc/init.d/S01hostname) but cannot get the change to survive a reboot.  It defaults back to "$os_prefix-$board_sn".  Am I missing something?

**Comment by ccrisan** [comment]
Hostname is not yes changeable. It will be soon, though.

**Comment by Arut42** [comment]
Thats easy, login with ssh and write the folowing:

echo "hostname" > /data/etc/hostname
mount -o remount -w /dev/root /
mv /etc/init.d/S01hostname /etc/init.d/S05hostname
mv /etc/init.d/S13mountall /etc/init.d/S01mountall 
sync
reboot

The problem is, set hostname before mount
/etc/init.d/S01hostname

sys_hostname_file="/etc/hostname" -> not mount, can't find file
hostname_file="/data/etc/hostname" -> not mount, can't find file

test -n "$os_version" || source /etc/init.d/base -> default maye-serial

case "$1" in
    start)
        msg_begin "Setting hostname"

        if [ -f $hostname_file ]; then -> file not found
            hostname=$(cat $hostname_file)
        elif [ -f $sys_hostname_file ]; then -> file not found
            hostname=$(cat $sys_hostname_file)
        else
            hostname="$os_prefix-$board_sn" -> default
        fi
        /bin/hostname $hostname
        echo "127.0.0.1 localhost $hostname" > /etc/hosts

**Comment by birukun** [comment]
Arut42 I tried that on my implementation but the root file system is locked so it did not stay persistent.  I believe it will be possible to do if you mount the filesystem elsewhere read/write and make the modification.  I have not tried that yet, playing with the dozens of other fun features first :-)

**Comment by Arut42** [comment]
this command remount writeable:

mount -o remount -w /dev/root /

don't forget space between /dev/root   and  /

best regards

Am 09.01.2016 um 04:54 schrieb birukun:

**Comment by ccrisan** [comment]
This procedure won't be needed anymore starting with 20160109; you will only have to create the file `/data/etc/hostname` containing your desired hostname and reboot.

**Comment by ccrisan** [comment]
I've just committed the changes required to allow setting a custom hostname from the UI. The feature will be available in the next release.

**Comment by joshhighet** [comment]
Hey @ccrisan , Thanks for all the work you have done on Motioneye, a great accomplishment. How exactly do I change the hostname over the UI?

**Comment by ccrisan** [comment]
@joshhighet Settings Menu -> General Settings > Hostname.

**Comment by ugoi** [comment]
What is the default hostname?

This doesnt work:

ssh pi@raspberrypi.local 

ping raspberrypi.local

**Comment by starbasessd** [comment]
The default hostname is meye-xxxxxxx with the xxxxxxx replaced by the last 8 characters of the CPU serial number. You can get the serial number via the command: 
> cat /proc/cpuinfo

but if you don't have a way to ssh in, or cannot connect a monitor and keyboard, you'll have to use a full raspberry pi os install to get it to respond to the ssh command you referenced, and then get it.

**Comment by starbasessd** [comment]
You could look on your router/modem to see what IP address was issued to the Pi (RPis mac addresses begin):
![Capture](https://github.com/motioneye-project/motioneyeos/assets/20134429/ada3d021-e2e7-4f04-9f2d-9d34547abd2c)
