### ISSUE TITLE
problem with wifi

### ISSUE THREAD

**Issue by jimujcic** [ccrisan/motioneyeos#1030]
I am having trouble getting the motion pi wifi to work.  Whats the best way to troubleshoot for problems with the motioneye if its not connecting.  I've reinstalled motioneye OS, tried a different raspberry pi and tried a different wifi usp.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems

**Comment by jasaw** [comment]
@jimujcic Did you manage to solve your wifi problem?

**Comment by jasaw** [comment]
No follow up, closing issue for now.
