### ISSUE TITLE
Ungrouped pictures

### ISSUE THREAD

**Issue by ginslo** [ccrisan/motioneyeos#1035]
System is auto-creating dated folders like this by design: 
`/home/ftp/sdcard/Camera1/2017-07-17/`

My video files are being written there but the still images are ending up ungrouped one level up here: 
`/home/ftp/sdcard/Camera1/`

This did not occur when first installed so it is the result of changes I made but I cannot figure out how to get it working again. Please point me in the right direction to get both videos and stills in the same dated folder. Thanks.

**Comment by ccrisan** [comment]
You have separate filename patterns for still images and movies. Make sure both of them have identical (or similar) patterns. More precisely, set *Still Images/Image File Name* as well as *Movies/Movie File Name* to e.g. `%Y-%m-%d/%H-%M-%S`.
