### ISSUE TITLE
Set static IP on existing installation

### ISSUE THREAD

**Issue by synaesthesiac** [ccrisan/motioneyeos#1036]
On an existing installation using the provided image, is it possible to change the LAN ip address to a static address? Would rather avoid reimaging as it's difficult to get physical access. Reason: WiFi used to access the device, LAN used to directly connect to the camera.

**Comment by jasaw** [comment]
Assign static IP to your MAC address at your DHCP server?

**Comment by synaesthesiac** [comment]
When I said LAN used directly connected to the camera, I mean pi > LAN cable > camera. There is no DHCP server.

**Comment by ccrisan** [comment]
What's wrong with setting a static IP from the settings panel, in the *Network* section?

**Comment by synaesthesiac** [comment]
Because that is only relevant for the wireless which is used for the management. I see nothing there for the LAN when WiFi is in use.

**Comment by ccrisan** [comment]
Unfortunately motionEyeOS doesn't work that way. It expects only one network connection. If you happen to also plug in the ethernet cable, it will start a DHCP server on that interface but the static IP address is used only once, for the first network interface it detects (wlan0, eth0, in this order). If you need fancier network setups, please use motionEye on top of a general purpose Linux distro.
