### ISSUE TITLE
Change wpa_supplicant.conf line ending automatically

### ISSUE THREAD

**Issue by jasaw** [ccrisan/motioneyeos#1037]
To avoid line ending issues caused by user error, it would be nice to change to Unix line ending automatically.
One idea is to put /boot/wpa_supplicant.conf file through dos2unix when generating the /data/etc/wpa_supplicant.conf file.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/thingos/commit/8556a04e97fd164b30c7aa0acc77e5ca429251de should fix wpa_supplicant.conf files created in Windows.
