### ISSUE TITLE
motioneyeOS does not reassign a camera id

### ISSUE THREAD

**Issue by thibmaek** [ccrisan/motioneyeos#1039]
I changed settings for username/passwords, my Pi (B+) rebooted and when I wanted to up the resolution for my generic USB cam, motioneyeos didn't assign a camera id when I changed to name.

Reboot or re-adding the camera doesn't reassign the ID to the camera.

![image](https://user-images.githubusercontent.com/6213695/28323759-fb33d7a2-6bd9-11e7-852e-ed08c1d86216.png)

**Comment by ccrisan** [comment]
Clear the browser cache and refresh.
