### ISSUE TITLE
How to change the network hostname

### ISSUE THREAD

**Issue by fredericcollin** [ccrisan/motioneyeos#104]
Hi, I have several Motioneye pi's on my network and have a hard time distinguishing them with their default names such as MEYE-A8AE5E340, etc...How can I rename them to something more intuitive such as 'entrance', 'garage', etc...?
Thanks in advance!

**Comment by phibes4000** [comment]
Nothing to do with SSID.  It's the hostname.  I asked the same question 12m prior - https://github.com/ccrisan/motioneyeos/issues/103.

**Comment by fredericcollin** [comment]
Hi phibes4000, of course you are correct! I do indeed mean 'hostname', thanks.

**Comment by ccrisan** [comment]
Hostname is not yes changeable. It will be soon, though.

**Comment by fredericcollin** [comment]
Thank you for your kind reply Crisan, looking forward to it!

**Comment by ccrisan** [comment]
I've just committed the changes required to allow setting a custom hostname from the UI. The feature will be available in the next release.

**Comment by fredericcollin** [comment]
Excellent, thanks!

On Feb 21, 2016 8:53 PM, Calin Crisan <notifications@github.com> wrote:
I've just committed the changes required to allow setting a custom hostname from the UI. The feature will be available in the next release.

---

**Comment by ioquatix** [comment]
How do you do this?

**Comment by ccrisan** [comment]
@ioquatix in Expert Settings you have a Hostname setting.

**Comment by alexxtasi** [comment]
Based on https://github.com/ccrisan/motioneyeos/issues/103#issuecomment-247540487 and my little experience, I  think it's:
_Settings Menu -> General Settings > Hostname_

**Comment by ioquatix** [comment]
Oh, that's awesome!
