### ISSUE TITLE
Snapshot zero length file

### ISSUE THREAD

**Issue by elyobelyob** [ccrisan/motioneyeos#1041]
Hi, am using the snapshot facility which works fine mostly. However, if no-one is logged into the admin area it returns a zero length file after a while. As soon as I log back into the admin area, it works again. 

This is using the method ... http://192.168.0.204/picture/1/current/?_username=admin&_signature=xxxxxxxxx

**Comment by ccrisan** [comment]
What version?

**Comment by elyobelyob** [comment]
motionEye Version | 0.35.2
Motion Version | 4.0.1+git37b3595
OS Version | motionEyeOS 20170329

Just noticed a new version. Updating now, just in case this was fixed in an earlier version.

**Comment by ccrisan** [comment]
Fixed in 0.36, latest motionEyeOS version.
