### ISSUE TITLE
Port forwarding loses title bar and footer bar overlays

### ISSUE THREAD

**Issue by websitefreedom** [ccrisan/motioneyeos#1042]
I'm using motioneyesos with motion settings on RPi zero wireless and love it - thanks! :-)

Accessing via my LAN works fine. I get the title and footer bar overlays with buttons etc...
![port-forwarded](https://user-images.githubusercontent.com/6287274/28377322-4f0a666e-6ca4-11e7-8a7d-e3c63062ed9b.jpg)
Setting up port forwarding, I log in and find I get the video stream but without title or footer bar overlays so I can't view stored pictures or movies...
![lan](https://user-images.githubusercontent.com/6287274/28377355-61dfe980-6ca4-11e7-9ac2-95bd09dc8e58.jpg)

Is there a way of seeing the title and footer overlays via port forwarding?

**Comment by ccrisan** [comment]
Forward port 80 instead of 8081 or whatever you forwarded.

**Comment by websitefreedom** [comment]
Okay thanks :-)
