### ISSUE TITLE
Need to be able to install pantilthat software 

### ISSUE THREAD

**Issue by guitarjhk** [ccrisan/motioneyeos#1045]
I have allready tryed a normal rasbian OS and add the Motioneye packet - that works - but the actions button dont work with python script - if I run the python script from ssh - it works fine
I know that actions button works if I follow the sample - but call python it dont work - I then notice that in MotioneyeOs - it is possible to call python - but the modul is not install and the install process call "apt-get" ect. that don't work - so guess only way is ask if the pantilthat software can bee install into the os from build ????
thanks in advance 

John

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives.

Python works perfectly on Raspbian.
