### ISSUE TITLE
Only few options for IP Cams via rtsp

### ISSUE THREAD

**Issue by sleepycats** [ccrisan/motioneyeos#1048]
Hello,

I can see only a few option for my IP CAM connected via rtsp. 
How can I switch on details like resoltion.

Thanks for your help in advance?

![image](https://user-images.githubusercontent.com/30460912/28609502-3c8eccc8-71e5-11e7-8093-71641f71fb1a.png)

**Comment by ccrisan** [comment]
Enable Advanced Settings.
