### ISSUE TITLE
RTMP stream!

### ISSUE THREAD

**Issue by Ohem** [ccrisan/motioneyeos#1054]
Hi!

I wonder if you could possibly replace the "fast jpeg streamer" with RTMP, I noticed you when I searched you couldn't implement it as you're dependent on motion.

But I thought why not have a separate process with VLC and output an RTMP stream? You've already stated that the JPEG streamer disables all surveillance features when running so you might as well replace it with RTMP.

There's NGINX webserver with RTMP module where you can grab the stream from, https://github.com/arut/nginx-rtmp-module (I tried this with OBS Studio in my local network and worked well, with small delay)

https://www.jpsaman.org/vlc/rtmp

Maybe try outputting to ogg? https://ipcamtalk.com/threads/how-to-use-vlc-to-transcode-ip-video-to-an-html5-compatible-format.1371/

**Comment by ccrisan** [comment]
That wouldn't be easy becuase of the way many things in motionEye rely on JPEG frames. I'm not saying it's impossible but it's not something I'm willing to take care of anytime soon. Pull requests are welcomed, though :)
