### ISSUE TITLE
Hello! I need your help...

### ISSUE THREAD

**Issue by misson112** [ccrisan/motioneyeos#1062]
![image](https://user-images.githubusercontent.com/30837273/29078640-ed2e5b60-7c95-11e7-9186-ed3f4c19ca04.png)

On motionEYE OS, I want a use Odroid Xu4 board with multiple camera system.

All camera was recognized but like a image, three camera was not working. Just only one camera was worked.

![image](https://user-images.githubusercontent.com/30837273/29078904-a92d5bb8-7c96-11e7-9acd-41476a5e6378.png)

What is error capturing first image?

How can I solve this problem?

Note that this system can works in raspberry pie3 with too slow FPS.

**Comment by jasaw** [comment]
After reading through motion source code, I can tell you that "Error capturing first image" means motion is unable to get any image from the camera, not a single image.

Those cameras with errors, what are they? network cameras? USB cameras? Could be a driver issue.

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
