### ISSUE TITLE
motioneyeos not detecting camera

### ISSUE THREAD

**Issue by emilioaray** [ccrisan/motioneyeos#1068]
I have  Install in Raspberry pi3 camera device: 
/dev/v4l/by-id/usb-Microsoft_Microsoft®_LifeCam_Studio_TM_-video-index0
and

Works properly for a period of time and then disconnects and stops working not recognizing the system.

You should remotely delete the camera and add it again to watch the video.

**Comment by jasaw** [comment]
Can you please attach log files?

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
