### ISSUE TITLE
Edit motioneye.conf

### ISSUE THREAD

**Issue by Thannor9435** [ccrisan/motioneyeos#1069]
I need to edit the file in order to change the media path, but even with chmod, root and both it says that is a read only file.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file

**Comment by ccrisan** [comment]
See also https://github.com/ccrisan/motioneyeos/wiki/motioneye.conf
