### ISSUE TITLE
Setup without Ethernet

### ISSUE THREAD

**Issue by bkorjonen** [ccrisan/motioneyeos#1073]
I want to run this on a Pi ZeroW. All setup done so far, but I do not have an Ethernet - only WiFi.

Which file(s) need to be modified and how to make it work?

Thanks

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-%28Plus%29-And-Zero

**Comment by NISALSILVA** [comment]
can i use this same link for raspberry pi 3 ? Same i need to connect over wifi 

Thanks .

**Comment by jasaw** [comment]
@NISALSILVA Yes, you can follow the same steps to pre-configure wifi on your pi3.
