### ISSUE TITLE
aPlay doesn't play sound

### ISSUE THREAD

**Issue by huvarda** [ccrisan/motioneyeos#1074]
When I run the aplay command it makes a static sound but no audio. How can I fix this?

**Comment by ccrisan** [comment]
What hardware? What version? What does your command look like?

**Comment by huvarda** [comment]
my command is "aplay sound.mp3" I am using a raspberry pi 3 and I am using motioneyeos-raspberrypi3-20170710.img

**Comment by huvarda** [comment]
I changed the extension to .wav but it didn't seem to do anything.

**Comment by ccrisan** [comment]
Aplay doesn't play mp3s. Convert your mp3 to wav (don't just change the extension).
