### ISSUE TITLE
Not booting after reinstall

### ISSUE THREAD

**Issue by Doctor-Propane** [ccrisan/motioneyeos#1076]
My last installation crashed and became corrupt after an update. I formatted the SD card using SDFormatter, downloaded the image from https://github.com/ccrisan/motioneyeos/releases, changed the extension from .gz to .img and loaded it to the SD card using Win32 Disk Imager.

While connected to a monitor, the raspberry pi does not boot. The lights are solid red and solid green, which looks like its not reading the SD card. I've used multiple cards and cards that were previously working with Raspbian. 

Am I missing a step here?

**Comment by ccrisan** [comment]
Properly extract the image, don't just change the file extension.
