### ISSUE TITLE
Motion Die Not Wirkung correctly in version   20170710

### ISSUE THREAD

**Issue by ssandel** [ccrisan/motioneyeos#1077]
Hi i got 2 Pi Zero w boards both worked well  with previous versions.
Since

motionEye Version | 0.36.1
-- | --
Motion Version | 4.0.1+git37b3595
OS Version | motionEyeOS 20170710

Motion ist not Well captured ....with Auto noise detection nothing happend.
Sincerely
Sandra

**Comment by ccrisan** [comment]
Your issue doesn't make sense. Please use only English words and clearly state your problem.

**Comment by jasaw** [comment]
Please describe the problem you're having. Provide log files if you can.
Without any information provided, I suggest you re-flash your microSD cards with the latest MotionEyeOS image.

**Comment by jasaw** [comment]
Closing issue due to lack of follow up from issue author.
