### ISSUE TITLE
SNMP

### ISSUE THREAD

**Issue by Zorbadil** [ccrisan/motioneyeos#1078]
Would it be possible to include snmpd in the next build?  I'd like to incorporate my cameras in my Observium system to monitor processor occupancy and network usage if possible.

**Comment by ccrisan** [comment]
Given the very limited cases where SNMP is actually useful with motionEyeOS and given that I'm trying to keep the size of the OS image as small as possible, the answer is no.

However you can fork motionEyeOS and [build](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) your own version, or you can use Raspbian + motionEye, if you want to install various other packages.
