### ISSUE TITLE
Reduce bcm2835-v4l2 max_video_width and max_video_height to reclaim some memory

### ISSUE THREAD

**Issue by jasaw** [ccrisan/motioneyeos#1080]
On a Raspberry Pi, there is no point in setting high max_video_width and max_video_height because it's not capable of encoding, or storing, or transferring via network 2592 x 1944 resolution video at high frame rate.

Reduce the default max_video_width and max_video_height to reduce GPU memory usage so more RAM can be allocated to CPU to reduce the OOM events.

Consider making this a config option?

Edit: My initial tests suggest quite a lot of RAM can be reclaimed with a more sensible default.

**Comment by ccrisan** [comment]
As far as I remember, those settings (also) affect the captured region. In stills mode the captured region is (used to be) smaller. If that's not (no longer) the case, I'm more than happy to remove them.

**Comment by jasaw** [comment]
I'm not sure if the captured region has changed recently.

From my observations, by setting max_video_width=1920 max_video_height=1200, we can save slightly more than 20MB of GPU memory at various resolutions. That is a lot of memory for devices with 512MB or less RAM.

Is it worth making this into a config item?

**Comment by ccrisan** [comment]
I believe it's safe to limit them to 1920x1080 or similar. That's a fairly high resolution for motionEye on a Raspberry PI :)

**Comment by jasaw** [comment]
merged.
