### ISSUE TITLE
Can only see 'today' images

### ISSUE THREAD

**Issue by AVSut** [ccrisan/motioneyeos#1081]
I have installed the 20170710 code on a Raspberry Pi ZeroW.  It works, including the wifi, but I only see one day of pictures in the browser.  If I delete all of those pictures then suddenly the next day can be seen.
Not sure if this is a bug or a feature not enabled correctly.  I am following the screen shots here: http://www.raspberrypi-spy.co.uk/2017/04/raspberry-pi-cctv-camera-with-motioneyeos/ that show that you can move backwards and forwards through various days.

**Comment by ccrisan** [comment]
What is your *Still Images > Image File Name* option set to?

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
