### ISSUE TITLE
Mail's picture problem .

### ISSUE THREAD

**Issue by Nico53220** [ccrisan/motioneyeos#1087]
It's me again, 
4 hours ago when a motion was detected i received some pictures with the different motions on it . But now i still received mail but without pictures, it's a bit troublesome :(
 
Thanks for your help :-)

**Comment by ccrisan** [comment]
It's a known problem. See https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails. There's a pending fix, but until then, just make sure your motionEyeOS doesn't have to deal with too many media files (by cleaning them regularly).

**Comment by Nico53220** [comment]
Thank you very much 😉
