### ISSUE TITLE
wifi extender as well?

### ISSUE THREAD

**Issue by tazboys** [ccrisan/motioneyeos#1092]
hi, i have wifi module on my pi so wondering if I can use the wifi as well as broadcasting another wifi to extend my wifi range in home? 

thanks,

**Comment by huvarda** [comment]
This question is unrelated to motioneyeos.  Sorry, I can't help you.

**Comment by ccrisan** [comment]
This is not possible with motionEyeOS. I recommend using Raspbian + a secondary wifi adapter.
