### ISSUE TITLE
Raspberry Pi release of 20170711 is not an img file

### ISSUE THREAD

**Issue by cyclingrocks** [ccrisan/motioneyeos#1098]
Downloaded the motioneyeos-raspberrypi-20170710.img.gz file and tried to unzip with 7-zip, but there isn't an image file in this package. I've downloaded the update before (June 2017) but would like the updated version. Thanks.

**Comment by ccrisan** [comment]
The OS image is there and is a valid image. Your 7-zip may not know about gzip.
