### ISSUE TITLE
N00b Request - Disable Camera Module LED

### ISSUE THREAD

**Issue by mehtaman** [ccrisan/motioneyeos#110]
Hi,

I am new to the Linux scene, I've setup MotionEyeOS in my RPi2B using the Rasp. Camera Module.

All is working well (Thanks to a fantastic OS) but I would like to disable the LED so I can place the camera near my front door without people knowing it's there. 

Is there a command I can run over SSH to disable the LED?

Thanks in advance!

**Comment by Mikiya83** [comment]
Hi
If it's an official Pi camera, look in the advanced settings, there is a toggle to disable LED.

**Comment by mehtaman** [comment]
Thanks you Mikiya83!!!

**Comment by Colbey** [comment]
I have an official Pi NoIR camera and do not have this option in advanced. I used to have in on motionPi but not since upgrading to motionEyeOs. is there something wrong with my config or is the Pi NoIR camera handled differently in this new version?

**Comment by jaytay79** [comment]
@Colbey, did you restore a motionpi config file onto motioneye? I had the same situation as you when I tried this so wiped it and started afresh.

**Comment by bortek** [comment]
This is what I do when I do not want to see lights coming from LEDs either on Pi itself or on Pi camera. Take a small peace of kids playing clay or a chewing gum and put it on the LED. Done.
