### ISSUE TITLE
Notification email failed: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by sol4ris33** [ccrisan/motioneyeos#1100]
Hello,

I'm french so sorry for my bad english....
Since i've installed last motioneyeos version (20170710) last week, i can't make email notification working anymore!
It worked like a charm with the previous version!

I configured it like with the previous version, and it do not work anymore :-(

My configuration:

**Email Addresses**
my.email@gmail.com
**SMTP Server**
smtp.gmail.com
**SMTP Port**
587
**SMTP Account**
my.email@gmail.com
**SMTP Password**
_The 16-chars passwd google gave me at https://myaccount.google.com/apppasswords_
**From Address**
_Empty_
**Use TLS** 
_ON_

**CASE 1:**
- When i click on TEST EMAIL i've the error message:
**## _Notification email failed: [Errno -3] Temporary failure in name resolution_**

I've checked all the topic about this issue before posting here, but nothing worked :-(
I repeat that it worked like a charm with previous version with the same email.
I tried to reset the smtp google password, but nothing changed...

**CASE 2:**
- In the **Network** settings, i have DNS Server to _8.8.8.8_
When i set this address to my router i've another message:
**_Notification email failed: [Errno 97] Address family not supported by protocol_**

**Thanks a lot** for your precious help...!

**Comment by ccrisan** [comment]
Please also post a screenshot of your email settings. Also make sure your internet connection is working fine on your PI. Try logging in remotely using SSH/putty and pinging e.g. google.com.

**Comment by sol4ris33** [comment]
Oh it's ok i found my problem..... My default gateway address was wrong (i had the default value 192.168.1.1, and it was wrong.....)

Thanks!
