### ISSUE TITLE
Installing ngrok 

### ISSUE THREAD

**Issue by alasso** [ccrisan/motioneyeos#1102]
Hi,

I am running motioneyeOS on a raspberry pi zero w and would like to install ngrok to access from internet.
If it is not ngrok may be another solution. 

Does anybody did this to guide me?

Thanks a lot in advance,
Adrian

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives

This being said, you either compile your own version of the OS or you go with Raspbian.

**Comment by huvarda** [comment]
You can try port forwarding to access it from the internet.  If you want your own domain then you can also use dynamic dns to access it from a custom domain.  Other than that I don't think there are any other choices.

**Comment by bkjaya2020** [comment]
You can use balena 
https://bkjaya.wordpress.com/2021/02/13/how-to-control-motioneye-cctv-system-on-a-raspberry-pi-3-remotely-using-balenacloud/
