### ISSUE TITLE
TP-Link WN822N wifi dongle doesn't work on motioneyeos.

### ISSUE THREAD

**Issue by shadowfxd** [ccrisan/motioneyeos#1106]
On raspbian I have to add the drivers by using:

    sudo wget http://www.fars-robotics.net/install-wifi -O /usr/bin/install-wifi

    sudo chmod +x /usr/bin/install-wifi

    sudo install-wifi

Then it works with motioneye, but when I try the dongle with motioneyeos, it doesn't work at all and with apt-get not working, I cannot install the drivers myself. Anyway you can add these please?

**Comment by ccrisan** [comment]
You can't install anything on motionEyeOS. Also I won't be supporting out-of-tree kernel drivers. Please use Raspbian if you must use this adapter.
