### ISSUE TITLE
Motion notifications not attaching images to emails

### ISSUE THREAD

**Issue by hxpaul** [ccrisan/motioneyeos#1108]
I have set up email notifications from my motioneyeos setup (raspberry pi zero with official raspberry pi camera) via a gmail account. All good and emails sending. However images are not being attached to the email. I am capturing images successfully. If I extend the "timespan to look for images" to more than one hour then I get images, I suspect these are not the images connected to the motion detection though. It feels like there is an hour's difference, as if the code that looks for the images is in one timezone and the code that sends the email is in another. Is this possible? They should both be in sync, even if the emails were sent with the wrong timestamp (say utc time instead of bst) the images and the email preparation should in the same local time. I've tried changing my timezone from UTC to London time to see if it makes a difference, but no. Here is a sample email:
 
<img width="1048" alt="screen shot 2017-08-30 at 15 24 08" src="https://user-images.githubusercontent.com/10348067/29877412-76f99abe-8d97-11e7-812e-b6ff3d8719e5.png">

I'm using gmail for the sending and receiving, though two different accounts.

Any advice here anyone?

Ace repo that I use a lot, thanks.

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails.

 Also please try the latest 20170827 prerelease as it incorporates some email attachment improvements.

**Comment by hxpaul** [comment]
Thanks, will clear down the image folder.
Is there a way to upgrade to a prerelease from the ui? Says I'm up to date - do I have to download the image manually?

**Comment by ccrisan** [comment]
@hxpaul https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-noticed-a-new-version-has-been-released-why-does-my-motioneyeos-say-its-up-to-date

**Comment by hxpaul** [comment]
awesome thanks 👍
