### ISSUE TITLE
Remote motionEye Camera: authentication failed

### ISSUE THREAD

**Issue by angares** [ccrisan/motioneyeos#1111]
Hello!

I'm trying to add a Remote motionEye Camera to motionEye Server, but "authentication failed". Checked password and ip, and no FNC. Don't know what to do now - can you help me?

I'm using latest version of motioneyeos (Pi2 - 20170827) and on server motionEye, installed on Pi3 with raspian jessie.

Greetings!
Nils

![img_0020](https://user-images.githubusercontent.com/4758785/29909095-9c0c884c-8e24-11e7-869f-dfa94f1876fe.PNG)
![img_0021](https://user-images.githubusercontent.com/4758785/29909098-9c3d4e64-8e24-11e7-91a4-7bf5ef77300c.PNG)
![img_0022](https://user-images.githubusercontent.com/4758785/29909097-9c2ba34e-8e24-11e7-8ad7-067b399cd4dd.PNG)
![img_0023](https://user-images.githubusercontent.com/4758785/29909096-9c29891a-8e24-11e7-9027-e87158432353.PNG)

**Comment by ccrisan** [comment]
I'll look into it.

**Comment by WayneKeenan** [comment]
Maybe as simple as pressing TAB after entering the password?

**Comment by angares** [comment]
@WayneKeenan I checked it, thats not the problem 
@ccrisan Thank you very much

**Comment by petermeigs** [comment]
I struggled with this authentication failure and finally went back to the 0.35.2 version.  Then that acted up as well, not letting me login in from my browser. As an act of desperation and a wild guess based on seeing a comment about http cookie name prefix in the 20170611 release, I deleted all the cookies and cached files in my browser. Now the 0.35.2 version is working just fine.

I haven't gone back to try 20170827 again for a real test but deleting cookies and cached files might help.

**Comment by ccrisan** [comment]
@angares you were right - there was indeed a bug when sending password to a remote motionEye camera. https://github.com/ccrisan/motioneye/commit/1d4041c0ca81c0911a8a20f47b7fae179c2ce167 fixes this. I will release a 0.37.1 version soon. Thanks for reporting this.
