### ISSUE TITLE
Multiple Cameras with motionEyeOS?

### ISSUE THREAD

**Issue by nxion** [ccrisan/motioneyeos#1118]
Hello,

I apologize if this question has been answered somewhere else. I have a ODroid-C2 that I wanted to use as the "server" and then have multiple Pi Zeros as remote cameras. Is it possible to pull multiple feeds into a central location?

**Comment by ccrisan** [comment]
Check out the [scenarios](https://github.com/ccrisan/motioneyeos/wiki/Usage-Scenarios). They apply to all boards, including the Odroid C2. I recommend that you configure your PI Zeros as [fast network cameras](https://github.com/ccrisan/motioneyeos/wiki/Fast-Network-Camera).

**Comment by nxion** [comment]
Thank you. My apologies that I missed this!
