### ISSUE TITLE
No advanced settings option - only see preferences

### ISSUE THREAD

**Issue by justenoughtobedangerous** [ccrisan/motioneyeos#1121]
I just installed motioneyeOS, and camera is working, but the only settings I have are 'Preferences'. I have no option to enable more settings, nor any General settings.
How can i get more settings via the UI?
   Raspberry Pi 3
   Pi NoIR camera
   Wifi enabled
   used motioneyeos-raspberrypi3-20170827.img
![image](https://user-images.githubusercontent.com/31741289/30176133-5a6f5558-93cf-11e7-9891-b3d3d76fb9d2.png)

**Comment by ccrisan** [comment]
Use the logout icon and log in with administrator.
