### ISSUE TITLE
MotionEyeOs on Hyber-V with ubuntu. (Central Server setup)

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#1128]
**Upgrading an existing MotionEyeOs system.**
10 x Raspberry Pi run today with one of the 10 Raspberry Pi as a hub.
Unfortunately, it is difficult to manage the captured images and videos from the 10 cameras.

I would therefore like to set up a MotionEye system based on 10 x Raspberry Pi in "fast network camera" mode, and a central server based on Windows Server 2016 with Hyber-V installed with ubuntu and MotionEye.

The server is an HP proliant with quadcore cpu.

Does anyone have experience with such an installation?

Pro / Cons

**Comment by ccrisan** [comment]
This is not a valid issue. Please use our [google group](groups.google.com/forum/#!forum/motioneye) for this kind of topics.
