### ISSUE TITLE
Streaming Authentication questions

### ISSUE THREAD

**Issue by oscarjim** [ccrisan/motioneyeos#1131]
I have enabled basic authentication under the video streaming options.  When I try to access the stream from an external connection I am prompted for Login and password details, however the credentials for either my user or admin account do not work.  The login window keep popping up.

With authentication disabled I am able to see the stream from an external connection.

Any ideas what could be wrong?  I have three raspberry PIs (model 2, Model 3 and a pi zero w)  I have different ports setup for each ones stream, and I have port forwarding rules setup in my router for all three.  None are setup as FNC.

**Comment by ccrisan** [comment]
If you're on 20170827, there's a known bug that has been fixed in upstream motionEye. Until the next stable release, I recommend using the current stable version (20170710).
