### ISSUE TITLE
Remote connection from mobile

### ISSUE THREAD

**Issue by daniele777** [ccrisan/motioneyeos#1133]
i try to connect from internet to motioneyeos .. i do that.. create virtual server on router called "meye"  .. on port 80 tcp and internal address identify raspberry wifi.. after that on browser of my phone i open chrome and i digit  myexternal_address/meye but can't connect.. why?

**Comment by ccrisan** [comment]
This is not intelligible. At least not to me. It may be related to https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-i-access-motioneyeos-from-the-internet though.
