### ISSUE TITLE
No more direct link to streaming ?

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#1135]
I have used the opportunity to link directly to a MotionEye stream like 192.168.1.x: 8081. 
It allows for zooming into a picture from a tablet. 

Unfortunately, this option is no longer available, or it has a different format. 
What is up and down on this now lacking functionality?

Here in version 20170710 where streaming link still exists.

![streaming](https://user-images.githubusercontent.com/9556987/30519319-c06ce4bc-9b93-11e7-9016-44ced756f925.JPG)

**Comment by ccrisan** [comment]
It still exists but 20170827 was affected by a bug that has been fixed in motionEye 0.37.1. The fix will be part of the next stable release. Until then, please use the latest stable release.

**Comment by SuneBielefeldt** [comment]
Thanks Calin, I'm glad to hear that. 😀
