### ISSUE TITLE
Use official toolchain for all Raspberry Pi builds

### ISSUE THREAD

**Issue by jasaw** [ccrisan/motioneyeos#1136]
Current Raspberry Pi builds are using buildroot's toolchain, which is causing Raspberry Pi `vcdbg` to fail, because `vcdbg` is closed-source and provided as a binary. Other precompiled /opt/vc binaries including libraries in [RPi firmware](https://github.com/raspberrypi/firmware/) have the same problem.

In order to get the precompiled binaries to work, we need to use the [official RPi toolchain](https://github.com/raspberrypi/tools).

It is probably worth providing all the /opt/vc binaries, similar to Raspbian.

Edit: Not sure if this is a ThingOS issue.

**Comment by ccrisan** [comment]
It's a thingOS issue for sure.

**Comment by jasaw** [comment]
I've created this issue in thingOS as https://github.com/ccrisan/thingos/issues/5
