### ISSUE TITLE
Surveillance Login Problems (basic and digest) 

### ISSUE THREAD

**Issue by mycol** [ccrisan/motioneyeos#1137]
Howdy, first i'd like to say great job putting this fantastic app out there for everyone to enjoy, your hard work is appreciated!

I've got a fresh install of MotioneyeOS running on a Pi3, all is good except I'm unable to login to the stream on port 8081 using authentication (works w/o). I've tried using diff user/pass combos, basic/digest, rebooting, etc.

Any help would be appreciated, I'll be happy to post a log output if someone can specify which log this would be found in (i couldn't locate).

**Comment by ccrisan** [comment]
It's a known bug that has been fixed in motionEye with https://github.com/ccrisan/motioneye/commit/7a8b5d78bee059f98bedd69d5cb3416a44d64c81. Please use the latest stable release of motionEyeOS until I manage to make a new release that incorporates the fix.
