### ISSUE TITLE
Cannot add Raspberry Pi 3 remote camera

### ISSUE THREAD

**Issue by onlize** [ccrisan/motioneyeos#1143]
Hello,

I configured camera module on RPi using the following instructions: http://elinux.org/RPi-Cam-Web-Interface

It works. I can go to http://RPiIPAddress/html and I can see everything through that camera. When I try to add it to my MotionEyeOs, I receive message "not a supported network camera". I tried to add this camera as Network Camera and as Simple MJPEG Camera, but have the same message.

What makes camera supported? I want to have simple camera added to MotionEyeOS software. How can I do it?

Thank you.

**Comment by ccrisan** [comment]
What is the URL you're trying to add to motionEyeOS? If you try opening it in a browser, what does it look like? Screenshots are encouraged.

**Comment by tommybuck** [comment]
@onlize try adding /cam_pic.php or /min.php on the end of your url. Does that work?

**Comment by onlize** [comment]
The url is http://RPiIPAddress/html.

Here is what I see on the page (The camera is rotated):

![image](https://user-images.githubusercontent.com/28982031/30694966-e7bdf988-9e9b-11e7-8947-8a8e15b6acde.png)

**Comment by onlize** [comment]
I do not care much about this software or any other. Is there any camera software that you would recommend? I want to have Raspbian with as little software installed as possible.

I have Raspberry Pi 3 with Camera Module attached.

Thank you.

**Comment by onlize** [comment]
@tommybuck, I will try it later today when I come home. Thank you for suggestion.

**Comment by ccrisan** [comment]
How about motionEye?

> I do not care much about this software or any other. Is there any camera software that you would recommend? I want to have Raspbian with as little software installed as possible.

**Comment by onlize** [comment]
I will use MotionEye if I have to. I thought there was more basic solution.

**Comment by ccrisan** [comment]
plain motion? [streamEye](https://github.com/ccrisan/streameye)?
