### ISSUE TITLE
Raspberry Pi 2 - cannot boot

### ISSUE THREAD

**Issue by gryzli133** [ccrisan/motioneyeos#1149]
Using Win32DiskImager I'm not able to install MotionEyeOS. Trying on two mSD cards, but every time it just start and display this colorfull first screen, after even 30min, nothing happend. If I'm using official Raspbian img, there is no problem at all... I was trying 8GB San Disk Industrial, and 32GB Kingston card. Also trying with:
motioneyeos-raspberrypi2-20170827
motioneyeos-raspberrypi2-20170710

Anybody can help where is the problem/what am I doing wrong?

**Comment by jasaw** [comment]
@gryzli133 Silly question, did you extract the GZ compressed image file first before writing to SD card?

**Comment by gryzli133** [comment]
Yes, I have done it with 7zip on windows 10, then write the img file with win32 disk imager... Is there any tutorial with step by step? Maybe I do a small fault. It is strange, because the new Raspbian works that way without problems...

**Comment by ccrisan** [comment]
Can I see a photo of the model written on your board?

**Comment by gryzli133** [comment]
My fault, it is my old board, I though it's pi2, but is just B+. Thank you very much for your help! Now it is working ;-)

**Comment by ccrisan** [comment]
:)
