### ISSUE TITLE
WebUI at HDMI

### ISSUE THREAD

**Issue by mecaz** [ccrisan/motioneyeos#1150]
Hello, 

Im am using Raspberry PI for monitoring IP Cams on my network
And my RPI connected to a screen via HDMI. 
I can connect and monitor my cams connecting from my tablet or mobile phone
But i wonder is it possible to show my cams on HDMI like WebUI. 
It would be great if possible.
Regards

**Comment by jasaw** [comment]
I think you're better off running Raspbian with PIXEL desktop environment. Follow the motionEye installation guide. As for showing the web UI on HDMI, auto launch chromium in kiosk mode, point it to localhost, and there you have it. You could also configure the mouse cursor to hide after some inactivity duration.

**Comment by ccrisan** [comment]
This is not going to happen given that we do our best to conserve resources on the PI so that the actual video processing can be as good as possible.
