### ISSUE TITLE
Iptable managing

### ISSUE THREAD

**Issue by sol4ris2048** [ccrisan/motioneyeos#1156]
Hello,

I wanted to manage iptables to close some ports on my raspberry pi (where i have installed motioneyeos for my pi camera).

But i can't install iptables-permanent and the file system is in read-only mode...

How can i do to secure quickly my system (at least close all ports i don't need...)

Thanks!

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-i-install-some-package

**Comment by ccrisan** [comment]
Use the /data/etc/userinit.sh script to run your iptables commands.
