### ISSUE TITLE
[installation docs]: a note about stripping device partition

### ISSUE THREAD

**Issue by tolitius** [ccrisan/motioneyeos#1159]
Since `writeimage.sh` appends `s1` or `p1` or `1` to the `BOOT_DEV`:

```bash
if [ `uname` == "Darwin" ]; then
    BOOT_DEV=${SDCARD_DEV}s1 # e.g. /dev/disk4s1
    diskutil unmountDisk ${SDCARD_DEV}
    mount -ft msdos $BOOT_DEV $BOOT
else # assuming Linux
    BOOT_DEV=${SDCARD_DEV}p1 # e.g. /dev/mmcblk0p1
    if ! [ -e ${SDCARD_DEV}p1 ]; then
        BOOT_DEV=${SDCARD_DEV}1 # e.g. /dev/sdc1
    fi
    mount $BOOT_DEV $BOOT
fi
```

and `df -h` usually shows device with its partition:

```bash
$ df -h
Filesystem                          Size   Used  Avail Capacity iused      ifree %iused  Mounted on
...
/dev/disk3s1                        15Gi  1.1Gi   14Gi     8%       0          0  100%   /Volumes/CANAKIT
```

it would make sense to add a note to the installation wiki to provide a device without a partition suffix: i.e. `/dev/mmcblk0p6` => `/dev/mmcblk0` or `/dev/disk3s1` => `/dev/disk3` to `writeimage.sh`.

this explanation is way longer than a proposed note in the wiki :) but I am sure I am not the only one who was puzzled for 30 seconds before looking inside the script.

**Comment by ccrisan** [comment]
Done!
