### ISSUE TITLE
SMS Notification

### ISSUE THREAD

**Issue by laurentli** [ccrisan/motioneyeos#116]
Hi Calin Crisan. First, thank you for your work. I discover Raspberry and your distribution, it's so amazing and powerful. I have a question, I test your email notification with motionpie, it work great. Now i want to have SMS notification. Do you have that function? with for example this module:

http://www.ebay.fr/itm/Sim800-Expansion-Board-With-GSM-GPRS-SMS-Function-For-Raspberry-Pi-2B-B-/141855363007?hash=item21073d0fbf:g:TlkAAOSwUdlWcwAk

**Comment by chaseacton** [comment]
You could do this without any additional hardware. Just use the webhook feature to post to a page on your server and then use Twilio to send yourself a text message. Probably wouldn't take more than 20 lines of code.

**Comment by laurentli** [comment]
I would hardware, because i don't want to manage server and QOS... let this task to IAP (FAI). Just buy Sim card. Is it possible with Crisan project >>> motioneyeos??? Thx

**Comment by ccrisan** [comment]
@laurentli, no, SMS is not possible with motionEyeOS and I don't have plans to implement such a feature.

**Comment by laurentli** [comment]
thx for reply, the only way is webhook thx

**Comment by jamie3** [comment]
You can use twilio API for sending SMS
