### ISSUE TITLE
Can use HTTP notification, but need alive notification too

### ISSUE THREAD

**Issue by s1h4d0w** [ccrisan/motioneyeos#1163]
MotionEyeOS is pretty much all I needed, so thanks for that! It even has a way to make a HTTP request when detecting motion, even better! However, our software also requires our motion detectors to send out an alive notification every minute. 

I'm pretty much a Linux noob, so I've logged in as root using SSH and did `crontab -e` to add this line to my crontab:

`* * * * curl "http://www.website.com/camerahandler.axd?Message=Alive&Camera=123456" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: nl" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Cache-Control: max-age=0" -H "Connection: keep-alive" --compressed`

I need all those headers for our server to recognize the call.

However, it doesn't seem to be executing, and I can't find a syslog in this OS. Do I need to install anything to make it work? I've gotten a little bit comfortable with Raspbian but this is all pretty new for me.

**Comment by ccrisan** [comment]
Aren't you missing an asterisk at the beginning of the line?

**Comment by s1h4d0w** [comment]
@ccrisan You are completely right, I can't believe I've been looking for a problem that was so easy to fix. Everything seems to be working now!
