### ISSUE TITLE
Password Changed? after changing WiFi TimeZone

### ISSUE THREAD

**Issue by b0rnwr0ng** [ccrisan/motioneyeos#1169]
Upgraded to 20171003, still having a WiFi drop out issue on pi3 on one device so far, so changed timezone to US/Eastern to America/NewYork and then I couldn't log back in at all.. had to do a new install..

**Comment by Apathialol** [comment]
I updated to the new version and it locked me out too, no timezone change required.

**Comment by jasaw** [comment]
I think this is a duplicate of issue #1116.
Please clear your browser cache and refresh the page.
Try logging in using these passwords: `*****`, or the sha1 of the five stars: `133e3d6b775613651eaedbf7e609d244f2f852af`
