### ISSUE TITLE
Fast Network camera mode less efficient

### ISSUE THREAD

**Issue by Mikiya83** [ccrisan/motioneyeos#1174]
Hi
I'm using MotioneyeOS updated on Rpi1 and Rpi3. Today i try to use "Fast Network Camera" on Rpi 1 and i'm suprised : in this mode, i get less FPS (with same resolution 1024x576) : ~2 fps instead of ~6fps in normal mode.
I can't understand why, CPU raise up to ~85% in normal mode and drop to ~30% in Fast Network Camera mode so i can't figure out where is the bottleneck :(
Do you have any ideas ?
Thanks

**Comment by ccrisan** [comment]
How do you measure the FPS?

**Comment by Mikiya83** [comment]
I use the metric displayed by motionEye on RPi3 (the RPi1 is added as Network cam).
And when i see the stream, it's clearly less smoth.
About the conf, i tested with more RAM for GPU (128 and 256), and i even tested in 640x480 and it's "stuck" around 2/3 fps :/

**Comment by Mikiya83** [comment]
I retried with 20171008 but i still can get more than 2/3 fps in FNC, i do not understand why.

**Comment by Mikiya83** [comment]
I'm sure i tested it a while ago and it worked fast, so i will check an older version to compare because it's a unsusable for now :(

**Comment by Mikiya83** [comment]
Hum i can't understand why, but i reinstalled from scratch and it's ok now .... so you can close this issue, i can't figured out what happened sorry.
