### ISSUE TITLE
Which .gz to download for Pi Zero W?

### ISSUE THREAD

**Issue by someevil** [ccrisan/motioneyeos#1175]
Sorry for a n00b question, but which image should I download for the Pi Zero W?

![image](https://user-images.githubusercontent.com/15650380/31480252-75b47b5e-af68-11e7-9916-040f1fea511a.png)

**Comment by jasaw** [comment]
use raspberrypi-20171008 image.

**Comment by ccrisan** [comment]
@someevil you can't reopen a closed issue. If you think this particular issue is still valid, please explain why. If you're referring to a different issue, then please open a new issue. In any case, you have found the correct wiki article and that's the way you should proceed with a Pi Zero W.
