### ISSUE TITLE
starting wpa_supplicant: failed (brcmfmac)

### ISSUE THREAD

**Issue by plankton99** [ccrisan/motioneyeos#1178]
getting this fail message on both Pi Zero W and Pi 3 B.
"starting wpa_supplicant: failed (brcmfmac)"  then it keeps rebooting.  

I have looked at all threads on this and there is no real answer, PLEASE HELP!

Checked all the boxes
1) diskpart clean and format
2) created wpa_supplicant.conf with unix EOL
3) doubled checked ssid and pwd spelling
4) ensured proper power delivered to Pi

I can't be the only one with this issue.

**Comment by davimas** [comment]
Hey, i have this isue all half day long, nothing help.
Then i see in Notepad++ that the ending was .txt 😅

**Comment by plankton99** [comment]
is there a way to load motioneye after the raspbian stretch desktop is installed with a s apt-get command?  Because the motioneye os is just not working
