### ISSUE TITLE
Feature request: sunrise and sunset based working schedule

### ISSUE THREAD

**Issue by MrJeromeV** [ccrisan/motioneyeos#118]
It could be useful to have motion detection starting at sunrise (+/- delta) and stopping et sunset, or the contrary for NOIR cam.

**Comment by olli84** [comment]
That would be great.

I have the CSI-NOIR-Cam and need in the night ISO400 because my infrared lights are not bright enough. Over the day ISO100 is perfect - so it would be great to change that automatic.

**Comment by EelskeM** [comment]
i love Motioneyeos! It would be great if the schedule also works when still images are taken to avoid the dark pictures during night..

**Comment by bortek** [comment]
Nice feature. But unfortunately this will require extra time to implement which the devs dont have.
