### ISSUE TITLE
Upgraded to pre release but does not reflect

### ISSUE THREAD

**Issue by b0rnwr0ng** [ccrisan/motioneyeos#1181]
I upgrqded toghe latest prerelease but no longer see options and erion appears to be previous version.

**Comment by jasaw** [comment]
Can you please attach your log files here?

**Comment by b0rnwr0ng** [comment]
Sorry, I wound up reinstalling fresh.  I dont see options for h264 but
somethibg tells me Ibwould need to compile rather than use an image

**Comment by jasaw** [comment]
@b0rnwr0ng You don't need to compile to get the H264 OMX encoder. It's already available in the [20171008](https://github.com/ccrisan/motioneyeos/releases/tag/20171008) pre-release.

**Comment by rwijnhov** [comment]
Where do we enable the H264. Where do we find it in the ui?

**Comment by jasaw** [comment]
Hardware accelerated video encoding (H264 OMX) is only available on Raspberry Pi hardware.

**Comment by b0rnwr0ng** [comment]
I have a raspberry pi3 and do not see the option.

**Comment by jasaw** [comment]
It's in the "Movie Format".

![motioneyeos-omx](https://user-images.githubusercontent.com/721280/31867954-b018e978-b7e3-11e7-957a-350fc97ca5b6.jpg)

**Comment by b0rnwr0ng** [comment]
Ahhh thank you.  I actually have been using fast vid camera and have that
disabled.  I will have to check it out though.  Thank you!

**Comment by jasaw** [comment]
@b0rnwr0ng Issue resolved now?

**Comment by b0rnwr0ng** [comment]
This can be closed.
