### ISSUE TITLE
Please add support for HikVision cameras

### ISSUE THREAD

**Issue by Karlamees** [ccrisan/motioneyeos#1183]
My friend just gave me an Hikvision Ip cam and i was really hoping that i could connect it to my existing MotionEye system.

**Comment by ccrisan** [comment]
Find your HikVision camera streaming URL (RTSP or MJPEG) and it should work with motionEyeOS.

**Comment by Karlamees** [comment]
Im getting the error "Recv failure: Connection reset by peer"

**Comment by ccrisan** [comment]
Again, make sure you're using the correct URL. Make sure the URL actually works well with Motion. If it does, it should work with motionEye(OS).

**Comment by Karlamees** [comment]
i got the RTSP feed working on VLC using:
rtsp://<username>:<password>@<address>:<port>/Streaming/Channels/<id>/
But MotionEyeOS still says unsupported camera

**Comment by ccrisan** [comment]
The following definitely is not a valid RTSP URL:
    rtsp://:@

    :/Streaming/Channels//`

Even if you remove the weird extra newlines, you get `rtsp://:@:/Streaming/Channels//` which is still not a valid RTSP URL, unless there's a syntax that I'm not aware of. Moreover, even if you replace `@` with the actual IP address, the two colons don't belong there.

Bottom line, make sure the URL works with Motion first. If it doesn't, there's nothing motionEye(OS) can do about it.
