### ISSUE TITLE
Upgrade from 20170212 not possible

### ISSUE THREAD

**Issue by HugoBerto** [ccrisan/motioneyeos#1186]
I have MotioneyeOS version 20170212 on a RaspberryPi3 and everything works quite fine. 
However, when I check for an upgrade in the gui it requests me the latest one (20171003), but the version won´t change after the update process is finished. It doesn´t show any errors, it just finishes the process without changing the actual version.

**Comment by ccrisan** [comment]
You're trying to upgrade from a version that is too old. The upgrade mechanism has radically changed since 20170212 and things no longer work as expected. I recommend staying with 20170212 if you're happy with it. Otherwise, you'll need to manually rewrite the OS image from scratch.
