### ISSUE TITLE
Where to turn on omx in the ui?

### ISSUE THREAD

**Issue by rwijnhov** [ccrisan/motioneyeos#1188]
Where do we find:
all of @jasaw's work to enable OMX h264 hardware acceleration on the RPi has been merged in (just make sure to choose the OMX version of the codec in the UI). Where do we choose this in the ui?

**Comment by jasaw** [comment]
@rwijnhov OMX codec is available under "Movies" section. Hardware acceleration is only enabled for video encoding when recording a movie.
