### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by Freeze44** [ccrisan/motioneyeos#1190]
Is there any solution to run motioneyeos without a network connection? The solution in the FAQ didn't work for me.

**Comment by ccrisan** [comment]
The fact that "it didn't work" for you won't allow us to help you. You need to come with more information (log files, errors, what exactly did not work).

**Comment by Freeze44** [comment]
When i setted the os_networkless variable to true i got the following error "can't stat /data/etc/os.conf: structure needs cleaning"
/etc/init.d/conf:line 15: /data/etc/os.conf: structure needs cleaning
I`m sorry but i`m a beginner and it`s my first raspberry-based project.

**Comment by ccrisan** [comment]
@Freeze44 that sounds like a filesystem corruption problem.

**Comment by jasaw** [comment]
@Freeze44 Have you tried reflashing your SD card?

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
