### ISSUE TITLE
No Network in menu

### ISSUE THREAD

**Issue by cr0co** [ccrisan/motioneyeos#1191]
Hello

i installed it on a pi 3 with jessie, it works but some menus are away.

i need the "Network" menu, so i can save the snapshots to my synology...
can you help me pls ?

![raspberrypi 1](https://user-images.githubusercontent.com/6071154/31713572-f5dc5ec4-b3fe-11e7-92c0-e3af3ba3215f.png)
![raspberrypi](https://user-images.githubusercontent.com/6071154/31713577-f85a9274-b3fe-11e7-9855-2282ef3ba7f6.png)

**Comment by ccrisan** [comment]
Set [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares] to true and make sure you run as root.
