### ISSUE TITLE
boot motioneyeos via network (nfsroot) with raspberry pi possible?

### ISSUE THREAD

**Issue by alexheinz** [ccrisan/motioneyeos#1197]
Hello,

I would like to boot motioneyeos not from the SD card but a network server via (DHCP/TFTP/NFS). The general procedure is explained here:
[https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md](url)

I see that those arguments are currently provided to the kernel:
`bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.fiq_fix_enable=1 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait ro rootflags=noload panic=10 quiet loglevel=1 ipv6.disable=1`

- Does motioneyeos come with required modules to make NFSroot work?
- Is nfsroot expected to work with motioneyeos?
- Is it enough to change the kernel arguments? (I assume /etc/fstab.disk also needs to be changed because it contains the reference to /dev/mmcblk0p1 and /dev/mmcblk0p3)
- Is there an example available?

Thank you for your help!

**Comment by ccrisan** [comment]
motionEyeOS doesn't come with any kind of network boot and I personally have no plans to add it in the near future. I recommend that you use Raspbian if you must have network boot.
