### ISSUE TITLE
USB hdd not selectable in File storage dropdown menu (anymore)?

### ISSUE THREAD

**Issue by olliraa** [ccrisan/motioneyeos#121]
Running the latest version with rpi2. Earlier when I tested the software for the first time usb drives worked perfectly. Now no drive shows upin the menu (tested with many different ones). The menu only shows the "SD card" and "Custom path". lsusb via ssh lists the devices ok, but for some reasion the menu in the gui does not get updated. What is the path to usb drives/workaround for this?

**Comment by ccrisan** [comment]
Please attach your log files.

**Comment by olliraa** [comment]
Here are (all?) the logs attached as zip.
[logs.zip](https://github.com/ccrisan/motioneyeos/files/87553/logs.zip)

**Comment by ccrisan** [comment]
Is there any reason why you left out dmesg.log (actually the most important one in this case)?

**Comment by olliraa** [comment]
Sorry, took a while to figure out that I had to:

mount the root as writable
dmesg > dmesg.log


But here it is. Hope it's ok :)


-Olli

2016-01-12 18:14 GMT+02:00 Calin Crisan <notifications@github.com>:

**Comment by ccrisan** [comment]
Wow I see now why you ommitted it :) You could easily download it from the UI (Expert Settings).

**Comment by ccrisan** [comment]
Nevertheless you forgot to attach it.

**Comment by olliraa** [comment]
It was attached, but apparently some mail server virus scanner did not like
it... Let's try again :)

https://onedrive.live.com/redir?resid=C769995EB0B2279B!45495&authkey=!ABoZu-TM_lKH6uw&ithint=file%2clog

Works now? :)

-Olli

2016-01-12 18:58 GMT+02:00 Calin Crisan <notifications@github.com>:

**Comment by ccrisan** [comment]
Nope, still not. Are you able to see the attachment in your comment?

**Comment by ccrisan** [comment]
Ah, nevermind. Just never use the mail to attach files. Always use github's UI.

**Comment by olliraa** [comment]
Ok, here's the dmesg.log as text (just to make sure):

[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Linux version 4.1.13-meye (ccrisan@supermicro) (gcc version 4.8.5 (Buildroot 2015.08-rc1-g3394b0c) ) #1 SMP PREEMPT Sat Jan 9 20:30:46 EET 2016
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine: BCM2709
[    0.000000] cma: Reserved 8 MiB at 0x36800000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 225280
[    0.000000] free_area_init_node: node 0, pgdat 8058a340, node_mem_map b6112000
[    0.000000]   Normal zone: 1760 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 225280 pages, LIFO batch:31
[    0.000000] [bcm2709_smp_init_cpus] enter (93c0->f3003010)
[    0.000000] [bcm2709_smp_init_cpus] ncores=4
[    0.000000] PERCPU: Embedded 10 pages/cpu @b60e5000 s11136 r8192 d21632 u40960
[    0.000000] pcpu-alloc: s11136 r8192 d21632 u40960 alloc=10*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 223520
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2709.boardrev=0xa01041 bcm2709.serial=0x79eb822c smsc95xx.macaddr=B8:27:EB:EB:82:2C bcm2708_fb.fbswap=1 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.fiq_fix_enable=1 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait ro rootflags=noload panic=10 quiet loglevel=1
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 878848K/901120K available (4003K kernel code, 235K rwdata, 1228K rodata, 172K init, 359K bss, 14080K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xb7800000 - 0xff000000   (1144 MB)
                   lowmem  : 0x80000000 - 0xb7000000   ( 880 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80524034   (5233 kB)
                     .init : 0x80525000 - 0x80550000   ( 172 kB)
                     .data : 0x80550000 - 0x8058afc8   ( 236 kB)
                      .bss : 0x8058d000 - 0x805e6ee4   ( 360 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:608
[    0.000000] Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000014] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000033] Switching to timer-based delay loop, resolution 52ns
[    0.000215] Console: colour dummy device 80x30
[    0.000409] console [tty1] enabled
[    0.000434] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=19200)
[    0.000457] pid_max: default: 32768 minimum: 301
[    0.000596] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000615] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001687] CPU: Testing write buffer coherency: ok
[    0.002168] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[    0.002188] [bcm2709_smp_prepare_cpus] enter
[    0.002273] Setting up static identity map for 0x8240 - 0x8274
[    0.008478] [bcm2709_boot_secondary] cpu:1 started (0) 16
[    0.008836] [bcm2709_secondary_init] enter cpu:1
[    0.008885] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[    0.010457] [bcm2709_boot_secondary] cpu:2 started (0) 17
[    0.010728] [bcm2709_secondary_init] enter cpu:2
[    0.010760] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.012510] [bcm2709_boot_secondary] cpu:3 started (0) 16
[    0.012764] [bcm2709_secondary_init] enter cpu:3
[    0.012794] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[    0.012870] Brought up 4 CPUs
[    0.012894] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.012904] CPU: All CPU(s) started in HYP mode.
[    0.012912] CPU: Virtualization extensions available.
[    0.013660] devtmpfs: initialized
[    0.031949] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.032217] clocksource jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[    0.033410] NET: Registered protocol family 16
[    0.039260] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.040578] bcm2709.uart_clock = 3000000
[    0.042132] Serial: AMBA PL011 UART driver
[    0.042247] dev:f1: ttyAMA0 at MMIO 0x3f201000 (irq = 83, base_baud = 0) is a PL011 rev3
[    0.042681] bcm2835-mbox bcm2835-mbox: mailbox enabled
[    0.085381] bcm2708-dmaengine bcm2708-dmaengine: DMA legacy API manager at f3007000, dmachans=0x7f35
[    0.085426] bcm2708-dmaengine bcm2708-dmaengine: failed to get irq for DMA channel 13
[    0.085443] bcm2708-dmaengine bcm2708-dmaengine: Initialized 8 DMA channels (+ 1 legacy)
[    0.086145] bcm2708-dmaengine bcm2708-dmaengine: Load BCM2835 DMA engine driver
[    0.086162] bcm2708-dmaengine bcm2708-dmaengine: dma_debug:0
[    0.086568] usbcore: registered new interface driver usbfs
[    0.086662] usbcore: registered new interface driver hub
[    0.086787] usbcore: registered new device driver usb
[    0.086907] media: Linux media interface: v0.10
[    0.086995] Linux video capture interface: v2.00
[    0.087551] raspberrypi-firmware raspberrypi-firmware.0: Attached to firmware from 2015-11-18 15:48
[    0.113412] Advanced Linux Sound Architecture Driver Initialized.
[    0.114880] Switched to clocksource arch_sys_counter
[    0.115342] FS-Cache: Loaded
[    0.115571] CacheFiles: Loaded
[    0.125704] NET: Registered protocol family 2
[    0.126817] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.126989] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.127182] TCP: Hash tables configured (established 8192 bind 8192)
[    0.127302] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.127367] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.127661] NET: Registered protocol family 1
[    0.128787] bcm2708_gpio: bcm2708_gpio_probe 80572ac8
[    0.130429] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.141984] FS-Cache: Netfs 'cifs' registered for caching
[    0.142461] Key type cifs.spnego registered
[    0.144498] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.144526] io scheduler noop registered
[    0.144546] io scheduler deadline registered
[    0.144597] io scheduler cfq registered (default)
[    0.145908] BCM2708FB: allocated DMA memory f6c00000
[    0.145953] BCM2708FB: allocated DMA channel 0 @ f3007000
[    0.151620] Console: switching to colour frame buffer device 82x26
[    0.155640] bcm2708_rng_init=b7806000
[    1.160011] vc-cma: Videocore CMA driver
[    1.160025] vc-cma: vc_cma_base      = 0x00000000
[    1.160035] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    1.160046] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.160290] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[    1.173559] brd: module loaded
[    1.174434] vchiq: vchiq_init_state: slot_zero = 0xb6c80000, is_master = 0
[    1.176323] usbcore: registered new interface driver smsc95xx
[    1.176403] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.376660] Core Release: 2.80a
[    1.376679] Setting default values for core params
[    1.376725] Finished setting default values for core params
[    1.577145] Using Buffer DMA mode
[    1.577160] Periodic Transfer Interrupt Enhancement - disabled
[    1.577170] Multiprocessor Interrupt Enhancement - disabled
[    1.577181] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.577198] Dedicated Tx FIFOs mode
[    1.577506] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xb6c14000 dma = 0xf6c14000 len=9024
[    1.577544] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
[    1.577567] dwc_otg: Microframe scheduler enabled
[    1.577629] WARN::hcd_init_fiq:412: FIQ on core 1 at 0x802bc5b8
[    1.577647] WARN::hcd_init_fiq:413: FIQ ASM at 0x802bc918 length 36
[    1.577664] WARN::hcd_init_fiq:438: MPHI regs_base at 0xb7898000
[    1.577691] dwc_otg bcm2708_usb: DWC OTG Controller
[    1.577738] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    1.577783] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    1.577836] Init: Port Power? op_state=1
[    1.577846] Init: Power Port (0)
[    1.578108] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.578128] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.578144] usb usb1: Product: DWC OTG Controller
[    1.578159] usb usb1: Manufacturer: Linux 4.1.13-meye dwc_otg_hcd
[    1.578174] usb usb1: SerialNumber: bcm2708_usb
[    1.579046] hub 1-0:1.0: USB hub found
[    1.579106] hub 1-0:1.0: 1 port detected
[    1.579498] dwc_otg: FIQ enabled
[    1.579509] dwc_otg: NAK holdoff enabled
[    1.579519] dwc_otg: FIQ split-transaction FSM enabled
[    1.579552] Module dwc_common_port init
[    1.579862] usbcore: registered new interface driver uvcvideo
[    1.579894] USB Video Class driver (1.1.1)
[    1.580476] bcm2708 watchdog, heartbeat=10 sec (nowayout=0)
[    1.580749] bcm2835-cpufreq: min=600000 max=900000
[    1.583427] sdhci: Secure Digital Host Controller Interface driver
[    1.583435] sdhci: Copyright(c) Pierre Ossman
[    1.583622] mmc-bcm2835 mmc-bcm2835.0: mmc_debug:0 mmc_debug2:0
[    1.583635] mmc-bcm2835 mmc-bcm2835.0: DMA channels allocated
[    1.604935] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.605221] hidraw: raw HID events driver (C) Jiri Kosina
[    1.605383] usbcore: registered new interface driver usbhid
[    1.605391] usbhid: USB HID core driver
[    1.605857] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.606105] NET: Registered protocol family 17
[    1.606176] Key type dns_resolver registered
[    1.607671] Registering SWP/SWPB emulation handler
[    1.608454] vc-sm: Videocore shared memory driver
[    1.608470] [vc_sm_connected_init]: start
[    1.608826] [vc_sm_connected_init]: end - returning 0
[    1.610696] ALSA device list:
[    1.610710]   #0: bcm2835 ALSA
[    1.611145] Waiting for root device /dev/mmcblk0p2...
[    1.644777] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.647078] mmc0: new high speed SDHC card at address b368
[    1.647406] mmcblk0: mmc0:b368 SD    3.76 GiB 
[    1.648522]  mmcblk0: p1 p2 p3
[    1.717013] EXT4-fs (mmcblk0p2): mounted filesystem without journal. Opts: noload
[    1.717068] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.717702] devtmpfs: mounted
[    1.717945] Freeing unused kernel memory: 172K (80525000 - 80550000)
[    1.778963] Indeed it is in host mode hprt0 = 00021501
[    1.940912] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.941057] Indeed it is in host mode hprt0 = 00001101
[    2.109644] EXT4-fs (mmcblk0p3): mounted filesystem with ordered data mode. Opts: (null)
[    2.114183] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.114203] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.114753] hub 1-1:1.0: USB hub found
[    2.114841] hub 1-1:1.0: 5 ports detected
[    2.196465] : bcm2835-v4l2: error -1 while loading driver
[    2.387925] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.474127] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.474149] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.476790] smsc95xx v1.0.4
[    2.507610] udevd[179]: starting version 3.1.2
[    2.515388] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:eb:82:2c
[    2.527147] random: udevd urandom read with 68 bits of entropy available
[    2.641211] bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated
[    2.642137] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x3f204000 (irq 80)
[    2.643232] bcm2708_i2c_init_pinmode(1,2)
[    2.643265] bcm2708_i2c_init_pinmode(1,3)
[    2.643575] bcm2708_i2c bcm2708_i2c.1: BSC1 Controller at 0x3f804000 (irq 79) (baudrate 100000)
[    4.217425] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    5.732505] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   11.271909] random: nonblocking pool is initialized
[ 1964.415408] EXT4-fs (mmcblk0p2): re-mounted. Opts: norecovery

**Comment by olliraa** [comment]
Hi.

I hope the dmesg.log was "ok" :) If there's something I can do for testing
this usb-issue, please let me know. My system is not yet in "production
use", so I'd glad to help.

-Olli

2016-01-12 19:26 GMT+02:00 Calin Crisan <notifications@github.com>:

**Comment by ccrisan** [comment]
Your dmesg.log file is as good as it can be. It's my spare time that's not too abundant these days. I haven't gotten to test this yet.

**Comment by olliraa** [comment]
It was all due to too low voltage for the usb. Just add max_usb_current=1 to config.txt and the usb drives work ok :)
