### ISSUE TITLE
MotionEyeOS crashing when accessed from Android device

### ISSUE THREAD

**Issue by patrezz** [ccrisan/motioneyeos#1218]
This happens every time and the crash is almost immediate. Changing web browsers doesn't help. Other platforms (windows, iOS) work fine. Log showing "ERROR: gdrive: request failed" but this only happens when I connect with my Android phone..

**Log:**
> 
> 
> 2017-11-03 20:48:29: [motioneye]    ERROR: gdrive: request failed: <urlopen error [Errno -3] Temporary failure in name resolution>
> 2017-11-03 20:48:29: [motioneye]    ERROR: failed to upload file "/data/output/Camera1/2017-11-03/20-48-00.jpg" with service gdrive: <urlopen error [Errno -3] Temporary failure in name resolution>
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 875, in upload_media_file
>   File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 98, in upload_file
>   File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 214, in upload_data
>   File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 341, in _request
>   File "/usr/lib/python2.7/site-packages/motioneye/utils.py", line 818, in urlopen
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 429, in open
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 447, in _open
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 1241, in https_open
>   File "/opt/buildroot/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/urllib2.py", line 1198, in do_open
> URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

**motionEye Version:** 0.37.1
**Motion Version:** 4.0.1+git2a140fa
**OS Version:** motionEyeOS 20171008
**Hardware:** Raspberry Pi Zero W

**Comment by ccrisan** [comment]
Make sure you have a working internet connection and the DNS server is properly configured.
