### ISSUE TITLE
No Chance to get any Image from MotionEye to run for the Pi 3

### ISSUE THREAD

**Issue by OldHolborn01** [ccrisan/motioneyeos#1221]
Hello,

First, for the Pi 1 B+ and P2 the Images workes very well for me!

I try out the same for Pi 3, but there are several of fails and it hangs on the login, but there are no chance because of User  and Password.

What goes wrong? (see the Logs in the Pictures)

The Hardware does function, I have tried 8GB and 16GB SD-Cards from Toshiba also with the original Image from Raspian, which is ok.
![dsc03369](https://user-images.githubusercontent.com/33372095/32408641-dd0b3bfe-c19b-11e7-8b99-edee7a3e5abe.JPG)
![dsc03371](https://user-images.githubusercontent.com/33372095/32408646-e6bf1152-c19b-11e7-8948-920524a52876.JPG)

Pleasy are there any Tipps?

Thank you
Reinhard

**Comment by jasaw** [comment]
Looks like a corrupted SD card. Have you tried reflashing it?

**Comment by OldHolborn01** [comment]
I´ve tried a 8GB SD-Card, a 16GB and also several other Cards, which I had used for the Pi 2 or Pi1 B+

The last one, (16GB Toshiba class 10), I putted the Noobs Image on them, because of find out a hardware problem. The Installation goes without any errors, therefore I think, the Card and the Pi are ok...

I will try it again and will post my results soon...

Thank you for help.

Reinhard

**Comment by OldHolborn01** [comment]
Yes, it was indeed the SD, 2 new cards are not working, but my cards that I used for Pi1 and Pi2 are running. The new cards, however, work with the normal operating systems for the Raspberry. It's very strange.

This clarifies the error and the topic can be closed.

Thank you very much for the help!

Reinhard

**Comment by jasaw** [comment]
Very glad that it's working for you now. Thanks for reporting back.
