### ISSUE TITLE
Camera is connected and recognized but won't display

### ISSUE THREAD

**Issue by freddickson** [ccrisan/motioneyeos#1222]
I am trying to setup MotioneyeOS for a school project. I have the Pi camera connected and it is recognized, the LED lights up by default and the Expert Settings option to toggle the LED functions. Not sure if there is a command I can run to check for video signal (maybe I have a faulty camrea) if anyone can help it'd be much appreciated, I only have another 4 days to work on this.

**Comment by jasaw** [comment]
Attaching log files would be helpful.

Have you tried running raspistill?

Stop motionEye first, then run raspistill.
`/etc/init.d/S85motioneye stop`

**Comment by jasaw** [comment]
Closing issue due to lack of update.
