### ISSUE TITLE
Dual camera on separate ports - possible?

### ISSUE THREAD

**Issue by discarn8** [ccrisan/motioneyeos#1226]
Calin (or anyone who may know):

Is it possible to add two cameras and have motioneyeos provide separate feeds for each camera on 2 separate ports?  i.e.: 

Camera 1 --> 192.168.0.100:8080
Camera 2 --> 192.168.0.100:8081

**Comment by portieay** [comment]
I too would like to know

**Comment by ccrisan** [comment]
That's what happens by default, except for the fact that ports start at 8081 instead of 8080.

**Comment by discarn8** [comment]
Thank you for the response, Mr. Crisan. I sincerely appreciate your software and all of your hard work that goes into it.

**Comment by ccrisan** [comment]
Can we close this issue now?

**Comment by discarn8** [comment]
Yes sir, please do and thank you, again
