### ISSUE TITLE
macOS - any way this can be installed on a Mac?

### ISSUE THREAD

**Issue by jat80** [ccrisan/motioneyeos#1229]
Just wondering if I can install this software ON a Mac?

**Comment by joshlukas** [comment]
Hi. Motioneyeos is a complete operating system based on a Linux kernel. Maybe there is a way to install motion and motioneye as a frontend on macOS, but I don't think so.

**Comment by tomwoodhams** [comment]
You could probably do it in parallels or similar, but would be a bit inefficient.

**Comment by jasaw** [comment]
@jat80 You're better off install motionEye on your Mac, rather than motionEyeOS. This [motionEye installation wiki](https://github.com/ccrisan/motioneye/wiki/Installation) might be helpful.

**Comment by jat80** [comment]
@jasaw I’ve looked throughout the wiki, issues and generally on google search and can find nothing on how to install motioneye on a Mac.  If you know of how please let me know but I have come to the conclusion it cannot be done

**Comment by jasaw** [comment]
Closing issue due to lack of interst.
