### ISSUE TITLE
Load screen showing lots of failures

### ISSUE THREAD

**Issue by hongomg** [ccrisan/motioneyeos#1235]
Hi

Thanks for the great work, I tried getting this working on my raspberry pi 3, made the SD card following the instructions online and it boots but showing lots of failure messages, and also I can't seem to find it in my home network afterwards, so I suspect I've installed it incorrectly.

Please see screenshot of boot screen on the pi: https://imgur.com/a/rzrIt 

Also note the ethernet error message near the top too which explains why I can't find it on the network (using wired ethernet)

**Comment by OldHolborn01** [comment]
same Problem for me, ccrisan says, it´s the SD-Card, try another one, this would help.
[https://github.com/ccrisan/motioneyeos/issues/1221#issuecomment-343320586](url)

**Comment by hongomg** [comment]
I put a samsung evo card in and it worked! thanks for the help

**Comment by jasaw** [comment]
Looks like an SD card issue and changing SD card resolved it. Closing issue.
