### ISSUE TITLE
Recorded Movies with 2 cameras not sepparated

### ISSUE THREAD

**Issue by tammycutzet** [ccrisan/motioneyeos#124]
Hi,

i habe two rtsp cameras. Everything is running fine, beside that when i click the movie icon i see all recorded videos. They are not sepparated by the camera names. Maybe a minor bug, or maybe my fault? Checked my settings twice. Should i change the prefix for recording?

**Comment by Banditen01** [comment]
You have to create 2x different folders for ex. Cam1 & Cam2 to separate files

**Comment by tammycutzet** [comment]
Solved, Thanks!
