### ISSUE TITLE
Deleting individual .avi files from the daily listing leaves the .avi.thumb file remaining.

### ISSUE THREAD

**Issue by stevec001** [ccrisan/motioneyeos#125]
When using delete all, it removes the daily folder completely.  When deleting just a single file it leaves the .avi.thumb file to take up storage space. Is it possible to remove the vid file and the thumb file?

**Comment by ccrisan** [comment]
Fixed upstream (in motionEye). The fix will be available with the next release.

**Comment by stevec001** [comment]
Cool. Thank you.

**Comment by J-Lacerte** [comment]
I used the 20200606 version and the 'thumb' still there after deleted all vid
