### ISSUE TITLE
Multiple ethernet cameras

### ISSUE THREAD

**Issue by resch59** [ccrisan/motioneyeos#1256]
I have installed motioneyeos on a pi zero and it works great. I was curious if I could have an ethernet switch with multiple cameras feeding a pi2 or pi3 running just motioneyeos.

**Comment by Chiny91** [comment]
You could.   I do, 2 * R Pi 3, each running motionEyeOS each with 3 IP cams; works a treat.

**Comment by resch59** [comment]
Thanks for reply. I will givie it a try.
