### ISSUE TITLE
Ehternet switch attached to RPi3 running motioneyeos with IP cameras

### ISSUE THREAD

**Issue by resch59** [ccrisan/motioneyeos#1261]

**Comment by jasaw** [comment]
What is this issue about? Please provide a detailed description of what the problem is.

**Comment by resch59** [comment]
Sorry really not an issue more a question. I would like to use a Pi3 with
the cameras attached to a Ethernet switch. Then use motioneyeos on the Pi.
Can the Pi then use wifi to send the streaming video and collected captures
to my home router.

**Comment by ccrisan** [comment]
You can do that but I recommend using Raspbian + motionEye for this setup. motionEyeOS is designed to only have one network connection.
