### ISSUE TITLE
homekit support

### ISSUE THREAD

**Issue by leonardpitzu** [ccrisan/motioneyeos#1262]
can you add homekit support via nodejs + homebridge? motion detection and streaming through homekit would be amazing!
as a suggestion: https://github.com/rxseger/homebridge-camera-motion

**Comment by pauldogg** [comment]
Same for Home Assistant would be great!
Thanks!

**Comment by SteveCohen** [comment]
I think stable homebridge plugins for this already exist. 
- Video can be streamed using [homebridge-camera-ffmpeg](https://github.com/KhaosT/homebridge-camera-ffmpeg/). 
- Motion detection info can be passed to homekit using motioneyeos' webhooks. A plugin like [homebridge-http-webhooks](https://github.com/benzman81/homebridge-http-webhooks) looks promising. 

Not as neat as a single 'all in one' plugin, but it works.

**Comment by ccrisan** [comment]
There are no plans to integrate motionEye "natively" with homekit. Plugins could be a solution, as @SteveCohen indicated.
