### ISSUE TITLE
Feature Request: Web video player of recorded video files

### ISSUE THREAD

**Issue by bmatic385** [ccrisan/motioneyeos#1264]
Hi,

is there posibility to implement web video player ?
So we now have a situation where You can only download recorded videos through web interface, it could be very nice if we could play it directly from web browser, like YouTube ?

Best regards to development team.

**Comment by jasaw** [comment]
There's already a pull request for this feature: https://github.com/ccrisan/motioneye/pull/218

**Comment by MrNeuronix** [comment]
I'm waiting for this feature too!

**Comment by bmatic385** [comment]
Thank You for information.
