### ISSUE TITLE
Motion Detection with video recording - suggestion

### ISSUE THREAD

**Issue by niallie** [ccrisan/motioneyeos#127]
If the slow frame rate in movie recording mode is caused by CPU load of the motion detection daemon, how about this as a solution: 

Once motion is detected, the motion detection daemon is suspended for the user-specified duration of the movie clip. So if the desired clip length is 30 seconds (or 30 still images) for example, the daemon stops for this period, to allow the CPU to focus on capturing and writing the media file, then kicks back in once the media recording is finished.

The current trade off between motion detection and high quality video (specifying fast network camera, thereby disabling motion detection) defeats the purpose of using this as an unattended home security monitor.

**Comment by ccrisan** [comment]
Given that at the root of the solution lays the motion daemon which does all the hard work, it would be very difficult to implement what you proposed without a serious amount of work without making changes to the source code of motion, which I'm not willing to do.
