### ISSUE TITLE
Motion and recording

### ISSUE THREAD

**Issue by ZioLucione** [ccrisan/motioneyeos#1276]
Hello,
I have scheduled the recording times but I am not able to tell MotionEye to record EVERYTHING during the working hours even changing the Motion detection trigger values or other settings like seconds between the frames etc..
Do you have a standard configuration in order to achieve the total record during the working hours bypassing the motion detection?
Thank you for your help.
Regards.
L.

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
