### ISSUE TITLE
admin password changes itself

### ISSUE THREAD

**Issue by bscuderi13** [ccrisan/motioneyeos#1279]
Whenever I make a configuration change in motion eyeos that requires a reboot my password no longer works after the reboot. I'm unable to login... I just tried reinstalling a fresh image and resetting everything up. I changed the admin password and that worked fine I only made it as far as changing the timezone to az and it required a reboot. upon reboot I could again no longer login. :( Im running motioneyeos on an odroid xu4

**Comment by ccrisan** [comment]
What OS version?

**Comment by bscuderi13** [comment]
motionEyeOS 20171008

I just reinstalled again and this time I tried a password without special characters and it works

**Comment by ccrisan** [comment]
It's either the well known issue #1116 that has to do with browser's cache or it's some special character that motionEye is not happy with. You could list here the special characters you're using (in some random order) if you want me to try investigating it.

**Comment by bscuderi13** [comment]
just a $

**Comment by bscuderi13** [comment]
oh maybe its the browsers cahce cause its doing it again without special characters

**Comment by bscuderi13** [comment]
okay its resetting my password to ***** is there a fix or prevention for this yet?

**Comment by ccrisan** [comment]
Yes, that's the browser cache issue. Clear it, refresh and it will stop doing that.

**Comment by ccrisan** [comment]
In the meantime use five stars as password if you do not want to reinstall.

**Comment by bscuderi13** [comment]
thnak you clearing refreshing worked and its back to my old password

**Comment by adrian0** [comment]
This is an infuriating bug. 
I have one pi zero w that I have been trying to set up for days now. Probably spent 8 hours going around in circles and continuously finding that I get locked out of my camera and unable to log in using the password that worked on previous attempts.
I can't find a pattern to this. It's definitely not the cache issue.

When i say it's infuriating, I'm now giving up and trialling other options - zoneminder etc. Arrgh.
