### ISSUE TITLE
Can Motioneyeos receive web requests?

### ISSUE THREAD

**Issue by bscuderi13** [ccrisan/motioneyeos#1281]
I've seen where a lot of peoples posts that want the custom functionality of turning on or off motion detection turning on or off streams etc... All the posts I've seen they use scripts to disable the service. However I don't want to shut the whole thing down.  I have played around with the developer options in chrome trying to figure out what gets sent when you apply changes etc.. My question is I cant figure out what is being sent.. Does motion eyeos not rely on web requests to work? It seems as though this would be the easiest way for me to add external control of features that are already possible in the GUI. 
For example When I arrive home my home automation hub sends a web request that turns off motion on my cameras. I could also have it disable the streams of the inside cameras to be sure you aren't being watched while leaving the outside streams still accessible in case you want to pull it up but without recording or notifications. All these things are currently possible by going into the GUI but it would be the most useful to have it all happen on its own behind the scenes.

**Comment by ccrisan** [comment]
motionEyeOS uses motionEye which does HTTP requests to the server to do its stuff, just like any other web app. See [main.js](https://github.com/ccrisan/motioneye/blob/master/motioneye/static/js/main.js#L393) for ajax calls.
