### ISSUE TITLE
RTSP network camera updates slow?

### ISSUE THREAD

**Issue by briankeegan1** [ccrisan/motioneyeos#1282]
Hi. I've been playing around with this on my Raspberry Pi 3 to try and get it to serve as a dual surveillance system in addition to a ZP-NE14-S NVR I have set up with four cameras. I network into each individual camera by selecting network camera and inputting the string rtsp://192.168.1.xx:10554/tcp/av0_0. I am able to connect to my cameras, however it seems like there is significant latency between Motioneye and the camera to the point where the video is quite literally frozen and then it will suddenly jump ahead and catch up.

Here are some chronological screenshots illustrating what I mean. The timer in the top right is of the NVR and the timer in the bottom right is of Motioneye. Notice how Motioneye's timer changes but the NVR's doesn't. It's not updating quick enough. In the third screenshot, the video suddenly fast forwarded ahead.
![image](https://user-images.githubusercontent.com/24945329/34140846-751e993c-e44b-11e7-8a86-d30db2dd520f.png)
![image](https://user-images.githubusercontent.com/24945329/34140852-7db94c5e-e44b-11e7-930b-e54ab973dc28.png)
![image](https://user-images.githubusercontent.com/24945329/34140856-82a2326c-e44b-11e7-8536-d846b41cec17.png)

I tested this with just one camera to ensure that it wasn't because I was using multiple streams that it was overloading the RPi3. I also upped the framerate, lowered the resolution, etc. in the settings on the left sidebar. Same result, frozen video and randomly jumps ahead.
Is there a way to somehow reduce the latency or am I asking too much of my RPi3 and Motioneye to send data from the Camera->NVR->Modem->RPi3? Sorry if this is a stupid question, I don't have much experience yet in networking. Thanks!

**Comment by ccrisan** [comment]
The stream is processed by [motion](https://github.com/Motion-Project/motion) and the output images are also generated by it. This looks like receiving or processing the stream is somehow delayed. However this is not something motionEye(OS) can fix.

Make that sure your network connection is good enough and that the available CPU power is large enough to handle all the processing (by monitoring the CPU usage and system load on your PI3). Reducing the resolution and/or framerate may improve the delays.

If network and CPU are not an issue, then I recommend that you [report a motion issue](https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue) and see what they have to say about this.
