### ISSUE TITLE
Raspberry Pi Zero W and No MMAL Camera Option

### ISSUE THREAD

**Issue by roger-zacharczyk** [ccrisan/motioneyeos#1288]
When adding new camera there is no MMAL option.

Camera works as local camera (V4L2).

Thus there is no Fast Network Camera option.

Image used: newest raspberrypi (not raspberrypi2 or 3 because raspberrypi3 didn't start on Pi Zero W).

**Comment by ccrisan** [comment]
I'm sorry but I don't get what this is about. You listed 3 totally unrelated supported features of motionEyeOS. Could you be a bit clearer about what this issue is about?

**Comment by roger-zacharczyk** [comment]
The goal is to enable FNC. I think this is available for MMAL camera only. But there is no MMAL camera option when adding new camera.

**Comment by ccrisan** [comment]
You don't add FNC to motionEye. In fact FNC has almost nothing to do with motionEye. When in FNC mode, motionEye won't allow you to add or remove cameras - it will statically display the MJPEG stream of the preconfigured FNC.

One more thing: you enable the FNC from Expert Settings - you don't add it. I was under the impression that this was clear from the beginning.

**Comment by roger-zacharczyk** [comment]
Ok, let me describe what I did.

1. I wrote the raspberrypi image on sd card
2. Started my RPI Zero W with this sd card
3. connected to the ip:80 in web browser
4. there is no FNC option in the expert settings

**Comment by ccrisan** [comment]
Now I get it. What OS version is this? Can I see a screenshot of your expert settings?

**Comment by jasaw** [comment]
@roger-zacharczyk Did you manage to get the FNC option? If not, try running the latest firmware.

**Comment by jnovack** [comment]
While the motion version and the motioneye version are the same on disk, the websites are different.

Raspberry Pi 2:
![image](https://user-images.githubusercontent.com/387006/41573258-d0aad38c-7349-11e8-848f-b569ff716250.png)

Raspberry Pi Zero:
![image](https://user-images.githubusercontent.com/387006/41573265-df6c94aa-7349-11e8-87b3-ea7a2a0cde1f.png)

I'm pretty damn sure I used the same image.  I can also confirm there's no "Fast Network Camera".  What's going on?

**Comment by ccrisan** [comment]
You forgot to enable Advanced Settings.

**Comment by jnovack** [comment]
Today, it was me. 

![image](https://user-images.githubusercontent.com/387006/41593955-be073a36-738f-11e8-9fab-5d81807b4ea8.png)
