### ISSUE TITLE
Update motioneyeos WiFi Settings

### ISSUE THREAD

**Issue by Apuxa** [ccrisan/motioneyeos#129]
Hi,
when I update motioneyeos ,  old wifi settings are include ?
I ask because I installed the system in a cctv box, use a WiFi stick and cannot open the case easy again.

Thank you
Apuxa

**Comment by ccrisan** [comment]
Normally yes, all settings are kept across updates. However, if your motiionEyeOS box is hard to reach and if you're happy with your current version, you shouldn't upgrade.
