### ISSUE TITLE
Motion show frame changes showing "-"

### ISSUE THREAD

**Issue by drbeckma** [ccrisan/motioneyeos#1298]
For my motioneyeos set up, I only see numbers from the 'show frame changes' option for about 2-3 seconds, they vary from 0-100 or upwards of 90k depending on settings, but then it will switch to that hyphen, only going back to numbers when I change settings and hit apply, and even then only for a few seconds before turning back into the hyphen. 

Any ideas on what's up with that?

Thanks!

![capture](https://user-images.githubusercontent.com/11670805/34412547-f56d308c-ebab-11e7-8251-eba1f8f7ae2e.JPG)

**Comment by SteveCohen** [comment]
The number in the top RHS indicates the number of pixels that have changed since the last frame = amount of motion. It'll show "-" when there's no motion detected. [official docs are here](https://motion-project.github.io/motion_config.html#text_changes).

**Comment by ccrisan** [comment]
@drbeckma, @SteveCohen pointed you to the correct reference. If you don't want to see that, just disable the *Show Frame Changes* option.
