### ISSUE TITLE
Date is incorrect.

### ISSUE THREAD

**Issue by JoshSimply** [ccrisan/motioneyeos#13]
Raspberry Pi B+ running version 20151021 with the date settings as follows:

Date Method HTTP   
Date HTTP Host  google.com  
Date Updating Timeout    10
Date Updating Interval   900

Current time is 1207pm but the time stamp is showing 507pm. Did I mess up a setting? Not sure how to correct the time...

**Comment by ccrisan** [comment]
What timezone have you configured in the settings panel?

**Comment by JoshSimply** [comment]
I had it set to US/Central. I just tried setting is to America/Chicago, as
well as changing the time method to FTP. Is working now.

Josh Blair, PMP
(806) 773-6818

**Comment by SuneBielefeldt** [comment]
8
