### ISSUE TITLE
Automatic Brightness

### ISSUE THREAD

**Issue by OldHolborn01** [ccrisan/motioneyeos#1304]
Hello,

I suspect that "automatic brightness" does not work. With this setting, the image will pump from dark to light and back again, but it will not snap.

The problem I have both in Raspi 1, 2 or 3 in the various recent releases of motionEos
I tried this with V4L2 Camera

Can anybody confirm this?

Best regards
Reinhard

**Comment by OldHolborn01** [comment]
I tried this with V4L2 Camera
...

**Comment by causalityzach** [comment]
I suspect your camera already has autobrightness so the camera and Pi are caught in a loop of trying to adjust to each other. That is what happened in my case. Please see this page with a similar complaint I found when I googled the issue myself: https://github.com/ccrisan/motioneyeos/issues/864
