### ISSUE TITLE
RasPi2 + NoIR Camera Module V2

### ISSUE THREAD

**Issue by smartsoldier** [ccrisan/motioneyeos#1305]
The camera seems to be detected but the preview just shows the camera behind a non-smoking sign icon. vcgencmd get_camera shows 1 and 1. I have tried with fast network camera and not. No authentication. /etc/modules already has:
bcm2835-v4l2 max_video_width=1920 max_video_height=1200
bcm2835-wdt
i2c-bcm2708
i2c-dev
[logs.zip](https://github.com/ccrisan/motioneyeos/files/1596103/logs.zip)

The camera is confirmed working with normal Raspbian tests.
Edit: I am reading a firmware revert might fix the issue? How do I revert firmwares in MotionEyeOS?

**Comment by jasaw** [comment]
Were you running an older motionEyeOS version where the system was running fine, then upgrade to a later motionEyeOS version and camera stopped working after that? If yes, from which version to which version?
If no, have you tried a different SD card?

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
