### ISSUE TITLE
how can add users to motioneyeos / samba

### ISSUE THREAD

**Issue by lucapizz** [ccrisan/motioneyeos#1308]
Hi,

first of all, sorry for my english.
This is not a bug, so if I have to write else where, please tell it to me.

My problem: I am using motioneyeos on my rpi2 and rpi3, and it works fine, it is fantastic.

I have also an other rpi as samba server on debian but after a while get corrupted on power failure because it is not read only. After many reading and trying step by step guides I failed, there was always something wrong.

So I decided to use motioneyeos as (that is already readonly) also samba server and it works fine.
I would like to add an other user with different password from root but I am not able to do it.
I try adduser and so on but without success, so, if it is possible, can you suggest me the rigth way?
I think this may be useful to others too.

Thank you a lot in advance.
Bye

**Comment by ccrisan** [comment]
You can't add more users to the samba configuration of motionEyeOS. At least not easily, because user management is integrated with the UI. Sorry about that, but having multiple samba users is not a common use case for motionEyeOS.
