### ISSUE TITLE
Where script adminpasswd ?

### ISSUE THREAD

**Issue by fuentes277** [ccrisan/motioneyeos#1314]
hello
where this script adminpasswd or how ejecute?

**Comment by ccrisan** [comment]
`PASSWORD="yourpassword" /usr/sbin/adminpasswd`. What are you trying to accomplish by executing this script? Why can't you use the normal UI for that?

**Comment by fuentes277** [comment]
thank you!

**Comment by jasaw** [comment]
@fuentes277 Has your question been answered? Are you happy for me to close this issue?

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
