### ISSUE TITLE
Fast Network Camera AND Webcam possible?

### ISSUE THREAD

**Issue by olli84** [ccrisan/motioneyeos#132]
Hey there,

It's not an issue, but i didn't know where to post it.

Is it possible to use a CSI Camera in Fast Network mode and a USB Webcam at the same time?

Thanks for your hard work,
Oliver

**Comment by Banditen01** [comment]
Hi, yes it's possible, I use that combination. Reg B

**Comment by Banditen01** [comment]
Oops, sorry didn't read the question complete, I leave to somebody else to answer. I do not use this combo. 

//B

**Comment by shinji2009** [comment]
hi. also interested in this one. still no info?

**Comment by ccrisan** [comment]
This will *never* be possible on a single Raspberry PI.
