### ISSUE TITLE
How to update to Motioneye 0.38 and Motion 4.1 t?

### ISSUE THREAD

**Issue by Alpengroove** [ccrisan/motioneyeos#1321]
Hi!

I just updated MotioneyeOS over the browser update feature, as my camera is installed at a remote place. I use Raspberry Pi zero w.
The actual version should be 20180101

But it only updated to:

motionEye Version        0.37.1
Motion Version        4.0.1+git2a140fa
OS Version        motionEyeOS 20171008

How can I update to Motioneye 0.38 or later and motion 4.1?

It is important to do it in a "safe" way, because the camera is over one hour (by car) away. I have remote access via VNC to a Raspberry Pi in the same net as the Motioneye camera.

Martin

**Comment by ccrisan** [comment]
20170801 is a prerelease. You can enable prereleases from your Settings menu (Expert Settings). I do not recommend however updating if the camera is in a remote place and you're not comfortable reflashing it in case of an error. Don't fix it if it ain't broken!
