### ISSUE TITLE
motionEye with ip6

### ISSUE THREAD

**Issue by glanghei** [ccrisan/motioneyeos#1325]
Hi, everyone,
I want to run motionEye with ip6. But I can't get the configuration right. motionEye is not started with interfaces in /etc/network but with a script. Actually it's easy, you have to switch on the ip6 protocol with the entry "iface[wlan|eth]0 inet6 auto" in the file "interfaces". If someone has an idea in which script and in which line the entry should be made. 
I use Raspberry Zero W with Raspberry-Camera,  motionEye with the default configuration.

**Comment by ccrisan** [comment]
IPv6 is disabled in motionEyeOS due to many issues raising from users with misconfigured networks. If you must use IPv6, I recommend installing Raspbian + motionEye.

**Comment by jordipalet** [comment]
Running latest motioneye version in a dual-stack box. If I set in motioneye.conf
listen to ::
it works with IPv6-only
tried ::, 0.0.0.0 and :: 0.0.0.0 and ::;0.0.0.0 and also those with "" and '', no luck ...

but doesn't work
What is the right config to make it dual stack?

I see that changing in /usr/local/python2.7/dist-packages/settings.py LISTEN = "" it works, but I guess is not the best place to configure it, as it may be modified by an update?

**Comment by starbasessd** [comment]
Probably safe at this point, as they are actively working to get rid of pythin2.7 anyway.
