### ISSUE TITLE
Using a url to activate action button

### ISSUE THREAD

**Issue by momoster69** [ccrisan/motioneyeos#1329]
I just set up an action button and I was wondering if there is a way to use a a url to trigger the action button?. Something like accessing:  http://192.168.x.x/action/1/unlock/. I did however get a link through using network developer tools in order to obtain a link just like above however it had a username and signature... not a username and password (seen the username and password from another post here).

**Comment by ccrisan** [comment]
That's the way motionEye works - the password is never sent in clear but a signature algorithm is used instead. See https://github.com/ccrisan/motioneye/blob/master/motioneye/static/js/main.js#L346 for details on the implementation.
