### ISSUE TITLE
rtsp: Unable to open video device

### ISSUE THREAD

**Issue by Marthinius** [ccrisan/motioneyeos#1330]
Hello,

First I tried installing motioneye on ubuntu 16.04 with armbian without success (some error). 
So I installed a motioneye OS to OrangePi One. Motioneye has started successfully, I added ip camera over rtsp protocol. The motionEyeOS config detect my ip camera but it says unable to open device with gray window. I can open the stream with VLC correctly with that rtsp URL. 
So URL works with VLC but does not with motionEye. 

I tried not only ip camera, but also usb camera still the same problem: Unable to open video device.

**Comment by Marthinius** [comment]
I reinstalled everything again ....Solved

**Comment by frobgm** [comment]
Marthinius, how do you add rtsp protocol to motioneye os?
thanks yours help!
