### ISSUE TITLE
Unable to add remote camera

### ISSUE THREAD

**Issue by someevil** [ccrisan/motioneyeos#1335]
Hi, 

I have successfully got my Raspi Zero W setup with a pi camera connected, this works great. 

I have just added a 5MP Night Vision Camera OV5647 to a separate Rasberry Pi 3, this has a local IP of 192.168.1.7, I have enabled the camera in the pi 3 settings, and I am wondering what else is required of me to add this camera to my camera server running on the Pi Zero W?

I see the setting options i am trying are: 

**Camera Type** >> Local Camera>>Network Camera>>Remote motionEye Camera>>Simple MJPEG Camera 
**URL** >> http://192.168.1.7:80
**Username** >> [blank]
**Password** >> blank]
**Camera**

I am assuming there is more required of me, as I am seeing the error 
_Failed to connect to 192.168.1.7 port 80: Connection refused_

I am assuming this would be a network camera?

Any guidance would be greatly appreciated. 

Thanks in advance.

**Comment by ccrisan** [comment]
What are you running on your PI3? What OS, what version of motionEye(OS)?

**Comment by someevil** [comment]
Pi 3 is running 2017-07-05-raspbian-jessie

Pi zero is running:
motioneyeos-raspberrypi-20171008.img
motionEye Version  0.37.1
Motion Version  4.0.1+git2a140fa

**Comment by ccrisan** [comment]
And what version of motion/motionEye on Pi3? What motionEye configuration? Some config files, logs, screenshots, anything.

**Comment by someevil** [comment]
I suppose that is my overarching question, do I have to have motionEyeOS installed on the Pi 3? 

I have other things running on the pi3 so I didn't want to have to start from scratch (by that I mean installing a fresh copy of MotionEyeOS onto a card for Pi3) if I could simply setup some kind of streaming from the camera on the Pi3 that could be picked up from the zero.

Do I have to start the pi3 with a clean install for this to work?

[motion.log](https://github.com/ccrisan/motioneyeos/files/1655279/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1655280/motioneye.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/1655281/messages.log)
[Uploading boot.log…]()
[Uploading dmesg.log…]()

**Comment by someevil** [comment]
I was just now able to work out how to do it without wiping my existing Pi3 OS, I used this tutorial.

The trick I had to do, when I had it running I had to enable MJPEG STREAM, then I copied the URL (looks like this - http://192.168.1.7/html/cam_pic_new.php?time=1516700719592&pDelay=40000)
Selected Network Camera.

Thanks anyways

**Comment by ccrisan** [comment]
You don't have to install motionEyeOS on your PI3 but I assume you have at least motion or motionEye installed on your Raspbian. Otherwise how would you expect your camera to be exposed over the network?

The logs you sent are from your Pi Zero W (since it's the one running motionEyeOS). These aren't of any interest, given that your Pi3 is the one that refuses connection on port 80.

**Comment by someevil** [comment]
> I assume you have at least motion or motionEye installed on your Raspbian.
Now here lies your first mistake, that is what I was trying to find out, is there something I can install on my pi 3 to get it broadcasting etc... my initial question was _I am wondering what else is required of me to add this camera_, it seems the answer was motion or motionEye is the answer is was looking for,
Cheers

**Comment by ccrisan** [comment]
@someevil you could install plain motion or MJPEG streamer but in that case it would be no longer a motionEye(OS)-related issue.

**Comment by someevil** [comment]
> @someevil you could install plain motion or MJPEG streamer but in that case it would be no longer a motionEye(OS)-related issue.

That is correct, but asking what is compatible with motionEyeOS is related to this GIT, hence me asking it here. 

Thanks

**Comment by someevil** [comment]
For future me (if I forget how to do this and I end up here again looking for this same answer), this is what I believe I was looking for - https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian
