### ISSUE TITLE
MotionEye that often goes down

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#1336]
This MotionEye installation, which is one out of 10, often fails to be restarted, after which it can run for several days without fail, yet it goes down again.

Is it possible to derive from the attached log file what is the reason for it going down?

[messages.log](https://github.com/ccrisan/motioneyeos/files/1651835/messages.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/1651836/boot.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1651840/motioneye.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/1651841/motion.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/1651846/dmesg.log)

![biscam01](https://user-images.githubusercontent.com/9556987/35220408-90738102-ff76-11e7-9069-9a1468f307ec.PNG)

**Comment by ccrisan** [comment]
Your messages log file says (among others):

    Jan 20 01:54:07 Biscam01 user.notice wifi: disconnected
    Jan 20 01:54:12 Biscam01 user.notice wifi: disconnected
    Jan 20 01:54:17 Biscam01 user.notice wifi: disconnected
    Jan 20 01:54:22 Biscam01 user.notice wifi: disconnected
    Jan 20 01:54:27 Biscam01 user.notice wifi: disconnected
    Jan 20 01:54:29 Biscam01 user.notice netwatch: cannot connect to www.google.com:80

This indicates poor connectivity via WiFi. I generally recommend using wired connection when dealing with video streaming. If that is not a possibility, make sure your WiFi router connection is strong and that you're using a stable and well performing WiFi router.

The same applies to your WiFi adapter that should be able to handle large amounts of traffic. You should also make sure the power supply is good and the voltage on your WiFi adapter does not drop below 4.75V.

**Comment by SuneBielefeldt** [comment]
Thank you for your input Calin
I must try to improve all conditions so that it can run steadily.
