### ISSUE TITLE
cannot write latest motioneyeos image to SD card

### ISSUE THREAD

**Issue by AhmedSalad** [ccrisan/motioneyeos#1338]
hello,

i seem to be getting a "SD not formatted. format SD card before you can use it" popup when i write the latest raspberry pi image to my SD card. ive used different SD cards thinking it was that but to no avail. i also tried downloading the ZIP file but windows does not fine  an image once the file is unzipped.

maybe it has something to do with having to delete ".gz" off the img before windows can recognize motioneyeos as an image? help!

**Comment by jasaw** [comment]
You can't just delete the .gz extension. You need to extract the file first.

**Comment by AhmedSalad** [comment]
Even if i download just the image file? I inderstabd extracting the zip. Sorry if this is a terrible question. Im just stuck stuck. Lol

**Comment by jasaw** [comment]
All the files available for download are gz compressed, so you'll need to extract the `img` file from it.
Here's a guide on how to extract a gz file: https://www.wikihow.com/Extract-a-Gz-File
Hope that helps.

**Comment by AhmedSalad** [comment]
Awesome! Thank you!!!!

**Comment by jasaw** [comment]
Issue appears to be resolved. Closing issue.
