### ISSUE TITLE
Feature Request: NTP server choice in GUI

### ISSUE THREAD

**Issue by lozziboy** [ccrisan/motioneyeos#134]
I ask for the possibility to customize the choice of the NTP server in the GUI

**Comment by funtomas** [comment]
me too 
i want use my local server like ntp server

**Comment by ccrisan** [comment]
Implemented with 908fb59ed10f0fb301c631c04c48a5b6a3f22b14 and f45885aeb9fa7c4dd5458c522a42e221d03839e5.

**Comment by funtomas** [comment]
thanks

**Comment by lozziboy** [comment]
Thanks Calin
