### ISSUE TITLE
Can't seem to get it to upload to the right GDrive folder

### ISSUE THREAD

**Issue by prexer** [ccrisan/motioneyeos#1340]
I've got a folder-id in my Google Drive account that I want to upload to.  It's in the /drive/shared-with-me/motionEye space, which is what the path to the folder looks like in the browser. 

When I specify the path with /shared-with-me,   it creates a new folder that is not the magic "Shared with me" folder.  

Is there a way to specify the folder-ID?

**Comment by ccrisan** [comment]
You're mixing up folder ids with URLs and google drive paths:
 * Folder ids are something you're not supposed to ever deal with, as a user.
 * The URL you're seeing in the address bar is also something you should not have to deal with.
 * Google Drive path is the one you're interested in and should probably look like `/motionEye`.

This being said, `/drive/shared-with-me/motionEye` is nonsense.
