### ISSUE TITLE
Can not APPLY my changes anymore

### ISSUE THREAD

**Issue by AST64** [ccrisan/motioneyeos#1345]
After doing some changes e.g. framerate or motion detection and pressing APPLY it always results in an error. When I reboot everything works again sometimes with the made changes sometimes not.

**Comment by ccrisan** [comment]
Please attach your motioneye.log file.

**Comment by AST64** [comment]
[motioneyeLOGFILE.log](https://github.com/ccrisan/motioneyeos/files/1667997/motioneyeLOGFILE.log)

Thank you ...

**Comment by ccrisan** [comment]
Your issue has been fixed via https://github.com/ccrisan/motioneye/commit/aef68011a811b681187d820dc2121807f7a2e5c3. It will be part of the next motionEyeOS stable release.

Until then, a possible workaround would be to supply a Network Share username.
