### ISSUE TITLE
Question: Show frame changes

### ISSUE THREAD

**Issue by mb39924** [ccrisan/motioneyeos#1350]
I have Motion Detection enabled and turned on Show Frame Changes.

Works great but I just noticed the text under te question mark says: ".. temporarily enable this option to .."

Why does it say 'temporarily'? does this function eat a lot of cpu?

Just curious :)

**Comment by ccrisan** [comment]
Usually users are not interested in having the frame change indicators permanently shown on their movies. Normally that's something you want to see only during the setup phase.

**Comment by mb39924** [comment]
Thanks for the quick reply. It helps me to quickly see if the detected motion is a raindrop on my window so I can ignore it or a real motion outside.
