### ISSUE TITLE
No attachments in notification emails

### ISSUE THREAD

**Issue by mireksochor** [ccrisan/motioneyeos#1354]
No attachments in notification emails :(
- Attached Pictures Time Span: 5
- Capture Mode: motion triggered (one picture)

motionEye Version | 0.38
Motion Version | 4.1
OS Version | Raspbian 9.1
Raspberry Pi B

apologies, I am new here:)

**Comment by ccrisan** [comment]
Have you checked https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails?

**Comment by seb276** [comment]
I install the latest version motioneye on Raspi3 and I have got mails with attachments with "motion triggered" but not with "motion triggered one picture".

Do you have and idea?

Thanks a lot

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails

**Comment by seb276** [comment]
Thanks, I read FAQ before and I configure Attached Pictures Time Span to a reasonable amount of seconds (30).

"motion triggered one picture" is working for you?
