### ISSUE TITLE
PI2 Unable to open video source after update

### ISSUE THREAD

**Issue by KiwiNibbler** [ccrisan/motioneyeos#1355]
Hi all,

I had a dead camera for a couple of months.  Yesterday I decided to rebuild it and get it back online.  All good.  But I noticed that there was a new version available (I ticked the box to get pre-releases).  So I upgraded the camera I rebuilt.  All good.

I decided to update my other two as well.  Half good.  One of them is fine; the other now shows the grey screen of death.  Camera two and three are identical in every way.  Same IR Camera (Which is why the colors may seem slightly off on camera 2).  But camera 3 did not like the upgrade.

All three cameras have the exact same configuration with the exception of camera names and IP addresses obviously.  A bit disappointing since camera 3 had been my most reliable historically.

![capture](https://user-images.githubusercontent.com/8879727/35587737-89b4353e-0663-11e8-8d99-f419f7ffee59.JPG)

I have logs but would prefer to not post them publicly.

**Comment by ccrisan** [comment]
Without logs (specifically motioneye.log) I won't be able to help you.

**Comment by KiwiNibbler** [comment]
Hi there,

I wasn't sure which log files would be most useful.  Here is my motioneye.log.  Debugging is on.  

Before grabbing the log, I did a reboot.  I also checked disk usage.  It has used .5 Gb of 14.5 Gb, so no issue on free space.
[Camera 3 Motioneye.zip](https://github.com/ccrisan/motioneyeos/files/1683114/Camera.3.Motioneye.zip)


Any insight would be greatly appreciated.

**Comment by KiwiNibbler** [comment]
It just occured to me that camera 2 and 3 have similar cameras, but not identical.  They used to be identical but the IR part of camera 3 died and I replaced the whole thing about six months ago.  It is a slightly different version, although nearly identical.  If that makes a difference.

**Comment by ccrisan** [comment]
Do you have 3 different Raspberry PIs? Or do you have a single one with 3 cameras connected locally? You mentioned updating 3 cameras and I assumed you meant 3 Raspberry PIs. Now you have sent me a motionEye log file that shows multiple cameras connected to same board. This doesn't make too much sense.

**Comment by KiwiNibbler** [comment]
I have three different PIs.  I inadvertantly sent you the logs from the headend, not the camera that is having issues.  I'll get a new log when I get home for just that one camera and post it.

**Comment by KiwiNibbler** [comment]
I did a hard reboot (turned off - turned back on) the faulty PI.  It is fine now.  I didn't realize that when I was getting logs from a head-end device, even if I have selected one of the other devices and clicked settings for it, it gets the logs for the head-end.
