### ISSUE TITLE
Super Mini 600TVL Mini Camera

### ISSUE THREAD

**Issue by jepolch** [ccrisan/motioneyeos#1356]
Calin, does motionEyeOS have support for this camera?

https://www.catalystmachineworks.com/collections/fpv-components/products/super-mini-600tvl-fpv-camera

**Comment by ccrisan** [comment]
This looks to me like an analog camera. Unless you find some kind of converter (video grabber I think it's called) that will transform the signal into a digital stream, it won't work with motionEyeOS.
