### ISSUE TITLE
red tint to video on both new pi z W and pi 3

### ISSUE THREAD

**Issue by madkatmando** [ccrisan/motioneyeos#1358]
just set up a pi zero w with the night vision camera and a pi 3 with the NoIR v2 camera.  Both have a pink/red tint to the pics and video.  A did a search and could really only find something about a bug back in 2014 but it wasn't for the MotionEye OS.  

is there anything i may have setup incorrectly or i should check?

Thanks
Kevin.

**Comment by mb39924** [comment]
That's normal because you are using camera's without an infrared filter.

https://youtu.be/OPdNzmP4Bm0

**Comment by ccrisan** [comment]
@madkatmando does this answer your question?

**Comment by madkatmando** [comment]
Ha. yeah that makes sense, Thanks for the replay @ccrisan and @mb39924. first time working with these, guess that shows.

thanks again for the quick responses
Kevin.

**Comment by madkatmando** [comment]
closing - thanks again.
