### ISSUE TITLE
Can you add nload (or something equivalent) to MotionEyeOS?

### ISSUE THREAD

**Issue by WentPostal** [ccrisan/motioneyeos#1359]
I looked around and I didn't really see anyone else asking for this.  However... I did not that it is commented on very often that using FNC as an option takes up more bandwidth.  I wanted to test out that theory but I cannot add packages to the OS (and FNC does not appear to be an option for motioneye on raspbian (though I am sure it can be done with steameye).  

At any rate... I saw that nload was in the packages of the source but the binary does not appear to be on the build (unless I am missing it somewhere).

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives.

If you want extra packages added, you can either [compile from sources](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) or use Raspbian.
