### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by JoeRelic** [ccrisan/motioneyeos#1361]
I am aware that motioneye.conf needs to be edited to recover a forgotten password, but how is that done from a Windows 10 machine?

**Comment by maglub** [comment]
# FAQ

* https://github.com/ccrisan/motioneyeos/wiki/FAQ#how-can-i-recoverreset-the-admin-password

```
Unfortunately there's no easy way to recover or reset your admin password. You'll need a computer running Linux and capable of mounting your ext4 partition from the SD card. Identify the data partition (normally the largest one) and look for the file /etc/motion.conf (on a live system it's /data/etc/motion.conf). Just clear out the value at the end of the line starting with # @admin_password.
```

# References

* http://www.ubuntugeek.com/how-to-read-ext3ext4-linux-partition-from-windows-7.html
