### ISSUE TITLE
PTZ with Logitech Orbit AF?

### ISSUE THREAD

**Issue by madryboy** [ccrisan/motioneyeos#1366]
so ive come to a little bit of a bump in the road as how i add pan and tilt capabilities to this i do understand that you have to add an executable file in the configuration folder that points to the device you want and lists the action that you would like it to do but how would i go about controlling or programming that executable to move a camera that has internal PTZ controls? its a Logitech Orbit AF just as a reference and thank you to anyone who can actually help me out with this or if this is in the wrong spot/location please feel free to remove this post

**Comment by ccrisan** [comment]
The internals of actually controlling the camera PTZ are beyond the scope of motionEye. Please refer to docs/forums/groups specific to your camera model and see if there's an open standard or some kind of revese engineering-based method to do that.
