### ISSUE TITLE
motioneyeos for ARMv7

### ISSUE THREAD

**Issue by ssridhar2065** [ccrisan/motioneyeos#1372]
Can we get a compilation package for ARMv7 with GNU-ARM cross compiler?
I had seen some ARM compilation instructions and I believe this has compatibility to compile and use with ARM processors.

If you can guide us it would be great.

**Comment by ccrisan** [comment]
motionEyeOS is already built for a few ARMv7 boards with the GCC cross compiler. [These](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) are the instructions on how to build it yourself.
