### ISSUE TITLE
USB Camera, mjpeg stream from it

### ISSUE THREAD

**Issue by molly78** [ccrisan/motioneyeos#1377]
I have a ELP USB 5MP fisheye camera that gets 2fps via its YUV stream

However I have confirmed that it will do 13-15 fps via it's mjpeg stream

 ffmpeg -f dshow -video_size 2592x1944 -framerate 15 -vcodec mjpeg -i video="HD USB Camera" out.avi

How can I transfer these settings to motioneye OS - I only need it to be a fast network camera...

**Comment by ccrisan** [comment]
Fast Network Camera doesn't work with USB cameras. It only works on Raspberry Pi boards with Raspberry Pi cameras.

You can't have a custom ffmpeg command running as a backend for motionEye. Your best bet is to see if you can instruct motion to use MJPEG using `v4l2_palette` in *Extra Motion Options*.
