### ISSUE TITLE
File storage

### ISSUE THREAD

**Issue by tjspragg** [ccrisan/motioneyeos#1379]
Hi! 

I'm really enjoying using this OS - it's really very user friendly! One issue I am having is with File Storage on Dropbox or Google Drive.

No matter how I try to set it up - I seem to receive the same error 'Accessing the upload service failed !'

Do you have any advice on how to go about fixing this? Any advice would be appreciated!

Tomas

**Comment by ccrisan** [comment]
Maybe if you let us know how you configured your upload services, we could offer some help. Screenshots are welcomed.

**Comment by tjspragg** [comment]
Thanks! Here's the screenshot! 
![screenshot 2018-02-18 22 16 20](https://user-images.githubusercontent.com/36174449/36357106-733e7478-14f9-11e8-9684-928102c5ab75.png)

**Comment by ccrisan** [comment]
And do you actually have a folder named `home` with a subfolder called `CCTV` in your Dropbox?

**Comment by tjspragg** [comment]
Yep - very sure. I had the same issue when using Google Drive and Dropbox
(with identical file structures).

**Comment by ccrisan** [comment]
@tjspragg let's see some logs then. `motioneye.log` would be of interest. Please enable debugging in Expert Settings first.

**Comment by tjspragg** [comment]
Enabled and attached! :) 
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1754765/motioneye.log)

**Comment by ccrisan** [comment]
@tjspragg you have a lot of errors that are consequences of wrong date/time. Please make sure your system can access the internet and has the correct date/time. My personal feeling, judging by the following errors, is that your DNS server, or in general, your network connection is problematic:

    dropbox: failed to obtain credentials: <urlopen error [Errno -3] Temporary failure in name resolution>

or 
    
    1970-01-01 01:07:06: [motioneye]    ERROR: dropbox: failed to obtain credentials: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
