### ISSUE TITLE
Question about the recorded video

### ISSUE THREAD

**Issue by dutchronnie** [ccrisan/motioneyeos#138]
Hello,

I have a question, i don't know if this is the right place, but i have been searching for a forum but can not find one. 
when there is motion, there is a video recorded, but my video's have only 1 picture every 4 seconds.
I have changed the frame rate, but i didn't get better pictures.
How can i set this to get a smooth video?

And is it possible to add a record button?
So i can make a video or picture when i want that to do.

Thanks, Hoping to hear soon.

**Comment by chfakht** [comment]
I have the same issue , have you tried to add more GPU Memory and overclocked ?

**Comment by ccrisan** [comment]
If it's a RPi1 you're talking about, then you're probably using a relatively big resolution and the processing power offered by your PI is not enough (hence the frame skipping). Try reducing both resolution and frame rate and see if the problem persists. I suggest using 640x480@5fps with a RPI1.

**Comment by chfakht** [comment]
@ccrisan  what about overclocking the GPU ?

**Comment by ccrisan** [comment]
@chfakht it doesn't make too much of a difference. It may give you a 20% performance boost but that's not really sensible.

**Comment by dutchronnie** [comment]
I am using a RPi1, and with a resolution of 640X480 and a framerate of 6, i shall change that to 5

**Comment by ccrisan** [comment]
Not really. Then your problem may be different. Please attach all of your logs. Maybe I can spot something fishy. You could also post your configuration (either a screenshot or your config files) *removing sensitive data*.

**Comment by dutchronnie** [comment]
I am trieing to attach the log files, but the window does not accept *.zip

**Comment by dutchronnie** [comment]
![logfiles](https://cloud.githubusercontent.com/assets/16868762/12590319/a2d67e72-c462-11e5-95bc-5dd5d0f1f307.gif)

ok, i have renamed the zip file to a gif, you have to rename it again to a zip.

**Comment by dutchronnie** [comment]
Is there a way to manually start the record of an avi, so i can see how much frames are in it?

**Comment by ccrisan** [comment]
I'm sorry but you haven't managed to attach the logs. No, there is no record button.

**Comment by dutchronnie** [comment]
![messages](https://cloud.githubusercontent.com/assets/16868762/12590446/5fd98e6a-c463-11e5-8fc9-47af19003531.gif)
![motioneye](https://cloud.githubusercontent.com/assets/16868762/12590447/5fd9d00a-c463-11e5-8882-8de7464dfc0f.gif)
![motion](https://cloud.githubusercontent.com/assets/16868762/12590445/5fd8b38c-c463-11e5-8696-59c687260f98.gif)
![dmesg](https://cloud.githubusercontent.com/assets/16868762/12590449/5fde1b9c-c463-11e5-943c-719c26993471.gif)
![boot](https://cloud.githubusercontent.com/assets/16868762/12590448/5fdd1aee-c463-11e5-916f-7d5f0331e8cc.gif)

Now the logfiles seperate, also renamed to a *.gif

**Comment by dutchronnie** [comment]
How can i send the logfiles?

**Comment by ektus** [comment]
Downloading the archive https://cloud.githubusercontent.com/assets/16868762/12590319/a2d67e72-c462-11e5-95bc-5dd5d0f1f307.gif did work, I was able to save it as .zip and open same, but that's no use as I can't read much from them. I did a re-upload of the file as zip, see below.
[a2d67e72-c462-11e5-95bc-5dd5d0f1f307.zip](https://github.com/ccrisan/motioneyeos/files/105467/a2d67e72-c462-11e5-95bc-5dd5d0f1f307.zip)

**Comment by dutchronnie** [comment]
Calin I Have send the log files by mail.

**Comment by ccrisan** [comment]
@dutchronnie here are a few notes:

* Your boot.log shows many reboots without a proper shut down. Have you cut the power of your motionEyeOS many times? Are you using a powerful enough PSU?

* You seem to be using a network share for storage. That could pose problems if the network connection is troublesome. Please try saving movies locally (on the SD card) and see if the problem persista.

**Comment by dutchronnie** [comment]
When i change some settings, Motioneyeos  wants to reboot sometimes, I have only 1 or 2 times did a reboot.
I asume that when motioneyeos wants to reboot, he does a proper shutdomn.
I am using de Rpi 1 model B
In the settings GPU = 128

Yes i am using a network share, it's a harddrive connected to the router with USB 3.0
The Pi has a wired network connection.
I will try to store the files localy.

The google drive option is not working on my system, so i can only store 32GB.
