### ISSUE TITLE
Remote viewing

### ISSUE THREAD

**Issue by gerrypdonnelly** [ccrisan/motioneyeos#1383]
Prob doing something stupid...
I have port 80 internal forwarded to external 8081.
Protocol TCP/UDP
When on the home network i get a picture no problem.
When I remote in I get the motion eye but instead of an image I get a camera with a line through it.
I have fast internet camera enabled and I am using the raspberry pi camera.

**Comment by ccrisan** [comment]
Fast Network Camera works on port 8081 ("internally"). Port 80 is used only to display the UI. Just use the following port forwarding setup:
 * 8080 -> 80
 * 8081 -> 8081
