### ISSUE TITLE
Bluez package

### ISSUE THREAD

**Issue by sfgabe** [ccrisan/motioneyeos#1387]
Has the Bluez package disappeared on motionEyeOS 20180101? 
bluetoothctl and hcitool commands have stopped functioning.

I'm on a pi zero w and ultimately trying to connect to a bluetooth speaker.

**Comment by ccrisan** [comment]
The Bluetooth functionality was never meant to be part of motionEyeOS. It got there by mistake. With recent versions, adding significant to the OS would increase the root partition usage, requiring a resize, which is not possible with the current firmware updating mechanism.

However if you must have Bluetooth with motionEyeOS, I recommend [building from source](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) after customizing it as you desire.
