### ISSUE TITLE
Web interface not accessible after overclocking 

### ISSUE THREAD

**Issue by iappletom** [ccrisan/motioneyeos#1391]
Hi, 
I need some help and advice here.
I over clocked my RPI 2 B to turbo using the MEyeOs interface and now it isn’t allowing me to access it to change it back. I really need to find a way to change the over clocking settings back to before. Is there a way I can do this easily, or could someone possibly tell me how to do it? 

Thanks so much! :)

**Comment by jasaw** [comment]
Pull out the SD card from the Pi, plug it into your computer. Open config.txt in the "Boot" partition.
Remove these lines:
```
arm_freq=xxxx
gpu_freq=xxx
sdram_freq=xxx
over_voltage=x
```
