### ISSUE TITLE
Adafruit TFT Pi Display installation

### ISSUE THREAD

**Issue by scott4205** [ccrisan/motioneyeos#1395]
Trying to add adafruit repo for pi tft display support. It appears that the MotionEyeOS has the relevant directories stripped out. 

Running this command;
`curl -SLs https://apt.adafruit.com/add-pin | bash`

following errors;

```
/etc/apt/sources.list 
/etc/debian_version
no such file or directory

wget
apt-key
command not found
```
 etc 

Is there a workaround solution to enable the display support or allow the repo onto the OS?

**Comment by mb39924** [comment]
Install motioneyeos on top of raspbian would be my guess.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives
