### ISSUE TITLE
How to build motionEyeOS from scratch

### ISSUE THREAD

**Issue by chfakht** [ccrisan/motioneyeos#140]
Hi , i want to build motionEyeOS from scratch (starting from buildRoot) because i want to customize it by adding some other packages that doesn't exist : let say that i want to install opencv to add some features like face detection or recognition ... can you tell me mr @ccrisan where to start ...
thanks a lot

**Comment by ccrisan** [comment]
[This](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) is a good place to start.

**Comment by jazeph** [comment]
> Hi , i want to build motionEyeOS from scratch (starting from buildRoot) because i want to customize it by adding some other packages that doesn't exist : let say that i want to install opencv to add some features like face detection or recognition ... can you tell me mr @ccrisan where to start ...
> thanks a lot

Did you have any luck on this? I am interested in the same...
