### ISSUE TITLE
Video download format?

### ISSUE THREAD

**Issue by iappletom** [ccrisan/motioneyeos#1401]
Hi,
I have set my camera to record video to motion and capture in HEVC .MP4.

For some reason when I download the video, it exports to .MP4.MPG
The .MPG seems to override the .MP4 format.

Anyway I can fix this?

Thanks! :)

**Comment by ccrisan** [comment]
Fixed in motionEye [0.38.1](https://github.com/ccrisan/motioneye/releases/tag/0.38.1), which will be part of the next stable motionEyeOS release.
