### ISSUE TITLE
Manual Update to the OS

### ISSUE THREAD

**Issue by sashsc** [ccrisan/motioneyeos#1403]
Therefore i´ve installed the Motioneye manual throu the alternative method.
How can I update the OS from 4.1 to 4.1.1 ?

It runs on Raspian Stretch and on a raspi 3

I´ve tried "apt-get update" and "apt-get upgrade" via putty.

But it takes no effect.

Greeting
Sascha

**Comment by ccrisan** [comment]
Short answer: no.
Long answer: you're mixing up projects and versions. You're running motionEyeOS, which is an OS hosting motionEye + motion. Judging by the version you mentioned, you want to upgrade motion. You'll have to wait till the next motionEyeOS release or use Raspbian.
