### ISSUE TITLE
Cannot access admin interface after change port to 8081

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [ccrisan/motioneyeos#1407]
Hi,
I Change my network port to 8081. When I access my address:8081 I see the streaming only. How can I access my admin interface back? I already try though 80.

Is it possible to roll back my port settings to 80 though SSH?

**Comment by ccrisan** [comment]
Port 8081 is already used for "raw" MJPEG video streaming. You should use a different port for the UI. You can change it via SSH. See:
 * https://github.com/ccrisan/motioneyeos/wiki/motioneye.conf
 * https://github.com/ccrisan/motioneye/wiki/Configuration-File#port
