### ISSUE TITLE
Wifi setting switched off automatically

### ISSUE THREAD

**Issue by downbike** [ccrisan/motioneyeos#1408]
Hi

I have been using motioneyeos with raspberry pi 3 and the official camera. I have it set as wireless connection with continuous recording and deleting files older than 4 days. I also set it with static IP address as well. 

Everything was working fine until 2 weeks ago when I can't connect wirelessly to it anymore. After connecting it to a monitor I notice that motioneyeos is trying to connect via a wired connection instead of the wireless one. 

Plugging into the Ethernet cable and I was able to access the web interface which confirmed that the wireless setting is off. However, I never turn it off and the admin is password-protected.  I have attached the boot and motioneye log file. Please let me know if you need the other 2 log files. 

Looking at the motioneye log file I notice that there are instances in which there is no more space in the drive anymore. Is that the reason motioneye automatically switched to a wired connection? 

[boot.log](https://github.com/ccrisan/motioneyeos/files/1759539/boot.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1759540/motioneye.log)

Thank you for your help. The motioneyeos is very cool. Thank you for your work in the project

**Comment by ccrisan** [comment]
You are running out of space on your data partition:

    IOError: [Errno 28] No space left on device

Many things (including WiFi configuration) may turn south if there's no more space on that partition. You might be lucky removing some media files. Otherwise you'll need to rewrite your SD card from scratch.
