### ISSUE TITLE
downloaded video won't play properly after upgrade to 20171008

### ISSUE THREAD

**Issue by atvinnys** [ccrisan/motioneyeos#1411]
Hi all

I can play the video recordings via the samba server just fine. (win10 terminal, using VLC)
but if I transfer the mp4 either via a simple copy to my desktop from an explorer or via the download option of the web GUI, and then play the video, it will not play properly: it shows the first image only and rolls thru time but the video is stuck on that first image.

I went back in time and I have not this problem with the previous version I was using (maybe 2 versions back). 
not quite sure what to make of this....
any idea?
thanks
vincent

**Comment by jasaw** [comment]
What did you use to play the recorded video? Try another player (not VLC).

**Comment by mb39924** [comment]
I had this problem also  with previous versions using vlc. For motioneyeos mp4 downloads I use windows mediaplayer.

**Comment by atvinnys** [comment]
I also remembered I upgraded VLC around the same time ..so I loaded up MPC and it works there.
so VLC is the issue here.

thanks for the input!
