### ISSUE TITLE
Wifi preconfiguration problem

### ISSUE THREAD

**Issue by berniemci** [ccrisan/motioneyeos#1416]
Hi, I followed the guide for Windows wifi preconfiguration to set up wpa_supplicant.conf. When I start the initial boot without an ethernet connection, it gets stuck on configuring wired network and goes into a loop.

Are the instructions up to date. I have a tried a number of times already without success.

**Comment by jasaw** [comment]
Presumably you followed this wifi pre-configuration guide: https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration
Have you read the wifi troubleshooting page? https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems

Do you mind posting your wpa_supplicant.conf file with SSID and psk masked out?
What hardware do you have? Is your wifi adapter supported? Some more details on your hardware set up might help.
Which version of MotionEyeOS are you running?

**Comment by berniemci** [comment]
Thanks for your response, Please close the issue. When using Notepad the file was saved as a text file in error. The instructions are fine.
