### ISSUE TITLE
Feature Request : Loop Recording

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [ccrisan/motioneyeos#1423]
It would be very useful a Video Storage option Called "Loop Recording", to delete the oldest video for record a new video if you card is full.

**Comment by jasaw** [comment]
Duplicate of https://github.com/ccrisan/motioneyeos/issues/785 and https://github.com/ccrisan/motioneyeos/issues/910.

**Comment by Alexandre-Mainardi** [comment]
Thanks Jasaw, im closing this issue to follow the correct topic.
