### ISSUE TITLE
Usage scenario with Multiple devices with a central server

### ISSUE THREAD

**Issue by declanor** [ccrisan/motioneyeos#1428]
Hi There.

Could a Pi3 be used as the central server in the "Mutiple devices with a central server"? I intend putting a small system, 3 pi based and 1 IP camera, on a boat and space and power are limited so a Pi would be ideal if possible?

**Comment by mb39924** [comment]
At the moment I'm using a pi3 as a central hub with two motioneyeos cameras connected , one with a pi zero w and one with an old b+

**Comment by ccrisan** [comment]
Yes, it could. It all depends on how much you'll ask of it, in term of number of cameras, resolution and framerate.
