### ISSUE TITLE
Install Homebridge on Motion Eye OS

### ISSUE THREAD

**Issue by VeniceNerd** [ccrisan/motioneyeos#1432]
Is it possible to install Homebridge on Motion Eye OS? 
https://github.com/nfarina/homebridge

The reason I’m asking is that I would like to run a Raspberry Pi 3 with the internal camera and Motion Eye OS as a security camera. I would like to install Homebridge and this plugin https://github.com/moritzmhmk/homebridge-camera-rpi to also make the camera available via HomeKit. 

That way Motion Eye will upload motion on my Dropbox and I can also have the Pi camera inside my Home app. 

Is this possible?

**Comment by jasaw** [comment]
Short answer is, no you can't easily install it on motionEyeOS. More info in the wiki: https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-i-install-some-package

If you want to do things outside the scope of motionEyeOS, you have 2 options:
1. Install motionEye on your favourite distro. Installation guide [here](https://github.com/ccrisan/motioneye/wiki/Installation). You can then install anything you like.
2. Clone, modify, and build your own motionEyeOS.
