### ISSUE TITLE
New Raspberry Pi 3B+ Released. Will it be compatible?

### ISSUE THREAD

**Issue by Dewey3** [ccrisan/motioneyeos#1434]
With today being International Pi Day (3.14), it looks like the folks at Raspberry Pi have released a new Pi, the 3B+.  The new Pi now has a new processor and now supports 5G networking.  Anyone have any ideas if we will be able to run MotionEye OS on it?  I would love to take advantage of the 5G wifi.

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-motioneyeos-be-ported-to-insert-your-board-here.

**Comment by Dewey3** [comment]
Fair enough :).

**Comment by talormanda** [comment]
Someone get this man a 3B+.

**Comment by Machou** [comment]
I'm really sorry, but I don't have enough money to order a RaspBerry Pi 3 B+, unfortunately.

Hopefully you can make it compatible.

Reagards,
Machou.

**Comment by PersistentThreat** [comment]
I'm very interested in running MotionEyeOS on Raspberry Pi 3 B+, but loading the current Raspberry 3 image does not work out of the box for me. Anyone else who had success with the Raspberry Pi 3B+? 

If there is no simple way of getting it to work, I would be happy to sponsor @ccrisan with a Pi3B+ board. However, it seems overly complicated to buy it myself and then send it to you physically. Would you accept a donation in say Bitcoin (or other crypto) equivalent of the price of a new Raspberry board?

**Comment by ccrisan** [comment]
@PersistentThreat, one kind user has already bought one for me and it's on its way. Thanks for offering though!

Unless there's something unusual about this board and provided the board arrives some time next week, I estimate an OS image will be ready by next Sunday.

**Comment by Moonbase59** [comment]
They use new firmware and (probably?) bootcode. On Raspbian, it saved me _a lot_ of effort to upgrade Raspbian and the firmware _before_ switching from a Pi 3B to a Pi 3B+. After that, I could just switch the Pi and continue using the same SD card.

**Comment by bsimmo** [comment]
It'll need the new Firmware & 4.14 Kernel I think, the processor is the same, just a revision change.
The USB/Lan and WiFi/BT chipsets have changed though.  WiFi is now also .ac so AP setup may be different, I've not tried it.
If MotionEyeOS is built on Stretch a simple apt update/upgrade should bring the updates, if done from a previous model Pi.

Of course it also brings with it PoE over Gigabit once they have their HAT available

Still using an Zero and an B+ for my camera, works fine for me. :-)  Only here to get a new image.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/releases/tag/20180401 adds support for RPi3B+
