### ISSUE TITLE
MotionEye OS and https

### ISSUE THREAD

**Issue by bbuehrer** [ccrisan/motioneyeos#1436]
I have a Raspberry PI with MotionEye OS.
A have a dyndns access from outside and in my Fritz!Box i have a port forwarding from port 8081 to my Raspberry PI. With http it works great.

Is there a way to works with https and a letsencrypt certificate?
How is the way to configure the MotionEye OS for that feature?

**Comment by ccrisan** [comment]
Use a reverse proxy for that. There are no plans to add HTTPS to motionEyeOS, given various limitations such as the fact that the certificate, even if free, would have to be renewed every now and then.
