### ISSUE TITLE
Tons of Questions

### ISSUE THREAD

**Issue by rosenzac** [ccrisan/motioneyeos#1437]
**First:** I have Motion-eye installed on my Raspberry Pi 3 Model B, and after logging in I don't know what to do.

**Secondly:** This is a school project so I have to use the school WiFi, but it refuses to let me connect when I type in the IP address. How do I work around this? (Our thought was to have the school make us a separate static IP and use that)

**Third:** Not Sure which IP address to be using to connect. The only one that came up with something was the Default Gateway which refused connection.

**Finally:** Any tips you have because we need help making our Pi 3 into a sort of Security Camera

If more information is needed, just ask and I will try to supply it

**Comment by ccrisan** [comment]
Please use the [google group](https://groups.google.com/forum/#!forum/motioneye) for this kind of questions. This is definitely not a valid motionEye(OS) issue.
