### ISSUE TITLE
Possible to have option for dyndns? type no-ip.org?

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1440]
it would be handy to have integrated option to have the dyndns on the motioneyeos system.
Imagine a Wi-Fi connection with a cell phone that acts as an access point 
whose IP would change with each connection. 
the dyndns would proceed to recall ip just remotely by name and not ip. 
in order to always have a mobile cam. It can be done?

**Comment by Chiny91** [comment]
It has been on the "to do" list for some while:
https://github.com/ccrisan/motioneyeos/wiki/Roadmap

It is reasonably simple (perhaps not as simple as having it built-in to motionEyeOS) to set it up externally.

**Comment by psts** [comment]
For noip.com, add this to your crontab: 
0 * * * * curl -u ‘your@email.com’:yourpassword "http://dynupdate.no-ip.com/nic/update?hostname=yourhostname.ddns.net"

**Comment by tigernero79** [comment]
Perfect I'll try as soon as I get rpi3 b + and more zero wh. I have no ip in fact

**Comment by Moonbase59** [comment]
I let my router do it for me (an AVM Fritz!Box), for both IPv4 and IPv6. Using [nsupdate.info](https://nsupdate.info/).

**Comment by leonardo-sereno** [comment]
> For noip.com, add this to your crontab:
> 0 * * * * curl -u ‘[your@email.com](mailto:your@email.com)’:yourpassword "http://dynupdate.no-ip.com/nic/update?hostname=yourhostname.ddns.net"

worked for me, thanks!
