### ISSUE TITLE
Sequential File Name?

### ISSUE THREAD

**Issue by rdb9879** [ccrisan/motioneyeos#1441]
Hello. I am using motioneyeos as a dash cam project in my car. Since my camera/pi will be mobile, I decided it was best to have the rasp pi zero w generate its own wifi hotspot by providing hostapd.conf. This means that there is no true time source, and every time I restart my car, the time is set to default Jan 1, 1970. This makes the video files appear on my sd card in a scrambled order, since they all more or less have the same file name/create date.

Is there any way to make the video file names just have a simple sequential index/number? Like when it decides to record a new video, it will read what the highest number that exists in the destination folder, increment it by one, and use that number as the new filename?

I am open to other solutions as well. I'd just like a good way to determine which video is the most recent.

**Comment by rdb9879** [comment]
Nevermind on this. I figured out how to do what I need using "Run Command After ..." and scripts. Thanks anyhow.

**Comment by joshferns** [comment]
> Nevermind on this. I figured out how to do what I need using "Run Command After ..." and scripts. Thanks anyhow.

Hi @rdb9879 I'm having a similar issue at the moment, could you please let me know how you ended up solving this?

Thanks.

**Comment by lucianaohira** [comment]
Hi all!!! We are also having the same issue... Hey @rdb9879, help us, pleeease! We have no idea about how to run scripts... :(

**Comment by lucianaohira** [comment]
Hey, hi all! Hey @joshferns!
In the field "Image File Name" (or Movie File Name), we just wrote %v for saving the still images at a number sequence like 01.jpg, 02.jpg and so on.

**Comment by joshferns** [comment]
Thanks a lot @lucianaohira will give this a shot.

**Comment by gnu-lorien** [comment]
For me %v didn't work. It had the effect of just never storing files correctly after the first one.

I think I may have figured out what the OP did though. You're able to add a custom startup script for when the device starts. https://github.com/ccrisan/motioneyeos/wiki/Tweaks#adding-custom-startup-commands

I used this to add a bash script that backed up my previous movies on startup. This can lead to some disorganized files still but it at least makes sure I don't end up with overwritten files. This could be improved upon to delete the previous files when done to make sure all new recordings are sequential.

/data/etc/userinit.sh
```
datadir=/data/output
tmpdir=$(mktemp -d -p $datadir)
for cameraname in Camera1 Camera2
do
	rsync -av $datadir/$cameraname $tmpdir
done
```
