### ISSUE TITLE
MotionEye and Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#1444]
Has received a handful of Raspberry Pi 3 Model B +.

Can they be used with MotionEye Image for Raspberry Pi 3, or should a new version be available?

Does anyone have experience here?

![2018-03-19 18 28 01](https://user-images.githubusercontent.com/9556987/37611687-525c81ee-2ba3-11e8-9e07-4a466dead1ec.jpg)

**Comment by ccrisan** [comment]
Duplicate of https://github.com/ccrisan/motioneyeos/issues/1434.
