### ISSUE TITLE
Are the codecs purchased for raspberry mpeg2 and vc1 used for emotioneye?

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1448]
I wanted to know if emotioneye uses codec mpeg2 or vc1 that you buy separately for the raspberry, having taken a "pi zero w" buying such licenses I would have a benefit in terms of use gpu? per os emotioeye?

**Comment by jasaw** [comment]
From my understanding, motion doesn't use hardware acceleration when decoding video stream, so no performance gain here. As for video encoding, hardware acceleration can be enabled by specifying the hardware accelerated codec in motion's config file. If you are going to record video using mpeg2, you might get some performance gain by purchasing the license, but it hasn't been tested before. There's already the hardware accelerated H264 encoding on motioneyeos which is free to use and already implemented, just choose h264_omx movie format.

**Comment by tigernero79** [comment]
Thanks
