### ISSUE TITLE
No Preview Mode on Fast Network Camera - USB no problem!

### ISSUE THREAD

**Issue by olli84** [ccrisan/motioneyeos#145]
Hey there,

i got a new Problem. When i try watch my live stream of my Pi2 with Fast Network Camera i can't see anything (Camera Symbol only).

When i try the same thing with my Pi1 with an USB Cam on it - i have no problem, everything is fine.

I know i had a similiar problem some days ago, but i don't know what we have done to solve this.

No authentication on, tried live stream and embedded URL. Every needed port is forwarded.

RPI1 with USB-Cam - 192.168.178.55 port 9105 (in Router) forwarded to port 80
RPI2 with CSI-Cam as Fast Network Camera - 192.168.178.56 port 9106 (in Router) forwarded to port 80 

Thanks for your help,

**Comment by bortek** [comment]
If this problem is still persistent please post your question on the forum page

https://groups.google.com/forum/#!forum/motioneye
