### ISSUE TITLE
last version with wi-pi key wifi

### ISSUE THREAD

**Issue by fdthierry** [ccrisan/motioneyeos#1456]
Hi everybody,

I have installed the last version of motioneye, all is OK in ethernet connection.
But, I want ton connect my Pi on Wifi Home with the Wi-Pi key

At the boot, wpa_supplicant indicate failed rt2800usb

See the log :
[boot.log](https://github.com/ccrisan/motioneyeos/files/1847372/boot.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/1847373/dmesg.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/1847374/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1847375/motioneye.log)
[wpa_supplicant.log](https://github.com/ccrisan/motioneyeos/files/1847376/wpa_supplicant.log)

My file wpa_supplicant.conf (My Pi is authenticated by mac address on my router) is on / disk
[wpa_supplicant.txt](https://github.com/ccrisan/motioneyeos/files/1847318/wpa_supplicant.txt)

What's my problem ?

Thanks for your help

**Comment by fdthierry** [comment]
I see my error, I'm flashing the SD card before write wpa_supplicant, I test it...

**Comment by jasaw** [comment]
I'm not sure if you've worked out the problem. Just in case you're still having wifi config issue, you might want to read these first.
https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems

One more thing, your `wpa_supplicant.txt` file should be named `wpa_supplicant.conf`.

**Comment by fdthierry** [comment]
One more thing, your wpa_supplicant.txt file should be named wpa_supplicant.conf. // Of course, but github refused .conf ;o)

**Comment by fdthierry** [comment]
It's OK for me, 
My error is flashing SD before write wpa_supplicant, 

Sorry,
Thanks
