### ISSUE TITLE
Configuring wireless network: no device (RPI3)

### ISSUE THREAD

**Issue by VFR4EVER** [ccrisan/motioneyeos#1460]
Hi there!

I have been struggling with this error and can´t understand what is happening in my RPI3.
I have the right version of OS, wired connection work fine, but wireless module seems to be inactive. 
What am I doing wrong?

Thanks for any help!
Cheers

**Comment by ccrisan** [comment]
1. What OS version (full URL to what you have downloaded).
2. Are you 100% sure it's a Raspberry Pi 3 model?
3. Does your wireless card work with Raspbian?
4. I suppose the error you set as issue title is part of what you see in your `boot.log` file. Can we see the entire file?

**Comment by VFR4EVER** [comment]
Here is the URL:
https://github.com/ccrisan/motioneyeos/releases/download/20180224/motioneyeos-raspberrypi3-20180224.img.gz

Positive! 100% sure

 I have installed raspbian and wifi is not working also... :(

I could see the error from the boot screen.

 So, something must be wrong with my RPi, right?

 Thanks

*De:* Calin Crisan <notifications@github.com>
*Enviada:* quinta-feira, 29 de março de 2018 20:52
*Para:* ccrisan/motioneyeos <motioneyeos@noreply.github.com>
*Cc:* VFR4EVER <delfimvfr@gmail.com>; Author <author@noreply.github.com>
*Assunto:* Re: [ccrisan/motioneyeos] Configuring wireless network: no
device (RPI3) (#1460)



   1. What OS version (full URL to what you have downloaded).
   2. Are you 100% sure it's a Raspberry Pi 3 model?
   3. Does your wireless card work with Raspbian?
   4. I suppose the error you set as issue title is part of what you see in
   your boot.log file. Can we see the entire file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ccrisan/motioneyeos/issues/1460#issuecomment-377352357>,
or mute the thread

**Comment by ccrisan** [comment]
There might be some hardware problems with your board. See if you can return it.

**Comment by VFR4EVER** [comment]
Thanks a lot. I ll try to figure out what is going on with my RPI..
Cheers

A sábado, 31/03/2018, 14:04, Calin Crisan <notifications@github.com>
escreveu:
