### ISSUE TITLE
date in the European format timestamp

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1461]
is it possible to choose the date in the European format under the item timestamp, then first the day then the month and finally the year? this can already be done for saved videos but not for live timestamp viewing on cam

**Comment by ccrisan** [comment]
@tigernero79 where exactly would you like the time format to appear differently? Show us with a screenshot.

**Comment by tigernero79** [comment]
simply instead of going out month and day, I would like to come out day and month, reverse year with days

![immagine](https://user-images.githubusercontent.com/35575744/38132891-36ba2dde-340d-11e8-8be8-12a0a87d411a.png)

now it goes 2018-03-31 I would like to go out 31-03-2018 in europe format with year at the end

**Comment by ccrisan** [comment]
@tigernero79 in the Settings Panel, go to Text Overlay, choose Custom Text and enter whatever pattern you like.

**Comment by tigernero79** [comment]
as you said, it works, I put "% d-% m-% Y /% H-% M-% S" and it only goes to start now to get date and time on two lines with the timestamp that character to use?

**Comment by tigernero79** [comment]
Solved "\n"
