### ISSUE TITLE
no FastNetworkCamera: Pi Zero W + Logitech C310

### ISSUE THREAD

**Issue by fujinjr** [ccrisan/motioneyeos#1463]
This is my setup:
Raspberry Pi Zero W + Logitech C310.

When I select FastNetworkCamera my system doesn't detect the Logitech C310.
Meanwhile when FNC is disabled it detect the C310 but with low FPS (as expected).

Any ideas? Thanks for your time.

[boot.log](https://github.com/ccrisan/motioneyeos/files/1865372/boot.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/1865373/dmesg.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/1865374/messages.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/1865375/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1865376/motioneye.log)
[raspimjpeg.log](https://github.com/ccrisan/motioneyeos/files/1865377/raspimjpeg.log)
[streameye.log](https://github.com/ccrisan/motioneyeos/files/1865378/streameye.log)

**Comment by ccrisan** [comment]
FNC only works with a Raspberry Pi CSI camera.

**Comment by fujinjr** [comment]
Is the Raspberry Pi Official Camera Module V2.1 8MP good?

**Comment by ccrisan** [comment]
> Is the Raspberry Pi Official Camera Module V2.1 8MP good?

Should be good enough.

> Another question... when I activate Enable System Monitoring I see...

Hover them with the mouse and you'll get a tooltip of their meaning.

**Comment by fujinjr** [comment]
It says streaming / capture framerate
So I assume: streaming is 'a', capture framerate is 'b', temperature is 'x', bandwidth is 'z', but...

```
a / b
x / y / z
```

**'y' ?**

**Comment by ccrisan** [comment]
Yes, you are correct. After reading your question again, I realized it was about the system monitoring option on a RPi. Yes, it's temperature/sysload/netspeed.

A sysload of 2.5 on a 4 core CPU is fine. You should be worried when the average reaches 4.

**Comment by fujinjr** [comment]
Isn't Raspberry Pi Zero W CPU's single core?

**Comment by fujinjr** [comment]
@Moonbase are you also uploading movies to Google Drive?
It seems that USB camera causes more load for the system.
