### ISSUE TITLE
Password length - max. 8 chars are considered for ssh login

### ISSUE THREAD

**Issue by snoopy0815** [ccrisan/motioneyeos#1466]
Not sure if it is a bug or a feature - but as password only the first 8 characters are considered for ssh login.
Even if I have set a longer password, I can login in ssh with only the first 8 characters - leaving out or putting in any characters afterwards - does not matter.
The http login luckily accepts only full password length :)

I could not find anything in the documentation regarding accepted password-length for ssh - therefore this post.

motionEye Version	0.37.1
Motion Version	4.0.1+git2a140fa
OS Version	motionEyeOS 20171008

**Comment by ccrisan** [comment]
Does the SSH login also accept the full password?

**Comment by snoopy0815** [comment]
yes - it accepts every further character if the first 8 chars are the right ones - including the full (correct) password...

**Comment by ccrisan** [comment]
@snoopy0815 does this happen with a more recent version?

**Comment by snoopy0815** [comment]
yes, it is even with the newest release version - I have just updated to try it:

motionEye Version | 0.38.1
Motion Version | 4.1.1
OS Version | motionEyeOS 20180224

**Comment by ccrisan** [comment]
@snoopy0815 your issue is valid, totally reproducible with all versions and totally surprising to me. I'll dig deeper and see how this is even possible.

**Comment by snoopy0815** [comment]
Thanks for your immediate response!

**Comment by ccrisan** [comment]
Fixed via https://github.com/ccrisan/motioneyeos/commit/5f54ef54c3d1f5a240e5b12b04b3263655d6b3d3. 

Apparently the default encryption algorithm used by passwd (at least in busybox) is `des`. And `des` only cares for the first 8 characters. From now on it's going to be `md5`.
