### ISSUE TITLE
Unable to Stream on Mobile Chrome & Saffari 

### ISSUE THREAD

**Issue by greenie1987** [ccrisan/motioneyeos#1477]
Since upgraded to the most recent version, I'm no longer able to stream from my mobile phone. I can login an view video from the "Dashboard" however I can't go straight to the stream. On Chrome for mobile I get an error message "Unable to download file", on Saffari I get a still image and it changes when refreshing the page. 

Chrome on my desktop streams just fine. 

Any help would be appreciated!

**Comment by ccrisan** [comment]
What type of camera do you have? More precisely, how did you add it to motionEye? Can we see some screenshots or a small screencast so that we can understand better what's going on?

**Comment by hfan0816** [comment]
I got the same problem too. I believe this is related to IOS 11.3.
After upgrading my Iphone 7 from IOS 11.2 to IOS 11.3, I got the same issue as describe by the thread author.
(connect to the streaming page)
1. Safari : still image, manually refresh will change the image.
2. Chrome : "Unable to download file"

Raspberry pi 3 model B
Raspberry pi camera v2
MotionEyeOS 20180101

Thank you!

**Comment by ccrisan** [comment]
Guys, I need to see a screencast or something. I don't own any apple products and I can't reproduce that. The error "unable to download file" doesn't make any sense to me.

**Comment by altamij** [comment]
Here is a screencast of what’s going on in chrome using iOS 11.3

https://www.dropbox.com/s/rx5cmyik13znd8y/ScreenRecording_04-10-2018%2016-34-34.MP4?dl=0

If I go to the same url in safari, it shows a still image instead of video. However if I go using a windows pc it shows video correctly in any browser

**Comment by ccrisan** [comment]
@altamij you're trying to view the MJPEG stream directly (judging by port 8081). That is:
 * not the recommended motionEye use case
 * not handled by motionEye, but by motion itself
 * not compatible with all browsers

In conclusion, there's nothing motionEye can do to fix it.
