### ISSUE TITLE
Feature req: Builtin support for Pi-Pan (Pan-Tilt kit)!

### ISSUE THREAD

**Issue by AnsuRio** [ccrisan/motioneyeos#148]
Hi all!

Pi-Pan is a Pan-Tilt kit for Raspberry Pi, and builtin support for this is MotionEyeOS would be a real killer. :) I don´t want to replace this solution, because it has nearly everything I want in it.

You will find more info here: [http://www.mindsensors.com/rpi/33-pi-pan](url)

**Comment by bortek** [comment]
Interesting question but there is no time for this now. Relates to #135 and #330
