### ISSUE TITLE
 motioneyeos and ipcam foscam motorized?

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1482]
I have a motorized foscam camera that I managed to add to my raspberry pi zero w, but there are no commands to make it rotate, a very useful option for people like me who has a motorized camera.

Is it possible in the future to add support for powered ipcam? for the pan and tilt?

rotation management at least?

**Comment by ccrisan** [comment]
Use [Action Buttons](https://github.com/ccrisan/motioneyeos/wiki/Action-Buttons). We can't figure out the commands for you.
