### ISSUE TITLE
password less login to motioneyeos

### ISSUE THREAD

**Issue by bennykap** [ccrisan/motioneyeos#1486]
Hi,
I am trying to login to device with motioneyeos via key-based authentication(password less ) via ssh.
I did a ssh-copy-id from another pc to the motioneyeos, but it is still asking for a password.

what i am doing wrong?

Thanks
Benny

**Comment by RejectH0** [comment]
Make sure the key you're authenticating with is entered in /data/etc/ssh_authorized_keys and is at least an rsa, dsa, ecdsa, or ed25519 key.   
```
cat ~/the-keyfile-you-copied.pub >> /data/etc/ssh_authorized_keys
```

**Comment by bennykap** [comment]
Thanks, It is working
