### ISSUE TITLE
can't set up network share on Pi 3B

### ISSUE THREAD

**Issue by ianporter13** [ccrisan/motioneyeos#1493]
got a strange issue where i cant connect a network share on a new install on a new Pi 3 B+

I'm running motionEyeOS 20180401 and mirrored the settings I have on my Pi Zero W that works fine

I can connect to the share from anywhere else but it wont connect from this new device

currently using FTP to the same share as a workaround

any ideas?

**Comment by ccrisan** [comment]
Please give us some more details. What error do you get? Can we see a log file?

**Comment by jka3588** [comment]
I'm having the same issue, but am fairly new to github. What can I provide that may help? The error that occurs when I try and add a network share is "Accessing network share failed: cannot mount network share!"

**Comment by ianporter13** [comment]
Yes that’s the error I see
I’ll get the logs off over the weekend

It had totally crashed this morning for some reason too 🙁

So far for diagnostics I’d followed a thread with a similar issue where you’d given details on trying to mount the drive from SSH but that doesn’t work either

**Comment by jka3588** [comment]
Check and see if you have a similar message to this, because that's what I'm seeing

SMB2.1) specify vers=1.0 on mount.
[Wed Dec 31 19:04:28 1969] CIFS VFS: cifs_mount failed w/return code = -22
[Wed Dec 31 19:04:28 1969] No dialect specified on mount. Default has changed to a more secure dialect, SMB2.1 or later (e.g. SMB3), from CIFS (SMB1). To use the less secure SMB1 dialect to access old servers which do not support SMB3 (or SMB2.1) specify vers=1.0 on mount.
[Wed Dec 31 19:04:28 1969] CIFS VFS: cifs_mount failed w/return code = -22

**Comment by ianporter13** [comment]
here's the log files from my installs
the one from the Pi 3B+ is the one with the issue
the one from the Zero is connected to the same share and works fine

[motioneye (working Pi Zero).log](https://github.com/ccrisan/motioneyeos/files/1938853/motioneye.working.Pi.Zero.log)

[motioneye (not working Pi 3B plus).log](https://github.com/ccrisan/motioneyeos/files/1938858/motioneye.not.working.Pi.3B.plus.log)

**Comment by ccrisan** [comment]
This should be fixed via https://github.com/ccrisan/motioneye/commit/1bce4dd358774f69e52fa3814eeea54e9fc6b156. It will be part of the next prerelease.

**Comment by ccrisan** [comment]
@ianporter13 can you please try the latest [nightly dev build](https://github.com/ccrisan/motioneyeos/releases/tag/nightly-dev) and see if the problem has been fixed?

**Comment by ianporter13** [comment]
Won’t be able to test for a few weeks as away from home

Ian

**Comment by Will-PH** [comment]
Just tested on my end and it seems to be working again, thanks for the fix.

![image](https://user-images.githubusercontent.com/39135552/41947408-5d97875c-79af-11e8-89bd-a28837a4f77c.png)
