### ISSUE TITLE
Clean Up Command Question

### ISSUE THREAD

**Issue by Dewey3** [ccrisan/motioneyeos#1499]
A couple of my cameras will sometimes capture an outrageous number of still images.  To keep MotionEyeOS running smoothly, I back up all images to an external hard drive and have the MotionEye OS still images set to delete after one day.  However, I sometimes find this is still not enough during those high movement events, such as, windy days.  I see that the default cleanup command variable is set to 43200 (twice a day).  Despite confirming that this is the cleanup_interval setting in my motioneye.conf file, I still sometimes end up with two days of stored still images.  I suspect if I want to change that cleanup command to four times a day, I would half the 43200 to 21600.  My question is to increase the cleanup command from two times a day to four times a day, do I use the resulting 21600 (go down), or do I add the 21600 to 43200 to equal 64800 (go up)?

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/commit/0db2bd53cb6414de2e7adb8f256e0d617d1c09bb reduces the default cleanup time from 43200 seconds to 3600 seconds. You'll have to manually edit your `/data/etc/motioneye.conf` though and tweak your `cleanup_interval`, as this is just a default. And you can also do that now, by the way.
