### ISSUE TITLE
email still pictures as attachment (no motion detection, but timelapse)

### ISSUE THREAD

**Issue by MartinKPi** [ccrisan/motioneyeos#151]
Thank you for a great software, I have just started to play with it.

Is there a possibility to send email with attached pictures taken with "still images"? As an example, picture taken every 12 hours would be emailed to a specific e-mail address.

Now there is a possibility to upload pictures to dropbox or GoogleDrive in "file storage", but not to e-mail them. I was trying to work out somethng with "Run a command" option and on_picture_save (quessing it from motion documentation), but I am lost.

Best regards.

**Comment by ccrisan** [comment]
In my opinion, this feature would generate an enormous amount of emails, something that would soon become annoying. I will implement FTP/HTTP upload but sending an emails with pictures isn't something I'm willing to work on.
