### ISSUE TITLE
 Pi-3B+ Version?

### ISSUE THREAD

**Issue by ptamike** [ccrisan/motioneyeos#1511]
I've just downloaded the latest image for the Pi3B, 20180224, but this won't boot on a Pi-3B+. I get 8 flashes of the activity LED indicating that the SDRAM is not recognised. This suggests the image needs a newer bootcode. I've tried this on two different Pi-3B+ devices with the same result but both devices run standard Raspbian ok. 

Having searched your Issues, I note that others have used version 20180401 with the Pi-B+ but that version doesn't seem to be available from your downloads page.

Do you have an updated version in the pipeline or can you direct me to 20180401.

Thanks,

Mike

**Comment by SelmaUrban** [comment]
https://github.com/ccrisan/motioneyeos/releases
