### ISSUE TITLE
The best small board video cam program in the world, but no sound.....tragic

### ISSUE THREAD

**Issue by keelobight** [ccrisan/motioneyeos#1512]
You've given us the BEST small board cam software in the world, but you say you have no plans to include sound.  You would make so many people so happy and I would sure make a donation to help your cause.  I beg you!  add sound!!!!!

**Comment by jasaw** [comment]
See https://github.com/ccrisan/motioneyeos/issues/105

**Comment by keelobight** [comment]
Oh thanks.  I'm actually trying to make a baby monitor too that my wife can just view on her phone around the house.  Absolutely love your OS, best I've ever seen I use it on all my cams in my business.  I've been up all night trying to find a solution I'm surprised how hard it is, there's just not much out there that works well.  And I'm no programmer so I have to find something intermediate level to implement.  Well thanks for writing back!

Sent from Yahoo Mail on Android 
 
  On Wed, May 9, 2018 at 10:33 PM, jasaw<notifications@github.com> wrote:   
See #105

**Comment by joshikoff** [comment]
I am more than happy having finally a good solution for cam controlls. Thank you for your efforts.

The more I think, the more I wonder why I have spent so much money on commercial / semi comercial solutions which finally did do a bad job.

I have 6 cam´s hooked up thru a RPi 3 and it works fantastic! Thank you so much.
