### ISSUE TITLE
SERIOUS BUG SSH

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1513]
I noticed that via Ssh I can access with root permissions with 2 different passwords how is it possible? indicating as username admin and password Processorxx or Processorxxxx where for x there are numbers, however, with root permissions this is a serious problem. use version 01 04 2018 on pi zero wifi

**Comment by ccrisan** [comment]
It's a known bug that has recently been fixed (via https://github.com/ccrisan/motioneyeos/commit/5f54ef54c3d1f5a240e5b12b04b3263655d6b3d3).
