### ISSUE TITLE
Where is motioneye/server.py stored in the motioneyeos source?

### ISSUE THREAD

**Issue by Repaler** [ccrisan/motioneyeos#1518]
Where is motioneye stored in motioneyeos' source? I intend to edit the server.py file to add in a couple of quick python commands but I cannot find where the server.py file is stored inside of the source (When I talk about server.py I am referencing the file in the motioneye source).

If I made no sense (or TL;DR), I would like to know where the server.py file, from motioneye (the web frontend), is stored inside of the motioneyeos source before making the img

Thanks.

**Comment by jasaw** [comment]
@Repaler Before you change anything in the root filesystem (partition 2), please be aware of the below items:
- the root filesystem is mounted as read-only and is not intended for tweaking
- upgrading your MotionEyeOS will remove all your changes

To answer your original question, you can find server.pyc here: `output/raspberrypi/target/usr/lib/python2.7/site-packages/motioneye/server.pyc`. Note that this is the compiled python file. The source file is not stored in the image. To make changes, you'll need to remount root filesystem as read-write, copy your modified server.py to the same directory as the server.pyc file, restart motionEye. This will generate a new pyc file, then you can remount the root filesystem as read-only.
