### ISSUE TITLE
Web interface missing overclock option

### ISSUE THREAD

**Issue by mauzzz** [ccrisan/motioneyeos#1519]
I have a pi zero w with pi camera module v2.1 and the latest release for the zero, motioneyeos-raspberrypi-20180224.img.gz. There is no overclocking setting in preferences for the pi zero. Am I using the wrong release?

**Comment by jasaw** [comment]
Make sure you log in as admin. Overclock settings should be under "Expert" options. You may have to enable "Advanced options".
If that doesn't solve your problem, maybe you could attach a screenshot?

**Comment by xoma262** [comment]
@jasaw I have the same isssue on Pi 3B
I attached the screenshot. Advanced checked in, logged in as admin, - nothing under expert settings. 
![capture](https://user-images.githubusercontent.com/11239109/40933445-778dd5b0-67ff-11e8-8aab-c2311e0a8400.PNG)

**Comment by jasaw** [comment]
@xoma262 That is very weird. I noticed you have system monitoring turned on. Can you please attach your log files here? Can you also attach your /boot/config.txt file?

**Comment by xoma262** [comment]
@jasaw I attached logs and config.txt file. Let me know if you need anything. 
Weird thing is that I have an overclocking feature on my RPi Zero W. 


[dmesg.log](https://github.com/ccrisan/motioneyeos/files/2070789/dmesg.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/2070790/boot.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/2070791/messages.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/2070792/motioneye.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/2070793/motion.log)
[config.txt](https://github.com/ccrisan/motioneyeos/files/2070804/config.txt)

**Comment by iamtheyammer** [comment]
For what it's worth I'm still having this issue. motionEyeOS 20180628, Pi 3b+.

**Comment by xoma262** [comment]
@iamtheyammer have you tried the latest build?

**Comment by iamtheyammer** [comment]
Not yet, I’ll try toda

**Comment by iamtheyammer** [comment]
Just tried it, same issue.

Versions:
motionEye Version | 0.39.3
Motion Version | 4.1.1
OS Version | motionEyeOS 20181209

**Comment by ccrisan** [comment]
The Raspberry 3 variant does not support overclocking.
