### ISSUE TITLE
What file types are available?

### ISSUE THREAD

**Issue by g2bb** [ccrisan/motioneyeos#1529]
What file types are available for the long term storage. I have looked all over the Wiki, FAQ, and Issues as well as several Google searches and I still can't find a solid answer. As I understand it (correct me if I'm wrong), the stream is mjpeg and the recordings are something else. I would like to know what all is available to save recordings as so that I have an idea how much storage I'll need for a 2 camera system.

**Comment by jasaw** [comment]
@g2bb For video recordings, you can choose OMX H264 with either mp4 or mkv format for the most efficient video encoding. How much storage you need depends on video resolution, bit rate (called quality in motionEyeOS), and frame rate.

**Comment by g2bb** [comment]
Thank you
