### ISSUE TITLE
Problem with Action Buttons

### ISSUE THREAD

**Issue by rockman55** [ccrisan/motioneyeos#1532]
Have made several post in regards to this problem, hopefully this will be the right place.
I have tried to make Action Buttons work using both Raspberry Pi 3 B and the new Raspberry Pi 3 B Plus, for a Pan and Tilt camera (ID 1). I can see the arrow buttons but they don't function, I have seen instructions to place the script files, some say /data/etc, others say /etc/motioneye. First there is not /etc/motioneye directory so I have placed them in the /data/etc folder. I am using an example for the scripts I found at this web site: https://raspberryblog.de/?p=2209.  Everything works on the Pi where I have the Pan Tilt set up. I cannot figure out how to get them to work like they should. 
I am using a Raspberry Pi 3 B on both installations, for the MotionEyeOS  system I am using:

motionEye Version | 0.38.1
-- | --
Motion Version | 4.1.1
OS Version | motionEyeOS 20180224
I am attaching a copy of the motioneye.log file and a copy of one of the scripts I am using.
Thanks in advance for the help. I can provide additional information as requested.
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/2066377/motioneye.log)

[down_1.txt](https://github.com/ccrisan/motioneyeos/files/2066380/down_1.txt)
[left_1.txt](https://github.com/ccrisan/motioneyeos/files/2066381/left_1.txt)

**Comment by ccrisan** [comment]
Your log says:

    2018-06-03 16:03:44: [motioneye]  WARNING: up_1: python: can't open file 'up1.py': [Errno 2] No such file or directory
    2018-06-03 16:28:40: [motioneye]  WARNING: down_1: command has finished with non-zero exit status: 1
    2018-06-03 16:28:40: [motioneye]  WARNING: down_1: Traceback (most recent call last):
    2018-06-03 16:28:40: [motioneye]  WARNING: down_1:   File "/data/etc/down_1", line 6, in <module>
    2018-06-03 16:28:40: [motioneye]  WARNING: down_1:     import Adafruit_PCA9685
    2018-06-03 16:28:40: [motioneye]  WARNING: down_1: ImportError: No module named Adafruit_PCA9685
    2018-06-03 16:28:42: [motioneye]  WARNING: down_1: command has finished with non-zero exit status: 1

You seem to require an extra python package, called `Adafruit_PCA9685`, which is not available on motionEyeOS. I'm afraid you'll have to move to Raspbian + motionEye if you really need to use it. Or, if you have the knowledge and time, add the package to a custom built motionEyeOS variant.

**Comment by rockman55** [comment]
Thanks, Calin for your response. I have built this package: https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian, and installed the Adafruit package. The action buttons will work with that installation, but it seems that many of the other functions of MotionEye are not there. Like check for update, backup and restore and others. Is there a way to do the Raspbian plus Motioneye and get all of the features that are in the original distribution?

Thanks for your help.

Danny aka rockman

**Comment by ccrisan** [comment]
I'm afraid that that's not going to be possible.

**Comment by rockman55** [comment]
What features would be available if I do a package of a custom built motionEyeOS variant? Are there instructions on how to do that? I have plenty of time for that.

Thanks 

Danny
