### ISSUE TITLE
Google photos

### ISSUE THREAD

**Issue by darkplatinum** [ccrisan/motioneyeos#1537]
Hi! Basically this is more of a request than an issue. 

So far I've started to setup my cctv system. Just waiting for my camera to arrive. During some tutorials I've seen your can send data to google drive. As google drive has free 15 GB of storage, it makes it a great choice for Free storage. But Google photos has UNLIMITED storage. Yes unlimited! Basically, in Google photo settings you change original quality to high quality . This convert 4K videos to 1080p. Is there a way to upload video recordings to Google photos automatically?

**Comment by ccrisan** [comment]
There are no plans to add Google Photos uploads feature in the near future. Pull requests are welcome, though.

**Comment by darkplatinum** [comment]
What do you mean by pull requests? I see the pull requests bar on GitHub. Is this used to submit requests?

Sorry I'm fairly new to GitHub so bear with me.

**Comment by jasaw** [comment]
@darkplatinum Pull Request is for submitting patches back to motionEyeOS.
You'll need to fork motionEyeOS project on Github, create a feature branch, commit your changes to this feature branch, then you'll be able to create a pull-request to submit your feature branch changes.

**Comment by darkplatinum** [comment]
@jasaw thanks for the info.
