### ISSUE TITLE
Motioneye ssh stuck after password

### ISSUE THREAD

**Issue by RickvanHek** [ccrisan/motioneyeos#1540]
I can't access my motioneye webpage through wifi, it just keeps loading. When I try to ssh to it and input as username: admin, i get the message "Welcome to ..." and then i have to enter my password. I do so and it just doesn't do anything. After a while i get "Server unexpectedly closed network connection".

It used to work, but now I can't do anything. Can't load the webpage, can't load with ssh. Any fixes?

**Comment by ccrisan** [comment]
There is a template for creating issues, which you seem to have ignored. Please start over by filling in the required details so that we can understand what's going on and help you.
