### ISSUE TITLE
Have you heard of Dietpi?

### ISSUE THREAD

**Issue by budpi** [ccrisan/motioneyeos#155]
Perhaps the nice folks at Dietpi would love to see about integrating this into there software. Would anyone else agree? How can we make this happen? Thanks!!

Sorry that this isn't really an issue. Love the project!

**Comment by ccrisan** [comment]
I'm not sure what this task you're proposing here would consist of. motionEyeOS is already a standalone OS that can be generalized and then customized for various other applications. [motionEye](https://github.com/ccrisan/motioneye) on the other hand could be based on any other distro, including Diet PI; I don't see why not. However that's some work I'm not willing to do myself. I'd be happy to help anyone wishing to do the job, though.
