### ISSUE TITLE
Remotely shutdown Pi-0 with Pi-3 as main server.

### ISSUE THREAD

**Issue by AbbasKagdi** [ccrisan/motioneyeos#1553]
Apologies if repeated,
I have my setup as follows:

Pi-3 : Logitech C270 : Main server : MotionEyeOS
Pi-0W : PiCam 8MP : Remote server : MotionEyeOS

Any options to shutdown the remote server just using the interface of main server?

Any options to Shutdown / Reboot all camera devices with single interface?

**Comment by ccrisan** [comment]
That won't be possible out of the box and it is not a planned feature. If you must have such a functionality, try implementing it using [Action Buttons](https://github.com/ccrisan/motioneyeos/wiki/Action-Buttons).
