### ISSUE TITLE
Not all cameras showing from port access?

### ISSUE THREAD

**Issue by Cybermaw** [ccrisan/motioneyeos#1559]
Hello Everyone!

I am having issues viewing all of my cameras on the port forward. I can only see one camera. How can I establish the ability to log into my motioneye from outside the network and see all of my cameras on one port? Below is what I can see when I log into my private IP admin page
![image](https://user-images.githubusercontent.com/40476885/41749292-6dd6496c-756a-11e8-8ef9-263d63f8de12.png)

However, when I go outside my network and type in http://(public IP):8081 it only shows me one camera.
![image](https://user-images.githubusercontent.com/40476885/41749322-95edd848-756a-11e8-8fa8-9d92f7ffce5e.png)

I want to be able to see all 3 of my cameras on one webpage when I am looking at it from outside the network. How can I achieve this? Thank you so much in advance!

**Comment by ccrisan** [comment]
Forward port 80, not port 8081 (which is the first camera stream).
