### ISSUE TITLE
Only 8 Action buttons are Shown

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneyeos#1561]
Hi,

I created 9 scripts for action buttons for camera 1:
-rwxr-xr-x    1 root     root           115 Jun 23 09:41 down_1*
-rwxr-xr-x    1 root     root           107 Jun 23 09:38 left_1*
-rwx------    1 root     root           488 Jun 23 13:42 preset1_1*
-rwx------    1 root     root           489 Jun 23 13:43 preset2_1*
-rwx------    1 root     root           444 Jun 23 13:33 preset3_1*
-rwxr-xr-x    1 root     root           111 Jun 23 09:39 right_1*
-r-rwxr-xr-x    1 root     root           120 Jun 23 09:41 up_1*
-rwxr-xr-x    1 root     root           157 Jun 23 09:06 zoom_in_1*
-rwxr-xr-x    1 root     root           157 Jun 23 09:06 zoom_out_1*

But only 8 Buttons are shown:
![image](https://user-images.githubusercontent.com/25499089/41809348-673256a4-76ec-11e8-9a94-9d02dbc4dcc8.png)

Is there a limitation to 8 Buttons?
Or can I configure the layout?
Thanks a lot...
helmar

**Comment by ccrisan** [comment]
Yes, the UI is limited to 8 buttons.
