### ISSUE TITLE
Night Vision support

### ISSUE THREAD

**Issue by danpowell88** [ccrisan/motioneyeos#1566]
I'm using a Pi 0 W and a one of the PI night vision ir cameras with IR leds.

If I understand correctly with these cameras the camera LED setting is used to trigger the night vision leds, is there a way to automatically trigger turning this on or off based on the darkness of the image?

**Comment by jasaw** [comment]
I'm not aware of any camera that uses the camera LED to turn on/off IR LEDs, but there are cameras that use the camera LED to turn on/off IR-cut filter.

To answer your question, no, there's no support to turn on/off night vision based on image brightness.
See https://github.com/ccrisan/motioneyeos/issues/1013
