### ISSUE TITLE
Will it be possible to have an update branch for the nightly?

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1567]
it would be nice to be able to access the nightly motioneyeos updates directly from the motioneyeos web interface without having to flash the rom each time manually or unplug the camera and then reassemble it. what do you think? obviously at the exit of a stable release we could also put that.

**Comment by ccrisan** [comment]
That's not something I'm willing to implement. Many users would simply go for it without realizing the consequences. If you want to upgrade to a nightly release, please use the command `fwupdate upgrade nightly-dev` while logged in via SSH/putty.
