### ISSUE TITLE
 Possible to have autofocus or focus adjustment camera v2 8mpxl

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1573]
I have a raspberry pi zero w on which I mounted a camera v2 8 megapixel, but I know that the images already after a meter are blurred a lot, someone suggested to turn the ring around the camera to see to improve the focus, I wondered if via software with motioneyeos there was the possibility to set an autofocus or to improve its quality without physically going to move the factory ring.

it's possible?

**Comment by ccrisan** [comment]
The Raspberry PI camera does not have autofocus and that's not something that can be implemented in software.

**Comment by tigernero79** [comment]
Crisan, I solved.

Basically, the camera has a ring that can be turned to the left or right to adjust the focus. I needed a toothpick to turn the ring counter-clockwise half a turn to have a perfect focus at 5 meters
