### ISSUE TITLE
pikrellcam as a replacement for motion

### ISSUE THREAD

**Issue by joedupa** [ccrisan/motioneyeos#159]
Pikrellcam project (https://github.com/billw2/pikrellcam) offers MUCH better quality video and stills (GPU based) output than Motion derivatives used in MotioneyeOS. Their interface sucks but the output at a full HD is phenomenal. Would that be possible to get the pikrellcam used as an image acquisition and processing pipeline and the MotionEyeOS to "drive and show" the things?

**Comment by ccrisan** [comment]
Unfortunately I don't have too much free time these days and this integration would be a serious development. I'll mark the issue as "won't fix" for now.
