### ISSUE TITLE
disabling email notification makes all fields blank

### ISSUE THREAD

**Issue by jokernapier** [ccrisan/motioneyeos#1595]
Hye,

When I want to disable email notifications, I uncheck "send an email" and all fields become empty.
Is it possible to not make them empty and keep smtp parameters ?

Thank you,

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20180627

### Board Model

I am using the following board/model: Raspberry PI 3B+

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: (insert your camera model, e.g. Logitech C290).

**Comment by ccrisan** [comment]
Not possible given the current implementation.
