### ISSUE TITLE
How to Update

### ISSUE THREAD

**Issue by vdyo** [ccrisan/motioneyeos#16]
Hi, I have the first pre-release installed, is there an easy way to update it, or do I need to re-image?

Regards

Damian

**Comment by ccrisan** [comment]
Just enable Prereleases in Expert Settings and hit the update button.

**Comment by vdyo** [comment]
Hi, I just tried that and I get a The update process has failed! error. I added enable pre release and I got the error when I chose Update, I restarted for good measure but same error.

**Comment by ccrisan** [comment]
Can I see your motionEye.log?

**Comment by vdyo** [comment]
sure one sec

**Comment by vdyo** [comment]
```conf_path /data/etc
run_path /tmp
log_path /var/log
media_path /data/output
motion-binary /usr/bin/motion-mrdave
log-level info
listen 0.0.0.0
port 80
mount_check_interval 300
motion_check_interval 10
cleanup_interval 43200
thumbnailer_interval 60
remote_request_timeout 10
mjpg_client_timeout 10
mjpg-client-idle-timeout 10
smb_shares true
smb_mount_root /data/media
wpa_supplicant_conf /data/etc/wpa_supplicant.conf
local_time_file /data/etc/localtime
enable_reboot true
enable_update true
smtp_timeout 60
zip_timeout 500
add_remove_cameras true```

**Comment by ccrisan** [comment]
The motioneye.log file, please (it's downloadable from the UI).

**Comment by vdyo** [comment]
ah ok

**Comment by vdyo** [comment]
Hi, I just emailed it to you. Thanks Damian

**Comment by ccrisan** [comment]
You log ends on the 14th of October and there's no sign of updating in it. Have you run out of space on your SD card?

**Comment by vdyo** [comment]
hmm 14.3/14.3 GB (99%) I guess so, let me see how to delete stuff.

**Comment by ccrisan** [comment]
Well that's your problem. After that, the update process should work flawlessly. Feel free to reopen this issue if it doesn't.
