### ISSUE TITLE
Real Time Clock

### ISSUE THREAD

**Issue by db414813** [ccrisan/motioneyeos#161]
I have a rpi2 that will not be connected to a network. Does motioneyeos support a real time clock if I add one?

**Comment by ccrisan** [comment]
Nope. MotioneyeOS requires a working internet connection.

**Comment by db414813** [comment]
Even motioneye running on raspbian needs a internet connection?

**Comment by ccrisan** [comment]
Nope. That's raspbian's problem :)

**Comment by db414813** [comment]
Great! Eh, don't think running motioneye on raspbian is a good idea. So I guess either get a ordroid c2 or xu4 with a RTC and run motioneye on arch linux or something. Thanks!
