### ISSUE TITLE
Disable locale storage only use network share storage

### ISSUE THREAD

**Issue by ronaldsnoeck** [ccrisan/motioneyeos#1635]
Hi,

thanks for the program and effort to help.
I use the motioneyos with shared folder. I store all motion triggered pictures on a NAS. 
But the pictures are also stored on the Raspberry PI sd card. Is there a way to switch of the locally store of pictures?

Regards

**Comment by ronaldsnoeck** [comment]
Hi,

or point out where to look in de source. I am able to build the image, great work by the way.

Regards
Ronald

**Comment by ccrisan** [comment]
If you have configured your system to use a network share, your media files will not be saved locally at all.
