### ISSUE TITLE
Configuration Web page at first boot

### ISSUE THREAD

**Issue by Jose-Monteiro** [ccrisan/motioneyeos#1637]
Dear Sir,
Is it possible to have, at the first boot, a web portal running at an specific IP, so we could type wifi ssid, password, email address, smtp? After a first successful boot this would no longer run, going directly to MotionEyeOS already configured.
Thanks in advace

José Monteiro

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: ( 20180730).

### Board Model

I am using the following board/model: (Raspberry PI Zero W).

### Camera

I am using the following type of camera: (Simple MJPEG Camera).

My camera model is: (Ov5647).

### Network Connection

My motionEyeOS unit is connected to the network via: (WiFi).

**Comment by ccrisan** [comment]
This sounds too complex to implement. Pull requests are welcomed, though.
