### ISSUE TITLE
Low fps when streaming from "Fast network camera" to motioneye installed on server

### ISSUE THREAD

**Issue by smumryak** [ccrisan/motioneyeos#1641]
I'm running motioneyeos on rpi zero w in "fast network camera mode", 1280x720@10fps, image quality 10%. Streaming preview over HTTP is extremely fast, looks like solid 10 FPS. 

I'm trying to connect this camera on my home server using motioneye on up-to-date Debian stretch. When i connect that remote camera as "Simple MJPEG Camera" it works extremely fast, same 10 FPS, but (obviously) no motion processing on server. So i'm trying to add it as "Network camera" and then FPS of preview from server drop really bad. Screen recording is [here](https://www.dropbox.com/s/gkosmkx34cztd5n/motioneye_bad.mov?dl=0). Left side - preview from server, right side - from motioneyeos on rpi. [Here's](https://www.dropbox.com/s/4iko327t0m5pazg/motioneye_good.mov?dl=0) preview of "simple mjpeg camera" on server setup. Same layout.

Where should I dig? 

Zipped logs from rpi [here](https://www.dropbox.com/s/r6log7bwdu7ong9/Logs.zip?dl=0). Includes boot, motion, motioneye, streameye and raspimjpeg logs. Do you need any server logs from me?

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20180730.

### Board Model

I am using the following board/model: Raspberry Pi Zero W

### Camera

I am using the following type of camera: Fast Network Camera

My camera model is: third-party raspi camera

### Network Connection

My motionEyeOS unit is connected to the network via: wifi

### Peripherals

I am using the following peripherals that I consider relevant to this issue: not using any peripherals except camera.

### Log Files

I consider the following log files relevant to this issue: (in the message)

**Comment by ccrisan** [comment]
@smumryak the moment you add your stream to a motionEye server as a Network Camera, you actually pass it through the Motion daemon, which implies video processing and passing video frames around between various processes, which is what you would get if you used Motion directly on your camera (disabling FNC mode) in the first place.

If you need motion detection and other related goodies, one way or another, you'll end up with a lower framerate; how low that is mainly depends on your hardware.
