### ISSUE TITLE
Backup data directly from microsd

### ISSUE THREAD

**Issue by andreluisos** [ccrisan/motioneyeos#1642]
It's not an issue, but I don't know where else to ask...

Is it possible to access /data/output directly from computer? motioneyeos isn't accessible, for some reason, and I need to backup some files from it.

**Comment by ccrisan** [comment]
Of course. You'll need Linux or any other OS that is capable of reading extended filesystems. On Windows you could use 3rd party drivers such as https://www.ext2fsd.com/.
