### ISSUE TITLE
Contribution: script to keep delete files from local storage when it's getting full.

### ISSUE THREAD

**Issue by andreluisos** [ccrisan/motioneyeos#1643]
Description:

MotionEyeOS defines an output folder and creates new folder with it's name based on the actual date date. Inside that folder, it stores the video created, naming them by time. In other words, you'll have a root folder and, inside that root folder, you will have other folers, in which the videos will be locally stored on the specific folder, depending on the day.

This script is useful if you upload your videos to cloud and have a limited local storage (not enough to use the "preserve" option), for instance.

What the script does:

- Detects the storage %.
- If the storage percentage is at 70%:
    - It'll go to the output folder and check if there are more than one folder.
        - If there are more than one folder in the output folder and the main condition is met (70% storage), it will delete the latest one created.
        - If there are only one folder, it will enter that folder and the oldest 5 files created.
- The cronjob will run the script every minute (which can be changed), but the script will only delete stuff is the main condition is met.

I couldn't find a script like this one, so I made it myself. As it's useful for me, it's probably for someone else too. I'm not sure where to post my contribution, so I'm posting it here.

I update the script now and then, so make sure to check and report issues (I'm a lawyer, not a computer expert... Take it easy).

You can find the script here:

https://github.com/andreluisos/motioneyeos/blob/master/storage_cleaner_script/storage_cleaner_script.sh

**Comment by ccrisan** [comment]
Thanks! We'll probably have to move this to the Wiki section.

**Comment by andreluisos** [comment]
https://groups.google.com/forum/#!topic/motioneye/l61M3aslE7s

Just found out we have this forum. You can delete this from here, if you want.
