### ISSUE TITLE
AV1 video codec

### ISSUE THREAD

**Issue by kahvis** [ccrisan/motioneyeos#1650]
Hey,

Have you considered to add AV1 video codec to system?
It is is an open, royalty-free video coding format designed for video transmissions over the Internet. FFmpeg has support since 4.0.

The bitstream code was finally frozen on 28 March 2018 for AV1. Chrome will have the support from chrome 70.

**Comment by ccrisan** [comment]
This should be implemented in [Motion](https://github.com/Motion-Project/motion) first.
