### ISSUE TITLE
Admin panel stop working over time.

### ISSUE THREAD

**Issue by andreluisos** [ccrisan/motioneyeos#1654]
Within a day or two motioneyeos (RPI3) no longer loads the admin page. Apparently, it stops making videos and uploading them to Good Drive. I still can ssh into RPI3 (very slowly, tho).

My build creates a lot of videos during the day (over 500). I use my own script to avoid full disk space (it delete oldest files).

https://github.com/andreluisos/motioneyeos/tree/master/storage_cleaner_script

Would the problem be with motioneyeos itself or the script?

**Comment by ccrisan** [comment]
This often happens when your data partition becomes full.

**Comment by andreluisos** [comment]
Seems to be right. There was a fault on my script. I fixed it and it's been running 3 days straight without problems. thanks.
