### ISSUE TITLE
Protection from e-mail overload

### ISSUE THREAD

**Issue by cwwells** [ccrisan/motioneyeos#166]
I would like to install motioneyeOS at a remote site I only visit monthly and am concerned that some malfunction or large numbers of events could flood me with email.  I don't think I will be able to access motioneyeOS over the internet as my remote provider doesn't provide a public IP. 

A feature to limit the number of emails someway would be much appreciated. Thank you for this great program !

Curt

**Comment by ccrisan** [comment]
Choose a larger event gap and you can be sure no email will be sent more often than the event gap.
