### ISSUE TITLE
Preferring an external USB WiFi dongle

### ISSUE THREAD

**Issue by bablat** [ccrisan/motioneyeos#1663]
Thanks for working on this project, good job!

I'm connecting to my home wifi network, and have two separate wifi adapters (the onboard one is wlan0, the USB one is wlan1).
I'd like to either prefer connecting with the wlan1, but can't manage to configure it anywhere (I tried altering os.conf but that didn't really help).

Is there a straightforward solution for this?

Thanks,

-bab

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version:20180627

### Board Model

I am using the following board/model: Raspberry PI 3B+.

### Network Connection

My motionEyeOS unit is connected to the network via: onboard wifi + external USB wifi dongle.

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * USB WiFi adapter

**Comment by ccrisan** [comment]
motionEyeOS wasn't designed with multiple network connections in mind, but if you must do that, you could manually configure your `wlan1` in your [userinit.sh](https://github.com/ccrisan/motioneyeos/wiki/Tweaks#adding-custom-startup-commands).

You'll need to manually start `wpa_supplicant`, then either use a dhcp client or add a static IP address to your interface.
