### ISSUE TITLE
Mass storage not recognised

### ISSUE THREAD

**Issue by Burgy22** [ccrisan/motioneyeos#1667]
Preliminary Docs

I confirm that I have read the CONTRIBUTING guide before opening this issue.

I confirm that I have read the FAQ before opening this issue.
motionEyeOS Version

I am running motionEyeOS version:20180627
Board Model pi3

I am using the following board/model:Raspberry pi 0w connected with fast networking to Raspberry pi 3B+ the mass storage hub
Camera

My camera model is:Raspberry pi camera v1.3
Network Connection

My motionEyeOS unit is connected to the network via:WiFi 

I am using the following peripherals that I consider relevant to this issue:
1Tb External Hard Disk (planed for mass storage)
Tried using the following formats, without success: fat32, ntfs, ext4.
Mass storage does not show up in the storage device pulldown list?
Log Files

I consider no log files relevant to this issue:

**Comment by ccrisan** [comment]
@Burgy22 log files please.

**Comment by Burgy22** [comment]
During installing (first boot) no Folders were produced on the Hard Disk, now done manually.
The Mass Storage is now in the pulldown list an can be used.
@ccrisan 
Many thanks for your excelent work..
