### ISSUE TITLE
Changing keyboard layout / language on Motioneye OS

### ISSUE THREAD

**Issue by kajan001** [ccrisan/motioneyeos#1668]
### motionEyeOS Version
motionEye Version | 0.39.2
Motion Version | 4.1.1
OS Version | motionEyeOS 20180627

### Board Model
Raspberry pi Zero W
I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

I am trying to change the keyboard layout to Swedish standard.
Where is the keyboard configuration file located? Or is there another configuration option available somewhere.

My apologies if this is already addressed somewhere. I have searched extensively on the web and the MotioneyeOS Wiki/faq/issues.

**Comment by ccrisan** [comment]
@kajan001 motionEyeOS has a web frontend which runs in your browser, on your computer. Changing the keyboard layout on your computer is not something that motionEyeOS can or should control.
