### ISSUE TITLE
IP Camera stream in low quality on motionEyeOS

### ISSUE THREAD

**Issue by wgergeus** [ccrisan/motioneyeos#1669]
I am running motionEyeOS version: (dev20180730). on Pi3 and i tried to connect an IP Camera to motionEyeOS .. 
the IP Camera working but only stream in low quality (**bad stream quality**)

_**i attatched 3 photos for the cam and its sittings**_

![camera2_20-56-58](https://user-images.githubusercontent.com/43858415/46496462-6a1f3300-c818-11e8-89a0-f485e63a6942.jpg)
![untitled](https://user-images.githubusercontent.com/43858415/46496463-6a1f3300-c818-11e8-9511-50b7d256cf2e.png)
![untitled1](https://user-images.githubusercontent.com/43858415/46496464-6a1f3300-c818-11e8-892d-cc00cb1aef72.png)

**_### so how i get it working with good quality ?_**

> **NOTE**:
> the IP Camera working on its phone app called (yoosee) with good quality

and this photo from my phone
![img_1994](https://user-images.githubusercontent.com/43858415/46496868-6213c300-c819-11e8-9468-6477fac10150.JPG)

**Comment by jasaw** [comment]
IP cameras typically have 2 streams, a low quality for motion detection, and a high quality for recording. I'm pretty sure motion software supports this, but I have never set one up before. Maybe someone else might be able to help you with the config.

**Comment by alexei-developer** [comment]
Also interesting, I am not find where set stream for motion detection and where set stream for write video. Please, help. =) It is possible?

**Comment by Chiny91** [comment]
Re @jasaw comment... that would be useful... peruse of the motion words... oh yes:
https://motion-project.github.io/motion_config.html#netcam_highres
I'd never noticed that before, thanks.

I need my system to run without fail in the next few weeks, but should be able to test by Christmas.   Of course by then, someone else will already have reported back 😄

**Comment by alexei-developer** [comment]
Thanks, but.... if i am add extra option
netcam_highres rtsp://192.168.0.50:554/user=admin&password=&channel=0&stream=0.sdp
or 
netcam_highres "rtsp://192.168.0.50:554/user=admin&password=&channel=0&stream=0.sdp"
myeyos write cannot open device... =(

![image](https://user-images.githubusercontent.com/4242358/47841109-8d161600-ddc9-11e8-8958-300373d91992.png)
otherwise if not extra option, then open device success:
![image](https://user-images.githubusercontent.com/4242358/47841129-a4ed9a00-ddc9-11e8-9829-81f5d40d6fbf.png)

Camera device set is stream 1: CIF (rtsp://192.168.0.50:554/user=admin&password=&channel=0&stream=1.sdp)
For extra option set steram 0: 1080

**Comment by alexei-developer** [comment]
All works. It is my camera very long connect in 2Mp and VBR mode... =(

**Comment by Chiny91** [comment]
Glad it worked.

I am testing netcam_highres myself and so far, so good.   To make it work:
(1) Use the low res URL as the Video Device in motionEyeOS
(2) Add an Extra Motion Option of `netcam_highres your_high_res_URL`
(3) Ensure the cam config delivers the correct video stream.

Some big files can be produced, which may be a problem for some.

**Comment by wgergeus** [comment]
i used this RTSP url "rtsp://192.168.8.109:554/onvif2" and it was the low quality image
and replaced to "rtsp://192.168.8.109:554/onvif1" with Video Resolution (800×600) the steam quality was good but when i move i get bad image 
![camera2_14-39-55](https://user-images.githubusercontent.com/43858415/47998691-ea330400-e108-11e8-8996-227e1d4e6e26.jpg)

**how can i fix this Issue?**

**Comment by ccrisan** [comment]
@wgergeus streaming issues when using RTSP are often reported when using UDP instead of TCP. Please try adding the camera using the TCP protocol (if you did not do that already). If the problem still persists, please [report a Motion issue](https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue).

**Comment by wgergeus** [comment]
@ccrisan thanks for your comment.
i tried to use the TCP protocol  but it doesn't work 
**unable to open video device**

in only work on UDP protocol  on this url : 

rtsp://192.168.8.109:554/onvif1

what can i do to solve this problem?

and i have another issue:

when tried to use motion notification by E-Mail i want to activate the notification at night only so if i tried to open TLS option the notification works but when i turn it off the system can't connect to wifi network and to solve that issue i had to format the SD Card and install motioneye os again 

so what can i do?

**Comment by ccrisan** [comment]
@wgergeus as I said in my previous comment, please [report a Motion issue](https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue).

**Comment by alexei-developer** [comment]
How change current add cameras from UDP to TCP? I am not find it in settings:
![image](https://user-images.githubusercontent.com/4242358/48181834-12557980-e33a-11e8-86c5-c796e8ceb0e3.png)

**Comment by ccrisan** [comment]
You need to remove and readd the camera.

**Comment by alexei-developer** [comment]
Oh, and add all cameras again with set all settings again? =(((

**Comment by Pilou72** [comment]
@wgergeus : Hi, I have exactly the same problem, with a Yoosee IP Camera freshly bought (Good quality with the Yoosee CMS, but very bad when movements with MotionEyeOS). Did you succeed in solving this problem ? Did you already report a Motion Issue ?

Thks,
Pierre
