### ISSUE TITLE
Mjpeg camera does not have option to remove 

### ISSUE THREAD

**Issue by mcline3207** [ccrisan/motioneyeos#1670]
motion eye version 4.1.1, I have read all documents. I need help to remove the MJPEG camera with out reinstalling the OS. Did not realize you can not record with this feature

**Comment by ccrisan** [comment]
I'm marking this issue as invalid because:

 * you ignored the issue template, failing to provide required information
 * motionEye can't be at version 4.1.1 - that's Motion
 * you **can** remove your camera using the Trash button on the top left corner, when having the settings panel opened

**Comment by ITCMD** [comment]
I too have this issue, the trash button is missing only on mjpeg cameras.

**Comment by ITCMD** [comment]
logging out then in fixed this issue
