### ISSUE TITLE
motionEye: CANT ACCESS to added in-browser video playback

### ISSUE THREAD

**Issue by fetienne** [ccrisan/motioneyeos#1671]
### motionEyeOS Version
I am running motionEyeOS version: (motionEyeOS 20180627).

### Board Model
I am using the following board/model: (raspberry 0).

### Network Connection
My motionEyeOS unit is connected to the network via: (WiFi).

### Log Files

Where I could find the added in-browser video playback ?
I can't see it under firefox.

Thank's

**Comment by ccrisan** [comment]
@fetienne in the media browser, as soon as you click on a recorded movie. If you don't see a play icon, then your browser probably does not support HTML5 video playback.

**Comment by fetienne** [comment]
Hi,

But I try on Firefox 62.0.3, Opera 56.0.3051.40 and Chrome 69.0.3497 on windows and Samsung internet 7.4.00.70 under Android.
On both, I can't see a play icon. Only Close and Download.

Which browser is compatible for that ?

Thank's.

**Comment by ccrisan** [comment]
Screenshot please.

**Comment by EOUpSL93Y** [comment]
Same problem on latest Motioneye. https://pic4a.ru/99/xyV.png
