### ISSUE TITLE
You cant use NAS on rtsp Remote CAM?

### ISSUE THREAD

**Issue by byEliteHacks** [ccrisan/motioneyeos#1673]
![chrome_2018-10-10_00-29-26](https://user-images.githubusercontent.com/24509725/46702542-cf619280-cc23-11e8-97d4-9faf9d2d3d3a.png)

### motionEyeOS Version

I am running motionEyeOS version: latest

### Board Model

Server Debian 9.5

### Camera

Network Camera

My camera model is: TV-IP314PI

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

**Comment by ccrisan** [comment]
* this is not motionEyeOS, it's motionEye
* version "latest" is not a valid version, although I can deduce it from the screenshot
* you need to enable [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) if you want NAS option to show up in that combo
