### ISSUE TITLE
Question about 1920x1080@30

### ISSUE THREAD

**Issue by oppsig** [ccrisan/motioneyeos#1674]
So I'm running a Pi Zero W with a Pi Camera V 2.1
Should this configuration not be able to stream/record 1920x1080@30?
Or is this require to much of a bandwith to properly stream smothly over wifi?
When i browse the camera on the web server of motioneyeos im probably only getting a few fps at that resolution.

### motionEyeOS Version

I am running motionEyeOS version: 20180627

### Board Model

I am using the following board/model: Raspberry Pi Zero V 1.1!

### Camera
V4L2

My camera model is: (The Raspberry Pi Camera Module v2).

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

**Comment by ccrisan** [comment]
You won't be able to run Full HD@30fps on the Zero. At least not with Motion which uses MJPEG.
