### ISSUE TITLE
Enable System Monitoring 

### ISSUE THREAD

**Issue by mryogihbear** [ccrisan/motioneyeos#1679]
Mine is a simple question.
Enable System Monitoring is enabled
 the output is:
54° I 1.22 I 6307kB/s

my question is what is the middle output? 
CPU Temp I ? I Bandwidth  

I have view the code and it has to do with average CPU load.
however i have no idea what the measurement is.

1.22 out of 10? 

What does this actually mean? 
I have looked around and search and can not find it.

Sorry for the lame question lol

**Comment by ccrisan** [comment]
It's the system load. It could be seen as 1 out of 4 for a quad core CPU, but it's a lot more than that :) Google for "system load linux" and you'll get more comprehensive explanations about it.
