### ISSUE TITLE
Broken streaming URL - app 'IP cam viewer'

### ISSUE THREAD

**Issue by RHTizzy** [ccrisan/motioneyeos#1689]
I have 5 identical cam setups on ' Pi zero W' with 'original 5MP raspberry Pi cam' and until recently accessed all 5 via the 'IP cam view' app through both LAN and WAN. 2 of the 5 cams have just been updated to the latest motioneyeOS firmware v0.39.3. Those 2 no longer provide the video stream in the same way and cannot be accessed by the 'ip cam view' app. The other 3 cam streams on the older firmware still work fine. The setup for the 5 cams and network environment was not changed at all other than the new firmware. The cam streams for the 'broken' firmware are still viewable through the web browser interface, both on LAN and WAN.

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 0.39.3

### Board Model

Pi Zero W

### Camera

I am using the following type of camera: MMAL

My camera model is: Pi Cam IR v2

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:
none

**Comment by ccrisan** [comment]
Then please report the bug to 'IP cam viewer'.
