### ISSUE TITLE
Addind Cameras Manually

### ISSUE THREAD

**Issue by n3rxstech** [ccrisan/motioneyeos#169]
How do I manually add cameras to MotionEyeOS? When it was motionpie there was an option drop down at the top of the page but in MotionEyeOS I see no such option anywhere when logged in as Admin.

**Comment by ccrisan** [comment]
Make sure you are indeed logged in as admin. You'll then see the menu icon on the upper-left corner. Open it and click on the cameras combo box. You should then see the add camera option.

**Comment by n3rxstech** [comment]
There is no cameras Combo box sir. I am including a screen shot.
[https://www.dropbox.com/s/rtt201759k2rseg/Screenshot%202016-02-18%2007.35.50.png?dl=0](url)

**Comment by ccrisan** [comment]
You have enabled [Fast Network Camera](https://github.com/ccrisan/motioneyeos/wiki/Fast-Network-Camera) which doesn't allow adding more than one camera.
