### ISSUE TITLE
option for number of columns missing in landscape mode

### ISSUE THREAD

**Issue by RHTizzy** [ccrisan/motioneyeos#1696]
Was using multiple column layout, but after validating 1 column layout, the option for 2 columns disappeared and does not reappear. 

Preliminary Docs
I confirm that I have read the CONTRIBUTING guide before opening this issue.

I confirm that I have read the FAQ before opening this issue.

motionEyeOS Version
I am running motionEyeOS version: 0.39.3

Board Model
Pi Zero W

Camera
I am using the following type of camera: MMAL

My camera model is: Pi Cam IR v2

Network Connection
My motionEyeOS unit is connected to the network via: WiFi

Peripherals
I am using the following peripherals that I consider relevant to this issue:
none

**Comment by ccrisan** [comment]
The Layout Columns option is only visible when in "landscape" mode (i.e. large screens). It doesn't appear on small screens (i.e. smartphones) because it has no effect there.
