### ISSUE TITLE
How do you control GPIO with raspberry pi when it detects motion? /\ Question

### ISSUE THREAD

**Issue by elementarykid** [ccrisan/motioneyeos#1697]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20180602

### Board Model

I am using the following board/model:Raspberry PI 3B+

### Camera

I am using the following type of camera: MMAL
My camera model is: Raspberry pi 1.3 Standard.

### Network Connection

My motionEyeOS unit is connected to the network via: WIFI

How do you control GPIO with raspberry pi when it detects motion?

**Comment by gitgoldberg** [comment]
First check out the Action Buttons example here:
https://github.com/ccrisan/motioneyeos/wiki/Action-Buttons

Then connect to your motioneyeOS Raspberry Pi through the web interface and look for the Motion Notifications option (near the bottom)
   Run a command
   Run an end command

Create two files in /data/etc contains your bash scripts to control the GPIO, as per the Action Buttons example, one script to make your GPIO HIGH, the other to make it LOW.
Remember to make these script files executable using:  chmod +x your_script_name
Finally plug the full path name of each script file into the 'Run a command' and 'Run an end command' boxes in motioneyeOS.  Might have to reboot.

I've tested this recently and the 'Run a command' script is executed when motion is first detected, and the 'Run an end command' script is executed when the motion event ends.
Hope this helps.

**Comment by elementarykid** [comment]
Thank you.
