### ISSUE TITLE
Surveillance password is saved as plaintext

### ISSUE THREAD

**Issue by ahoward1024** [ccrisan/motioneyeos#1704]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20180627

### Board Model

Raspberry PI 3B+

---

I'm not sure if this is intentional or not, but the password for the surveillance URL is saved as plaintext in the `/data/etc/motion.conf` file.

### Screenshot

![capture](https://user-images.githubusercontent.com/13790819/47932933-a5089b00-de98-11e8-8386-63e95e33fbbd.PNG)

**Comment by ccrisan** [comment]
The surveillance password is stored in plain text because motionEye needs it to be supplied as plain text to Motion when providing the streaming credentials.
