### ISSUE TITLE
Broken streaming URL for 3rd part apps

### ISSUE THREAD

**Issue by RHTizzy** [ccrisan/motioneyeos#1707]
After updating to the latest motioneyeos firmware, the video streams are no longer accessible via the streaming URL to 3rd party apps. 

Three times now you've said 'report it to them' even when asked what was changed in your firmware. So I ask you: report what to them? 
I repeat: what did you change in the last firmware that would cause the streaming URL to break? Cams with the older firmware still work fine with the 3rd party app, the app was not updated in the meantime.....

Interesting that you would close and classify this issue as invalid when asked what you changed.... Did you not keep track of what you changed or are you just an arrogant dick?

Preliminary Docs
I confirm that I have read the CONTRIBUTING guide before opening this issue.

I confirm that I have read the FAQ before opening this issue.

motionEyeOS Version
I am running motionEyeOS version: 0.39.3

Board Model
Pi Zero W

Camera
I am using the following type of camera: MMAL

My camera model is: Pi Cam IR v2

Network Connection
My motionEyeOS unit is connected to the network via: WiFi

Peripherals
I am using the following peripherals that I consider relevant to this issue:
none

Log Files

**Comment by ccrisan** [comment]
> Did you not keep track of what you changed or are you just an arrogant dick?

Maybe a bit of both, although I can't see the connection between the two. When you're dealing with 50 new github issues every week and some of them opened by people like you, it's getting harder and harder not to be one :)

In response to one of your many recent commends, I remember telling you that nothing has recently changed regarding the streaming URLs nor the authentication.

You never told us which is the version that still works for you, so it's hard to compile a list of changes that may impact your setup. Nevertheless, you can see all the changes in every version in the [releases](https://github.com/ccrisan/motioneyeos/releases) page; same applies to [motionEye](https://github.com/ccrisan/motioneye/releases).

Please stop opening issues about this problem unless you have some feedback from the developer of the app you mentioned.
