### ISSUE TITLE
How do you control a servo with the "action buttons"?  || QUESTION ||

### ISSUE THREAD

**Issue by elementarykid** [ccrisan/motioneyeos#1710]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20180627
### Board Model

I am using the following board/model:  Raspberry PI 3B+

### Camera

I am using the following type of camera: MMAL

My camera model is: Standard 1.3

### Network Connection

My motionEyeOS unit is connected to the network via: Wifi

**Comment by ccrisan** [comment]
Please use the [motionEye forum](https://groups.google.com/forum/#!forum/motioneye) for this kind of questions.
