### ISSUE TITLE
Why is FTP so bad?

### ISSUE THREAD

**Issue by talormanda** [ccrisan/motioneyeos#1712]
Every time I connect to it, it seems to time out, or take forever to load. All I am doing is loading a directory or moving a few files and it will stop connecting. SMB seems to be perfect though.

**[pi 3b+]**

![image](https://user-images.githubusercontent.com/10092964/48363366-bc533f80-e673-11e8-922f-b9609221ff86.png)

**Comment by ccrisan** [comment]
That's not normal. It's hard to say what's going on there with your FTP server but it should definitely not say "connection refused". Please attach all the log files and maybe we'll be able to identify the problem.

**Comment by talormanda** [comment]
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/2577368/dmesg.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/2577369/boot.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/2577370/messages.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/2577371/motioneye.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/2577372/motion.log)

@ccrisan I transferred 193 files (pictures) and it randomly gave the same ERROR, then kept going a little while later. Sometimes it will do this, other times it will ERROR and refuse to connect again. This has been happening always, even between reloads of the OS and switch from a 3b to a 3b+.

**Comment by ccrisan** [comment]
@talormanda you're having some network connectivity issues:

    user.notice netwatch: cannot connect to www.google.com:80, rebooting

and

    user.notice ethernet: disconnected

You have enabled the network connectivity watching option, which reboots your system when it detects that connection with the given host cannot be established. This is why you're getting the FTP errors.

**Comment by talormanda** [comment]
@ccrisan I will test this and report back.

**Comment by talormanda** [comment]
@ccrisan how would this be a network connectivity issue? My pi is hardwired directly to the router?
