### ISSUE TITLE
Web interface unaccesible after changing port

### ISSUE THREAD

**Issue by jimmyeao** [ccrisan/motioneyeos#172]
Changed the port to 83, now it doesnt repsond on that port, ssh in and do a netstat and it shows time wait. Scan with fing and port 83 is not showing. Are there iptables in use?

**Comment by ccrisan** [comment]
Nope. iptables is not used by default. Were you trying to access the system directly from your local network? Would you be able to recover some log and config files from your SD card to see what happened?

**Comment by jimmyeao** [comment]
Sorted it now, had it set to medium over lock (pi b, 512mb) and what was happening was a constant reboot- reflashed it and set the over lock to low and it all seems stable now..

Thanks!

Jimmy White


On 21 Feb 2016, at 09:56, Calin Crisan <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope. iptables is not used by default. Were you trying to access the system directly from your local network? Would you be able to recover some log and config files from your SD card to see what happened?

-

**Comment by emosbek** [comment]
Hello,

Same happen to me just now. connected the r.pi to a monitor and are up and running via terminal. Any chance for me to revert port change?

Regards
