### ISSUE TITLE
Action button doesn't show up

### ISSUE THREAD

**Issue by Yosonix** [ccrisan/motioneyeos#1720]
Hi,

I'm having a strange trouble and I can't find the answer anywhere.

I'm running on :

**motionEye Version | 0.39.2
Motion Version | 4.1.1
OS Version | motionEyeOS 20180627
Board : raspberry pi 3 B+**

I created action buttons **light_on_1** & **light_off_1** and made them executable in the **/etc/ folder**.  My **cameraid** is **1**.

<img width="428" alt="putty" src="https://user-images.githubusercontent.com/45320002/48973061-57b2c000-f037-11e8-849e-546459039154.png">

Then, when I click on the camera frame nothing happen. I tried to reboot, reinstall the os but nothing works.

<img width="958" alt="camera" src="https://user-images.githubusercontent.com/45320002/48973074-8b8de580-f037-11e8-9857-089890e820b5.png">

Did I miss something ?

Thanks for your help.

**Comment by gitgoldberg** [comment]
Please make sure your light_on_1 and light_off_1 scripts are placed in /data/etc not /etc as per the clear instructions on the action button help page.

**Comment by Yosonix** [comment]
Thanks it works !
