### ISSUE TITLE
Can't see video after first motion detection

### ISSUE THREAD

**Issue by amammes** [ccrisan/motioneyeos#1729]
YES, I confirm that I have read the [CONTRIBUTING]
YES, I confirm that I have read the [FAQ]
I am running motionEyeOS version: dev20181130
I am using the following board/model: Raspberry Pi 3 Model B
I am using the following type of camera: V4L2
My camera model is: Microsoft LifeCam HD-5001
My motionEyeOS unit is connected to the network via: Wifi 2.4
I am using the following peripherals that I consider relevant to this issue: none
I consider the following log files relevant to this issue:
motion.log, motioneye.log messages.log boot.log dmesg.log
I have my system set to record movies on motion.
After rebooting, motionEyeOS loads fine, the camera is seen fine. If I stand in front of the camera it starts recording, and then after a while the web interface real time camera shows a camera icon with a line crossed in front. If I look at the movie history, the last video has no thumbnail and I cannot play it.

This did not happen in dev20180627 which would record the movies without issue.
[boot.log](https://github.com/ccrisan/motioneyeos/files/2639389/boot.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/2639390/messages.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/2639391/dmesg.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/2639392/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/2639393/motioneye.log)

Note: You will see undervoltage warning in the log. I changed the power supply this morning and the warnings have disappeared, but the issue I am reporting continues.

**Comment by bertdebondt** [comment]
I experience the same problem. 
Raspberry Pi3B+ running from SDcard with latest MotionEyeOS  dev20181210.
It seems after a motion detection somehow motion crashes and you get the camera icon with a line across.
Web interface is still working, a simple config change restarts the thread and camera image is visible again.

**Comment by mrturbopi** [comment]
Same problem on a Pi 2B with a v1 raspberry pi camera on any pre-release 20181129 or newer.  

Strangely, a Pi Zero W, also with a v1 camera doesn't have any problems on the latest pre-releases.  

In debug mode, you will see a message many times before the watchdog timeout and motion process being killed.  

**Dec  2 11:44:10 hostname user.debug motion: [1:ml1] [DBG] [ENC] ffmpeg_encode_video: Receive packet threw EAGAIN returning -2 code :Resource temporarily unavailable
Dec  2 11:44:10 hostname user.debug motion: [1:ml1] [DBG] [ENC] ffmpeg_put_image: Buffered packet
**
Figured this might be relevant as the movie encoding doesn't finish and leaves you with an unplayable file after the motion process is killed.

**Comment by bertdebondt** [comment]
Still looking for the problem. At the moment I enabled back again the motion detection (where the problem is located). 
Yesterday (when motion detection was activated again) I disabled both "Auto Noise Detection" & "Despeckle Filter" ticks and since then the thread did not crash. 
Now I only enabled "Auto Noise Detection" on 1 Pi and only enabled "Despeckle Filter" on the other Pi. 
I'll let you know which option exactly makes the thread  crash since running motion detection without both options works.

**Comment by bertdebondt** [comment]
Problem still occurs. With or without  "Auto Noise Detection" & "Despeckle Filter" ticks.
It happens when motion detection is activated and a file recording is running.
Max. recording time is 300sec at the moment. Going to reduce this time to see if it helps. (Previous 2018-10-xx version worked perfectly). If problem remains... going to have to downgrade since releases above 2018-10-xx are broken

**Comment by jasaw** [comment]
@amammes @mrturbopi  [dev20190118](https://github.com/ccrisan/motioneyeos/releases/tag/nightly-dev) *should* fix your problem. Please report back whether it works for you.

**Comment by mrturbopi** [comment]
@jasaw Looking good ~12 hours in.  Movie lengths/sizes that would have crashed the motion thread recorded normally.  Thanks again for your sleuthing on this, I had no idea where to start looking for the culprit that was causing the motion thread to time out.

**Comment by bertdebondt** [comment]
350 mp4 recordings later (each around 10 to 30 mb) on more than 24h, no issues.
Problem seems solved completely now. :+1: 
thanks again for great support
one small note: motion 4.2.1 runs also great and stable with motioneye on a Raspbian (not MotionEyeOS).
This nightly build is a keeper. ;-)

**Comment by ccrisan** [comment]
I think we're ready for a prerelease that will eventually become our next stable release.
