### ISSUE TITLE
ntp.conf

### ISSUE THREAD

**Issue by Chiny91** [ccrisan/motioneyeos#173]
I'm a user of ntp in motionEyeOS, using another Raspberry Pi as a GPS ntp server.

I've managed to lose the original /etc/ntp.conf but have a note that I have added:
```
# If all else fails, let motionEyeOS do its own thing
server  127.127.1.0
fudge   127.127.1.0 stratum 10
```
so that in the event of motionEyeOS losing the network connection, ntp for motionEyeOS will function correctly.   This would work for others using ntp and an internet server, say from the pool.

The server & fudge lines are very common in example ntp.conf files but not in motionEyeOS default.

**Comment by ccrisan** [comment]
Added.
