### ISSUE TITLE
20181129 Pre Release

### ISSUE THREAD

**Issue by duckietm** [ccrisan/motioneyeos#1735]
Hello,

I read that we can't do an Live Update in the 20181129 Pre Release.
Will this fixed in the stable release?

**Comment by ccrisan** [comment]
@duckietm most likely not, unless someone jumps in and actually implements an intelligent and safe mechanism that deals with the partition layout change in a non-destructive way.

@jasaw proposed a solution but I can't seem to find the issue where we've been discussing this.

**Comment by jasaw** [comment]
@ccrisan @duckietm The solution that I proposed is here: https://github.com/ccrisan/motioneyeos/issues/1582#issuecomment-443921121

**Comment by duckietm** [comment]
Yes, agree completely. We could add a checkbox next to firmware upgrade button that says "reformat data partition". We could also add a warning about losing media files. I think that should satisfy a lot of users.

This would be a great option, this will save me alot of work !

**Comment by jasaw** [comment]
Created "reformat data partition" issue here: https://github.com/ccrisan/motioneyeos/issues/1756
