### ISSUE TITLE
Network settings necessary improvements

### ISSUE THREAD

**Issue by MCSTN** [ccrisan/motioneyeos#1745]
### **THANKS CCRISAN!**
MotionEyeOS is definitely a great project and runs very smoothly on both Raspberry PI 3B+ and Odroid XU4.
My disabled Dad benefits of your impressive piece  of software and your great work every day; making his life easier.  So thanks a lot!

### **motionEyeOS Version**
motionEyeOS 20180627

### **Board Model**
4 Raspberry Pi 3B+ (MMAL Local cameras)
1 Odroid XU4 (hub)

### **Camera**
4 MMAL PICam

### **Usage Scenario**
Multiple Raspberry PI 3B+ MMAL cameras devices  with a central Odroid XU4 server with USB HDD Samba shared for pictures/videos storage; Gigabit Ethernet connected.  (works perfect! :-))

### **Context**
Obviously I chose the Ethernet gigabit closed network solution over the WiFi (hack-able and jam-able) network solution for both network throughput and security reasons. 
I am very happy with this choice and your excellent MotionEyeOS achieves excellent performances with four (1 indoor & 3 outdoor) 1024x576x24bits cameras @5 fps plus motion detection done locally on each camera and captured movies sent to the samba share over Ethernet.  Flawless & impressive!
I'm using crontab and buttons too!  Perfect! :-) 

Since MotionEye is listening on every available NICs I was logically planning on adding an USB wifi key on the Odroid XU4 server  to gain mobile acces to the MotionEye web interface via WiFi on my local home network.

It is stated in the wiki/static_ip.conf:  "If both wireless and ethernet connections are enabled, the ETHERNET connection will ALWAYS USE DHCP".

It is also stated in the /wiki/Tweaks#manually-editing-network-configuration: "There's no /etc/network/interfaces file. Networking is configured by a few init scripts at/etc/init.d/, using simple configuration files..."

### **Improvement**
One major improvement (if doable) would be to give the possibility to setup both eth and wlan to what ever is convignent (static or dhcp) .
And if not possible should'nt it default to static on both?  So users could connect to any network without having the need for a DHCP server.

### **subsidiary questions, if I may **

Is there anny chance I could modify the /etc/init.d/scripts to set static ip on eth0 and dhcp or static ip on wlan0? 

Can I install a DHCP server on one of the static IP Raspeberry PI 3B+ MotionEyeOS cameras on the ethernet network to answer the DHCP Ethernet request from the MotionEyeOS server (already using the static ip possibility on the wifi usb NIC)? 
How Would camera performance decrease?

THANK'S  AGAIN!  Please excuse my poor English.

**Comment by ccrisan** [comment]
If you need a more complex network setup, please use Raspbian or any other general purpose Linux distro.

> Is there anny chance I could modify the /etc/init.d/scripts to set static ip on eth0 and dhcp or static ip on wlan0?

You could do that but I don't think that is advisable, unless you're prepared to maintain your own OS variant.

> How Would camera performance decrease?

DHCP vs static IP setups won't affect your camera performance.
