### ISSUE TITLE
Feature Request: fwupdate upgrade from a local file

### ISSUE THREAD

**Issue by jasaw** [ccrisan/motioneyeos#1746]
During development, I find it way easier to drop a compiled xz firmware onto the device and run fwupdate to upgrade from the file, rather than provide a version or URL. (I apologize in advance if there's already an existing way to do this)

@ccrisan What are your thoughts on adding this feature to ease development and testing?

**Comment by ccrisan** [comment]
The idea is not bad at all. The `fwupdate` script could be easily adapted to start the upgrade from a local file.

**Comment by jasaw** [comment]
Already implemented.
