### ISSUE TITLE
Raspberry Pi zero / Raspberry Pi zero W - What release to use

### ISSUE THREAD

**Issue by srjjohnson** [ccrisan/motioneyeos#1751]
### Preliminary Docs

What version to use for the Raspberry Pi Zero W.

### motionEyeOS Version

What version do you use for the Raspberry pi Zero and Raspberry Pi Zero W - Pi/Pi2/Pi3 ???

https://github.com/ccrisan/motioneyeos/releases/download/20180627/motioneyeos-raspberrypi-20180627.img.xz

https://github.com/ccrisan/motioneyeos/releases/download/20180627/motioneyeos-raspberrypi2-20180627.img.xz

https://github.com/ccrisan/motioneyeos/releases/download/20180627/motioneyeos-raspberrypi3-20180627.img.xz

### Board Model
Raspberry Pi zero W

### Camera

V42L

### Network Connection

Wifi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

### Log Files

I consider the following log files relevant to this issue:

**Comment by zeitg31st** [comment]
You need to use the Raspberry Pi Version for Pi Zero, I can confirm it works 😉 

[https://github.com/ccrisan/motioneyeos/wiki/Supported-Devices](url)
