### ISSUE TITLE
How To's ie the ?  link on the settings do not work

### ISSUE THREAD

**Issue by ejwjohn** [ccrisan/motioneyeos#1765]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: motionEyeOS 20181209

### Board Model

I am using the following board/model: (Raspberry B+

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Pi Camera and EPL USB

### Network Connection

My motionEyeOS unit is connected to the network via:WiFi
## Peripherals

I am using the following peripherals that I consider relevant to this issue:

### Log Files

I consider the following log files relevant to this issue:

**Comment by davisstu** [comment]
Yes it is extra information on the setting that displays when hovered over. What browser and version are you using? I would always suggest the latest version of Chrome or Firefox.

**Comment by ejwjohn** [comment]
Hi,

I feel a bit stupid now, I thought they were links to select not hover points..... all well everythgin working on that score.

THanks

JohnW

**Comment by ejwjohn** [comment]
Hi,

I feel a bit stupid now, I thought they were links to select not hover points..... all well everythgin working on that score.

Thanks

JohnW
