### ISSUE TITLE
WiFi 

### ISSUE THREAD

**Issue by GamingMineblox** [ccrisan/motioneyeos#1766]
My WiFi is not working for Some reson and i also made a .conf file before starting up the first time but it still does not work
![img_0414](https://user-images.githubusercontent.com/42892277/50739576-d415f280-11e2-11e9-91bd-83db2f29de72.jpg)

**Comment by GamingMineblox** [comment]
<strong></strong>

**Comment by GamingMineblox** [comment]
i can't find that location, i can find this:
![image](https://user-images.githubusercontent.com/42892277/53072579-cb088880-34e5-11e9-977e-51e8dd5640cc.png) naam = name

**Comment by McTucker** [comment]
Hi,
I know that naam=name, I live in Oldenzaal ;-)

In the left top corner you can do a search for "brcmfmac"
You will find 35 issues. Hopefully one will suite you.
