### ISSUE TITLE
Need help with crontab

### ISSUE THREAD

**Issue by McTucker** [ccrisan/motioneyeos#1768]
Made a crontab with: crontab -e
It didn't exist yet, but now it contains:

 /1     *     *     *     *      echo "`date`" >> /data/log/cron_test.log

The log isn't get updated.
Somebody knows what I'm doing wrong?

motionEye Version | 0.39.3
Motion Version | 4.1.1
OS Version | motionEyeOS 20181209

**Comment by McTucker** [comment]
It had to be
*/1 * * * * echo "date" >> /data/log/cron_test.log

**Comment by ashishbindal93** [comment]
Hi
I need a little help related to this topic.

I want to add command in crontab to run every 15 mins to update time from NTP server on my local network. I am unable to find any command for date updation.

Someone please help

**Comment by jasaw** [comment]
MotionEyeOS already supports NTP. You can enable NTP from the web interface and point it to your local NTP server. That is the proper way of maintaining time on your device rather than jumping the time every 15 minutes.

**Comment by ashishbindal93** [comment]
Hi thanks for such a quick reply.
I am already following that way of doing it.

My problem is that I have several cameras built with raspberry motioneyeos all pointing to my local NTP server running on another raspberry on same network.

My system is cut-off from internet so I have attached a RTC to the raspberry running NTP server.
All is working fine, but sometimes the cameras start too early than NTP server and then cameras show wrong time "01-01-1970".

Cameras don't correct time after boot.

All IPs on the network are fixed.
 
I want my cameras to poll time every 15 mins from my local NTP server. Crontab seems a good option. Please help.

**Comment by Chiny91** [comment]
It may be common but it is horrible to twiddle time every 15 minutes.   How about running _ntpdate_, just once, as a command when your motioneyeos has booted, to get away from 1970, then back to ntp, if your ntp server really does work without a net connection.

**Comment by ashishbindal93** [comment]
Hi 
I have tried your suggestion but dont know why it is not working.
Please see the output of the commands and guide me.
![output](https://user-images.githubusercontent.com/3213567/63223834-07891880-c1d9-11e9-9da5-add94dadcaff.png)

**Comment by Chiny91** [comment]
It looks as though you have ntp running on motionEyeOS, so ntpdate objects.   Not tested; I suggest you try another port (the -u option) or stop ntp first, use ntpdate, then re-start ntp.   But really, ntp should correct a large time difference on startup (ISTR that motionEyeOS uses ntpd -g), so just stopping/starting ntpd should do it.   Just booting motionEyeOS on to a running ntp server should work.   I'd concentrate on that problem; ensure your R Pi ntp server is running first, ideally always running, as it takes a small number of hours for ntpd to settle.

**Comment by jasaw** [comment]
@ashishbindal93 When you get year 1970 date, can you run `ps | grep ntp` command to see if ntpd is running?
ntpd should be running in the background, and with `-g` option too. There's a bug in ntpd where it crashes silently: https://github.com/ccrisan/motioneyeos/issues/1468 You could be running into this bug too.

**Comment by Chiny91** [comment]
@jasaw How about replacing the buggy ntp with [ntpsec](https://www.ntpsec.org) ?    Smaller footprint, active development so bugs likely to get fixed, tidier than a watchdog for ntp failures.   I've had ntpsec running since 2016, with 2 or 3 motionEyeOS instances reliably sync'ing against it.   I see ntpsec is now packaged in Debian Buster, so that probably says something for stability.   Acknowledged it may simply be too much work to replace ntp in motionEyeOS.

**Comment by jasaw** [comment]
I have no experience with ntpsec, but from the documentation, it looks like a good replacement for ntpd. @ccrisan Should we evaluate ntpsec?

**Comment by ashishbindal93** [comment]
@Chiny91 your solution worked.

Steps I followed:
1. crontab -e
2. */5 * * * * ntpdate -u 80 192.168.1.200

Thank you so much everyone for help.

Need little more help :)

Whats the command to shutdown the camera ( motioneyeos raspberry pi ) ?
How can I instruct the cameras from master device( another raspberry pi connected to the same network ) to do the same ?
