### ISSUE TITLE
How do I edit the modprobe.conf file?

### ISSUE THREAD

**Issue by mehtaman** [ccrisan/motioneyeos#177]
Hi All,

I would like to disable the WiFi Power Management so the device is always on.
What directory is the modprobe.conf in and what commands to I need to change to prevent the device from going into power save mode?

Thanks :+1:

**Comment by ccrisan** [comment]
For that, please use the latest prerelease version [20160221](https://github.com/ccrisan/motioneyeos/releases/tag/20160221) and edit the `/etc/modprobe.d/modprobe.conf` file.

Normally the WiFi power management is disabled by default from kernel and using module parameters, for the most common wifi drivers.

**Comment by mehtaman** [comment]
Thank you I will take a look later today
