### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by fujinjr** [ccrisan/motioneyeos#1779]
What happens when there are too many recorded movies and there is no space left in my disk? 
Will new movies overwrite the old ones?

**Comment by jasaw** [comment]
Short answer is, don't fill up your disk, unless your disk is not the root filesystem. New media will not overwrite old ones.

See:
https://github.com/ccrisan/motioneyeos/issues/785
https://github.com/ccrisan/motioneyeos/issues/1164
