### ISSUE TITLE
Ability to Automaticly do scheduled reboots via the admin setting

### ISSUE THREAD

**Issue by Ash-Bash** [ccrisan/motioneyeos#1786]
Feature Request:
Could motioneye have the ability to do scheduled reboots via the admin settings with like a dropdown box which could allow for reboots for every 6 hours (possible increments of 3 or 6) etc. this may help relieve system stresses like Memory Usage like ram, etc. also  if a user is on motioneye webpage a notification should popup 30-15mins before its scheduled Reboot.

**Comment by ccrisan** [comment]
Use crontab if you need this functionality. It's not something one would want to have in their UI.
