### ISSUE TITLE
Ability to have Smarter Motion Detection (Only Detect Motion in Certain Parts of the Camera View)

### ISSUE THREAD

**Issue by Ash-Bash** [ccrisan/motioneyeos#1787]
Feature Request:
Could you add a Option to enable a smarter Motion Detection that allows you the specify which part of the Camera View(Image) you want to trigger a response. So for example I have a camera setup towards a Gate and on the right & a bit of the top of the screen there is a Bush that moves in the wind but the gate which I want to detect movement from is on the bottom right with the path way going to the left, I want to ONLY detect motion from the pathway to the gate. so for this feature a popup would be needs with the camera view with a Vector shape (will be covering the image at first of cause) that allows for adding points which acts as the area you want to detect motion from can be shaped by user. This will help save storage and unwanted captured files.

**Comment by ccrisan** [comment]
You could use the motion mask or the smart mask feature that is already available in motionEye.
