### ISSUE TITLE
Cannot set static ip because the config file writes config file in lowercase letters, always use dhcp

### ISSUE THREAD

**Issue by developsessions** [ccrisan/motioneyeos#1792]
I am running motionEyeOS version: motioneyeos-raspberrypi-dev20190126
I am using the following board/model: Raspberry Pi 1
My motionEyeOS unit is connected to the network via: Ethernet

The problem is, that this motioneyeos installation always starts in dhcp ethernet mode, because the config file writes writes the keywords in this file in lowercase letters, but the bootup scripts expect uppercase letters. I have changed the keywords in the file /data/etc/static_ip.conf manually by ssh to uppercase letters and now the boot up script /etc/init.d/S40network sets the static ip correct like expected.

Please fix this bug in the next versions. Thank you!

**Comment by ccrisan** [comment]
This should be fixed by c296914e4aa7a5a949e7286ea769f9125e824859 - stuff in `/data/etc` will automatically be converted to uppercase, as needed, upon upgrade.
