### ISSUE TITLE
Rain and Motion Detection

### ISSUE THREAD

**Issue by amitfalana** [ccrisan/motioneyeos#1793]
Hello...
I am a new user of the software and have installed the application on the Raspbian OS.
Although I see that the motion detection gets activated by rain droplets. Do I need to configure motion detection in a certain way (filers, etc.) which can avoid this.

Cheers!
aD

**Comment by jasaw** [comment]
try turning on despeckle filter.

**Comment by jasaw** [comment]
No follow up from issue author, closing issue.
