### ISSUE TITLE
Anyone have a solution to sync with DropBox

### ISSUE THREAD

**Issue by vdyo** [ccrisan/motioneyeos#18]
I saw the google Drive one, is there a similiar method?

**Comment by oopeekoo** [comment]
There is this: https://github.com/andreafabrizi/Dropbox-Uploader
It works fine in Raspibian (done a quick test once), haven't tried it in motioneyeos or motionpie.

**Comment by IamC8** [comment]
Hi look here: https://github.com/ccrisan/motioneyeos/issues/31 The problem is the stat command. The code requires BIN_DEPS="sed basename date grep stat dd mkdir". All are present but not stat.

**Comment by vdyo** [comment]
Thanks for the answer, might be a bit my own Linux ability, but I can probably find someone to add it for me.

**Comment by ccrisan** [comment]
"Official" support for Google Drive and Dropbox is coming soon. Stay tuned :)

**Comment by vdyo** [comment]
Awesome

**Comment by SuneBielefeldt** [comment]
Dropbox and Google Drive support
It's very good news, looking forward to the next great version.
😊
