### ISSUE TITLE
Feature Request:  Add mysql client to motioneyeos image

### ISSUE THREAD

**Issue by discarn8** [ccrisan/motioneyeos#1801]
I currently write server stats to a mysql db (CPU / video temperatures, cpu load, mem, etc.)

I'd like to be able to do the same from my RPis running motioneyeos.  Would it be a reasonable ask to add some sort of sql client to the motioneyeos image, allowing writes to a sql db?

Alternately, I understand that motion already allows for sql writes upon detection / events.  Has anyone utilized that built-in sql feature to write to a sql db for other items, such as for my request?

**Comment by ccrisan** [comment]
The answer is no, because:

 * adding such a function to motionEyeOS would increase the image considerably
 * very few users would actually find this useful
 * there are other means to achieve similar functionality,  through webhooks

**Comment by discarn8** [comment]
Copy that. Thank you for the reply, sir (and the great work, you do)
