### ISSUE TITLE
Wifi not working on pi zero

### ISSUE THREAD

**Issue by j-dizzle1** [ccrisan/motioneyeos#1804]
I have tried both Mac and windows 10, uploading the wpa_supplicant.conf (sidenote I have tried copying and pasting everything to make sure it is exact to no avail)  The os boots but it says it can't find wpa_supplicant.conf.  It then reboots over and over.  I have tried different psu and that did not work.  The only thing I can guess is that something is up with my wifi.  If I set it to connect to a hotspot on my phone will I be able to reconfigure the wifi later?  I will also try reflashing it and using ethernet on a pi 3.  Thank you

**Comment by jasaw** [comment]
Have you read these?
https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems

**Comment by cameronbunce** [comment]
The same image will not work not he Pi3 because the Pi Zero uses a different processor (same as the original Pi) 
Have you tried using a standard Rasbian image to verify that all is well with your board and your Wifi setup?
I've just used dev20190204 on my Zero and it works just fine.

**Comment by captaintapir** [comment]
I can confirm that I'm also experiencing this on a Pi Zero W.  I've just upgraded to the latest version (20190209, but had the same issue with 20190119) and the first boot works fine.  I start configuring it and at some point I need to restart.  Once I do so, it goes into a boot loop.

wpa_supplicant.conf disappears from /boot, which I assume is meant to happen?

I'd post logs, but it doesn't look to have saved any - /var/log is a symlink and there doesn't appear to be a log elsewhere on either partition.

**Comment by ccrisan** [comment]
@captaintapir 

> wpa_supplicant.conf disappears from /boot, which I assume is meant to happen?

Yes, that is normal, starting with recent dev/nightly versions.

> I'd post logs, but it doesn't look to have saved any - /var/log is a symlink and there doesn't appear to be a log elsewhere on either partition.

Assuming you pulled out the SD card and browsed it using your PC, the `/var/log` on your `root` partition is indeed a symlink to `/data/log`, which you'll find on your `data` partition, under the path `/log`.

Also, the next nightly build will have wpa_supplicant debugging enabled when `OS_DEBUG` is set. Could you please try it as well (as soon as it will be ready) and turn on the *Expert Settings > Enable Debugging option*? Then, in case of WiFi problems, the `wpa_supplicant.log` should contain more details on the problem.

**Comment by captaintapir** [comment]
Great, thanks.  Will try it once it's released.

**Comment by ccrisan** [comment]
[dev20190218](https://github.com/ccrisan/motioneyeos/releases/tag/nightly-dev) is ready and available for testing.
