### ISSUE TITLE
Question about Bugfixing in version 20190119

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneyeos#1810]
Hi, 

the changelog of the new version 20190119 says:
"OS: Raspberry PI (all): fixed a nasty stability issue when using the OMX h264 encoder"

Could you give some details about the bug that was fixed?

Thanks a  lot 

helmar

PS: updated all my cams with the commands you provided on release page.
All updates where installed properbly-

**Comment by jasaw** [comment]
@helmar74 See https://github.com/ccrisan/motioneyeos/issues/1730#issuecomment-455128464

**Comment by ccrisan** [comment]
> All updates where installed properbly-

@helmar74 thanks for your feedback.
