### ISSUE TITLE
Third party cameras

### ISSUE THREAD

**Issue by kgoerbig** [ccrisan/motioneyeos#1812]
Can motioneyeos support adding third party camera's as 'remote cameras'? Example:

https://www.banggood.com/NEO-COOLCAM-NIP-55-HD-720P-Mini-WiFi-IP-Camera-Wireless-P2P-Baby-Monitor-Network-CCTV-Security-Camer-p-1291925.html?rmmds=search&ID=43101&cur_warehouse=CN

https://www.banggood.com/Digoo-BB-M1-Wireless-WiFi-USB-Baby-Monitor-Alarm-Home-Security-IP-Camera-HD-720P-Two-Way-Audio-p-1083520.html?rmmds=search&cur_warehouse=CN

**Comment by ccrisan** [comment]
In theory yes. Please use the [motionEye Google group](https://groups.google.com/forum/#!forum/motioneye) for this kind of questions.
