### ISSUE TITLE
Can't turn LED Off HD Pro Webcam C920

### ISSUE THREAD

**Issue by mostym** [ccrisan/motioneyeos#1826]
Hi there.  I love your software, though I did I have one question.  How can i turn off the LED on my HD Pro Webcam C920?

Thanks!

**Comment by ccrisan** [comment]
No idea. That's something specific to the camera itself, not the V4L2 interface, as far as I know.

**Comment by mostym** [comment]
Hey @ccrisan when I install just motioneye on raspbian, and then do the following, I can turn off the LED.  Can I please request this as an enhancement?  I would much rather use your motioneyeOS.  Thanks!

```
sudo apt-get install uvcdynctrl
sudo uvcdynctrl -i /usr/share/uvcdynctrl/data/046d/logitech.xml

# LED off
uvcdynctrl -s 'LED1 Mode' 0
```

**Comment by ccrisan** [comment]
We have `uvcdynctrl` on motionEyeOS so you can use that.

**Comment by allthegoodnamesweret4ken** [comment]
@mostym 
> 
> ```
> sudo apt-get install uvcdynctrl
> sudo uvcdynctrl -i /usr/share/uvcdynctrl/data/046d/logitech.xml
> 
> # LED off
> uvcdynctrl -s 'LED1 Mode' 0
> ```

Did you manage to switch off the LED? If so, care to share how? I have the exact same camera, and am facing the same problem.

**Comment by alpa2009** [comment]
knowing this is an old post, but having the same problem: it seems that control option 'LED1 Mode' does not exist, at least it is not listed when listing the available user controls...  was this ever solved? Tnx

**Comment by sfduff** [comment]
Using **uvcdynctrl** to turn off Logitech c920 LEDs does work, even with the errors, so long as you don't have the local pi camera interface enabled using Raspi-config.  
As soon as the pi camera interface is enabled, it stops working; disable it and once again!
I have a couple of RPi's using 'both' a pi camera (for night vision) and a Logitech c920 for daytime connected.
I used to be able to operate both from the same pi3b+ using Stretch, but have not been able to do the same with Buster.
I'm guessing it is something to do with address space for the devices, but it is a bit beyond me tbh, and help welcome.

**Comment by floriansiepe** [comment]
For those who are facing the same issue. I was able to disable the led by using `v4l2-ctl`.

```bash
# Get the right device
v4l2-ctl --list-devices
# Get the current setting (my device was /dev/video4)
v4l2-ctl --get-ctrl=led1_mode -d /dev/video4
# Disable the LED
v4l2-ctl --set-ctrl=led1_mode=0 -d /dev/video4
```

**Comment by Paderman** [comment]
> For those who are facing the same issue. I was able to disable the led by using `v4l2-ctl`.

Thank you for your help 🙂

Where can I find all commands for this camera?
I must e.g. flip the camera but I don't know how does it work.

Is it possible to get and set frame rate and many more?
Currently it gives only 5 FPS in [motion](https://motion-project.github.io). Used system is [Orange Pi Zero2](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-Zero-2.html) with the latest _Orangepizero2_3.0.6_ubuntu_jammy_server_linux5.16_...

Thank you in advance.
