### ISSUE TITLE
Is it too soon to ask... Pi 3 Compatibility?

### ISSUE THREAD

**Issue by mehtaman** [ccrisan/motioneyeos#183]
Hi ccrisa,

I was just wondering if you would be looking at adding the various new drivers/packages into MotionEye OS for the new Pi 3 board?

**Comment by ccrisan** [comment]
Wait till I get my hands on a PI3.

**Comment by Mikiya83** [comment]
And please don't forget the Odroid C2 after the C1 that you already support, i find it more interesting than RPi3 for the same price, if it's supported by motioneyeos, it could be perfect ! :D

**Comment by samg2016** [comment]
Added motioneye to my new pi3 yesterday. Runs very well.

**Comment by db414813** [comment]
Yes. Odroid c2 support would be fantastic! Don't want to overwhelm you with boards though. Next thing ya know someone will be asking or orange pi support haha.

**Comment by ccrisan** [comment]
Orange PI has already been requested a couple of times. The only real problem with many boards is the testing procedure right before a release, which is already painful.

**Comment by db414813** [comment]
I wouldn't touch an orange pi. Horrible reviews on Amazon. I'll buy either a rpi3 or odroid c2, if it is supported. It would be my main server for my Motioneye set up. The c2 and the gigabit Ethernet is what has my attention.

**Comment by ccrisan** [comment]
I hear you :)

**Comment by alipepic** [comment]
hello,

we downloaded the pi 3 image of motioneyeOS. Having issues, in short administrative panel only has one new section, all the other sections of the administrative panel are gone. The frame rate is extremely slow . Advise please. thank you very much.

**Comment by andrewvictor** [comment]
Having great success running several RPi3 integrated into one hub, on WiFi and uploading images directly to Google Drive.  Tested this platform throughout the winter (Canada, -35C) with great success!

**Comment by bortek** [comment]
Great, I will therefore close this one.
