### ISSUE TITLE
Small problem with ntp

### ISSUE THREAD

**Issue by DD-DE** [ccrisan/motioneyeos#1834]
When booting, motioneyeos does not get the correct date from ntp server. As far as I can see, it's a simple fix: in /etc/init.d/S50date, there is a wrong path for ntpdate, should be /usr/bin instead of /usr/sbin.

Thanks for a cool project!

**Comment by ccrisan** [comment]
Thanks! Fixed via https://github.com/ccrisan/motioneyeos/commit/47e0d54de34125e2212efaa0b713904591a4b2e6.
