### ISSUE TITLE
Windows VM?

### ISSUE THREAD

**Issue by popcicle2003** [ccrisan/motioneyeos#1845]
Hi. I have a Windows Server 2016 running Plex, SMB, and a web server. I was wondering if there is a way that I can get it to run motioneyeos so that I could use it as a server for my raspberry pi's already set up. I had an idea of running a light Linux distro on a VM but not sure if that would work. I know this is a long shot but I can try really anything.

Thanks,
Daniel

**Comment by ccrisan** [comment]
Please use the [motionEye forum](https://groups.google.com/forum/#!forum/motioneye) for this kind of questions. Long story short, Linux VM yes, Windows VM no.
