### ISSUE TITLE
Will an external wifi adapter help Fast Network Camera performance with a RPi ZW

### ISSUE THREAD

**Issue by PedroC1999** [ccrisan/motioneyeos#1847]
I currently have an RPI ZW set up as a Fast Network Camera over wifi with an RPI 3B as a recording/upload device.

I have the CSI Pi camera 1.3, set to a resolution of 1280*1024 with a quality of 15% with a streaming FPS of 15 (I can put it between 10 and 20 and there is no difference)

On the RPI 3B, I get a ~15fps reading in the first number, and ~4-7fps in the second number. The second number is consistent with the FPS produced in the output videos

Is this due to a network throughput limitation? What can a Pi Zero W under ideal conditions do in terms of resolution and FPS when used as a Fast Network Camera (and btw, overclocked to the High preset)

Many thanks, Pedro

**Comment by ccrisan** [comment]
It may be due to network limitations (that's the main bottleneck afaik).
