### ISSUE TITLE
motioneyeos hangs on colored boot screen - Pi 2

### ISSUE THREAD

**Issue by lpgordon** [ccrisan/motioneyeos#185]
I had  motioneyeos working flawlessly on a Pi B+. I got a new Pi 2 and when I moved the SD card over and booted it stuck on the multicolored screen. I tried a fresh image on a new card and that also hung.

I tested the Pi 2 with a Raspbian image and it worked fine.

Any suggestions?

**Comment by ccrisan** [comment]
Please download and write the [RPI2](https://github.com/ccrisan/motioneyeos/releases/download/20160109/motioneyeos-raspberrypi2-20160109.img.gz) OS version.
