### ISSUE TITLE
Can motioneyeos run a python script continuously when booting up?

### ISSUE THREAD

**Issue by khaiz91** [ccrisan/motioneyeos#1852]
Is "Adding Custom Startup Commands" by create the file /data/etc/userinit.sh a one time execution during startup only?

If I'm assigning a button switch to a GPIO, once it is pressed it will trigger another GPIO to turn on.

It has nothing to do with the motioneye, but i want my RPi to have both this button and triggering function and surveillance feature under 1 RPi.

Thank you.

**Comment by ccrisan** [comment]
You can run a script from `userinit.sh` in background, by appending ` &`.
