### ISSUE TITLE
dev20190311 bug on pizero w

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1853]
the version dev20190311 contains several bugs on pi zero w, it does not recognize more camera coming from a price of the prerelease version 20190223 and reformatting the pizero w from zero 

i have  error : You have not configured any camera yet. Click here to add one...

pi camera 8mpixel
I also want to clarify that with release 20190119 the fastcamera moalità works on pizero and picamera

![Immagine](https://user-images.githubusercontent.com/35575744/54125014-2a322c80-4404-11e9-8f1d-dfbaf4c0fe59.png)

**Comment by zapletaldavid** [comment]
Same behavior on RPi 3B with RPi Camera V2, unable to add camera. Reverted back to dev20190223.

**Comment by tigernero79** [comment]
@zapletaldavid on dev20190223 

A information to you works FAST CAMERA mode?

**Comment by tigernero79** [comment]
on dev20190223 work fastnetwork caera mode image?

**Comment by zapletaldavid** [comment]
OK, sorry. No, it doesn't, no picture after switching to fast network camera mode on dev20190223.

**Comment by ccrisan** [comment]
Guys, the two bugs have been fixed as follows:

 * Fast network camera mode, by adf81dea0d34e7b80fa8db151a45ff2585b9308c
 * MMAL camera, by https://github.com/ccrisan/motioneye/commit/443ab40c3608b645c2b0ba8e7d93c7d42b13d09b

Thanks for reporting.

**Comment by tigernero79** [comment]
ok thanks, but always solved with version 20190311 or we have to wait for new image?

**Comment by ccrisan** [comment]
Wait for the new nightly build to be ready.

**Comment by tigernero79** [comment]
Thanks
