### ISSUE TITLE
motion eye on raspberry pi zero

### ISSUE THREAD

**Issue by thostie2002** [ccrisan/motioneyeos#1861]
which version do I need for the raspberry pi zero?

**Comment by tigernero79** [comment]
https://github.com/ccrisan/motioneyeos/releases/download/20190119/motioneyeos-raspberrypi-20190119.img.xz

**Comment by thostie2002** [comment]
thank you it worked, but what is the host port?

**Comment by tigernero79** [comment]
port is 80 is change in gui after

http://rasp_ip
