### ISSUE TITLE
Clarity on Upload & Storage Length

### ISSUE THREAD

**Issue by Saleshorse** [ccrisan/motioneyeos#1862]
Sorry to open an issue, just curious of the settings in video and stills and how that would affect the uploaded storage. I see that the images are cached locally and I've set the length (for now) to one week. I'd prefer to upload each and use the server (VPS) to handle long term storage. Is the settings under each of those options going to clear storage on the SFTP site I'm using?

**Comment by ccrisan** [comment]
Currently only the Google Drive upload service allows removing old files upon cleanup.
