### ISSUE TITLE
How would it perform on Odroid xu4?

### ISSUE THREAD

**Issue by Wursthandschuh** [ccrisan/motioneyeos#1866]
I tried motioneye in docker. It's super fluent and I can capture 720p 25fps easily with low cpu draw.
The rpi 3b+ can't even handle 480p 10fps. It's delayed by 20s or more. Often stops working completly.

Thus I'm looking for alternatives. Can anyone share how the xu4 performs as a motioneye hub? What fps/resolution can I expect?

**Comment by ccrisan** [comment]
@Wursthandschuh please use our forum for this kind of topics: https://groups.google.com/forum/#!forum/motioneye.
