### ISSUE TITLE
Please add rtl8188fu kernel module

### ISSUE THREAD

**Issue by r0d0dendr0n** [ccrisan/motioneyeos#1868]
I recently bought a usb wifi dongle. Pretty nice device, although it seems not to be supported by motioneyeos. Weird, despite the fact that other Realtek dongles are supported: rtl818x, rtl8192cu, rtl8xxxu, rtlwifi.

The rtl8188fu can be found here: https://github.com/kelebek333/rtl8188fu . I kindly ask to consider adding this driver to the source tree of this great project.

In the meantime, can anyone please guide me to some docs on how to cross compile this module on a generic linux desktop for an armv6 raspberry pi? I believe this could be done and then easily copied over to motioneyeos via ftp.

**Comment by ccrisan** [comment]
As long as the driver is not part of the mainline kernel or the official Raspberry Pi kernel, it won't be part of motionEyeOS. We don't commit to maintain out-of-tree drivers.
