### ISSUE TITLE
Pi 3B+  Not working

### ISSUE THREAD

**Issue by MrCarrotMan** [ccrisan/motioneyeos#1869]

**Comment by MrCarrotMan** [comment]
Hello I have just tried to do install MotionEyeOS on my pi 3B+ once I’ve done it it it worked but when I rebooted the pi would not boot MotionEyeOS or Raspbian but MotionEyeOS worked fine on pi 3B

**Comment by dfdy** [comment]
I can confirm that the latest release is not booting on my Pi 3B+.

**Comment by Gioser98** [comment]
The latest release is working fine on my Pi 3B+. Did you try installing it again?

**Comment by ccrisan** [comment]
I am running the latest nightly build on a RPi 3 B+ as we speak.
