### ISSUE TITLE
Recommended Router for use with Motioneyeos? 

### ISSUE THREAD

**Issue by Tontothecat** [ccrisan/motioneyeos#1872]
Hello github peeps!

I'm having an interesting issue that I hope someone can help with.. 

I have setup a 2015 RPi3 with an old logitech webcam, used in  my home WiFi and works perfectly, I was able to use the Web interface and could see the feed from the camera. 

I then took this setup to my sister's (where the only differences were the screen/header for the pi and the WiFi router)..
The RasPi connects to her WiFi and her router can see it (her router is a Vigor Draytek, we even use the same ISP)
Her router has allocated an IP to my RasPi but I could not use the Web interface nor could I ping it.. 
Advanced IP scanner never detected it there either.. However it did jump IP addresses:
e. g. the router had x. X. X. 1 
my laptop had x. X. X. 3 and that's all Advanced IPScanner would see.. 
Yet motionEyeOS showed the RasPi ip address as x. X. X. 2.. 

Is there a perfect Router type or router configuration that I should use with MotionEyeOS?

I have even tried to use a config file to manually set an ip address but that didn't do the trick..

I took my setup back home - made sure I gave it my WiFi settings again--and it works.. 

I then tried the newest build (by weds 20th mch) and once again, fine at my house but not at my sister's.. 

I'm convinced its the router configuration at my sister's house but I am unsure what it could be.. Does anyone have any pointers or has come across this issue?

Many thanks in advance

**Comment by ccrisan** [comment]
There's no such thing as a perfect router for motionEyeOS. It's rather about a router that works well with the Raspberry Pi (most of them do). Please use our [forum](https://groups.google.com/forum/#!forum/motioneye) if you're looking for recommendations.
