### ISSUE TITLE
Dev20190327 fnc not working system monitoring?

### ISSUE THREAD

**Issue by tigernero79** [ccrisan/motioneyeos#1875]
@ccrisan Do you also confirm that in fast boot camera mode, even if you enable the voice system monitoring, the FPS item does not exit by clicking on image? in motioneye mode it works instead. this release however solved the problem of the update from previous versions. thank you

**Comment by ccrisan** [comment]
@tigernero79 I'm not sure I understand what you mean. Please make sure you're using the correct names of the various functions of motionEye(OS).

I assumed that *fast boot camera mode* would in fact mean *fast network camera mode*, but the *the voice system monitoring* beats me.

Please attach a couple of screenshots exemplifying what you mean by *FPS item does not exit by clicking on image*.

**Comment by tigernero79** [comment]
@ccrisan 
Example working button enable system monitoring motioneyeos

![Screenshot_20190401-221353_Chrome](https://user-images.githubusercontent.com/35575744/55356738-bbf4fd00-54cb-11e9-96ce-a6b69b1edf43.jpg)

Example not working the button enable system monitoring on fast network camera enable
![Screenshot_20190401-221720_Chrome](https://user-images.githubusercontent.com/35575744/55356848-f8285d80-54cb-11e9-8491-5d16766100ce.jpg)

**Comment by tigernero79** [comment]
@ccrisan 

in practice it does not take into account the file monitor_1 and not from values ​​by clicking on video, also with dev20190402 I noticed that ilf ile monitor_1 exists but now neither in motioneyos than in fastboot camera mode from values. does not take into account the file monitor_1 in short

**Comment by ccrisan** [comment]
The fast network camera mode is a simple MJPEG stream directly displayed in browser. There's no (easy) way we can transmit monitoring information with MJPEG frames. And this is not some regression bug recently introduced.

**Comment by tigernero79** [comment]
@ccrisan ccrisian with dev20190402 even in normal mode now I have more info from monitor_1, so I don't talk about fcn now, in practice I no longer see the values ​​in degrees fps from monitor_1, this with your defaul script, you see them?
