### ISSUE TITLE
[RPi 2, Simple MJPEG] empty section "File Storage"

### ISSUE THREAD

**Issue by argenistobago** [ccrisan/motioneyeos#188]
Hi,

I've got motionEyeOs on RPi2 (latest release).
Successfully added Simple MJPEG Camera (Dahua). I can see stream, video is ok.

Unfortunately in section "File Storage" I have only one position "Run A Command".
I want to record on USB HDD.
There were no more changes in any config files.

Is it a bug?
Can I set the path in different way?

![016-03-02_19-27-30](https://cloud.githubusercontent.com/assets/17599893/13470624/5cdf8776-e0ad-11e5-870f-7a8db3450bfe.png)

**Comment by ccrisan** [comment]
Don't use simple mjpeg camera if you want motion detection and other options.

**Comment by argenistobago** [comment]
I want only save video on HDD. Is it impossible for MJPEG?
I cannot use RSTP because I receive unresolved error (rtsp netcam returned erroneous response: RTSP/1.0 401 similar to [)](https://bitbucket.org/ccrisan/motioneye/issues/198/d-link-dcs-935l-rtsp-error)

**Comment by ccrisan** [comment]
Use Network Camera then.

**Comment by argenistobago** [comment]
This answer resolves problem :) Thanks a lot.
