### ISSUE TITLE
Proper place to add static route in MotionEye OS

### ISSUE THREAD

**Issue by wboerhout** [ccrisan/motioneyeos#1888]
I want to add a static route to the network config. Has to do with VPN access to the shell.

`route add -net 10.8.0.0/24 gw 192.168.2.2`
 
What is the proper place to add this command?

**Comment by jasaw** [comment]
Try putting this command in `/data/etc/userinit.sh`? I'm not sure whether network interface going down will automatically remove this static route. If it does, then you'll need to hook it into ifup script, wherever that may be.

**Comment by wboerhout** [comment]
This file did not exist, but I created it with the command in it, and apparently is was executed by the startup sequence. This will do fine, thanks!
