### ISSUE TITLE
Missing advance options

### ISSUE THREAD

**Issue by MikeMikeB** [ccrisan/motioneyeos#189]
Just installed latest version on RPi B+. Attached two usb cams to it but their resolution is poor (should not be). Tried to do some configuration (checked Configuiration screens in the Wiki), but I do not see any options to do that. It's like every single advance configuration option is missing. I use Firefox on Windows 7.

**Comment by ccrisan** [comment]
May i see a screenshot?

**Comment by MikeMikeB** [comment]
Sorry, my bad. I completelly overlooked "Advanced Settings" switch on the page. Got it now.
