### ISSUE TITLE
Google Drive features

### ISSUE THREAD

**Issue by Jefferysan** [ccrisan/motioneyeos#1891]
Does the google drive setup automatically delete old footage as it gets closer to maxing out in storage or hit a certain date or GB? Or does this have to be done manually. How frequent can it upload to a google drive?

I really want to start purchasing the extra equipment for my setup, but want to confirm on this feature as it is my make it or break it requirement :)

**Comment by bob-lee** [comment]
[Clean Cloud](https://github.com/ccrisan/motioneye/pull/1118) feature is waiting to be released soon, the feature is in release candidate both in `motioneye` and `motioneyeos`.
