### ISSUE TITLE
Zero W: many pictures cause memory problem

### ISSUE THREAD

**Issue by white-rabbit07** [ccrisan/motioneyeos#1901]
Hi. I'm running 
motionEye Version | 0.40rc5
Motion Version | 4.2.2
OS Version | motionEyeOS dev20190408
on a Rasperry Pi Zero W (with Wifi-Connection). Everything worked fine ... but now the Webcam took so many pictures that a memory problem occured. On some days there are about 4000 pictures ... sometimes "just" 800. The RasPi takes photos since the beginning of this month (it's just a nesting box cam)

When I try to access the pictures via WebGUI I just get:
"An error occurred. Refreshing is recommended."
When I restart the RasPi the problem still exists.

I deleted many files via ssh on /home/ftp/sdcard/<date>/* 
Now I can access the pictures with my browser again but that's no solution for the problem. 
So next thought: create an additional swap-file to increase memory ... I tried this:
mkdir -v /var/cache/swap
cd /var/cache/swap
dd if=/dev/zero of=swapfile bs=1K count=4M
chmod 600 swapfile
mkswap swapfile
(https://askubuntu.com/questions/33697/how-do-i-add-swap-after-system-installation)
But the "mkswap"-command is missing.

So: what to do? 
Any ideas?
Thanks!

**Comment by ccrisan** [comment]
Enabling swap on an SD card is very unpractical and many times useless, due to the very slow random read/write. If your system runs out of memory, I strongly recommend either cleaning up your media folder or upgrading to a more powerful board.
