### ISSUE TITLE
MJPEG URLS in Version 20190427

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneyeos#1903]
Hi,

I only have a question.
I upgraded my cams to 20190427 successfully. 
In the Changelog i read:
"motionEye: added support for mjpeg://" 

Does this mean, I can access the stream of the camera with a mjpeg URL?
I tried different URLs, but I don't manage to get it running...
Which port do I have to use?
Thanks a lot

helmar

**Comment by Nypan-sr** [comment]
IP:8081

**Comment by helmar74** [comment]
it's the "normal" streaming port?
If I change it here:
![image](https://user-images.githubusercontent.com/25499089/57189162-2c4bcf80-6f0b-11e9-8b22-5e4fd25c247e.png)


Than I have to use that one?

**Comment by ccrisan** [comment]
> Does this mean, I can access the stream of the camera with a mjpeg URL?

It doesn't mean that, but you could have done that before, assuming your MJPEG client accepted the `mjpeg://` scheme.

This is about motionEye being able to pass a `mjpeg://` netcam URL to the underlying Motion daemon.

> Which port do I have to use?

It's `8081` unless you changed it explicitly.
