### ISSUE TITLE
How To Make Smooth The Streaming And Storage?

### ISSUE THREAD

**Issue by CaputoDavide93** [ccrisan/motioneyeos#1909]
I'm new of motioneye, I really like the idea but do not fit my purpose so far...

I need basically 2 things :
- Streaming from anywhere.
- Storage Video 24h a day (only Video) on a google drive / Dropbox 

Witch one is the best setup? Maybe Rasp PI W is not enough powerful ? 
 
So far the result was not the best, the fps really low... and storage if off!
Can someone give me a config or suggestions of how to do better?

Many Thanks!

**Comment by ccrisan** [comment]
This is an issue tracker. Please use our [forum](https://groups.google.com/forum/#!forum/motioneye) or [Facebook page](https://www.facebook.com/motioneyeos) if you need suggestions or recommendations.
