### ISSUE TITLE
Add autossh tool to default BuildRoot config

### ISSUE THREAD

**Issue by dbruneau-ie** [ccrisan/motioneyeos#191]
Hi,

I was wondering if you would consider compiling with the tool "autossh" enabled.  I've compiled from source with it activated and it appears to work as expected on raspberrypi2

I think it's a useful utility to have.  It can be used to automatically handle ssh disconnects.

My use case is SSH tunnelling out and RemoteForwarding a port.

Regards and thanks for all your work.

**Comment by kamusz** [comment]
+1 on this from my side. Autossh would help me much too.

**Comment by ccrisan** [comment]
It's a small binary so I just added it to the OS with b509f61d15fc842353fb5441d46fae1e40de29e4.
