### ISSUE TITLE
Motion Detection Not Working

### ISSUE THREAD

**Issue by DiversSundries** [ccrisan/motioneyeos#1912]
Hi. MotionEyeOS has been great for getting me up and running, but I can't get it to do motion detection. I've tried both the 20190427 and 20190119 version (logs and settings from the latter) on Raspberry Pi 3B+ with CSI camera in MMAL mode. I've fiddled with the settings a lot, over several days, and reinstalled from scratch several times:

- Threshold all the way down
- Frame rate up and down
- Low and medium resolutions
- Low minimum frames
- Despeckle and Noise filters on and off

Most posts here are from people trying to figure out how to reduce the number of false positives. I can't get anything.

Once in the past few days, I succeeded in getting some motion-triggered videos, but haven't been able to recreate that success. What I really want is motion-triggered photos, but no luck so far, at all. I'm trying to capture boats going by on the river outside. There are hundreds of opportunities in a day. 

Streaming and manual capture of photos both work great. No problem at all. Perhaps the size of the ships' movement relative to the frame is too small?

I realize this is probably a "motion" issue, but wondering if something's lacking in my MotionEye or MotionEyeOS settings, since all my interactions are through the MotionEye interface.

Thanks! Great project. Just trying to figure out how to get it to 100% by getting motion detection working.

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.
YES

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.
YES
### motionEyeOS Version

I am running motionEyeOS version: 20190119

### Board Model

I am using the following board/model: Raspberry PI 3B+

### Camera

I am using the following type of camera: MMAL

My camera model is: Raspberry PI CSI v2.1
### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

### Peripherals
None

### Log Files

I consider the following log files relevant to this issue:

 * motioneye.log
 * motion.log
 * motioneye.conf (renamed to .txt to upload)
 * thread-1.conf (renamed to .txt to upload)
 * example.jpg
![example](https://user-images.githubusercontent.com/50386681/57342571-7e5c4300-710d-11e9-9953-04c1e5ee65ac.jpg)
[thread-1.txt](https://github.com/ccrisan/motioneyeos/files/3155005/thread-1.txt)
[motioneye.txt]
(https://github.com/ccrisan/motioneyeos/files/3155004/motioneye.txt)
[motion.log](https://github.com/ccrisan/motioneyeos/files/3154995/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/3154996/motioneye.log)

**Comment by DiversSundries** [comment]
Yikes! I should be careful what I wish for. I had missed **"Capture Mode = Motion Triggered"** under the Still Images section. After setting that, with the Minimum Motion Frames set to 1, Despeckle and Noise  Filters Off and Noise Level set to 0, the triggered images started pouring in. 

I'll play with these settings and try again. If all goes well, I'll see how it works under the latest version.
Perhaps this post will be useful to someone else.

**Comment by ilovelinux** [comment]
I guess that this issue can be closed
