### ISSUE TITLE
Noir Cam No Auto Exposure 

### ISSUE THREAD

**Issue by peternsomerset** [ccrisan/motioneyeos#192]
Hi,

I install motioneyeos OK but when I tick the box for auto,  the screen cycles through about 6 levels of brightness.
My pi noir works OK with raspian and motionos works with microsoft USB cam.
Any suggestion as to what is causing this to happen?
Thanks

**Comment by ccrisan** [comment]
Don't enable auto brightness (if that's what you mean by the "box for auto") for RPi cameras.

**Comment by peternsomerset** [comment]
OK, is that the same for motion as well or just motioneyeOS that does not have this function?
Thanks
--
Sent from myMail app for Android Friday, 04 March 2016, 07:32am +00:00 from Calin Crisan < notifications@github.com> :

**Comment by ccrisan** [comment]
It's motion's internal function. motionEye(OS) doesn't interfere in any way with the video processing.

**Comment by peternsomerset** [comment]
OK thanks.
