### ISSUE TITLE
Cloud cleanup not working

### ISSUE THREAD

**Issue by patrickhener** [ccrisan/motioneyeos#1924]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190427

### Board Model

I am using the following board/model: Raspberry Pi 3B

### Camera

I am using the following type of camera: Raspberry Pi Camera
My camera model is: v2 Noir

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet
### Peripherals

- 

### Log Files

I consider the following log files relevant to this issue:
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/3197233/dmesg.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/3197234/boot.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/3197235/motioneye.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/3197236/messages.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/3197237/motion.log)

### Screenshots
![1558345502_1145_20052019_473x438](https://user-images.githubusercontent.com/7579055/58012475-d5dab580-7af4-11e9-9e92-078e5939f16f.png)
![1558345525_1145_20052019_486x416](https://user-images.githubusercontent.com/7579055/58012482-d96e3c80-7af4-11e9-8b7b-62c50ae66b66.png)
 
# Issue

So I configured cloud cleanup to cleanup with the files on gdrive. But it just doesn't.

**Comment by ccrisan** [comment]
Judging from your logs, the given folder does not exist on Google Drive:

    Exception: folder with name "/Ueberwachung" does not exist

**Comment by patrickhener** [comment]
That's what I thought at first, too. But it does. It is there. It does upload to that folder correct. It just does not cleanup afterwards.

**Comment by bob-lee** [comment]
@patrickhener I am using gdrive,  `Loacation` field configured without leading slash and curious if that's causing your problem. I will test on my rpi and see if leading slash reproduces the problem.

**Comment by bob-lee** [comment]
I could reproduce this issue with Location '/CCTV2' so current code doesn't handle a leading slash properly. I will prepare the fix in `motioneye` project.
@ccrisan In `clean_cloud` feature, I assumed that a folder named in `Location` field is a direct child of the 'root' so it would not like `'A/B'`. Is this assumption valid?

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/pull/1310 has been merged and the next motionEyeOS nightly build will have it.

**Comment by patrickhener** [comment]
I am on dev20190620 now and still the cloud cleanup is not working. Neither with or without a leading slash.

**Comment by bob-lee** [comment]
@patrickhener can you please provide logs without a leading slash?

**Comment by patrickhener** [comment]
@bob-lee : My bad! Actually it does work now. Sorry for the inconveniences.
