### ISSUE TITLE
A Resolution Question

### ISSUE THREAD

**Issue by Dewey3** [ccrisan/motioneyeos#1930]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190119

### Board Model

I am using the following board/model: Raspberry PI 3B

### Camera

I am using the following type of camera: V4L2

My camera model is: ELP 1MP Day Night Vision Indoor & Outdoor

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

### Peripherals

I am using the following peripherals that I consider relevant to this issue: N/A

### Log Files

I consider the following log files relevant to this issue: N/A

I asked this question first on the Google Groups, but did not receive any answers.  I would like to ask it here, and if this is not proper place, I do sincerely apologize.

I've been using my ELP 1MP cameras (https://www.amazon.com/gp/product/B00VFLWOC0/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) for a couple years and have been very happy with them.  I have always run them at 800x600 resolution (30FPS MJPEG / 20FPS YUY2) and keep the Motioneye OS video setting at 10FPS.  I recently switched to 1280x720 resolution (30FPS MJPEG / 10FPS YUY2) and have been quite impressed with the much wider screen view.  My questions are 1), while it doesn't seem that I have lost anything in the view, does this higher resolution come at a cost somewhere else in the pictures?  And 2), will this higher resolution of 1280x720 over 800x600 make anything like the Raspberry Pi or the camera itself have to work harder since I still keep Motioneye OS set at 10FPS?

**Comment by ccrisan** [comment]
Higher resolution (even if framerate is kept the same) means higher information to process with each frame. In your case it's almost double.

So to answer both your questions, yes, it does come with a probably small cost of extra CPU usage. But if you're happy with what you get, then why bother?
