### ISSUE TITLE
How connect rasp to tv with hdmi

### ISSUE THREAD

**Issue by mb39924** [ccrisan/motioneyeos#1944]
I want to view my steams on a tv using  hdmi. Plugged it in and it doesn't work. I thought there used to be a setting (hdmi preview?) to turn hdmi on but I can't find it anywhere. 

At the moment I'm using one iegeek camera and a raspberry-pi with latest motioneyeos build as a central hub. 

Can anyone point me in the right direction?

**Comment by auxz2jz** [comment]
Turn on Fast network mode and there's an HDMI preview works great for me just trying to get the rstp to work now

**Comment by mb39924** [comment]
Ah ok.. Im using a raspi with motioneyeos as a hub with mom-motioneyeos cameras. So no fast network mode for me.

Would be a great feature to be able to connect a monitor to a hub.

**Comment by ShibumiDesign** [comment]
If you have a smart tv connected to your local network with a web browser in your tv (many newer ones do), just browse to your MotionEyeOS hub IP address... or connect a laptop or pc to your tv and browse to your hub IP address

**Comment by ccrisan** [comment]
@mb39924 motionEyeOS is not designed to be used as a frontend. You should use a dedicated PC with a web browser.
