### ISSUE TITLE
Raspbion + MotionEye on Pi Zero W low FPS while recording

### ISSUE THREAD

**Issue by Mogolino** [ccrisan/motioneyeos#1949]
Hi, I got very low FPS when recording on my Pi Zero W with Raspbian + MotionEye. While streaming I get around 10 fps (is that a normal value for a Pi Zero W?). When recording the stream drops down to 0 or 1 fps after around 3 seconds. The recorded file also has like 1 fps.

That's not normal I guess, because I used to use my own python script for recording and streaming and i had like 10 fps on both. Also while watching the stream during reocrding.

I switched to MotionEye because of the beauty of the interface and the simplicity.

Here is what I am using:
Raspberry Pi Zero W
Raspbian 9.9
Motion 4.1.1
MotionEye 0.40

Movie recording format: H.264/OMX (.mp4)
File storage: local directory
Video Resolution: 800x600
Camera Type: MMAL Camera

Thanks.

**Comment by jasaw** [comment]
@Mogolino If you are using Raspbian & MotionEye, you should be reporting your issue in [MotionEye](https://github.com/ccrisan/motioneye) project.

You are probably using a software video encoder to record your video, overloaded your CPU, causing your frame rate to drop.
See https://github.com/ccrisan/motioneye/issues/930 for more info on how to enable hardware encoder on Raspbian & MotionEye setup.
