### ISSUE TITLE
Options in web interface disappeared 

### ISSUE THREAD

**Issue by pumbaa2183** [ccrisan/motioneyeos#196]
I in stalled Motioneyeos ( love it ) and set up everything correctly, I had it uploading images to Dropbox and had the email notification setup and working as well. However after tweaking some. Video resolution and shutter speeds, I no longer have the options to do the following things in my web interface: 

Add camera
Upload to Dropbox
Tweak motion settings 
Email notifications 

also before making these tweaks I made a backup -- but when I got to restore the back up it fails.

Any suggestion on how to get these items back? I will be willing to send log files later -- I can't currently as I'm on my iPad and have to access to the log files. 

I have plans to add another camera. 

Thanks you for the hard work, this has turned out to be not only a useful project for me to tinker w/ and get my feet wet w/ Pi but it was fun :)

![image](https://cloud.githubusercontent.com/assets/17677233/13549640/f7a53aae-e2d7-11e5-8646-24aa91d6e2a7.png)
![image](https://cloud.githubusercontent.com/assets/17677233/13549641/f7b26742-e2d7-11e5-9735-5737b56964d9.png)

**Comment by ccrisan** [comment]
Disable Fast Network Camera in Expert Settings if you want motion detection, upload to Dropbox and others.

**Comment by pumbaa2183** [comment]
Thank you !
