### ISSUE TITLE
View camera on main monitor

### ISSUE THREAD

**Issue by glennford49** [ccrisan/motioneyeos#1967]
How to use main monitor to display camera output, in defaults its on console mode, is it possible?

**Comment by jasaw** [comment]
See below:
https://github.com/ccrisan/motioneyeos/issues/1435
https://github.com/ccrisan/motioneyeos/issues/1497
https://github.com/ccrisan/motioneyeos/issues/1944
https://github.com/ccrisan/motioneyeos/issues/1953
https://github.com/ccrisan/motioneyeos/issues/1150

**Comment by jasaw** [comment]
I believe the question has been answered. Closing issue.
