### ISSUE TITLE
Strange settings in 20190619 release?

### ISSUE THREAD

**Issue by PieBru** [ccrisan/motioneyeos#1968]
Hi Calin,
a freshly built SD from https://github.com/ccrisan/motioneyeos/releases/download/20190619/motioneyeos-raspberrypi-20190619.img.xz used on a Raspi Zero W with a common 5MP camera, the web UI shows the camera video and only 4 config sections: Preferences, Network, Services, Expert settings.
Network settings doesn't reflect the writeimage.sh -n parameter value.

The release isn't labeled as "dev" or experimental, is this intentional?
Thanks,
Piero

**Comment by PieBru** [comment]
Partially solved.
The UI by default doesn't ask for login and disables most "admin" config sections.
However, only the Preferences section should be visible by the "user" login, as it was in the previous release. 
I was fooled by the "Expert settings" section. IMO Network, Services and Expert settings shouldn't be accessible to not-admins cam users/viewers.
Piero

**Comment by ccrisan** [comment]
Can I see a screenshot of the issue? Also a browser full refresh (clearing cache) could help.

**Comment by PieBru** [comment]
Steps to reproduce, I'm on Arch Linux:
1. $ sha256sum motioneyeos-raspberrypi-20190619.img.xz
a0c7bbc17e6ce6c91af4d3a53cdf82df1e543b91964ff1dd7e478a88626f6d31  motioneyeos-raspberrypi-20190619.img.xz
2. $ sudo ./writeimage.sh -d /dev/sdd -n 'ssid:password' -i motioneyeos-raspberrypi-20190619.img.xz
3. Boot the Raspi Zero W using the just imaged microSD.
4. Wait for the assigned DHCP lease, wait some minutes more to complete the (slow) PI startup.
5. Browse using a "New private window" on the latest Firefox (so there is no cache). In my case the address is http://meye-abcca2ca.local/
6. At the web UI login prompt don't type anything, only hit the <ENTER> key.
7. After the local cam image is displayed, click the up-left ME menu and the attached screenshot appears.
Thanks,
Piero

![Screenshot from 2019-06-23 17-28-23](https://user-images.githubusercontent.com/6537434/59978551-b0eace00-95dd-11e9-8b62-6585e3d5a329.png)

**Comment by 2lostkiwis** [comment]
I also have the same issue on an Raspi 3 Model B+ with 8MP CSI camera.

**Comment by ccrisan** [comment]
Indeed, this can be reproduced and is a motionEye bug. In short, it displays settings that were previously marked and advanced to a non-admin user.

**Comment by kjr88** [comment]
Hi there, is there a workaround for this? I've just encountered the same issue on a pi zero w, running motionEyeOS 20190911
![Screenshot from 2020-01-30 22-45-56](https://user-images.githubusercontent.com/57465002/73499199-5c030780-43b7-11ea-86e5-55162f6349f2.png)

**Comment by ccrisan** [comment]
@kjr88 that's a known bug triggered by the fact that you're not logged in with admin. It's been fixed in motionEye and will make its way into motionEyeOS these days. Until then, just log in with admin and you'll be fine.
