### ISSUE TITLE
Motion detection outside set working scheedule for detection. 

### ISSUE THREAD

**Issue by Banditen01** [ccrisan/motioneyeos#197]
One of two cameras are sending motion detection notice (without pictures attached and no recording are made) still sending emty detection notice to my e-mail. Any clue what's wrong?

**Comment by ccrisan** [comment]
What's the connection between the title and the description of the issue? Do you expect pictures attached to emails or do you not expect any email at all? Please attach your configuration (removing sensitive data from it).

**Comment by Banditen01** [comment]
Sorry, I understand your confusion, one of my cameras are sending e-mail motion detection notice when it´s supposed to be in non motion detect mode, set up by working Schedule function. It saves picture/movies on local disk but do not attache any pictures in e-mail and do not upload to Google Drive (even if I get okay from test service bottom). After some motion detetect on and off and also Schedule on and off and a reboot it sems to work again.When you ask for configuration, do you want all five different log files?

**Comment by ccrisan** [comment]
I need the thread-*.conf and motion.conf files that are in the archive that you get when you click the Backup configuration button. Always remember to remove sensitive data from them.

**Comment by quantum8** [comment]
I am getting a similar issue where it is recording motion events when they happen, regardless of being inside or outside the schedule. I'm running 20160605 on a rpi model b.
[Config.zip](https://github.com/ccrisan/motioneyeos/files/351152/Config.zip)

**Comment by ccrisan** [comment]
@quantum8 So what you're saying is that you get motion movies outside of the configured working schedule?

**Comment by ccrisan** [comment]
Ah I just noticed your working schedule is invalid. The "from" must be less than the "to" field. You cannot have a working schedule for a day span to the next day.

**Comment by quantum8** [comment]
That makes sense, I'll change the settings and see how it goes from there.

**Comment by geoffp13** [comment]
Why on earth !!! - :-( I give up - so frustrated with this software - it is so close to working yet fails through simple errors in construction and explanation. Needs a little common sense and forethought !!
