### ISSUE TITLE
Cant uninstall motioneyeOS 

### ISSUE THREAD

**Issue by melikhammoud** [ccrisan/motioneyeos#1970]
Im working on a project for my graduation and i was thinking about using motioneyeOS but it didnt work for me... Now i dont know how to remove it from the SD card so i can get access to the raspbian terminal and use it normally again.... Do i have to format the SD card and install raspbian again or is there anyway to remove motioneyeos only? Im new to all of this, its my first time using raspberry pi....

**Comment by jasaw** [comment]
Download Raspbian image and flash it on the SD card. There's no need to format the SD card.

**Comment by melikhammoud** [comment]
but ill have to update it again and download all the apps that i had previously installed??

**Comment by melikhammoud** [comment]
> Download Raspbian image and flash it on the SD card. There's no need to format the SD card.

but ill have to update it again and download all the apps that i had previously installed??
