### ISSUE TITLE
Pi cam not work

### ISSUE THREAD

**Issue by recfrf44** [ccrisan/motioneyeos#1972]
I have installed motioneyeOS - everything works, camera works.
I have installed motioneye - 
latest version RaspbianOS
pi_stretch_motion_4.2.2-1_armhf.deb
All according to the instructions, without errors.
Web interface does not identify the camera.
Add bcm2835-v412 to /etc/modules
Reboot
after accessing the web interface -  {"error": "internal server error"}
crash all command - -bash: /bin/ls: Input/output error, and crash ssh

**Comment by jasaw** [comment]
This is an issue with Raspbian + MotionEye setup, please post your issue in [MotionEye](https://github.com/ccrisan/motioneye) project.
When you report any issue in the future, please provide more information and attach log files where possible.
