### ISSUE TITLE
Raspberry Pi 2 Model B - Increasing GPU memory causes system to fail.

### ISSUE THREAD

**Issue by Triavati** [ccrisan/motioneyeos#198]
Everything works fine when I have my GPU memory set to 128 and the overclock speed at "Pi2". When I increase the GPU memory to 256, and overlock to Pi2, I get the "Reload recommended" error, and am forced to reinstall the MotionEyeOS to get it working again. 

It's my understanding that I dictate the GPU memory, and what is left over goes to the CPU. So if the pi 2 has 1024 MB of available memory, assigning 256 to GPU should leave plenty left over for system processes. Am I missing something?

**Comment by ccrisan** [comment]
I'll look into it.

**Comment by Triavati** [comment]
Thank you! I'm a true novice in the raspberry pi community, so I'm 90% sure that my problem is user error. MotionEyeOS is amazing, and I'm currently using the motion detection to protect my valuables from my roommate's thieving friends.

I'm trying to optimize my settings so that I reduce the frame-rate drop I encounter when motion is detected. It's trying to stream, record, and detect motion at the same time (640 15fps), which is what lead me to adjust the memory and clock speed. Any advice would be greatly appreciated! Keep up the good work.

**Comment by Priso19** [comment]
Same on RPi3

**Comment by ccrisan** [comment]
The bug has been fixed and the fix will be included with the next release.
