### ISSUE TITLE
Support for Atomic Pi?

### ISSUE THREAD

**Issue by Espionage724** [ccrisan/motioneyeos#1983]
- https://dlidirect.com/products/atomic-pi

It's essentially a x86 SBC that uses either UEFI (default) or Legacy boot, and can handle typical Linux distros and Windows 10 even.

I believe this SBC would scale nicely with motioneyeOS.

**Comment by Commander-Crash** [comment]
On the latest version motion is useless if it cant record video with out it being frozen up for the 1st 20 seconds.

**Comment by ghost** [comment]
On the latest version motion is useless if it can't record video without it being frozen up for the 1st 20 seconds.

**Comment by starbasessd** [comment]
motionEyeOS doesn't have a version that supports Atomic Pi. It is Intel based, not ARM based.
