### ISSUE TITLE
No motion notifications (email or command) ERROR: failed to list disks

### ISSUE THREAD

**Issue by mrtruebeliever** [ccrisan/motioneyeos#1986]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

### Board Model

I am using the following board/model: FreeBSD

### Camera

I am using the following type of camera:  Simple MJPEG Camera.

My camera model is: RPi camera on RPi Zero.

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

### Log Files

I consider the following log files relevant to this issue:

[motioneye.log](https://github.com/ccrisan/motioneyeos/files/3372369/motioneye.log)

**Comment by ccrisan** [comment]
You're probably using motionEye, not motionEyeOS. I'm sorry but motionEye is not officially supported on FreeBSD so you're on your own.

In any case, the problem here is the missing `/proc/mounts`:

    IOError: [Errno 2] No such file or directory: '/proc/mounts'
