### ISSUE TITLE
after update/upgrade of raspbian port 8081 wants to download a file

### ISSUE THREAD

**Issue by Lukobravo** [ccrisan/motioneyeos#1993]
All,

       After I completely updated and upgraded Raspbian, when I navigate via web browse to the ip address of all of my motioneye with streaming port of 8081. My browser initiates a download and asked me if I want to open or save. 

motionEye Version | 0.40
Motion Version | 4.2.2
OS Version | Raspbian 9.9

What can I do to fix this? I've changed the streaming port but no matter what port I use it still wants to download a file. When I try to add these cameras to my motion controller I get this error when I try to add:

Type: Remote motionEye Camera
URL: http://myipaddress:8081
Camera: Failed to connect to ip address port 8081: No route to host

Thanks in advance for help!

**Comment by jasaw** [comment]
You might get a response if you ask in [MotionEye](https://github.com/ccrisan/motioneye) project, seeing that you're running MotionEye + Raspbian.
