### ISSUE TITLE
V380 WIFI Camera unable to connect in motioneye

### ISSUE THREAD

**Issue by bobster316** [ccrisan/motioneyeos#1997]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

My existing setup is sort of working with a wyse cam v2. 
I just picked uop a generic wifi camera from ebay
https://www.ebay.co.uk/itm/Wireless-WIFI-IP-Camera-1080P-HD-Network-Cam-CCTV-In-Outdoor-Security-IR-Night/183706592224?epid=24026715061&hash=item2ac5c423e0:g:tvcAAOSwi05dIF7i

Can someone help to advise what setting to use to connect this camera to motioneyeos

**Comment by ccrisan** [comment]
Please use our [forum](https://groups.google.com/forum/#!forum/motioneye) for this kind of questions.
