### ISSUE TITLE
No email notifications after installing motioneyeOS

### ISSUE THREAD

**Issue by SuperSharpShooter** [ccrisan/motioneyeos#2]
I've just installed the new version, and motion detection and image and video capture are working fine, however no emails are being sent.

I've got it set to use gmail to send the images, and it is set up exactly as it was with the previous version, but it seems there's no attempt for the emails to be sent. I can't see anything in the logs that shows any attempt, or any issues with sending the emails.

Link to logs: https://www.dropbox.com/s/y33mtwfpj8ibu38/motioneye.zip?dl=0

**Comment by mikecarr** [comment]
I am having the same exact issue and I see nothing in the logs suggesting it is even trying to send email.

**Comment by sinbrkatetete** [comment]
Same here.

**Comment by arxat** [comment]
I also receive notifications by email, I have everything configured properly and that motionpie if it works.

**Comment by arxat** [comment]
After doing some tests I have seen with notifications if I Raspicam but not an IP camera through RTSP

**Comment by SuperSharpShooter** [comment]
I'm using the Raspicam, but am getting no email notifications.

**Comment by ccrisan** [comment]
The issue has been fixed upstream in motionEye with version 0.28.2. It will soon be included in the next motionEyeOS version.
