### ISSUE TITLE
access motioneyeos directly from windows laptop from ethernet cable

### ISSUE THREAD

**Issue by SiriusFuenmayor** [ccrisan/motioneyeos#2002]
Is there a way to connect to the motioneyeos GUI by connecting an ethernet cable directly from the raspberry pi to a windows laptop or pc? I have seen this done with raspbian:

https://notenoughtech.com/raspberry-pi/connect-raspberrypi-pc/#jp-carousel-2585
https://www.instructables.com/id/Use-Raspberry-Pi-3-With-Windows-10-Laptop/

**Comment by jasaw** [comment]
Yes you can. You need a cross-over Ethernet cable. Configure your MotionEyeOS device to static IP, make sure it's in the same subnet as your PC that it's connected to. You probably need to disable Network Link Watch. You may also need to put your PC's IP as Default Gateway address, and probably DNS Server too.
If you want time sync on your isolated MotionEyeOS device, you'll need to set up a time server on your PC too, something like ntpd.

Btw, this is a question, not an issue, so I'm closing it.
