### ISSUE TITLE
Pi 4 fast network cam missing

### ISSUE THREAD

**Issue by Woody565** [ccrisan/motioneyeos#2008]
Hi All,

I have just installed the lastest nighty build (dev20190715) on a pi 4 bbut the fast network cam option is missing?

Also would it be possible to get a hdmi preview on normal mode? I know i could get the motioneye page open over hdmi but would just want the live feed like the option you get in fast mode

Thanks

**Comment by ccrisan** [comment]
Fixed via https://github.com/ccrisan/motioneyeos/commit/9caf02e7068d384d848a43aa21799025493f979f.
