### ISSUE TITLE
Downgrade quality after 12:00 oclock

### ISSUE THREAD

**Issue by fefed22** [ccrisan/motioneyeos#2020]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190427

### Board Model

I am using the following board/model: Raspberry Pi 3

### Camera

I am using the following type of camera: MMAL Camera

My camera model is: Night vision camera module for Raspberry Pi

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

### Screenshot

![Capture d’écran 2019-07-30 à 14 52 23](https://user-images.githubusercontent.com/650791/62130879-3e56c780-b2da-11e9-918d-bc7aa601ff03.jpg)
![Capture d’écran 2019-07-30 à 14 51 06](https://user-images.githubusercontent.com/650791/62130880-3e56c780-b2da-11e9-9c1f-16075886979c.jpg)

### My issue

I have :
- activate continous recording at 1920x1080 (quality 75%)
- H264/OMX and a max length : 900 seconds
- Store file on a NAS on network

after 12:00 oclock, the quality file is downgrade as i have put quality to 5% !!! but not at all...
did you know this issue ?

PS : as you can see screenshot give you resolution for each video but quality are really different !

**Comment by jasaw** [comment]
I think it's the same as this bug: https://github.com/ccrisan/motioneyeos/issues/1900
Please try the latest nightly dev and report back. https://github.com/ccrisan/motioneyeos/releases/tag/nightly-dev

**Comment by rotrials** [comment]
It looks like the same issue. An fast fix is to decrease the resolution at  1280x720. But anyway, please let as know if the with the latest nighty dev is working.I'm also interested...

**Comment by fefed22** [comment]
Have you a way to switch the update checker to dev or nightly channel ?

**Comment by haha150** [comment]
> 
> 
> It looks like the same issue. An fast fix is to decrease the resolution at 1280x720. But anyway, please let as know if with the latest nighty dev is working.I'm also interested...

Having issues with the nightly dev which i posted in https://github.com/ccrisan/motioneyeos/issues/2012

**Comment by fefed22** [comment]
I make a test whith video recording only AND reduce resolution to 1600x1200...
i come back with some news...

PS : i notice that when i put 1600x1200 i see that the cam zoom OUT !!

**Comment by fefed22** [comment]
i have the same issue after changing settings but NOT upgrading to last release (dev).

Have you a way to switch the update checker to dev or nightly channel ?
Or i will erase all data on SD card ?

**Comment by jasaw** [comment]
@fefed22 Enable "Enable Prereleases" under "Expert Settings" and try checking for upgrade again. This won't wipe all your data on SD card unless something goes wrong horribly and you have to reformat the SD card.

**Comment by jasaw** [comment]
@fefed22 Have you tried the nightly build or prerelease? Low bit rate issue should be fixed by now.

**Comment by jasaw** [comment]
No update from @fefed22 . I'm going to assume it's recording bitrate issue which has been fixed.
