### ISSUE TITLE
After upgrading to Chrome Version 76.0.3809.100, I can no longer see video from Motioneye

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneyeos#2030]
Hi,

I have several  motioneyeos cams running. 
After Upgrading to Chrome Version 76.0.3809.100 it's not possible to view the video live stream on the startscreen of motioneyeos.
Any other Browser (and also Chrome version 75.x.x.x) is working.
Any  idea how I get it running with chrome > 76.0.3809.100 ?

 I have:
1. Reset chrome
2. Reinstalled chrome
3. Reset chrome again

Looking for tier III answers since it still works on other computers - Its not Windows, MSI, raspberry pi, network etc, because it still works on anything not upgraded to chrome 76.

Thank's a lot

helmar

**Comment by grhangelone** [comment]
Same here.
I'm using above version, too on my desktop linux boxes.
But I can take snapshots and watch them on the snapshot browser.

Looking at the pagesource, it seems to be stuck at the initializing.

![Bildschirmfoto zu 2019-08-08 10-34-47](https://user-images.githubusercontent.com/35765416/62688047-4db7ce00-b9c8-11e9-8a7a-f245f0192e2e.png)

I also just upgraded motioneye to the latest version because of this.
Doesn't help.

**Comment by woznyp** [comment]
Hi, I had the same issue and as a workaround I've edited JavaScript files related to refreshing the video stream.
Please follow motioneye web interface repository thread:
https://github.com/ccrisan/motioneye/issues/1401

**Comment by Nameback** [comment]
Same issue here, ended up rebuilding my whole motioneye setup only to find this thread. Didn't even think to check here. Good catch!

**Comment by helmar74** [comment]
Hi,

here are the necessary commands:
mount -o remount,rw /
cd /usr/lib/python2.7/site-packages/motioneye/static/js/
cp frame.js frame.js.orig
cp main.js main.js.orig

Than copy the two file from rhe repository above to usr/lib/python2.7/site-packages/motioneye/static/js/

Than reboot motioneyeos

Than delete cache of Chrome.

That's all ;-)

**Comment by helmar74** [comment]
Hi,
now I the live stream of the cameras are shown in Webinterface of chrome... but the left frame is greyed out and I can't click anything. It's the same on every browser.... reboot didn't helped....
![image](https://user-images.githubusercontent.com/25499089/62818874-bf6d5480-bb4d-11e9-8c32-a6dceb4c432e.png)

**Comment by ccrisan** [comment]
Already fixed in motionEye. Will be available in the currently baking nightly build.
