### ISSUE TITLE
All cameras stopped working

### ISSUE THREAD

**Issue by bobster316** [ccrisan/motioneyeos#2034]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

### Board Model

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 4.

### Camera

Wyze Cam v2

### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g.  Ethernet.

![motioneye problem](https://user-images.githubusercontent.com/36663088/62809673-80121a00-baf3-11e9-89ba-216eb7405ca5.JPG)
[motion.log](https://github.com/ccrisan/motioneyeos/files/3488084/motion.log)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by bobster316** [comment]
When checking with VLC all Wyze camera's work fine

**Comment by Weeman89** [comment]
Just signed up to github to leave a comment.

I've had the same/similar problem, are you using Chrome and have you tried Firefox?

**Comment by bobster316** [comment]
Currently using motioneyeos-raspberrypi4-dev20190715

**Comment by bobster316** [comment]
Just tried with Firefox and it works! Thanks
what is stopping chrome from running it?

**Comment by SoloSquirrel** [comment]
Same issue, all cams stuck in spinney-circle mode.  Tried Firefox, and everything works fine.

**Comment by helmar74** [comment]
look at #2030

**Comment by grhangelone** [comment]
Go to chrome://flags and search vor "lazy"
disable both options
for now this helps the most

**Comment by helmar74** [comment]
Hi, I disaled both options, but it's not working for me....
![image](https://user-images.githubusercontent.com/25499089/62820300-96a38a00-bb62-11e9-9116-7db50d99c683.png)

**Comment by ccrisan** [comment]
Already fixed in motionEye. Will be available in the currently baking nightly build.

**Comment by neilyoung** [comment]
@ccrisan When will the fix be available in the raspberry PI 3 images? Is there any way to get notified?

**Comment by ccrisan** [comment]
@neilyoung use the latest nightly build.
