### ISSUE TITLE
Missing Email Settings in GUI

### ISSUE THREAD

**Issue by sherm8n** [ccrisan/motioneyeos#204]
I set up to send email notifications the other day, when now when I login those settings are now gone. The whole menu section where to set it up is just missing. 

This is the menu closed:
<img width="553" alt="screen shot 2016-03-10 at 10 37 43 am" src="https://cloud.githubusercontent.com/assets/1237709/13680148/2d56a7f0-e6ac-11e5-8812-a919aa0bd577.png">

Menu open:
<img width="553" alt="screen shot 2016-03-10 at 10 36 50 am" src="https://cloud.githubusercontent.com/assets/1237709/13680159/38e1032c-e6ac-11e5-8398-fdce2843f993.png">
<img width="549" alt="screen shot 2016-03-10 at 10 37 01 am" src="https://cloud.githubusercontent.com/assets/1237709/13680165/3e20bbac-e6ac-11e5-9baa-1aac52dd11e7.png">
<img width="553" alt="screen shot 2016-03-10 at 10 37 10 am" src="https://cloud.githubusercontent.com/assets/1237709/13680170/42d94b14-e6ac-11e5-825c-cd6d08cfbac0.png">
<img width="554" alt="screen shot 2016-03-10 at 10 37 20 am" src="https://cloud.githubusercontent.com/assets/1237709/13680176/47bf865c-e6ac-11e5-8335-cc569e635a04.png">
<img width="554" alt="screen shot 2016-03-10 at 10 37 25 am" src="https://cloud.githubusercontent.com/assets/1237709/13680180/4c9a32ee-e6ac-11e5-91f5-a02f62aa5039.png">

I'm using a RPi 3 with MotionEyeOS.
Having the issue on Chrome and Safari.

**Comment by sherm8n** [comment]
Okay, it seems that the "Fast Network Camera" option diables notifications. However, when try to disable that option, I get an error and am unable to disable it.
<img width="910" alt="screen shot 2016-03-10 at 11 16 12 am" src="https://cloud.githubusercontent.com/assets/1237709/13681343/9bafba2a-e6b1-11e5-9416-d1cea8547c43.png">
<img width="861" alt="screen shot 2016-03-10 at 11 16 19 am" src="https://cloud.githubusercontent.com/assets/1237709/13681344/9d9101b4-e6b1-11e5-8382-426a1462041a.png">

**Comment by ccrisan** [comment]
Indeed, the Fast Network Camera mode disables all those motion-related options. The error you get is a known RPI3-related problem and will be fixed soon.

**Comment by ccrisan** [comment]
The bug has been fixed and the fix will be included with the next release.
