### ISSUE TITLE
Overclocking Raspberry Pi4

### ISSUE THREAD

**Issue by bobster316** [ccrisan/motioneyeos#2048]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: motioneyeos-raspberrypi4-dev20190813.img

### Board Model

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 4b

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Wyze Cam v2

### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, . WiFi,

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 

I am trying to overclock the cpu and gpu of my raspberry pi 4b 4Mb  but whatever changes i make to the config.txt file there is no difference.

[root@MotionEYE ~]# vcgencmd get_config int | grep "arm\|over"
arm_freq=1500
over_voltage=2

Also i dont think the gpu overclock is working either.

Here is my config.txt file from motioneye running on the raspberry pi 4B 4Mb

force_turbo=0
arm_freq=2000
over_voltage=6

gpu_mem=620
over_voltage=2

dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on
dtparam=audio=on

dtoverlay=vc4-fkms-v3d
max_framebuffers=2

**Comment by ccrisan** [comment]
First off, I don't think overclocking the RPi4 is officially supported. Secondly, this is not something motionEyeOS should deal with.
