### ISSUE TITLE
Installinng dyndns client

### ISSUE THREAD

**Issue by darrenc90** [ccrisan/motioneyeos#206]
Hi Cailin,

Great bit of software here, my only issue going right now is that I don't know how to install dyn's dns client, or any other software for that matter, can you please walk me through it?

thanks,
Darren

**Comment by Banditen01** [comment]
https://github.com/ccrisan/motioneyeos/issues/194

**Comment by sinbrkatetete** [comment]
I've done it following the instructions on the [tweaks page](https://github.com/ccrisan/motioneyeos/wiki/Tweaks) Banditen01 linked and instructions on [duckdns](https://www.duckdns.org/), I use as the dynamic dns service (and recommend).

**Comment by aubvmk** [comment]
Hello everyone,
I have make a fork with include inadyn package and add a boot startup.
For the config add inadyn.conf in /boot

Here: https://github.com/ViaMonkey/motioneyeos

Auban
