### ISSUE TITLE
Motioneye doesnt work in Chrome anymore

### ISSUE THREAD

**Issue by Oxize** [ccrisan/motioneyeos#2068]
Chrome did a new update, but i dont see any video feeds anymore from MotionEye. It keeps loading and loading.

When i open motioneye page with Edge or Firefox i have no problems. Anyone got a solution for Chrome?

**Comment by mb39924** [comment]
There is a fic in te latest update.

**Comment by ccrisan** [comment]
Fixed in recent nightly builds.
