### ISSUE TITLE
SNTP without internet connection interrupts the boot sequence

### ISSUE THREAD

**Issue by popoviciri** [ccrisan/motioneyeos#2119]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.
_yes_

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.
_yes_

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).
_Bloated build from latest dev branch 50228024._

### Board Model

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).
_3B_

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).
_MMAL FNC with multi stream_

My camera model is: (insert your camera model, e.g. Logitech C290).
_raspicam NoIR v2_
### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).
_ethernet_

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 
If the cameras are prevented to have access to the internet, the latest SNTP fails to update the time and locks the boot sequence:
```
---- booting motionEyeOS dev20190930 ----
 * Detecting disk device: /dev/mmcblk0
 * Mounting filesystems: done
Running sysctl: OK
 * Loading kernel modules: done
 * Setting hostname: done
 * Configuring CPU frequency: done
 * Starting syslogd: done
 * Loading device-tree overlays: done
 * Starting throttle watcher: done
 * Starting eudev: done
 * Starting watchdog: done
 * Starting rngd: done
 * Configuring wired network: dhcp
Starting sntp: sntp 4.2.8p13@1.3847-o Sun Sep 29 23:50:58 UTC 2019 (1)
pool.ntp.org 37.44.185.42 no UCST response after 5 seconds
FAIL 
```
The culprit is the `s48sntp` startup script which looks after `SNTP_SERVERS="pool.ntp.org"`. My way around this issue was to hard code the above pool with my local ntp server one could also easily broadcast from another raspberry pi. But I believe the `S50date` should be the only one looking for time. Also, even without the correct time, the other services should be allowed to progress.

**Comment by ccrisan** [comment]
Oups, forgot about the default `S48sntp` init script. Fixed via https://github.com/ccrisan/thingos/commit/831264f36a343196db65761d5557eec5a251377b.
