### ISSUE TITLE
Camera/site cannot be reached after reboot

### ISSUE THREAD

**Issue by SheffieldUser** [ccrisan/motioneyeos#2122]
Hi
I have successfully installed 3 Raspberry Pis with Motion Eye - great piece of kit - thank you.
But the fourth (and last) is causing problems
Pi board 2011.12
Motion Eye version  motioneyeos-raspberrypi-20190911.img.xz

It installs without problem.
It works until I enter the Network details which are exactly the same as for the other three
When I reboot up come the message "This site can't be reached" ... and it can't. I need to reformat the sd card and start again.

The only thing that I can think of is that I am using an 8GB SD card rather than a 16GB that I have used in the other three. If this is the case and I should have spotted it - apologies for wasting your time

Thanks in anticipation

**Comment by ccrisan** [comment]
@SheffieldUser you forgot to mention the models of your Pis and to add some logs.

**Comment by SheffieldUser** [comment]
Hi 
Sorry for the omissions

The Pi with the problem is a Model B Revision 2 with 512 MB memory (2011.12)
The camera is a raspberry V1.3

Motion Eye software is motioneyeos-raspberrypi-20190911.img

[boot.log](https://github.com/ccrisan/motioneyeos/files/3682237/boot.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/3682240/dmesg.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/3682241/motion.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/3682242/motioneye.log)

Hope that this helps. 

Thanks

**Comment by ccrisan** [comment]
Your `boot.log` says:

    ---- booting motionEyeOS 20190904 ----
     * Detecting disk device: /dev/mmcblk0
     * Mounting filesystems: done
     * Loading kernel modules: done
     * Setting hostname: done
     * Configuring CPU frequency: done
     * Starting syslogd: done
     * Starting throttle watcher: done
     * Starting eudev: done
     * Starting watchdog: done
     * Starting rngd: done
     * Starting wpa_supplicant: done (mt7601u)
     * Configuring wireless network: 192.168.1.104/24
     * Setting static gateway to 192.168.1.254: done
     * Setting static DNS server to 8.8.8.8: done
     * Setting current date using http: failed
     * Starting http date updater: done
     * Starting crond: done
     * Starting motioneye: failed
    ---- shutting down motionEyeOS 20190904 ----
     * Stopping motioneye: failed
     * Stopping crond: done
     * Stopping date updater: done
     * Stopping network: done
     * Stopping wpa_supplicant: done
     * Stopping rngd: done
     * Stopping eudev: done
     * Stopping throttle watcher: done
     * Stopping syslogd: done

First off, the version reported is not `20190911`. Are you sure you have downloaded and written the correct version? Is the `boot.log` complete?

Then, you have configured static IP. 99% of the problems where users report networking issues with static IP configuration are caused by static IP misconfiguration. Following lines indicate the static settings you configured and the fact that a simple `curl` command to `google.com` (used to set the date) fails:

     * Configuring wireless network: 192.168.1.104/24
     * Setting static gateway to 192.168.1.254: done
     * Setting static DNS server to 8.8.8.8: done
     * Setting current date using http: failed

**Comment by SheffieldUser** [comment]
Hi 
The issue is solved.
I was under the impression that I had the latest version - but obviously not.
I was going straight to the settings menu/option without creating a user profile - this removed a lot of the settings options which were necessary.
I apologise for my stupidity and wasting your time.
Thank you for your help.
Regards
Andrew
