### ISSUE TITLE
Showing cpu usage / temperature

### ISSUE THREAD

**Issue by molly78** [ccrisan/motioneyeos#213]
Much thanks for an awesome piece of software :)

Any chance you could add the cpu usage / Pi temperature on the main page? Top corner perhaps?
Maybe memory allocations as well?

And hey, since I'm here maybe the different storage used for videos vs stills?

Help to see if you're overloading the Pi

Playing with it on a new pi3 and trying to trouble shoot when two cams won't display. 

Again huge thx :)

**Comment by funtomas** [comment]
for cpu temperature you can make your own script in "storage" directory

cd storage
nano cpu.sh
// add this lines in editor
#!/bin/bash
cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
cpuTemp1=$(($cpuTemp0/1000))
cpuTemp2=$(($cpuTemp0/100))
cpuTempM=$(($cpuTemp2 % $cpuTemp1))
echo CPU temp"="$cpuTemp1"."$cpuTempM"'C"
//press CTRL+x for finish and SAVE file
chmod +x cpu.sh
// and run script
./cpu.sh

**Comment by EpicLPer** [comment]
It would be nice to see this on the dashboard if possible, I'm getting weird errors with my Pi 1 and I'm not sure if it's in any way due to overheating and/or in a problem when the sun shines for a longer time on it.

**Comment by bortek** [comment]
Not for now.
