### ISSUE TITLE
Can't update from motionEyeOS 20190427

### ISSUE THREAD

**Issue by sagitt** [ccrisan/motioneyeos#2131]
Raspberry pi zero W
fresh install of motionEyeOS 20190427
Press Check, start update, update successful
after reboot same version

how i can do?

**Comment by GrueMaster** [comment]
I ran into a problem with this release on my Pi zero W as well.  I ended up downloading the 20190911 image and now everything works (mainly my arducam - that was my real issue).  It took ~10 minutes to reimage and reconfigure.

The wiki is outdated, to download it, go to the releases area here:  https://github.com/ccrisan/motioneyeos/releases

**Comment by ebretteville** [comment]
<img width="795" alt="Capture d’écran 2019-10-15 à 21 05 52" src="https://user-images.githubusercontent.com/3687099/66861670-b9518500-ef8f-11e9-9c6f-63cb78564411.png">
Same here and when downloading and trying to flash the pine64 img version with balenaetcher it says the img is corrupted.
