### ISSUE TITLE
Motioneye on raspbian not working

### ISSUE THREAD

**Issue by HU022** [ccrisan/motioneyeos#2138]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### Board Model

I am using the following board/model: Raspberry pi 3b+ running raspbian

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Trust trino

### Network Connection

My motionEyeOS unit is connected to the network via: wifi

Hi, i installed motioneye on raspbian. This is because i want to use motioneye while viewing the cam's in the browser at the same time wihout buying another pi. I successfully installed motioneye, but when i enter the ip adress of my pi it doesn't show up.

**Comment by jasaw** [comment]
@Wouterkaas Your question is about motionEye, please ask in motionEye project: https://github.com/ccrisan/motioneye
From memory, I think the web interface runs on port 8765 by default. Try http://<RPi_IP_Address>:8765
Check your `/etc/motioneye/motioneye.conf` file.
