### ISSUE TITLE
MP4 wrapper for video

### ISSUE THREAD

**Issue by molly78** [ccrisan/motioneyeos#214]
Again rocking software!

Since I check in using my iOS devices, any chance I missed the ability to change the video wrapper type?

It doesn't seem to want to handle the avi's generated and perhaps a MP4 may be more cross platform?

...

I forgot about vlc and it handles the avi's perfectly

However when you generate a time lapse it just disappears. There's not prompt in iOS with the generated file

Thx again

**Comment by bortek** [comment]
Please post your question on the forum , see if any other members responds to it.
