### ISSUE TITLE
Setting not available

### ISSUE THREAD

**Issue by uac988** [ccrisan/motioneyeos#215]
Just installed latest release 20160109 on Pi2, standard Pi Camera

Web interface is different to descriptions on web. No admin login key icon. Setting are limited to

Layout Columns  
Fit Frames Vertically
Frame Rate Dimmer  
Resolution Dimmer   

Literally cannot do anything with web interface. Real time monitor of camera does work in web browser

**Comment by molly78** [comment]
Perhaps it looks like you're logged in as a user
Click on the user icon on the left to get the prompt to login

**Comment by uac988** [comment]
Thanks for the fast feedback! I am away from the unit at the moment so
am running from memory.... I did click on the user icon. No prompt to
login appears. No much appeared to happen. Will double check again
tonight though.
Also it appears I could not login via SSH until I've logged in at
least once via keyboard. Is this normal?
David
----- Original Message -----

**Comment by molly78** [comment]
did you reboot the device after the initial install boot up?

default login for admin is no password - should set that asap

**Comment by Ethocreeper** [comment]
? for me it worked just fine it the pi1b+ and the pi3.
i just connected to them then trust there certificate the firs time and asks for login just enter admin in the username and hit enter. then i enabled advanced settings.
