### ISSUE TITLE
Raspberry 3

### ISSUE THREAD

**Issue by duckietm** [ccrisan/motioneyeos#216]
Hello,

I installed the oh so nice Motion Eye Os on the raspberry 3 and all looks fine first hand, Thanks for this :) 
However a couple little points:

- if i make changes to the webinterface i sudenly recive a error: "An error occurred. Refreshing is recommended." and then nothing happens and making the change again same error, after a reboot i can change stuff again ? (to go straight to the error, use the disable light switch)

- Enabled the SSH, but it is not working ....

- Where are the overclock settings ?

**Comment by ccrisan** [comment]
I'm working on the issue related to the errors you get. No overclocking settings are supported for the RPI3.

**Comment by ccrisan** [comment]
The bug has been fixed and the fix will be included with the next release.

**Comment by duckietm** [comment]
Okie Thanks !



 Van:   Calin Crisan <notifications@github.com> 
 Aan:   ccrisan/motioneyeos <motioneyeos@noreply.github.com> 
 Cc:   duckietm <troop@duckplaza.com> 
 Verzonden:   15-3-2016 16:25 
 Onderwerp:   Re: [motioneyeos] Raspberry 3 (#216) 


I'm working on the issue related to the errors you get. No overclocking settings are supported for the RPI3.
