### ISSUE TITLE
Time Zone Issue

### ISSUE THREAD

**Issue by forum999** [ccrisan/motioneyeos#2164]
FIrst off, love the software its great!

other than the issue with not being able to use ip camera connected directly to the ethernet port there seems to be a bug in the software.

When i change the time zone in the menus from utc to GMT i hit apply and the pi reboots but the settings stay on UTC meaning my unit is an hour slow.

Is there a way to rectify this please?

**Comment by ccrisan** [comment]
UTC and GMT should indicate the same timezone. The difference between them is the leap second, as far as I know.
