### ISSUE TITLE
notification email failed error no 97 address family not supported by Protocol 

### ISSUE THREAD

**Issue by cbrtumkur** [ccrisan/motioneyeos#2192]
![motionerror](https://user-images.githubusercontent.com/14069712/68666929-d9626d00-056a-11ea-8319-cf3e37a3debc.png)
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: motioneyeos-raspberrypi3-20190911.img.xz

### Board Model

I am using the following board/model: (Raspberry PI 3B+).

### Camera

I am using the following type of camera: (raspberry pi 2).

My camera model is: (raspberry pi 2).

### Network Connection

My motionEyeOS unit is connected to the network via: (Ethernet).

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by Dewey3** [comment]
You might want to try dropping the "@gmail.com" from the SMTP Account name and giving it another try.

**Comment by cbrtumkur** [comment]
Sir I  Hotmail, the same error, thank you in advance
