### ISSUE TITLE
Where is the settings.py file?!

### ISSUE THREAD

**Issue by projectzro** [ccrisan/motioneyeos#2199]
According to the [wiki](https://github.com/ccrisan/motioneyeos/wiki/Tweaks) the file should be in /programs/motioneye/settings.py.

I remounted / and /boot for read/write like instructed at the top but the directory just doesn't exist.

Version Info:
`OS_NAME="motionEyeOS"`
`OS_SHORT_NAME="motioneyeos"`
`OS_PREFIX="meye"`
`OS_VERSION="20190911"`

I am trying to add my SSL cert and the only guide I found that did not involve installing 3rd party software is this [comment](https://github.com/ccrisan/motioneyeos/issues/663#issuecomment-449993473). 

I don't know why I cant just add them to the keystore like any other webserver application I have ever used. If there is an easier way to do this please let me know. 

I have seen a few comments about adding other software, but I don't see any way to do that. wget and dpkg are not installed in the version I have, and I don't see any documentation as to what the OS uses as a package manager. 

Thanks in advance!

**Comment by ccrisan** [comment]
You're right: the wiki article was outdated and I have now removed the misleading section.

In any case, installing stuff on motionEyeOS is not possible. If you need extra packages, I recommend that you go with [motionEye](https://github.com/ccrisan/motioneye) on Raspbian.
