### ISSUE TITLE
Can't change USB webcam frame rate

### ISSUE THREAD

**Issue by stanciu** [ccrisan/motioneyeos#220]
I've installed 20160306 on a Raspberry Pi 3, and it works fine with the camera module (apart from the led not turning off), but I can't say the same about the Logitech USB webcam that I've attached to it.

For some reason I cannot change the frame rate for the USB cam (An error occurred. Refreshing is recommended.), and the frame rate keeps jumping to random values between 15.9/3.1fps and 36.5/4.3fps, leading to results like [this](http://i.imgur.com/gLxyd8d.png) (webcam on the right, camera module on the left).

The webcam works fine when connected to another computer.

This is what I found in the logs after trying to update the frame rate:

`2016-03-17 15:35:24: [motioneye]    ERROR: global name 'arm_freq' is not defined
Traceback (most recent call last):`
  `File "home/ccrisan/motioneyeos/output/raspberrypi3/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception`
`  File "home/ccrisan/motioneyeos/output/raspberrypi3/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1603, in wrapper`
`  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 229, in post`
`  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 158, in wrapper`
`  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 458, in set_config`
`  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 311, in set_camera_config`
`  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 408, in set_camera`
`  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 139, in set_main`
`  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 1911, in _set_additional_config`
`  File "/usr/lib/python2.7/site-packages/motioneye/boardctl.py", line 143, in _set_board_settings
NameError: global name 'arm_freq' is not defined`
`2016-03-17 15:35:24: [motioneye]    ERROR: 500 POST /config/0/set/?_=1458243293952&_username=admin&_signature=39bcbdcd1c237d460f873e2b05619fc97e78713f (192.168.1.100) 724.55ms`

Any idea what the cause of this might be?

Thanks!

**Comment by ccrisan** [comment]
It's a known bug that has already been fixed. It will be available with the next release.
