### ISSUE TITLE
video thumbnails

### ISSUE THREAD

**Issue by pgkool** [ccrisan/motioneyeos#221]
This is an amazing build that makes the motion software very user friendly. Thankyou for the hard work.

Is there a way to pick what thumbnail is selected for the motion videos? After I changed the 'frames to capture before motion is detected', the thumbnail is no longer of the object that has caused the detection.

Thanks in advance.

**Comment by ccrisan** [comment]
The thumbnail should be the central frame (the middle of the movie). There's no way to change that.
