### ISSUE TITLE
Error when toggling CSI Led to Off

### ISSUE THREAD

**Issue by mnosam** [ccrisan/motioneyeos#222]
Logged in as Admin, version 20160306 on a Raspberry Pi 3.

When toggling the 'CSI Led' to 'Off' and then pressing 'Apply', I get the prompt to reboot the system. After pressing 'Yes' the system does not reboot and an error message is displayed at the top of the screen: 'An error occurred. Refreshing is recommended.'

Refreshing the page then shows the 'CSI Led' as toggled 'Off' yet the Led is still on. After rebooting the system from the General Settings menu the camera Led is still on. Weird.

**Comment by ccrisan** [comment]
Already reported and fixed.
