### ISSUE TITLE
Advanced settings missing 

### ISSUE THREAD

**Issue by lassewr** [ccrisan/motioneyeos#2228]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version
I am running motionEyeOS version: (20190911).

### Board Model
I am using the following board/model: (Raspberry PI 3B+).

### Network Connection
My motionEyeOS unit is connected to the network via: Ethernet.

### The Issue

I have made a setup with a raspberryPi zero w for a motioneye cam setup and then a server/hub with motioneye. This works fine on the surface. They can be connected and I was nearly ready to celebrate.... but...

My problem is the _advanced settings_, where I can specify where to store the recordings and so on? It does not show. I’ve read many places that I’m supposed to activate the advanced settings under “general settings”. But I can’t find it.

Any ideas to finish my setup?

The following screenshots are from a clean install, made without adding the wpa_supplicant.conf
I’ve tried different SD cards and 4-5 re-flashing the image to the cards. none of it solved the problem.

![68BEE40C-11EB-40E7-96D1-0615C7D619AB](https://user-images.githubusercontent.com/59034275/71132149-030c5500-21f7-11ea-9470-36444449ca89.jpeg)
![54F40637-6BC6-4F9C-BFAC-3C3B50A5A270](https://user-images.githubusercontent.com/59034275/71132150-030c5500-21f7-11ea-8f7c-29461883d95c.jpeg)

**Comment by lassewr** [comment]
I think this problem is really weird. All tutorials and screenshots show a different interface than the one I see.  
Did I miss something obvious?

**Comment by jasaw** [comment]
Did you log in as Admin?

**Comment by ccrisan** [comment]
Actually what's been previously called "Advanced Settings" is now gone. All settings are always visible for admin user.

**Comment by lassewr** [comment]
But I was logged in as admin !??

I think I’ll try with a clean install and pay even closer attention to that part. I don’t think I’ve ever logged in as user... can’t see why I would du that right now.

**Comment by ccrisan** [comment]
@lassewr what particular options are you missing?

**Comment by lassewr** [comment]
I formatet both SD cards in the Raspberry pi zero W and Raspberry pi3... and did one of the installation guides again. It looks like everything works now. I’m  really not sure what happened. I did log in as Administrator, but must have entered some wrong information or switched a wrong setting on/off.

My advice is to focus on the installation and only play with settings you need. 😅

But thank you very much for your time. I appreciate you taking your time to help.

**Comment by balkalabs** [comment]
I know this issue is closed but i had the same.
For the record, "fast network camera" was turned on in expert settings tab.

**Comment by lassewr** [comment]
> I know this issue is closed but i had the same.
> For the record, "fast network camera" was turned on in expert settings tab.

Thank you. It might be the reason... it’s working right now and “fast network camera” is indeed turned off.
