### ISSUE TITLE
Moving sshd_config to /data/etc

### ISSUE THREAD

**Issue by edenhaus** [ccrisan/motioneyeos#2234]
I would suggest to move the **sshd_config** to _/data/etc_, so a software update will not override the config, if someone has modified it. I think some users are changing the file for security reason.

As example, I only allow ssh logins wia public_key and I also changed the ssh port.

Unfortunately I didn't understand, where I should move the sshd_conf, located under _board/common/overlay/etc/_. As part of the solution, we can create a symbolic link, which points to _/data/etc_

Thanks in advance

**Comment by ccrisan** [comment]
The SSH configuration has been rewritten in https://github.com/ccrisan/motioneyeos/commit/a8f140575c1b1561fe423856d77d501862ecff56.

The wiki page has been updated to reflect the new configuration: https://github.com/ccrisan/thingos/wiki/SSH.

You should now be able to add your stuff to `/data/etc/sshd_config` without it being wiped out by firmware updates.
