### ISSUE TITLE
USB File Storage

### ISSUE THREAD

**Issue by BrianDurward** [ccrisan/motioneyeos#224]
Here are the screen shots.
Brian

![screenshot at 2016-03-22 14 17 59](https://cloud.githubusercontent.com/assets/10829258/13955938/95b75bf0-f03e-11e5-8c70-cd857fe198f8.png)
![screenshot at 2016-03-22 14 20 40](https://cloud.githubusercontent.com/assets/10829258/13955963/b11a14a0-f03e-11e5-8e96-c2e3bcb0759f.png)

**Comment by ccrisan** [comment]
What happens if you navigate to sda1 or sdb1?

**Comment by BrianDurward** [comment]
In sda1 I find a current (dated) directory.
Nothing in sdb1.
![screenshot at 2016-03-22 15 40 52](https://cloud.githubusercontent.com/assets/10829258/13957555/b94cce64-f044-11e5-8f6d-12e175df7c8f.png)

I should mention that I used gparted to prepare the USB dive and selected ext3 file types.

**Comment by ccrisan** [comment]
So what seems to be the problem?

**Comment by BrianDurward** [comment]
I was looking in home/ftp/storage where sda1 and sdb1 are both empty.
![screenshot at 2016-03-22 15 59 11](https://cloud.githubusercontent.com/assets/10829258/13958238/530b50a0-f047-11e5-94b7-0464685202f4.png)

So all is clear - I navigate to /data/media/sda1/myfolder

Many thanks for your quick help.

Brian

**Comment by ccrisan** [comment]
Alright :)
