### ISSUE TITLE
Connecting 2 differnt routers to a single MotionEyeOS operating system

### ISSUE THREAD

**Issue by GhettoBurger996** [ccrisan/motioneyeos#2262]
Hey all, 

This isn't really an issue related to the functionality of the OS, rather a personal problem that I'd like the solution to.

I am currently running MotionEyeOS on a basic computer, which is connected to my router via Ethernet connection, to access the dashboard of the Operating system I have type in the interface wlan0 IP address that the OS assigns (for instance 10.10.2.109). This MotionEyeOS Setups will be Called HUB.

Using a raspberry pi which is situated in another location (using another router and in turn assigned a unique IP address) I would like to feed the video stream directly to HUB.

I cannot find any documentation, video, etc on how to do so. (images below should help clarify problem).

The only potential solution I can see to this is adding the router configuration in the file 
wpa_supplicant.conf within MotionEyeOS. However, even after doing that it doesn't seem to work.

I'd appreciate any help, thanks!

![alpr7](https://user-images.githubusercontent.com/24411647/72489838-49d77580-37ca-11ea-8b34-feafb65bb769.png)

**Comment by digiltd** [comment]
You say two routers in different locations, do you mean different locations in the same house i.e. the same network?
