### ISSUE TITLE
cannot add my cameras

### ISSUE THREAD

**Issue by holzfelix** [ccrisan/motioneyeos#2280]
Hi I use the current motion eye os on a rasperry 3b+

When I try to add my camera like this as network camera:

rtsp://admin:123456/192.168.178.100/stream0/

I goth the error Name or service not known or camera not supported. ... 

its a simple rtsp stream

**Comment by ccrisan** [comment]
`rtsp://admin:123456/192.168.178.100/stream0/` does not look like a valid RTSP URL. Try:
 * url = rtsp://192.168.178.100/stream0
 * username = admin
 * password = 123456

**Comment by holzfelix** [comment]
works thanks

**Comment by joeydream** [comment]
how about there is only one row for you and you must put the admin and password in one line?


> `rtsp://admin:123456/192.168.178.100/stream0/` does not look like a valid RTSP URL. Try:
> 
> * url = rtsp://192.168.178.100/stream0
> * username = admin
> * password = 123456
