### ISSUE TITLE
change admin password. but motion.conf still show 4fd2cd40fc8c7501958fd4af8511aed07590d1c7

### ISSUE THREAD

**Issue by knnleow** [ccrisan/motioneyeos#2291]
### Preliminary Docs

change admin n user password. both password works.
but /data/etc/motion.conf still show 4fd2cd40fc8c7501958fd4af8511aed07590d1c7 for admin user.
tried login using this default password, it work. now i am concerned.
cannot find any place that store this fixed admin password.
how to remove this password admin password. 

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (20200203).

### Board Model

I am using the following board/model: (Raspberry PI 3B+).

### Camera

I am using the following type of camera: (MMAL).

My camera model is: (Raspberry Pi Camera Module).

### Network Connection

My motionEyeOS unit is connected to the network via: (WiFi).

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

NA

### Log Files

I consider the following log files relevant to this issue:
NA

**Comment by ccrisan** [comment]
The value that you see associated to `admin_password` in `motion.conf` is the hash of your password. For backwards compatibility, motionEye will also allow you to log in if you supply the text that is associated with `admin_password`, in your case being the hash.

The behavior that you see is normal. If you consider there's a security concern with this implementation, please let us know.
