### ISSUE TITLE
protocol rtsp not supported - release 20151103

### ISSUE THREAD

**Issue by scoobyd00** [ccrisan/motioneyeos#23]
With the latest release when trying to add a rtsp network camera im unable to do so and
get the error 'protocol rtsp not supported'.

The pre-release versions worked fine.

**Comment by scoobyd00** [comment]
@ccrisan is it easy to sort this issue? The latest release had been running stable on my pi 2 for over 48hrs now but without rtsp support

**Comment by ccrisan** [comment]
The issue has been fixed. I'll release a new version within the following week.

**Comment by scoobyd00** [comment]
Excellent thanks.

**Comment by dmolner** [comment]
Realy work?
I test but with same message 'protocol rtsp not supported'.

**Comment by ccrisan** [comment]
I haven't gotten to release the new version yet. Hang on another few days.

**Comment by dmolner** [comment]
Perfect! 
With this option I only need two more, upload ftp and take pictures when motion occur.

**Comment by scoobyd00** [comment]
New release is working well with rtsp.
Thankyou.
