### ISSUE TITLE
EsCam QD300 with MotionEyeos

### ISSUE THREAD

**Issue by xxllo** [ccrisan/motioneyeos#230]

**Comment by xxllo** [comment]
This translition is with Google
Have an IP Cam from ESCAM qd300 and can not do to activate the cam in Monioneye it . What am I doing wrong???

**Comment by guadacorte** [comment]
i also have an ip camera. I cannot get it to work
i have a ideanext C1702W. Sometimes it will connect using rtsp but only a grey screen with the time and date stamp showing

**Comment by xxllo** [comment]
look here
https://www.ispyconnect.com/man.aspx?n=ideanext

**Comment by badele** [comment]
Hi,

I have received my new Escam Brick QD300. It work fine with motioneyeos. For that, i did it :
- Go to https://www.ispyconnect.com/man.aspx?n=eScam#
- Click to "Brick Qd300" and enter informations
- Go to motioneyeos and add network camera
- Paste the previous ispyconnect informations

Note: For configuring the camera (change résolution, network address, etc), it seem we must have a windows operating system.

For me this issue can be closed

**Comment by ccrisan** [comment]
@badele thanks for sharing this with us. I'll close the issue then.
