### ISSUE TITLE
default html folder

### ISSUE THREAD

**Issue by sucdejan** [ccrisan/motioneyeos#238]
Please help!
Where is default "open from outside" html folder?
I made a script that print some data to file from attached i2c sensor and I don't know where to store this file to be visible from browser (192.168.0.xxx/datafromsensor.txt)..

**Comment by ccrisan** [comment]
You can't. Not with motionEyeOS. Try Raspbian instead.

**Comment by sucdejan** [comment]
Found it!
I can write a file and store it in »/usr/lib/python2.7/site-packages/motioneye/static/img« and file is visible from webbrowser.
