### ISSUE TITLE
Raspberry Pi 4 USB mass storage beta

### ISSUE THREAD

**Issue by Chiny91** [ccrisan/motioneyeos#2391]
Not a problem, my 2 * motionEyeOS R Pi have been running for years (amazing) and my AI-improved motionEye for well over a year. 

Still, always room for improvement and this **_official_** [boot from USB mass storage](https://www.raspberrypi.org/forums/viewtopic.php?t=274595&p=1663644#p1663644) caught my attention.   It could be useful for motionEyeOS where increased storage could be useful, and SSD less likely than SDcard to be worn/corrupted.    Still beta, so not mainstream, yet.

**Comment by PsyEng** [comment]
If you like to boot from external devices, look into my small guide 
[Boot motioneyeOS from USB/SSD on Raspberry Pi 4B only](https://github.com/ccrisan/motioneyeos/issues/2439)
