### ISSUE TITLE
Webinterface Bootstrap

### ISSUE THREAD

**Issue by weiserhei** [ccrisan/motioneyeos#2397]
Hello,
this issue is not targeted at motioneyeos in particular, rather than the webinterface which is the same for motioneye.

Whats the reason behind building it without any frontend library? While the hand-crafted UI Elements and colors have their charm, Im having some trouble using it on my mobile device. 

Beeing curious I came up with a working prototype for the Settings Panel using Bootstrap. I havent looked at all the Pages/Elements yet, but it looks promising to me. If there is any interest in "bootstrapping" motioneye I might give this a try. Maybe there are some obstacles hidden which renders all of the work useless, so please let me know. 

<details>
  <summary>Screenshots</summary>

![mobile-2](https://user-images.githubusercontent.com/7581732/83033983-09b9b680-a038-11ea-8cb8-3ab12eb5054f.png)

![mobile-tooltip2](https://user-images.githubusercontent.com/7581732/83032767-88adef80-a036-11ea-8d63-8e5b63e0dbbf.png)

![desktop](https://user-images.githubusercontent.com/7581732/83032780-8b104980-a036-11ea-9687-8e7ec99d37f8.png)
</details>

**Comment by jasaw** [comment]
If you are not aware, https://github.com/ccrisan/motioneye is the web UI part of MotionEyeOS. Can you please repost this question there? I think you might get more responses there.
Personally, I like bootstrap.

**Comment by weiserhei** [comment]
Thanks for the headsup, I close this one then 👌
