### ISSUE TITLE
firefox view pictures

### ISSUE THREAD

**Issue by funtomas** [ccrisan/motioneyeos#24]
there is a problem with FF 42 and viewing picture logs
web page is broken

**Comment by ccrisan** [comment]
What do you mean by "picture logs" and what do you mean by "web page is broken"? A screenshot might help me understand the problem.

**Comment by Feuxxxeu** [comment]
In FF v41 it was ok with menu on the dates manu on the left and the pictures on the right.
On FF v42 menu is on top, and pictures down under.
![example](https://cloud.githubusercontent.com/assets/15118885/11014064/d038c602-8526-11e5-8a38-e55a8b1f53ab.JPG)

**Comment by ccrisan** [comment]
You're right, the new firefox does exhibit this weird behaviour. I'll make sure to fix this asap.
