### ISSUE TITLE
RPi3: No preview when in Fast Network Camera 

### ISSUE THREAD

**Issue by perrychan** [ccrisan/motioneyeos#240]
I am unable to preview the camera once I switch on Fast Network Camera on my RPi 3.

**Comment by ccrisan** [comment]
Have you tried refreshing the window a couple of times? The MJPEG "technology" can sometimes be problematic. Does it work if accessed from a webcam app? If it doesn't, could you please attach all of your logs?

**Comment by perrychan** [comment]
Realized that I was not forwarding to the unique port in my port fowarding. Closing!
