### ISSUE TITLE
Raspberry PI Zero + Night Vision Issue

### ISSUE THREAD

**Issue by STUKguy** [ccrisan/motioneyeos#2400]
Hi,  basically i brought the below
https://www.ebay.co.uk/itm/5-Megapixel-Infrared-Night-Vision-IR-CUT-Camera-For-Raspberry-Pi-4B-3B-Zero-NEW/293554729746?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

Connected it and when i power on the PI Zero W i get this
![image](https://user-images.githubusercontent.com/66088795/83255420-4a384200-a1a8-11ea-8dcf-9d75314f2669.png)

And this is what i get when i log in to motion eye os (latest build) bare in mind it is the middle of the day and room i bright
![image](https://user-images.githubusercontent.com/66088795/83256793-fc710900-a1aa-11ea-93fc-057e13d86e3d.png)

This is with CSI Camera led off

If i adjust the small screw next to IR thing on the side
![image](https://user-images.githubusercontent.com/66088795/83257138-a2247800-a1ab-11ea-9ad8-698c5cb3e9c0.png)

so they are both off 
![image](https://user-images.githubusercontent.com/66088795/83257175-bb2d2900-a1ab-11ea-8390-a862aa75e9de.png)

i still get this when i log into motion eye
![image](https://user-images.githubusercontent.com/66088795/83257218-d0a25300-a1ab-11ea-8bd7-09db06de5513.png)

If i enable CSI and reboot the camera i still get the same thing but when i face the camera towards my PC monitor the colour is fine but when i face the camera around my room the colour is all purple-ish
![image](https://user-images.githubusercontent.com/66088795/83257503-6dfd8700-a1ac-11ea-8d48-1f9dc544a313.png)
![image](https://user-images.githubusercontent.com/66088795/83257597-9dac8f00-a1ac-11ea-9782-3388eb57e02c.png)

and finnaly if i turn the sreaws again nothing changes.

I have played about ith the colour setting on Motion eye but this does not and like i said when i point it towards my screen all the colours are correct.

Any ideas, sorry about the really long post

**Comment by JohanD78** [comment]
Your camera is a no ir-filter type (ir cut), thats what the lights are for, emitting IR light that the camera can see in a totaly dark room.

What you see is normal for a no-ir camera.

**Comment by STUKguy** [comment]
@JohanD78 thank you for your reply, the problem i am having as explained above in a bright room the image is still the same but from my understanding this should be happening in a bright room.

**Comment by JohanD78** [comment]
![pinoir-thumbnail](https://user-images.githubusercontent.com/59706257/83302387-8cd73a00-a1fb-11ea-97e9-fd01636f69e5.jpg)

[https://raspi.tv/2013/pinoir-whats-it-for-comparison-of-raspicam-and-pi-noir-output-in-daylight](url)

Dont matter if it is dark or bright. You got a no-ir cam and thats the tint you get with those.

**Comment by STUKguy** [comment]
@JohanD78 Damn thank you that explains a lot. Im trying to build a out door camera with night vision what would suggest i use for the camera?

**Comment by omgitsaheadcrab** [comment]
The camera you have is the only one that will be able to see anything in the dark, so stick with that.

**Comment by zubzero689** [comment]
i was doing similar you might want to get more IR light i had to i couldnt see a thing unless i was within like 10 feet of the camera and i hung them under my camera different power but works great and most are rated to 80 feet

**Comment by PsyEng** [comment]
@STUKguy What you're searching, is something like this:
https://www.amazon.de/dp/B07XTBQ1BN/ref=cm_sw_r_other_apa_i_My-2Eb5DCGWCG
This has a built-in IR-cut filter, which can be activated and disabled automatic, so you've a clean/real view on day and nightvision at night.

**Comment by PsyEng** [comment]
@STUKguy What you're searching, is something like this:
https://www.amazon.de/dp/B07XTBQ1BN
This has a built-in IR-cut filter, which can be activated and disabled automatic, so you've a clean/real view on day and nightvision at night.

**Comment by STUKguy** [comment]
> @STUKguy What you're searching, is something like this:
> https://www.amazon.de/dp/B07XTBQ1BN
> This has a built-in IR-cut filter, which can be activated and disabled automatic, so you've a clean/real view on day and nightvision at night.

Thank you so much, I will order this now

**Comment by PsyEng** [comment]
@STUKguy You´re welcome. I find another way, but accident today^^
You can set under the "Extra Motion Options” box this parameter and it should be fixed
mmalcam_control_params -awb greyworld

**Comment by STUKguy** [comment]
@PsyEng Hi, Thank you agian, i tried that but nothing happened
![image](https://user-images.githubusercontent.com/66088795/83977380-0b1c9600-a8f8-11ea-81b7-ed338aabe2d2.png)

**Comment by STUKguy** [comment]
@PsyEng its working now kind of
![image](https://user-images.githubusercontent.com/66088795/83977623-c8f45400-a8f9-11ea-9adb-9fdbf4e57257.png)
Atleast nothing is pinky/purple. I have ordered the camera you suggested just waiting for that to arrive before i decide which one i want to use. Thank you again soo much

**Comment by STUKguy** [comment]
@PsyEng Thank you again for your help the camera arrived last week (or the week before) and i finnaly have set everything up and it works great had to make some tweaks (used Pi insted of Pi Zero) Ive just noticed the camera is slightly out of focus, is there anyway to adjust this with out dismantling the camera?

**Comment by PsyEng** [comment]
@STUKguy You can turn the lense to the right and left to steer focus. It could be a little bit hard, so don't worry. The focus is quit fine, so you've to be patient to get the perfect spot.

**Comment by STUKguy** [comment]
@PsyEng Thank you, i may have to abandon the project as i got everything set up and in focus and then came night time and the camera see's nothing just black

This is the image during the day
![10-21-17](https://user-images.githubusercontent.com/66088795/85996111-61618e00-b9f9-11ea-9525-dec39edc8540.jpg)

This is the same image at night
![00-09-26](https://user-images.githubusercontent.com/66088795/85996170-6f171380-b9f9-11ea-9fdc-32e8351db4bc.jpg)

i may try putting the other camera back in and see how that works

**Comment by PsyEng** [comment]
@STUKguy Two things. First, ist not possible to view trough a window, because the leds blends), second, you didn't input the code for greyworld or the leds blends the photodiode so the camera doesn't get in nightvision mode. It looks like the camera doesn't get in nightvision, because I can see violet lights on the image.

**Comment by STUKguy** [comment]
@PsyEng the camera has been placed inside a camera enclosure and is behind a 1mm thick transparent plastic sheet. I didnt think the camera
![image](https://user-images.githubusercontent.com/66088795/86012090-76e4b100-ba15-11ea-837e-26d888b33271.png)
needed the code but i will put it in now and see how it works tonight

**Comment by PsyEng** [comment]
Trough glass or something else, you won't be able to see something else. The infrared spots will reflect on the glass and the camera is blinded.

**Comment by STUKguy** [comment]
@PsyEng the camera needs to be on the outside of the plastic sheet? So if I cut a hole that should fix the problem?

**Comment by PsyEng** [comment]
Maybe. I don't know exactly, if the infrared spots can get through the plastic. You've to test it by yourself.

**Comment by STUKguy** [comment]
@PsyEng what I will do is see how the code works tonight with the camera out side if no change the I will bring in side and test again

**Comment by zubzero689** [comment]
Just an FYI when I put my cameras out side I had to put out some IR leds to get a better view i bought them of Amazon because I put mine in housing of dummy cameras and could only use 1 led of the two it comes with

**Comment by STUKguy** [comment]
@PsyEng So I had to do some more changes I had to upgrade to a PI 4B 2GB found out that the LED need to be on the outside but the night sensor can be behind a glass to work correctly which works well but and images beyond 3 meters come out very blurry. The spec sheet for the IR LED's online 3 meters is the maximum length for a decent image these LEDS are rated at 3w. Based on actual CCTV camera with Night vision they usually come with a 12v IR led which from previous cameras I know can get a decent image further that 3 meters just unsure how to implement this in to my project as I doubt the PI can power a 12v LED

**Comment by STUKguy** [comment]
@zubzero689 Thank you for your comment I also had to use 1 LED as I could not get the 2nd to power unsure if this was a faulty LED.

**Comment by jasaw** [comment]
@STUKguy It's much easier to run a 12V power supply, run the IR LEDs off the 12V, and step the 12V down to 5V for the RPi. You can easily find a step-down DC-DC converter for $2 for the 12V to 5V conversion.

**Comment by STUKguy** [comment]
@PsyEng @jasaw Thank you for you help, but i have had to give up on this project as it is starting to cost to much and is just becoming really annoying

So this is the layout i managed
![20200718_132530](https://user-images.githubusercontent.com/66088795/87936758-5398a900-ca8b-11ea-8366-35c7fd11005d.jpg)

i re routed the night sensor so it would work with the 12v IR LED ring but then come to the night i got this image when i pointed the camera outside
![Screenshot_20200718-225321_Chrome](https://user-images.githubusercontent.com/66088795/87936898-96f31780-ca8b-11ea-8eda-e3546f8469bc.jpg)

Even after turning Greyscale off same thing

I also pointed the camera indoors
![Screenshot_20200718-225406_Chrome](https://user-images.githubusercontent.com/66088795/87936948-aeca9b80-ca8b-11ea-9f8e-3fa10062a316.jpg)

This is the front veiw of the camera
![20200719_215410](https://user-images.githubusercontent.com/66088795/87937072-e8030b80-ca8b-11ea-844e-372de1181f3a.jpg)

i tried with the NOIR camera and excatly the same no differance, i am at a loss how to fix this but i am assumeing the issue im having now is with the IR Leds being to close to the lens but as this project has cost me to much already and i have found the Reolink 420 camera has what i need i will abandon this project and purchase the Reolink and re purpose the PI 4 for a NAS stoarge im looking to build.

Thank you again.

**Comment by jasaw** [comment]
@STUKguy I understand your frustration. I built my own cameras and had the same issues where the ir light was drowning the camera because of ir reflection. I ended up 3d printing a shield around the camera, added foam tape to press this shield against the housing glass to make sure there's no ir leakage. I also 3d printed mounting brackets to hold all the parts in place. I even designed my own ir led board ring around the camera. After 2 years in the outdoor, all the cameras are still working well while the Chinese cheap counterparts are partially broken by now.
My camera hardware design is here. https://github.com/jasaw/camera_hardware/tree/master/rpi-zero-w
The design still has issues, but should give you an idea of what I've done in case you still want to proceed with your camera. 

In the future, I would just install off the shelf good quality cameras with good optics. Don't bother with cheap cameras.

**Comment by STUKguy** [comment]
@jasaw I didnt buy a cheap chinise camera, by the looks of it mine and your idea were the same i just dont have access to a 3d printer. Looking further at your instruction i wish i found that out a lot earlier it would have made my life a lot easier.

The reason i was looking to build a PI camera is i need CCTV with FTP storage which only Motion Eye and now Reolink offer
