### ISSUE TITLE
Possible to install MotionEyeOs into raspbian?

### ISSUE THREAD

**Issue by zettam** [ccrisan/motioneyeos#241]
I use my raspberry to do many things. One of them is stream two webcams from its physical point.

I use motion for that, however, I like the interface (with multiple cameras) of MotionEyeOS. I've never installed or used it so far, I'm only basing off my thoughts on the screenshots I've seen about this software.

So I'm wonderin:

Would it be possible to install motioneyeos into raaspbian? I would like to run it as a web server instead of installing it as a complete new operating system. 

This would do the job painlessly.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian
