### ISSUE TITLE
don't get any settings options with new setup

### ISSUE THREAD

**Issue by pumbaa2183** [ccrisan/motioneyeos#243]
I decided to build a 2nd, camera but after installing and setup the OS on my SD card and logging into the web interface I discovered that I do not have the options to setup anything for the camera ( please see screen shots) 

I have formatted and installed different versions of the OS several times ..... Suggestions ?
![screen shot 2016-04-03 at 7 37 51 am](https://cloud.githubusercontent.com/assets/17677233/14232221/9fa8d496-f970-11e5-93ab-bbf19f591c76.png)

**Comment by ccrisan** [comment]
Close the menu, use the key icon to log in as administrator and do your stuff.

**Comment by pumbaa2183** [comment]
Thats the screen I get after first boot up before I can log in as admin, when I am logged in as the default admin.

**Comment by ccrisan** [comment]
Does the settings menu automatically open after first boot?

**Comment by pumbaa2183** [comment]
yes it does, but it opens to what you see in the screen shot --- so I don't get the option to set an admin username and password, or set my Wifi info :( 


Sent from Alto - altomail.com

**Comment by ccrisan** [comment]
If it does, close it and use the key icon to log in as administrator.
