### ISSUE TITLE
Trigger recording

### ISSUE THREAD

**Issue by speeskeek** [ccrisan/motioneyeos#2450]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: motionEyeOS 20190911

### Board Model

I am using the following board/model: Ordoid XU4

### Camera

I am using the following type of camera: bunch of cheap aliexpress network camera's

### Network Connection

My motionEyeOS unit is connected to the network via: gigabit lan

### Issue

Can I trigger recording of one or more camera's by curl or something?
**Example1:** when my alarm system goes off I read a relay in to some raspberrypi, and this one now triggers a push message to my cell phone. but I want motioneye to also record ALL my cams for 5 minutes to see the bulgars (or my cat?) running.
**Example2:** same thing with my doorbell. Doorbell is connected to a raspberry and when the door rings, I get a push with a picture on my phone. I want motioneye to record the next 2-3 minutes to see where the deliveryman is putting my amazon boxes.

**Comment by jasaw** [comment]
See this: https://github.com/ccrisan/motioneyeos/issues/842#issuecomment-412384288
and this: https://github.com/ccrisan/motioneyeos/issues/842#issuecomment-414375686
