### ISSUE TITLE
How to rest password  

### ISSUE THREAD

**Issue by lodgemoorlad** [ccrisan/motioneyeos#2452]
Hi all
Like a fool, I have forgotten my pw. Is there any way I can change it from a terminal, or do I have to take out the Micro SD and do it that way, here's hoping.
Thanks in advance

**Comment by grphx7** [comment]
To do it via CLI you can edit the motion.conf.  Clear out the data in the password field then try to login with no password for admin.  be sure to set a new password once you get in.

**Comment by lodgemoorlad** [comment]
Hi
Really appreciate your help grphx7, could save me a whole lot of time and
inconvenience. Thanks👍
