### ISSUE TITLE
Store picture when sensor detection happens

### ISSUE THREAD

**Issue by borney** [ccrisan/motioneyeos#246]
Hello,
I'm using motioneyeos 20160320 on two raspi A+ with installed raspicams succesfully and now I like to store pictures independent of the motion detection. Testing that function with:  
wget http://192.xx.xx.xx/picture/1/current/
creates at first a picture file with 0 lenght and no picture, but repeating the command succesfully stores a jpeg picture as desired. 
Using Firefox with http://192.xx.xx.xx/picture/1/current/ opens the picture at the second try.
Thanks for any help.

**Comment by ccrisan** [comment]
If you really need it like that, set https://github.com/ccrisan/motioneye/wiki/Configuration-File#mjpg_client_idle_timeout to 0 in your /data/etc/motioneye.conf file.
