### ISSUE TITLE
Recording file unplayable

### ISSUE THREAD

**Issue by downbike** [ccrisan/motioneyeos#2461]
Hello
I noticed that I am unable to play some of the recorded .mp4 files (see screenshot attached in the post). The unplayable file would have the generic mountain and sun thumbnail. Other files without the generic thumbnails played just fine. I tried multiple video player (VLC included) and none was able to play the file. I know it is a full file because of its ~50MB file size. 

I rolled back into the 20190911 version because of the issue with the latest build (20200606) in which the motioneye OS only record a single file and then stop (reported [here ](https://github.com/ccrisan/motioneyeos/issues/2235))

I attached the motioneye log and screenshots of my video recording setting and the thumbnails of the unplayable files at the end of the post. 
Not sure if this is relevant but when I installed the 2020 and the 2019 build, I used the restore function to restore all my previous settings (from a 2018 build) so i didn't tweak the setting from scratch again. 

Is this an issue with hardware or software? Any fix? Thank you for your time. I really appreciate all your efforts into this project. 
 
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190911 (roll

### Board Model

I am using the following board/model: Raspberry Pi 3 Model B

### Camera

I am using the following type of camera:  V4L2 camera

My camera model is: Raspberry Pi Camera V2.

### Network Connection

My motionEyeOS unit is connected to the network via: Wifi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * 32GB microSD card 

### Log Files

I consider the following log files relevant to this issue:

 * attach motioneye.log
[motioneye(1).log](https://github.com/ccrisan/motioneyeos/files/4908109/motioneye.1.log)

![Annotation 2020-07-11 231345](https://user-images.githubusercontent.com/36092436/87240347-998ba800-c3cd-11ea-9225-bd8f8b6314cd.jpg)

![Annotation 2020-07-11 231345_1](https://user-images.githubusercontent.com/36092436/87240511-08b5cc00-c3cf-11ea-9575-6692ad0538cc.jpg)

**Comment by starbasessd** [comment]
I would try turning off H.264/OMX and just choose H.264
