### ISSUE TITLE
direct video stream url

### ISSUE THREAD

**Issue by aristosv** [ccrisan/motioneyeos#248]
I have a raspberry pi 3 with the raspberry pi camera v1.3 connected on it, running the latest version of motioneyeos.

I am trying to connect the pi/camera with a third party program (webcamxp, sighthound etc) but I don't know the URL of the video stream. I tried scanning for it using ispy software, but it can't find anything.

What is the direct video stream url when the pi is running motioneyeos?

Thanks

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#whats-the-deal-with-snapshot-url-streaming-url-and-embed-url

**Comment by cederlof** [comment]
@ccrisan There is only a description on provided URL, no example of a streaming URL?

**Comment by ccrisan** [comment]
@cederlof if you click on it, a popup window should appear with the actual link to copy.

**Comment by Bluscream** [comment]
what about RTMP?

**Comment by IngiDingi** [comment]
Hi.

I also dont know how to build the right URL for streaming.
I followed the LINK which is mentiond above but sorry, I dont get it.
Can you provide an example of an URL so I can understand how to use it?

Thanks
Ingo
