### ISSUE TITLE
How do I get the Web Hook notification to post an image?

### ISSUE THREAD

**Issue by wadewegner** [ccrisan/motioneyeos#25]
Note: even though I choose POST it always switches back to GET.

Here's what I see:

http://requestb.in
GET /url
 0 bytes 12s ago  
From <IP>
FORM/POST PARAMETERS

None
HEADERS

Accept-Encoding: identity
Via: 1.1 vegur
Total-Route-Time: 0
Host: requestb.in
X-Request-Id: d85565e8-186e-4300-a94e-5175e8c32f77
Connect-Time: 1
User-Agent: Python-urllib/2.7
Connection: close
RAW BODY

None

**Comment by ccrisan** [comment]
It was a bug indeed. Thanks for reporting the issue.
