### ISSUE TITLE
ftp to sd card 

### ISSUE THREAD

**Issue by Tntceria** [ccrisan/motioneyeos#251]
When I ftp to  motioneye and look in the sdcard directory I have no files.  I do have file storage on for the sdcard and I have ftp enabled.  When I look in the /data directory I do see the camera movies and pictures.   
  When I turn file storage on for a usb device and ftp to motioneye the files do appear under storage/sda1 as expected. 
  It appears there is a problem with the bind mount does anyone else have this problem??

**Comment by ccrisan** [comment]
What motionEyeOS version do you use? Do your *sdcard* files show up in `/data/output` (where the ftp sdcard mount should point to)?

**Comment by Tntceria** [comment]
I am using version 20160320, the files are showing up in /data/ , /data/output/  is empty so I guess that is the problem. Is there away to change the storage to go to /data/output/ ?

**Comment by ccrisan** [comment]
Of course, you should simply change the *Root Directory* setting accordingly. It is set to `/data/output` by default but you have probably changed it afterwards.
