### ISSUE TITLE
URGENT! Latest update brakes the notification settings!!

### ISSUE THREAD

**Issue by AnsuRio** [ccrisan/motioneyeos#255]
![screen shot 2016-04-15 at 17 38 38](https://cloud.githubusercontent.com/assets/9256550/14566755/2498a1e4-0331-11e6-8566-f54fb40c6468.png)

After the latest release with the support for setting your own hostname, everything seems to have been pushed one row down.

Could you please look over this and apply a fix for it? :) Both my cameras ended up liked this...

**Comment by ccrisan** [comment]
What was the previous version that you've been running? DId you "skip" a version when updating?

**Comment by kodapaio** [comment]
Nope, the latest version was the one from jan that I was running. And updated to the latest.

**Comment by Mikiya83** [comment]
Same problem here, without "skipping" version (i'm on "release" updates only)

**Comment by ccrisan** [comment]
I admit I added an extra parameter to the SMTP settings (namely *From Address*) but I wrote the code in such a manner that it would detect old vs. new config lines. I'm afraid that in your case you'll need to reconfigure your SMTP settings from scratch. I'm sorry for the inconvenience and I promise not to add any more SMTP params in the near future :)

**Comment by Mikiya83** [comment]
Oh no prob man, it takes 10s to reconfigure SMTP server ;) So feel free to timprove your amazing project when you want, thanks for your work ! We signal the problem but it's not a big deal :+1:
