### ISSUE TITLE
Adding the Raspberry Pi NoIR Camera Module

### ISSUE THREAD

**Issue by mroberts77** [ccrisan/motioneyeos#2569]
Have the latest version of Motion IO running on Zero W, trying to add the NoIR camera, and have seen but can't seem to track down:
1) extra motion commands to convert to black and white (when IR lights used, still pinkish)
2) adjustment for blurryness?

![image](https://user-images.githubusercontent.com/49018165/98454170-4bd24280-2116-11eb-8a65-789e4506b241.png)

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

### Board Model

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: (insert your camera model, e.g. Logitech C290).

### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by mroberts77** [comment]
Ran using Raspbian only, and seems to be clearer than for OS. Also, can convert to Black and white with this code 
`camera.color_effects = (128,128) # turn camera to black and white`
>  can that be done in Motioneye OS in extra Motion Options?

![image](https://user-images.githubusercontent.com/49018165/98486033-b4312a80-21cf-11eb-8a6f-8868f82453c0.png)
![image](https://user-images.githubusercontent.com/49018165/98486042-cc08ae80-21cf-11eb-912a-d78c4ca89505.png)

**Comment by mroberts77** [comment]
Blurriness seems to have been adjusted with manual focus and restart.
How to convert to black and white only?
![image](https://user-images.githubusercontent.com/49018165/98501451-1c016880-2204-11eb-91af-c57260c0b332.png)

**Comment by cap9qd** [comment]
You can set the AWB mode to greyworld by selecting the option in the video
section if using fast network camera or by using the extra motion options
listed in the post below if using the full installation.

https://github.com/ccrisan/motioneye/issues/1370#issuecomment-527471418

**Comment by mroberts77** [comment]
tried typing:
mmalcam_control_params -awb greyworld

didn't seem to make a difference, also tried 'tungsten' instead, no apparent effect: probably missed the way to add the info?

**Comment by Pi-DD** [comment]
Did you restart Motioneye? Check what level of Motion is installed - needs to be 4.3 at least for “greyworld”. I’m running motioneye 0.42.1 and Motion 4.3.1 under Raspbian and it works OK

**Comment by mroberts77** [comment]
Pasted in rebooted, and even "apply" still color, got the version you have: what am I doing wrong?

![image](https://user-images.githubusercontent.com/49018165/98742523-7238ed80-2363-11eb-8b4b-0b093caef648.png)

![image](https://user-images.githubusercontent.com/49018165/98742763-d0fe6700-2363-11eb-9b07-f5c596aaeed9.png)

**Comment by cap9qd** [comment]
Greyworld isn't black and white. It is just properly white balanced now but
still color.
