### ISSUE TITLE
corrupt files

### ISSUE THREAD

**Issue by Tntceria** [ccrisan/motioneyeos#257]
I noticed as the file storage starts to get large 100+ files. They also become corrupt so that the files cannot be opened.  Could this problem be related to the 10 sec file listing timeout.

**Comment by ccrisan** [comment]
The corruption normally has nothing to do with the number of files. It might be that the more files you have, the bigger the probability is that a file gets corrupted.

**Comment by Tntceria** [comment]
Once the problem starts occurring it seems to happen to all falls that are stored.  I also tried saving to a thumb drive and the results seem to be the same.

**Comment by ccrisan** [comment]
How do you know the files are corrupted?

**Comment by Tntceria** [comment]
When I try to view them i get a message that states part of the file is either missing or corrupt

**Comment by ccrisan** [comment]
Can you attach such a file here?

**Comment by Tntceria** [comment]
Ok here is one. 
![07-52-48](https://cloud.githubusercontent.com/assets/18428229/14638199/3c772c56-0604-11e6-9b43-1c37c633e103.jpg)
