### ISSUE TITLE
Home Assistant Motion Eye Motion Detection

### ISSUE THREAD

**Issue by mattjones2300** [ccrisan/motioneyeos#2600]
I am running motionEyeOS version: 0.10.2 inside Home Assistant on a Raspberry Pi 4. 

I am using 3 Wyze Cameras with RTSP. All cameras work great. I have enabled motion detection with "share frame changes" and can see motion detecting.

My issue is with the web hooks. The webhook will only detect motion on 1 camera. When motioneye restarts all 3 cameras will send a webhook each but after that, the cameras will detect motion but a webhook will not be called. 

Configuration:

Camera1:
http://IPADDRESS/api/webhook/123456 (post form)

Camera2:
http://IPADDRESS/api/webhook/654321 (post form)

Camera3:
http://IPADDRESS/api/webhook/56789 (post form)

I have tried this with MQTT as well and get the same response. All MQTT commands fire for all 3 cameras on reboot. After reboot only 1 camera will notify on motion. I have tried switching the order of the cameras to confirm it is software and not hardware related. All cameras are able to send motion notifications, but regardless of the order, only 1 camera will work with motion notifications.

Is there a way to get all 3 cameras to continuously  call individual webhooks every time motion is detected?

**Comment by starbasessd** [comment]
Need to contact HASSIO Community Support for motionEye:
https://community.home-assistant.io/t/home-assistant-community-add-on-motioneye/71826
FRENCK has made changes and won't communicate them to us...
