### ISSUE TITLE
[Feature request] Sound alarm when motion is detected

### ISSUE THREAD

**Issue by ovz93br43v7** [ccrisan/motioneyeos#2617]
This is just a feature request:

I would like to see a feature for a sound alarm [connected to GPIO or USB] which is activated when a motion is detected to scare possible intruders.

**Comment by starbasessd** [comment]
You can play a mp3 file:
#2627 
Helps keep track of gradchildren in areas they're not allowed.
Just feed it to a PA speaker/Amplifier.
