### ISSUE TITLE
Port Forarding on BT HomeHub 5A

### ISSUE THREAD

**Issue by halfbyte-tech** [ccrisan/motioneyeos#262]
I am trying to set up port forwading on my BT HomeHub 5A, but i'm, not sure of what "Game or application" setting to use, and have tried various settings, but i'm not given the port nimber. **Help!**

**Comment by chrislongden** [comment]
Just create a new "game or application" that uses a random external port that points to internal port 80. Then just map your "device" to that "game or application".

Don't forgot to click on that device and state Yes to "Always use this IP address".
