### ISSUE TITLE
How send picture and video to telegram when trigger motion

### ISSUE THREAD

**Issue by SergeiCherevko** [ccrisan/motioneyeos#2622]
I want to send picture (screenshot of video) when triggering motion

I use section
 * Run an end command

 * `curl -s -X POST "https://api.telegram.org/botXXX/sendPhoto" -F chat_id="XXX" -F photo=%f`
But it's doesn't work
can anybody help with this?
![image](https://user-images.githubusercontent.com/17637953/103420540-d3817e00-4ba8-11eb-809c-42281b62a0a2.png)

**Comment by starbasessd** [comment]
You may want to put your command in a bash script and see if it works there. If it does, then call the command here. Also, you may need to put a delay of 1-2 seconds [sleep 2] befor the command to give motionEye a chance to create the file.

**Comment by SergeiCherevko** [comment]
I use this and it's works perfectly

https://github.com/DaniW42/motioneye-telegram

**Comment by skizzo** [comment]
Anybody's got an idea how to transmit the name of a created movie file?

**Comment by glowinthedark** [comment]
@skizzo in raw `motion` the file name is `%f` — motioneye is just eye candy on top of `motion` — the entire purpose of the app is to help you avoid manually editing `/etc/motion/motion.conf`, easily manage multiple cameras, etc, but otherwise you can do the same with just plain `motion`
