### ISSUE TITLE
Google Drive/Dropbox: "Accessing the upload service failed: !"

### ISSUE THREAD

**Issue by camilomarino** [ccrisan/motioneyeos#2623]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: dev20201026.

### Board Model

I am using the following board/model: Raspberry Pi Zero W.

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Raspberry Pi Camera Module v2.1

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi.

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

None

### Log Files

I consider the following log files relevant to this issue:
[motioneye.log](https://drive.google.com/file/d/1BWU-sNMRSNQ96komBGxjJsnudV9HIoyJ/view?usp=sharing)
[boot.log](https://drive.google.com/file/d/1Mt8HIuXktKYkWrel9cfcPMuwRaWLAVPt/view?usp=sharing)

### Issue
The problem I have is that when trying to configure Google drive as I show below:
![motioneyeproblem](https://user-images.githubusercontent.com/47334227/103446323-0c7b2a80-4c5d-11eb-9e43-839d0b4d38aa.png)

It shows me the message: "Accessing the upload service failed:!". I am sure that the "Camera" folder exists in my Google Drive and that the key obtained is correct.

Checking the [motioneye.log](https://drive.google.com/file/d/1BWU-sNMRSNQ96komBGxjJsnudV9HIoyJ/view?usp=sharing), it says:
```
2021-01-01 18:05:01: [motioneye] ERROR: gdrive: failed to obtain credentials: <urlopen error [SSL] ASN1 lib (_ssl.c: 727)>
2021-01-01 18:05:01: [motioneye] WARNING: accessing gdrive failed: <urlopen error [SSL] ASN1 lib (_ssl.c: 727)>
```
The exact same thing happened to me when setting up Dropbox.

**Comment by starbasessd** [comment]
Unable to reproduce in motionEyeOS 20190911, 20200606 or dev20201026 on Pi3B+ or Pi4-4GB with either service.

**Comment by starbasessd** [comment]
No response in >30 days. If you are still having issues, please open a new issue.
