### ISSUE TITLE
Problem connecting to a 5GHz WPA2 only network

### ISSUE THREAD

**Issue by LEONIDAS-0117** [ccrisan/motioneyeos#2638]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606

### Board Model

I am using the following board/model: Raspberry PI 3B+ and Raspberry PI 4B

### Camera

I am using the following type of camera: Simple MJPEG Camera

My camera model is: Raspberry Pi Camera Rev 1.3 (for the 3B+) and 5MP OV5647 (for the 4B)

### Network Connection

My motionEyeOS unit is connected to the network via: 5GHz WiFi with WPA2 (Only encryption method) and CCMP (Only Cipher method)

### My problem

I have being trying to connect to a 5GHz network that only admits WPA2 as Encryption method and CCMP as Cipher for the past few days.
In a fresh install the pi 3 and 4 connects with no problem to my 2.4GHz network that is also WPA2 and CCMP only, but not to the 5GHz network, only after specifing some parameters in the wpa_supplicant.conf i was able to connect to the 5GHz network.

Maybe this info can be added to the Wiki for the [Wifi Preconfiguration](https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration) section.

This is the wpa_supplicant.conf that worked for me:

```
country=AR
update_config=1
ctrl_interface=/var/run/wpa_supplicant
        
network={
    scan_ssid=1
    ssid="network-name"
    psk="password"
    proto=RSN
    key_mgmt=WPA-PSK
    pairwise=CCMP
    group=CCMP
    auth_alg=OPEN
}
```
If not sure what Cipher is being used you can edit:
```
pairwise=CCMP
group=CCMP
```
to
```
pairwise=CCMP TKIP
group=CCMP TKIP
```

**Comment by starbasessd** [comment]
Noted for documentation.
