### ISSUE TITLE
Porting to another controller with SD slot

### ISSUE THREAD

**Issue by Saiberion** [ccrisan/motioneyeos#264]
What are the necessary steps to port motioneyeos to another controller and how can I use the rootfs created by buildroot (without build.sh) as I need to create an UBI image with everything included and no SD card slot available.

**Comment by ccrisan** [comment]
That's a BuildRoot question, not a motionEyeOS question. Porting motionEyeOS to another board can be done by copying the board/[some_existing_but_similar_board] folder to board/[some_new_board]. You'll also need to copy the configs/[some_existing_but_similar_board]_defconfig to configs/[some_new_board]_defconfig.
