### ISSUE TITLE
My Raspberry Pi4 4GB won't boot

### ISSUE THREAD

**Issue by TorbenRaspberryPi** [ccrisan/motioneyeos#2644]
i have installed the Os using the Raspberry Pi Imager Software using the custom .img selection but when i put it onto the raspberry pi it gets stuck in a loop in the boot loader screen.

**Comment by starbasessd** [comment]
Install RaspberryPiOS on SDCard
Insert in Pi4 and boot.
Run the following commands:
sudo apt update && sudo apt full-upgrade -y
sudo reboot
Run further commands:
sudo rpi-eeprom-update -y
sudo reboot
confirm eeprom is now Sep 2020 or newer:
sudo vcgencmd bootloader-config
If it is, then you should be good to go, if you have ethernet connected. If you want wifi, then you need to add the wpa_supplicant.conf file to the 30MB /boot partition.
