### ISSUE TITLE
where do I find the meye-xxxxxxxx boot login?

### ISSUE THREAD

**Issue by stavropn** [ccrisan/motioneyeos#265]
I have tried to boot but always stuck to boot login. Where can I find username and password for boot login?
Than you

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#command-line--shell-access,  https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-am-only-getting-white-on-black-text-on-my-monitor-where-is-my-ui and https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-are-the-default-web-ui-credentials.

**Comment by stavropn** [comment]
Thank you for your prompt answer but I still do not understtand. The program does not boot for all the above to happen.

**Comment by al090187** [comment]
How do you know the program has not started?

**Comment by stavropn** [comment]
it keeps asking for login

**Comment by al090187** [comment]
On what? Are you trying to SSH in, or on the webpage?

**Comment by al090187** [comment]
In either case, the default username is admin, with a blank password, as given in the third link ccrisan posted about an hour ago.

**Comment by stavropn** [comment]
it keeps saying wellcome   meye-18f00912 login:

**Comment by al090187** [comment]
Have you tried admin?

**Comment by stavropn** [comment]
yes 
thank you
