### ISSUE TITLE
Will the new CSI RPI camera v2 module work?

### ISSUE THREAD

**Issue by ReonBalisty** [ccrisan/motioneyeos#267]
Will the new CSI RPI camera module v2 work with RPI 3 with the Motion Eye OS?

**Comment by ReonBalisty** [comment]
Specifically the NoIR camera module

**Comment by ccrisan** [comment]
No idea :) I'd have to get one myself but I suppose the worst case scenario is a RPi firmware update requirement which I'll be happy to do.

**Comment by chumleybob** [comment]
just tried the new v2.1 camera and the image does not look as good as the old 5mp one 

also its upside down and mirror by default

**Comment by ReonBalisty** [comment]
Ordered both will post image differences once I get the old and new set up.

**Comment by deruiter** [comment]
I'm using a RPi 3 and the V2 camera. 

Very sad to see the image mirrored nd no option to correct it.

**Comment by cjmair** [comment]
I found that using the command :-
v4l2-ctl --set-ctrl horizontal_flip=1
via a SSH terminal connection, changed the image to be the correct way

regards
Colin

**Comment by cjmair** [comment]
I also added the command
v4l2-ctl --set-ctrl horizontal_flip=1
to the file /etc/rc.local just before the exit 0 line, to ensure that the command was run at every reboot
Sure there must be a better way, but it works :-)

**Comment by pieterpoorthuis** [comment]
I have a Raspberry Pi model 3B with the v2 camera. Problem is that motioneye doesn't recognize the camera. I'm sure the v2 camera works, because other tools like Rpi cam web interface do work with this camera.
I ran rpi-update, so my system is up to date. Motion eye shows the following screen:
![image](https://cloud.githubusercontent.com/assets/13945200/15138177/74e57080-168e-11e6-9a4c-b2bebd5f0515.png)

Any idea how to get my v2 camera working in motioneye?

**Comment by ccrisan** [comment]
If you ran `rpi-update` and it succeeded, you are probably running Raspbian with motionEye, not motionEyeOS. If you run Raspbian, make sure you have loaded the `bcm2835-v4l2` module.

**Comment by pieterpoorthuis** [comment]
thanks, the v2 camera now works. Setted resolution at 1600x1200, motion uses 40% cpu... quite steep

**Comment by olavt** [comment]
What was the trick to get the v2 camera to work with the MotionEyeOS? I get the "(no cameras)" message.

**Comment by pieterpoorthuis** [comment]
Run rpi-update, followed by modprobe bcm2835-v4l2

On Mon, May 30, 2016 at 9:34 PM, olavt <notifications@github.com> wrote:

> What was the trick to get the v2 camera to work with the MotionEyeOS? I
> get the "(no cameras)" message.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ccrisan/motioneyeos/issues/267#issuecomment-222545128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANTJcDlA_o6q3hnaet6xdAhSsiagT0nWks5qGzvigaJpZM4IPdXe>
> .
>



-- 
Pieter Poorthuis
+31 6 43497969 / Skype: pieter.poorthuis
Senior Sales Engineer
BitPay Europe BV
https://www.bitpay.com

**Comment by olavt** [comment]
Got "command not found" on "rpi-update"

**Comment by ccrisan** [comment]
@olavt wait for the next motionEyeOS update. I'm working on it :)

**Comment by Renader** [comment]
Hello @ccrisan, thanks for your great work. Is the v2 camera now running with MotionEyeOS? 
I'm new to this and not familiar with motionEye. If the v2 camera doesnt work yet with MotionEyeOS, can i simply use https://github.com/ccrisan/motioneye on rasbian to get the same surveillance features?

**Comment by ccrisan** [comment]
It does.

**Comment by nextgen1979** [comment]
Hello , i have the same issue with motionEyeOS  , i have the motioneyeos-raspberrypi3-20160703 version and one v2 camera.   and Local Camera  - no camera .  what the solution ?

Thanks in advance

**Comment by ccrisan** [comment]
@nextgen1979 does it work with Raspbian?

**Comment by nextgen1979** [comment]
i dont have try for the moment , have try only with motioneye OS. I will try tomorrow with raspbian and motioneye application.

**Comment by ccrisan** [comment]
Please try raspbian and the raspistill/raspivid applications, just to be able to rule out a faulty camera or any other hardware-related issue.

**Comment by nextgen1979** [comment]
ok i will try this tomorrow and keep you inform .  thnks for this great app and os  :)

**Comment by nextgen1979** [comment]
Hello, i have make a mistake with the cable of the camera . Sorry .  And thanks for your help and support.

**Comment by ian6301** [comment]
I have a clean install of the latest version of MotionEyeOS on my RPi3 and it won't recognise my v2 Pi Camera...

Did this definitely get fixed in the end?

I have checked the camera with Raspbian and it works fine, so not a hardware issue...?
