### ISSUE TITLE
LD_PRELOAD=/usr/lib/v4l2convert.so

### ISSUE THREAD

**Issue by ivityc** [ccrisan/motioneyeos#269]
Hi 
I used motion previously with RPI3 and a Creative USB Webcam. To have it working I had to start the process with the  "LD_PRELOAD=/usr/lib/v4l2convert.so" before it.

Is there a way to configure motioneye to do the same ?
I tried to modify the /usr/bin/meyectl file and motion file with no luck

Thanks for your support
Iv

**Comment by ivityc** [comment]
Ok I managed to edit the /etc/init.d/S85motioneye
adding the following lines and now the webcam works fine

  LD_PRELOAD=/usr/lib/v4l1compat.so
  export LD_PRELOAD

**Comment by djtale** [comment]
Hello @ivityc , do you remember where in S85motioneye you put those lines ?

That would help me a lot.

**Comment by ivityc** [comment]
hi, I do not remember exactly, but I think it was quite at the beginning of the file right after the line
#!/bin/bash
