### ISSUE TITLE
RSTP BUG after many hours - Pixel View

### ISSUE THREAD

**Issue by philou15** [ccrisan/motioneyeos#2691]
Hye 
I HAvez a bug on wascam CCTV 

Then i configure it ok, but after manu hours, the picture it not good. 
i take the rstp flux 
rtsp://IP:554/1
1280*720

Like this

![Capture](https://user-images.githubusercontent.com/11060597/110215705-7d340280-7eab-11eb-952c-24e65aaed131.JPG)

Do you have any idea ? 
tks

**Comment by starbasessd** [comment]
No comments. I couldn't find any info on WASCAM CCTV. If you are still looking for help, Post your Manufacturer and specific model for the camera. Some generic help includes using UDP instead of TCP, and see if the camera supports an rtmp:// connection.
