### ISSUE TITLE
Network Share Works but doesn't

### ISSUE THREAD

**Issue by ShosMeister** [ccrisan/motioneyeos#2709]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: motionEyeOS 20200606.

### Board Model

I am using the following board/model: RPi Zero (2) and RPi 3B+.

### Camera

I am using the following type of camera: MMAL

My camera model is: RPi v2.

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi.

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * USB External Hard Disk)

### Log Files

Share is setup on the hub
![Screen Shot 2021-03-27 at 12 46 53 PM](https://user-images.githubusercontent.com/10685152/112727826-a409b580-8efa-11eb-85f2-cbf384b62d30.png)

Have 2 RPi Zeros w/cameras. RPi 2 works for the network share
![Screen Shot 2021-03-27 at 12 47 07 PM](https://user-images.githubusercontent.com/10685152/112727836-b5eb5880-8efa-11eb-9c59-a2a25b6e7780.png)
 
RPi 1 does not - fails setting from web UI.
![Screen Shot 2021-03-27 at 12 47 26 PM](https://user-images.githubusercontent.com/10685152/112727849-c8659200-8efa-11eb-9393-6c6592b187e8.png)

Manually mounting the same point from command line (SSH) works.
![Screen Shot 2021-03-27 at 12 49 45 PM](https://user-images.githubusercontent.com/10685152/112727867-f77c0380-8efa-11eb-9ed3-dde16a6c8d76.png)

Once there, I can use the custom path file storage from the web UI and it does save images there.

I don't mind if I need to have it set using custom path rather than network share but if I reboot, the mount point will be gone and have to be manually remounted before the camera will work again.

From the motioneye.log after I try to test the connection from web UI:
2021-03-27 12:52:00: [motioneye]    ERROR: failed to mount smb share "//172.20.15.220//storage/sda1/MEye-01.d" at "/data/media/motioneye_172_20_15_220__storage_sda1_meye_01_d_admin"
2021-03-27 12:52:00: [motioneye]    ERROR: access to network share //172.20.15.220//storage/sda1/MEye-01.d failed: cannot mount network share

Options? Suggestions?

**Comment by starbasessd** [comment]
Rpi0-2 doesn't have the leading / for share name, Rpi0-1 does have a leading / for the share name.
which causes the error:
2021-03-27 12:52:00: [motioneye] ERROR: failed to mount smb share "//172.20.15.220//storage

**Comment by ShosMeister** [comment]
Got it. Thanks!

**Comment by starbasessd** [comment]
Glad to help. Sometimes you can't see the forest for the trees...
