### ISSUE TITLE
Whitelist IP bypass user/viewer login

### ISSUE THREAD

**Issue by emosbek** [ccrisan/motioneyeos#271]
Got Raspbian running browser in kiosk mode and need it to automatically preview my MotionEye without login request.
Is there a way  to add/whitelist a local ip to bypass the login request?

Thanks

**Comment by al090187** [comment]
When I log into mine it doesn't ask for a login, unless I click to change user. Have you set a password for the standard user as well as admin?

**Comment by emosbek** [comment]
I have password for both admin and user account. this is necessaryfor my setup, but a whitelist function would help a whole lot
