### ISSUE TITLE
Pi3 and second Wlan device

### ISSUE THREAD

**Issue by gvet** [ccrisan/motioneyeos#272]
Hej,
I am trying to permanently deactivate the embedded Pi3 wlan device and use an external rtl8712u USB WLAN adapter.
I get the following error: netdev:wlan0 already exists

Can anybody give help?

**Comment by ccrisan** [comment]
Starting with 20160801 (hopefully released sometime tomorrow), you'll have the possibility to blacklist modules using `/data/etc/modprobe.conf`. More details [here](https://github.com/ccrisan/motioneyeos/wiki/Tweaks#loading-custom-modules-at-startup).

You'll probably want to add `blacklist brcmfmac` to `/data/etc/modprobe.conf`.
