### ISSUE TITLE
[Question] Is motioneye still maintained?

### ISSUE THREAD

**Issue by RicardoCst** [ccrisan/motioneyeos#2722]
Not to be rude but there has not been any commits anymore since 2020, im just curious if its still being maintained.

**Comment by starbasessd** [comment]
Yes, it is being maintained. Some programmers have lives, there's been a pandemic going on, Real Life(TM) can step in the way, etc. 
I do my part to support it, too.

**Comment by RicardoCst** [comment]
I know programmers have lives and I respect the programmers working on motioneye, but I was just curious because a lot of software vanishes / stops being maintained without the end user noticing.

Anyways, thanksfor answering my question and the best of health to you!

**Comment by starbasessd** [comment]
If they stopped maintaining it, they forgot to tell me, and forgot to turn off the lights...
