### ISSUE TITLE
No  images  Error mjpg client timed out receiving data on port 8081

### ISSUE THREAD

**Issue by mwy6283** [ccrisan/motioneyeos#2735]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version Thru docker 
[_motioneye_logs.txt](https://github.com/ccrisan/motioneyeos/files/6450410/_motioneye_logs.txt)

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

### Board Model PI 4 4g 

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

### Camera Reolink 410 5mp

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera). Network

My camera model is: (insert your camera model, e.g. Logitech C290).

### Network Connection  LAN
My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).

### Peripherals POE 

I am using the following peripherals that I consider relevant to this issue:
 External hard Drive
 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by starbasessd** [comment]
This would be more appropriate on https://github.com/ccrisan/motioneye/issues
What do you use for docker run command?
Are you using portainer or other wrapper?
Are you using HomeAssistant or other base?

**Comment by starbasessd** [comment]
This would be more appropriate on https://github.com/ccrisan/motioneye/issues
What do you use for docker run command?
Are you using portainer or other wrapper?
Are you using HomeAssistant or other base?
If no response, closing.

**Comment by starbasessd** [comment]
No response
