### ISSUE TITLE
images not uploading to Google drive on one of my multiple cameras - all the rest are fine

### ISSUE THREAD

**Issue by Hambo1946** [ccrisan/motioneyeos#2736]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version 20200606

I am running motionEyeOS version:20200606
### Board Model

I am using the following board/model: Raspberry Pi zero wh

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Raspberry Pi NOIR Camera Module V2

### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).
WiFi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:
Photos saved to a windows share via SAMBA
 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. mo
[boot.log](https://github.com/ccrisan/motioneyeos/files/6473302/boot.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/6473304/motioneye.log)
[motion.log](https://github.com/ccrisan/motioneyeos/files/6473305/motion.log)

tioneye.log)
 * (attach e.g. boot.log)

**Comment by starbasessd** [comment]
Please answer the questions and include the messages and motioneye logs.

**Comment by Hambo1946** [comment]
[messages.log](https://github.com/ccrisan/motioneyeos/files/6473338/messages.log)
I have 4 cameras on Raspberry Pi zeros all working perfectly with the latest version of MotionEyeOS and all are storing images on different windows shares perfectly. However this particular one will not upload anything to Google drive and all the others do. Can anyone offer some suggestions? The camera is in a rather inaccessible place so I would rather not re-image and start from the beginning if I can help it!

Thanks in advance

Graham

**Comment by starbasessd** [comment]
The motioneye log is showing it can't find the file to upload.
If you can ssh into the Pi in question, check free space on /data partition (df -h)
Compare the other settings for the gdrive upload to ones that work.

**Comment by Hambo1946** [comment]
Hi I looked at the motioneye log and found the entry below. Is this what
you are referring to? I am not very familiar with linux but I am assuming
'/data/media/motioneye_192_168_0_201_public_hambopics_intrays_rpinoir_xbmcuser1/2021-05-13/2021-05-13'
means at there is a link from the raspberry pi to the windows share at
\\192.168.0.201\public\hambopics\intrays\rpinoir. I can see lots of images
using WINSCP on the raspberry pi and assume it is mounting to this
directory. If this is the case, I can confirm that all my other cameras
store their photos on the various subdirectories on the share
\\192.168.0.201\hambopics\intrays and they all work. The share is some
1.16Tb of free space

OSError: [Errno 2] No such file or directory:
'/data/media/motioneye_192_168_0_201_public_hambopics_intrays_rpinoir_xbmcuser1/2021-05-13/2021-05-13'
2021-05-13 16:24:11: [motioneye]    ERROR: failed to upload file
"/data/media/motioneye_192_168_0_201_public_hambopics_intrays_rpinoir_xbmcuser1/2021-05-13/2021-05-13"

**Comment by starbasessd** [comment]
I understand that your camera is in a difficult to access location, but my recommendation is to back up the settings, and re-image and restore the settings. 
You didn't post the messages log, and didn't post the df -h for that PI, I cannot continue diagnostics. Maybe someone else can.

**Comment by Hambo1946** [comment]
Hi,

Here is a screenshot of df -h. I tried to do df -h > df.txt but it sais it
was a read only filesystem

**Comment by Hambo1946** [comment]
![df -h](https://user-images.githubusercontent.com/25013619/118152661-df116b00-b40c-11eb-86b6-dcb2b9f60622.jpg)

**Comment by Hambo1946** [comment]
@starbasessd
There doesn't seem to be a messages.log file but I have renamed the messages file to messages.log. Hope this is what you asked for 
[messages.log](https://github.com/ccrisan/motioneyeos/files/6473646/messages.log)

 there is one called messages which I renamed to messages.log

**Comment by Hambo1946** [comment]
[messages.log](https://github.com/ccrisan/motioneyeos/files/6473655/messages.log)

**Comment by starbasessd** [comment]
Where do your cameras that work save files?
Settings, File Storage, Storage Device & Root Directory?
How about the Camera with issues?
If you change the Camera with issues to 
Settings, File Storage, Storage Device: Custom Path
and Root Directory: /data/output/Camera1
and leave the File Uploads:  GDrive alone, does it work?

**Comment by Hambo1946** [comment]
[messages.log](https://github.com/ccrisan/motioneyeos/files/6473666/messages.log)

**Comment by Hambo1946** [comment]
@starbasessd All the cameras store the files as folders onderneath a common location. Here is ascreenshot of the RPI with the issues. All cameras have folders beneath hambopics\intrays

 [
![networkShare](https://user-images.githubusercontent.com/25013619/118154812-6bbd2880-b40f-11eb-9799-cc1cdb52fa58.jpg)

](url)

**Comment by Hambo1946** [comment]
![NetworkshareNoIssues](https://user-images.githubusercontent.com/25013619/118155337-0c134d00-b410-11eb-9099-0c6176214cbe.jpg)

Here is the screenshot of one of the other cameras with no issues

**Comment by Hambo1946** [comment]
I'll have a go at your suggestion of saving the images on the SD card now

**Comment by Hambo1946** [comment]
No that drew a blank I am afraid. The pictures were successfully loaded but the Google  part produced no uploads just as before. Screenshots attached
![localNetworkShare](https://user-images.githubusercontent.com/25013619/118156962-e129f880-b411-11eb-9e42-3f724f6602b5.jpg)

![captured_images](https://user-images.githubusercontent.com/25013619/118157054-fb63d680-b411-11eb-97a8-8af9d0f1a53a.jpg)

**Comment by starbasessd** [comment]
Does Test Service work?

**Comment by starbasessd** [comment]
And does /RoofCamera/ exist at the root of your GDrive?

**Comment by starbasessd** [comment]
Also ssh in, and run 
logrotate -f /etc/logrotate.conf
the repost the logs after trying to upload again.

**Comment by Hambo1946** [comment]
Yes the test service works on all cameras. /RoofCamera/ does exist at the root. I have tried to change its name as well on a number of occasions. The test service always works and I can go into GDrive an manually copy images into it but nothing ever is uploaded from MotioneyeOS for this particular camera.

I shall now run logrotate and post you the logs

**Comment by starbasessd** [comment]
testing uploads from a PC or MAC doesn't mean it's set up for the Pi.

**Comment by Hambo1946** [comment]
No I meant going into Google drive on the PC to see if images were uploaded. I have carried out this course of action for all the otyher pi cameras. It's just this one which has never been able to uploaded iamges to Google.

Here are the new files. I have also rebooted the Motioneyeos

[motioneye.log](https://github.com/ccrisan/motioneyeos/files/6474001/motioneye.log)

[messages.log](https://github.com/ccrisan/motioneyeos/files/6474004/messages.log)

**Comment by Hambo1946** [comment]
Just to make clear. The Google test service works on all my raspberry pi Motioneye cameras. 
Here is a screenshot showing no files are uploaded to the Google drive folder 
![Google_drive](https://user-images.githubusercontent.com/25013619/118166315-3cadb380-b41d-11eb-9d96-e58b4d8a08d4.jpg)

**Comment by Hambo1946** [comment]
@starbasessd 
Yes the test service works on all cameras. /RoofCamera/ does exist at the root. I have tried to change its name as well on a number of occasions. The test service always works and I can go into GDrive an manually copy images into it but nothing ever is uploaded from MotioneyeOS for this particular camera.

I shall now run logrotate and post you the logs

**Comment by Hambo1946** [comment]
@starbasessd 
[messages.log](https://github.com/ccrisan/motioneyeos/files/6474357/messages.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/6474358/motioneye.log)

**Comment by Hambo1946** [comment]
@starbasessd 

Still no luck with the Google upload I am afraid
![Google_drive](https://user-images.githubusercontent.com/25013619/118169755-36b9d180-b421-11eb-9c41-93a5205b17b4.jpg)

**Comment by Hambo1946** [comment]
@starbasessd 

Please find the new logs after I tried to upload to Google
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/6474385/motioneye.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/6474386/messages.log)

**Comment by Hambo1946** [comment]
@starbasessd 

Looking at the motioneye.log, it seems I have the exact same message when the target is /data/output/Camera1 as I had when the images were stored on my windows share

extract from Motioneyeos.log

2021-05-13 18:48:58: [motioneye]    ERROR: failed to upload file "/data/output/Camera1/2021-05-13/2021-05-13" with service gdrive: [Errno 2] No such file or directory: '/data/output/Camera1/2021-05-13/2021-05-13'
 but that directory does exist and the files are clearly visible in the screenshot below
![captured_images](https://user-images.githubusercontent.com/25013619/118171014-b6946b80-b422-11eb-9a5f-c5121ab52c92.jpg)

**Comment by starbasessd** [comment]
I understand that your camera is in a difficult to access location, but my recommendation is to back up the settings, and re-image and restore the settings.

**Comment by Hambo1946** [comment]
@starbasessd 

Thank you. I took your advice and did a fresh install which cleared the problem. Thank you for all your help - much appreciated :-)
