### ISSUE TITLE
Lens correction for wide angle lenses

### ISSUE THREAD

**Issue by joshlukas** [ccrisan/motioneyeos#274]
Hello,

just wanted to know if there is any possibility to do a lens correction for wide angle/fisheye lenses, so the image isn't distorted that much. Could not find anything related to motion on how to do that. Maybe the Pi is not fast enough to do that job on-the-fly?

Greetings and as always. Good job with motioneyeos.

Lukas

**Comment by ccrisan** [comment]
Nope. I don't think that is supported by motion.

**Comment by Genestealer** [comment]
Two years on, I just wanted to ask if wind angle lense correction is supported?
