### ISSUE TITLE
So Lemme get this straight.... the answer was

### ISSUE THREAD

**Issue by Davidleebjr** [ccrisan/motioneyeos#2745]

**Comment by Davidleebjr** [comment]
I don't know how to get motioneye to boot from usb and I don't care if it gets fixed....   is that the answer i read from 8 or 9 months ago from the developer?

**Comment by starbasessd** [comment]
No. You can boot to USB with Raspberry Pis using the appropriate dev20201026, and changing the default boot partition file cmdline.txt entry from 
root=/dev/mmcblk0p2 
to 
root=/dev/sda2
before first boot. Don't forget to add the wpa_supplicant.conf and ssh.txt files if wanted/needed

**Comment by starbasessd** [comment]
It is a work in progress.

**Comment by Davidleebjr** [comment]
Thanks.. i just got enlightened to this... I just need a simple viewer for the basement workroom to monitor front door and side porch...  correct assumption that motion eye is the best solution????

**Comment by starbasessd** [comment]
Best? Can't say. Watching 2 cameras is very doable. You didn't post any other information from the questions asked in the opening page. You just made a rude comment/question.
