### ISSUE TITLE
Auto-deletion of pictures

### ISSUE THREAD

**Issue by Github197** [ccrisan/motioneyeos#2746]
I setup the motioneye camera to make a picture every x minutes. When the picture is taken it is automatically uploaded to my NAS and would not be needed anymore on the camera. Due to the limited card memory the card storage is filled up quite quickly. I would like to have an option which is automatically deleting the old pictures. It would be enough to have a cronjob running every day to delete all pictures under /data/output/Camera1/ like rm -R /data/output/Camera1/20*, but I am not able to write to the file /etc/crontabs/root.

Is there any other solution how to do it or could there be an option integrated in the web GUI that pictures will be deleted after the successful upload to e.g. FTP?

Thank you, René

**Comment by starbasessd** [comment]
If your NAS is capable of SMB/CIFS, you can do the primary creation of the files there by changing: Settings, Files Storage, Storage Device, Network Share, and set the SMB/CIFS share. Then you don't have to worry about storage.
As to running a cron job, SSH or use the console (monitor/keyboard) and follow the instructions here:
https://github.com/ccrisan/motioneyeos/wiki/Tweaks#running-commands-at-regular-intervals-cron-support

**Comment by starbasessd** [comment]
If you have further questions, please answer the questions for the system when you opened the ticket.

**Comment by Github197** [comment]
Thank you that helped!
