### ISSUE TITLE
Camera stops when use SMB

### ISSUE THREAD

**Issue by bazcurtis** [ccrisan/motioneyeos#275]
Hi,

After the update to 20160410 I can now use SMB to my Mac running 10.11.4. This was issue #160. The dated folder is made in the share and video is put in that folder, but after about 10 minutes the camera will disappear. As soon as I switch back to local storage the camera will return.

What information can I send to help find the issue?

Best wishes

Michael

**Comment by bortek** [comment]
try the latest build.
