### ISSUE TITLE
Video stream quality

### ISSUE THREAD

**Issue by jagauthier** [ccrisan/motioneyeos#2753]
### motionEyeOS Version

I am running motionEyeOS version: 0.42.1

### Board Model

I am using the following board/model:  Debian 10

### Camera

I am using the following type of camera: Simple MJPEG 

My camera model is: Axis 211 and also Samsung J7 with "IP webcam"

### Network Connection

My motionEyeOS unit is connected to the network via: Wired Ethernet 100M

I recently took an old phone Samsung Galaxy J7 and put streaming IP webcam on it.  It has been pretty stable, and I can access the video stream over IP:8080/video and even at it's highest resolution it looks great.

I tried to add this to motioneye and the performance is very poor.  I lowered the resolution and quality quite a bit (1280x720) and it's still quite slow to watch the live stream.

Any suggestions on improvement?

**Comment by starbasessd** [comment]
Need the motionEyeOS version:  (like 20200606 or dev20201026)
Need which Pi or other board you are running (Like Pi3B+ or 4B-4GB or Odroid)
You can turn off some features, or lower the resolution to speed things up. 
What is the stream type? mjpeg is slower than rtsp://.

**Comment by jagauthier** [comment]
I'm not using MotionEyeOS.  I'm using straight Debian 10 in a Virtual Machine on an 8 core i7-9700K CPU @ 3.60GHz with 2 processor allocations to the VM and 4G RAM.

It is mjpeg. Not sure if it support rtsp.    I'll have to check and see.  
But, I did lower the resolution (I can lower it more to test)

**Comment by starbasessd** [comment]
Sorry, you created this ticket in the motionEyeOS issues, not the motionEye issues.
https://github.com/ccrisan/motioneye/issues
On my production hub (i5/16GB/1TB) and my Ubuntu 20.04 LTS VM (4CPUs/4GB/50GB/2TBNAS) I have 6 cameras (3 d-Link DCS-5020-L (mjpeg 800x600), 2 Foscam (rtsp: 1280x720) and USB Generic Dashcam 1024x768)) for testing and I avg 15-20 FPS per camera streaming to http://ip_address:8765 WebGUI.

**Comment by jagauthier** [comment]
Oh, I suck. Sorry about that!

That is quite strange then.  I know the performance is there because when I look at it over the web interface it's amazing.   My older two cameras are pretty old, so I expect it from them.  I will continue to experiment with the settings!

**Comment by starbasessd** [comment]
The only reason I point it out is because they can be very different, and solutions for one might not work for the other, and you can find lots of solved issues in the right category.
