### ISSUE TITLE
No more video in chrome since update on R91 (fine on Firefox)

### ISSUE THREAD

**Issue by kduytsch** [ccrisan/motioneyeos#2754]
I tried the lazy loading image trick, but seems that the flag is no more available on this R91 version

**Comment by starbasessd** [comment]
Windows 10:
Google Chrome is up to date
Version 91.0.4472.77 (Official Build) (64-bit)
Works with motionEye 0.41
motion 4.3.2-1
on Ubuntu 20.04 LTS

**Comment by starbasessd** [comment]
Same Chrome,
RPi3B+


motionEye Version | 0.42.1
Motion Version | 4.3.1
OS Version | motionEyeOS dev20201026
works fine

**Comment by starbasessd** [comment]
If you have any specific set to test, I can do lots of different combinations.

**Comment by kduytsch** [comment]
I'll go for a fresh install with motionEyeOS, probably better

**Comment by kduytsch** [comment]
ok, motionEyeOS is installed, but impossible to get a static IP. Each time I run the S40Network script, I end up with a DHCP address, any idea ?

**Comment by starbasessd** [comment]
In the  WebGUI, in Network, Change IP Configuration from DHCP to Static and fill in the information. If you are using Ethernet instead of WiFi, change Wireless Network to Off, and you can change IP Configuration from DHCP to Static and fill in the information.
My Preferred  method, however is to enable a static IP in the router's DHCP to issue the static IP address there, that way if there is a network issue, you can still get it to boot normally and pull an address, instead of having to jump through a bunch of hoops to try to recover connectivity.

**Comment by starbasessd** [comment]
Out of curiosity, where are you getting your setup instructions?

**Comment by kduytsch** [comment]
I found it easier to do it via GUI indeed. Setup instructions from https://github.com/ccrisan/motioneyeos/wiki/Tweaks#manually-editing-network-configuration

Now, I have GUI up and running, however, I can't import my config from old setup... And can't add my cameras as they say not supported. I was expecting to be able to copy overt the thread<x>.conf file

**Comment by starbasessd** [comment]
No, to 'import' you need to do a backup on the old setup, then restore to the new setup, under the WebGUI.
What camera(s) are you trying to set up, and how are you trying to set them up? 
What  Camera Type (Local V4L2, Local MMAL, Network, Remote MotionEye, or Simple MJPEG)
If Network, Remote, or MJPEG, what are you using for the URL?

**Comment by kduytsch** [comment]
Import didn't work from the backup, probably because not same version

So I'm trying to re-setup everything from the thread file I have in the backup

All my cameras are IP cam, the URL from the thread are 
netcam_url http://192.168.0.30:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2
netcam_url rtsp://192.168.0.31:554/live/ch0
netcam_url rtsp://192.168.0.32:554/live/ch0

**Comment by starbasessd** [comment]
Sorry, I don't see camera manufacturer(s) and model(s) on this thread.
The camera setup files are camera-1.conf files in the modern (newer than 20190911)
In motionEyeOS the files are located in /data/etc
It is best to use the WebGUI to add cameras.

**Comment by kduytsch** [comment]
well, I'm using cheap chinese camera, no brand there. They have been working since the begining with motion/motionEye

Even on motion website they claim the RSTP format would allow to support any kind of camera

I have now copied the thread.conf into camera.conf and I can see my cameras again. Just seems to be some issue with the "add Camera" command

**Comment by starbasessd** [comment]
"Even on motion website they claim the RSTP format would allow to support any kind of camera"
Not exactly. They (motion-project) can support any Valid (follows the standards) RTSP format camera. I have 2 Foscam rtsp cameras and even they don't use the same output URL. One is 
rtsp://ip_address:88/videoMain
and the other is
rtsp://ip_address/video.mp4
when the 'standard' is rtsp://ip_address:554/(path)
Glad to hear you are up. Please close if resolved.

**Comment by kduytsch** [comment]
not, don't take me wrong. What I wanted to say is that the interface even didn't allow me to enter a RTSP address (error with libcurl)

For the rest, I'm very happy with the interface, thank you for your work

I'm closing as I finaly can see my cameras in Chrome, the rest of the setup will now continue

**Comment by starbasessd** [comment]
Ignore the error, this is just a sample screenshot of how to add your camera
netcam_url rtsp://192.168.0.31:554/live/ch0

![image](https://user-images.githubusercontent.com/20134429/121542711-5d463a80-c9d6-11eb-9148-b662f1f90d5c.png)

**Comment by kduytsch** [comment]
well, I had an issue with libcurl saying rtsp wasn't enabled or so
