### ISSUE TITLE
Local Camera not detected 

### ISSUE THREAD

**Issue by lexhick** [ccrisan/motioneyeos#2755]
Hi !
I'm a new user of openeyeOS dockerised with portainer ans I can't get my local camera (ribbon type ) to be recognised by openeye.
The camera is ok with raspian .
I've tested "vcgencmd get_camera" > supported=1 detected=1
And I get video with "raspistill -o testshot.jpg"
My pi is a Pi4B , Raspian 5.10.17, OMV 5.6 (Usul), openeyeOS 0.42.1

Can you help me please ? thanks

**Comment by starbasessd** [comment]
It would have been better to use the 
https://github.com/ccrisan/motioneye/issues
where we just solved that issue.
https://github.com/ccrisan/motioneye/issues/2136
