### ISSUE TITLE
Failed Boot with Raspberry Pi 4 Motioneyeos Release version: 20200606

### ISSUE THREAD

**Issue by ThePandyMan** [ccrisan/motioneyeos#2760]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606.

### Board Model

I am using the following board/model: Raspberry PI 4.

### Details

Two files included with the disk image (start4.elf and fixup4.dat) are outdated and cause failed boot using the image provided on the supported devices page.

### Solution

* Extract the two files (start4.elf and fixup4.dat) from the May 7th 2021 release of "Raspberry Pi OS with desktop" on the official raspberry pi website. 
* Replace the two files included with the Motioneyeos (version 20200606) release with the newly extracted files
* This solves the boot failure.

**Comment by starbasessd** [comment]
The issue with that is USB cameras don't work. It is a posted resolution here already. dev20201026 resolves the issue correctly, and as an added benefit, enables USB Boot with the latest rpi-eeprom-updates applied. The instructions are posted in other Issues here, too.
