### ISSUE TITLE
Optimal setup to maximize FPS in movies.

### ISSUE THREAD

**Issue by fujinjr** [ccrisan/motioneyeos#2774]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190911.

### Board Model

I am using the following board/model: Raspberry PI 3B+, Raspberry PI 0w.

### Camera

I am using the following type of camera: Fast Network Camera.

My camera model is: Raspberry Camera PI V2 8 MP.

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi.
 

I'd like to know if my current setup is optimal in order to maximize FPS in movies.
I attached two images, any opinion? 
Am I using the FNC and RTSP correctly?

![pi0w](https://user-images.githubusercontent.com/37943766/125850606-96208eae-ee1e-4203-9023-5ac045c7d884.PNG)
---
![pi3](https://user-images.githubusercontent.com/37943766/125850623-647efd76-808c-47c5-937e-4e0587f93f85.PNG)

**Comment by starbasessd** [comment]
I would upgrade your motionEyeOS to 20200606 or dev20201026, rather than use any 2019 version. There were a number of updates and changes since then.

**Comment by cap9qd** [comment]
I would try setting movie pass through on your RPi3B+ instead of omx-h264.
The RPi-0W is encoding the video in hardware to h264 so you shouldn't need
to reencode the stream. Motion daemon on the RPi3B+ will still have to
decode it to do the motion detection but doing pass through might lower
your load. I am not sure this will help you much with fps.

I found if the video was low enough resolution (<1080p) I had better
performance (in terms of CPU load on my motioneyeos server) by leaving my
RPI-0W FNC setup as a mjpeg stream and using the hardware encoder on my
odroid server to encode to h264. I found this recommendation on the motion
project forum that motion deals well with jpegs for the motion detection
algorithm and motion does not hardware accelerate the decode of h264 so the
CPU load takes a hit. Of course I can't find the post now when I need it
but worth a try.

This work was in terms of getting my CPU load down to support more cameras
on my one server so may not be the advice you are looking for here.

**Comment by starbasessd** [comment]
@cap9qd Be aware that you lose text overlays (time/date etc) using Pass Through recording, if it is not generated on the camera, which is why I didn't recommend that optimization...

**Comment by fujinjr** [comment]
> I would upgrade your motionEyeOS to 20200606 or dev20201026, rather than use any 2019 version. There were a number of updates and changes since then.

I'm not able to physically access the two devices, so I don't want to risk a remote update. 
Anyway is the use of RTSP, in my Pi3 B+ 'Camera Device', correct?

**Comment by starbasessd** [comment]
Yes.

**Comment by fujinjr** [comment]
> Yes.

I want to clarify some doubts that I have: 
if on the current setup I'll change the Camera Device, on the Pi 3B+, to -> http://192.168.1.112:8081 then I'll should observe a significant drop in FPS, am I right?

What are the disadvantages with my setup... loss in video quality?

**Comment by cap9qd** [comment]
Ah yes I am not concerned about text overlay. Sorry for the omission.

**Comment by starbasessd** [comment]
Then your setup is almost maxed out. 
@cap9qd 's suggestion to shift to Pass Through is best. To give yourself the best optimization you really do need to update to current versions, just check out the improvements in the change logs here:
https://github.com/ccrisan/motioneyeos/releases

**Comment by starbasessd** [comment]
> 
> 
> > Yes.
> 
> I want to clarify some doubts that I have:
> if on the current setup I'll change the Camera Device, on the Pi 3B+, to -> http://192.168.1.112:8081 then I'll should observe a significant drop in FPS, am I right?

Not necessarily, depends on what else is going on. The option slider for framerate limitations isn't absolute. If you have 1 camera, it will try to go that fast, but if the streaming camera is only sending 10 FPS, then that will be your upper limit. If you have other things on your network that eats bandwidth then you may not get the full FPS you've selected to send in FNC mode. On the other hand, if things are pretty idle, you may get the same framerate in both port 8081 vs port554/rtsp...

> 
> What are the disadvantages with my setup... loss in video quality?

**Comment by fujinjr** [comment]
> > I want to clarify some doubts that I have:
> > if on the current setup I'll change the Camera Device, on the Pi 3B+, to -> http://192.168.1.112:8081 then I'll should observe a significant drop in FPS, am I right?
> 
> Not necessarily, depends on what else is going on. The option slider for framerate limitations isn't absolute. If you have 1 camera, it will try to go that fast, but if the streaming camera is only sending 10 FPS, then that will be your upper limit. If you have other things on your network that eats bandwidth then you may not get the full FPS you've selected to send in FNC mode. On the other hand, if things are pretty idle, you may get the same framerate in both port 8081 vs port554/rtsp...
> 

With port 8081 the maximum FPS that I saw was 6 with many lags.

In the following weeks I'll stick with RTSP, I'll increase the 'Image Quality' to 40 on the FNC and see if I'll notice any improvement, quality wise; after all I'm good with 10 stable FPS.

**Comment by starbasessd** [comment]
Also, on the PiZero, you will need to watch your bit rate for the stream to get best frame rate, resolution, and quality... PiZero supports 802.11g, but seldom if ever gets anywhere near 54Mbps, which is also dependent on other traffic, the router used, and distance to the router...

**Comment by fujinjr** [comment]
Update: with Image Quality up to 40 I don't notice improvements in the image quality; I'll go back to 25. 
I could try to increase the resolution to 720p though.


> Also, on the PiZero, you will need to watch your bit rate...

Take a look:

![WiFi](https://user-images.githubusercontent.com/37943766/125924076-86c2144a-f010-4be3-b9ce-64334944ee3e.JPG)

**Comment by fujinjr** [comment]
Update: with Image Quality set to 40 I don't notice improvements in the image quality; I'll go back to 25. 
I could try to increase the resolution up to 720p though.


> Also, on the PiZero, you will need to watch your bit rate...

Take a look:

![WiFi](https://user-images.githubusercontent.com/37943766/125924678-1384d70a-3e09-4cf9-a9dc-cfdb258cb65d.JPG)

**Comment by starbasessd** [comment]
By bit rate I was referring to the PiZero, Settings, Video Device, Bit Rate, currently set to 1Mb/sec. To improve your frame rate & quality, try increasing to 2Mb/sec, and slowly increase until you don't notice any more improvement.  Realize, though, at some point you will saturate your connection to WiFi. This is not brain surgery, just rocket science, where you try a setting and notice a result. Think: SpaceX and Elon Musk....   :)

**Comment by fujinjr** [comment]
> try increasing to 2Mb/sec

I did, let's see what happens!

Another question: do you usually activate 'Denoise' option in your FNC cameras?

**Comment by starbasessd** [comment]
I activate Auto Noise Detection and Despeckle Filter anytime they are available as an option.

**Comment by fujinjr** [comment]
I was referring to the option inside the pi0:

![pi0](https://user-images.githubusercontent.com/37943766/126031880-d0fca852-0660-42db-aa75-49cdf302e960.PNG)

**Comment by starbasessd** [comment]
Yes, enabled.

**Comment by fujinjr** [comment]
I don't notice any difference increasing the bitrate to 2.00 Mbps.
Right now I set the bitrate to 1.25 Mbps and increased FPS to 12 and I get consistent results; one strange thing I noticed is that the Image quality slider (from 25 up to 100), on the Pi0, doesn't affect video quality to my perception.

Question: if I activate RTSP on the Pi0 but then add a camera on the Pi3 using http://192.168.1.112:8081, will it work?

**Comment by starbasessd** [comment]
The quickest way to answer your last question is to try it.
The easy answer is Yes.
BTW, the real test of the resolution, quality, frame rate and bitrate changes is not the 'preview' video showing the live feed, but the recorded video.

**Comment by fujinjr** [comment]
> BTW, the real test of the resolution, quality, frame rate and bitrate changes is not the 'preview' video showing the live feed, but the recorded video.

I test the video quality, and FPS, with VLC.

**Comment by starbasessd** [comment]
BTW, the real test of the resolution, quality, frame rate and bitrate changes is not the 'preview' video showing the live feed, but the recorded video.
VLC is still looking at the preview stream...

**Comment by fujinjr** [comment]
> VLC is still looking at the preview stream...

I use VLC with downloaded movies and then I observe Codec information.

Today, in one of the recorded videos, I saw a forward jump in time (of 20 seconds); it looks like someone edited and cut a portion of the video. Is it a possible effect that happens with RTSP?

**Comment by starbasessd** [comment]
Yes, occasionally. If/when that happens, you can try adding the camera as UDP instead of TCP.

**Comment by fujinjr** [comment]
> If/when that happens, you can try adding the camera as UDP instead of TCP.

How do I do that?


A suggestion for the future: is it possible to add, inside motioneyeos, the possibility to activate a different ISO during the night?

**Comment by starbasessd** [comment]
Remove the camera from motionEyeOS
Select the PiZero Camera in the dropdown
Click trashcan icon
Click Add New Camera
Add camera back,
![Untitled](https://user-images.githubusercontent.com/20134429/126155242-ae77730c-551a-469b-a589-33d0d6d909bc.jpg)
Select UDP this time.

As to the feature request, please start a new issue with it, so I can tag it as Feature Request.

**Comment by starbasessd** [comment]
As an aside, using older versions, I had to use URL: rtsp://192.168.2.120/h264 with the above settings to get UDP to work. There are many issues with the older versions of motionEyeOS and RTSP 9both sending and receiving) that have been fixed in the most recent versions (20200606 and dev20201026) compared to the 2019xxxx versions.
