### ISSUE TITLE
Feature request Audio

### ISSUE THREAD

**Issue by jordanwilliams1** [ccrisan/motioneyeos#2778]
Most new cameras now come with audio as standard. I Feel like it would be extremely benefaction to have this added. Due to the audio issue I personally won't be using the software, but the software is great and that's the only downfall sadly. I'd highly suggest that you reconsider adding this to the software. Alot of people would want this and sometimes its necessary for a crime that's taken place.

**Comment by starbasessd** [comment]
Duplicate request for audio feature.
