### ISSUE TITLE
USB camera video resolution isn't updating

### ISSUE THREAD

**Issue by sts-ryan-holton** [ccrisan/motioneyeos#2781]
### motionEyeOS Version

- dev20201026

### Board Model

- Raspberry Pi 4, 4GB model

### Camera

I'm using a USB webcam, from the brand Benewy

### Network Connection

I'm connected over Wi-Fi

### Peripherals

Just the USB camera

### The problem

I'm currently trying to adjust the video resolution of my camera under the Video Device section, however, when setting the resolution to a larger resolution and saving, the new resolution does not change, it's always what appears to be 640x480.

The USB webcam I've got supports resolutions up to at least 1280x720, so that's what I'd like,.

I did try setting: `height 800` as a test in the Extra Motion Options, but this appeared to crash the system.

What am I missing and how can I set the resolution of this camera?

![config](https://user-images.githubusercontent.com/25177538/126539283-90c090e4-fe11-4db7-98ec-571888259733.PNG)

**Comment by starbasessd** [comment]
While I am trying to throw together a Pi4-4GB dev20201026 with USB camera, please try lowering your framerate to 15 or 10 FPS for testing purposes.

**Comment by sts-ryan-holton** [comment]
I've just lowered both the video streaming and main video to 10fps, and stream quality to 75%. If it helps, here's some other version info:

- Motion Version: 4.3.1
- motionEye Version: 0.42.1

![config-overview](https://user-images.githubusercontent.com/25177538/126541509-aca09041-1bb8-4477-b0db-cef6829f0c4b.PNG)
![new-config](https://user-images.githubusercontent.com/25177538/126541512-f3a04b1d-466b-40d3-a3a9-104288921a66.PNG)

**Comment by starbasessd** [comment]
Hmmm. 
Do you click Apply at the top of the window?
Do you have 800x600 in your dropdown for resolution? 
Can you select Custom and try 1024x768 and 800x600?
I do not get the Brightness, Contrast and Hue options on my Tiga
I also set Fit Frame Vertical and 1 column options in Settings, Preferences..
If you can get it to record video, in VLC you can view framerate and resolution (and other parameters), what does it record as?
Have you connected your other Pi4 to it (the Pi4 with the camera) as Network Camera
and tested?
Which make and model of USB camera? 
If I go to Benewy.net and check products, webcam they have nothing listed and their support is a hotmail account.

**Comment by sts-ryan-holton** [comment]
I'll have to look into the fit frames vertically option and the others as you described, I'm currently not at the Pi so will clarify those questions as soon as I can, but what I can check here is:

- I do click "Apply" at the top of the screen, the Pi then does it's spinning and then reloads.

- I've tried setting "Custom" as a resolution to 1280 width and 720 height, this made no difference but I can try the exact measurements

- the camera is [this one](https://www.amazon.co.uk/Microphone-Desktop-Conference-Studying-Compatible/dp/B089LTY8X7/ref=mp_s_a_1_1_sspa?dchild=1&keywords=benewy+webcam&qid=1626897356&sprefix=Benewy&sr=8-1-spons&psc=1&smid=A3J9ITXBRZ4BLV&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExUjExUFhSNUNSSENRJmVuY3J5cHRlZElkPUEwNzA1MTkwM0Y0SExDTUpSUTlKMSZlbmNyeXB0ZWRBZElkPUEwNTc5MTk3VVlFTEJIUUlaN1o1JndpZGdldE5hbWU9c3BfcGhvbmVfc2VhcmNoX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=)

**Comment by starbasessd** [comment]
Curiosity: do you have any other USB devices plugged in?

**Comment by starbasessd** [comment]
Also, if-when you can SSH or get to the console, run the command:
vcgencmd get_throttled
and post result, please.

**Comment by sts-ryan-holton** [comment]
Here's some more findings:

1. Running: `vcgencmd get_throttled` gives me the following: `throttled=0x0`.
2. I don't have any other USB devices plugged in, just the camera plugged into a USB 2.0 port, I've tried both ports and also both USB 3.0 ports with the same results.
3. I do have `800x600`, I've just tried this and the resolution doesn't change from `640x480`.
4. Weirdly, if I set a smaller resolution, like `320x240` this resolution works, but changing it back to the resolution I desire just reverts it back to `640x480`.
5. Setting `1024x768` and `800x600` with the Custom option doesn't set these as the resolution, resolution remains unchanged.
6. Fit frames vertically is switched on.

**Comment by starbasessd** [comment]
Interesting. I am at a loss diagnosing in motionEyeOS. Do you have another SDCard or USB Thumb drive to load RaspberryPiOS to run some other commands?

**Comment by starbasessd** [comment]
lsusb doesn't provide info that would help diagnose, and most other tools are missing, too...

**Comment by sts-ryan-holton** [comment]
Maybe the Extra Motion Options would allow me to set the height and width? What format would I need to put in here to try that?

**Comment by starbasessd** [comment]
One option per line
same format as motion, as found here:
https://motion-project.github.io/motion_config.html#width
the whole document is helpful
https://motion-project.github.io/motion_config.html

**Comment by sts-ryan-holton** [comment]
Okay, so I just tried this in the extra motion options:

```
height 1280
width 720
```

And I get an error:

> An error occurred. Refreshing is recommended.

And after refreshing it says I haven't configured any cameras, so rebooting the pi kind of fixes the config, but why is this broken?

**Comment by sts-ryan-holton** [comment]
My logs:

[motion.log](https://github.com/ccrisan/motioneyeos/files/6870289/motion.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/6870290/dmesg.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/6870291/boot.log)
[messages.log](https://github.com/ccrisan/motioneyeos/files/6870292/messages.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/6870293/motioneye.log)

**Comment by sts-ryan-holton** [comment]
Okay, so I'm noticing in the log file when I attempt to change the video resolution these kinds of warnings?

> Jul 23 18:47:06 meye-carcam user.warn motion: [1:ml1:Car Cam] [WRN] [VID] v4l2_pixfmt_set: Adjusting resolution from 1280x720 to 640x480.

This seems to be in line with what I'm experiencing, each time I try and set a larger resolution, the video always appears as `640x480`, but in the dropdown it's still set to the resolution I desire, what does this mean?

**Comment by sts-ryan-holton** [comment]
Right, somehow I've managed to get it working after some more digging, so I came across this command online that apparently reads the supported resolutions of a camera:

- `v4l2-ctl --list-formats-ext`

The output gave me:

![Capture](https://user-images.githubusercontent.com/25177538/126823466-dc2edef5-a01d-4243-aa4e-5a391c3a4aa1.PNG)

And then I came across the [v4l2_palette](https://motion-project.github.io/motion_config.html#v4l2_palette) option, and then it occured to me that the default (number 17) which is reading from `YU12` adds up with the very few resolutions in my output above, but MJPG has more resolutions including the one I need, so in the extra motion options I added:

- `v4l2_palette 8`

Applied the changes and now my resolution has been set successfully!
