### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by Ferrox12** [ccrisan/motioneyeos#2785]
Hi,
is there a method to implement the SSL certificate on motioneyeos?

**Comment by starbasessd** [comment]
Not directly. You could use an nginx forwarder or use motionEye with nginx following these instructions:
https://github.com/ccrisan/motioneye/wiki/Running-Behind-Nginx

**Comment by Ferrox12** [comment]
OK, thank you very much!!!

**Comment by Ferrox12** [comment]
Is there another method?

**Comment by starbasessd** [comment]
There isn't an internal to motionEyeOS answer. You would need to set up another box with nginx or similar or a combo with another OS, motionEye and nginx or similar as an SSL redirector (assuming you are trying to set up https from the world to your internal motionEye server). If it's all internal networking, no need for SSL.

**Comment by starbasessd** [comment]
You could set up RaspberryPiOS with docker and run both the docker version of motionEye and nginx to keep it on the same box.

**Comment by Ferrox12** [comment]
OK thanks for the help!!!
