### ISSUE TITLE
Can't access Motioneyeos webpage

### ISSUE THREAD

**Issue by kner7** [ccrisan/motioneyeos#2797]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606

### Board Model

Pi 3B

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

none for now

### Network Connection

Ethernet

### Peripherals

none

### Log Files

none
 
So I've made a connection and pinging the ip that angry ip scanner shows  MEYE is on is receiving packets but i can't access the webpage on that ip it refuses the connection?

![image](https://user-images.githubusercontent.com/16978895/130852298-a0ff3d6f-6f49-464c-8b8f-0d1b1e49f699.png)

**Comment by starbasessd** [comment]
What browser?

**Comment by kner7** [comment]
google chrome

**Comment by kner7** [comment]
i just checked edge it's working. Sorry for the trouble, thx for the help!
