### ISSUE TITLE
Not start A20 board

### ISSUE THREAD

**Issue by ot-i-to** [ccrisan/motioneyeos#2800]
U-Boot SPL 2018.09 (Jun 06 2020 - 14:07:46 +0000)
DRAM: 1024 MiB
CPU: 912000000Hz, AXI/AHB/APB: 3/2/2
Trying to boot from MMC1

U-Boot 2018.09 (Jun 06 2020 - 14:07:46 +0000) Allwinner Technology

CPU:   Allwinner A20 (SUN7I)
Model: LeMaker Banana Pi
I2C:   ready
DRAM:  1 GiB
MMC:   SUNXI SD/MMC: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

HDMI connected: Setting up a 1920x1080 hdmi console (overscan 0x0)
In:    serial
Out:   vga
Err:   vga
SCSI:  SATA link 0 timeout.
AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl SATA mode
flags: ncq stag pm led clo only pmp pio slum part ccc apst 

Net:   eth0: ethernet@01c50000
starting USB...
USB0:   USB EHCI 1.00
USB1:   USB OHCI 1.0
USB2:   USB EHCI 1.00
USB3:   USB OHCI 1.0
scanning bus 0 for devices... 1 USB Device(s) found
scanning bus 2 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
378 bytes read in 1 ms (369.1 KiB/s)
## Executing script at 43100000
3097304 bytes read in 201 ms (14.7 MiB/s)
34831 bytes read in 4 ms (8.3 MiB/s)
## Booting kernel from Legacy Image at 41000000 ...
   Image Name:   Linux-4.9.136
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3097240 Bytes = 3 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
EHCI failed to shut down host controller.
EHCI failed to shut down host controller.
   Loading Kernel Image ... OK
   Using Device Tree in place at 43000000, end 4300b80e

Starting kernel ...

**Comment by starbasessd** [comment]
It would be extremely helpful to answer the questions presented when you opened the issue.

**Comment by ot-i-to** [comment]
download ends on "Starting kernel ... "

**Comment by ot-i-to** [comment]
### Preliminary Docs

I **confirm** that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I **confirm** that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606 for Banana PI M1 

### Board Model

I am using the following board/model: [CubieBoard2](http://cubieboard.org/model/cb2/) 

### Camera

I am using the following type of camera: USB

My camera model is: Logitech, Inc. Webcam C930e ID: 046d:0843

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * no
 
### Log Files

I consider the following log files relevant to this issue:

 * no

**Comment by starbasessd** [comment]
Have you tried booting to an SDCard image? 
It is not a Banana Pi, it may be a 'clone', but I do not see support for it specifically in the BootRoot supported boards. It says it supports an older Ubuntu. Does it support an Ubuntu newer than 12? (Preferably 16.04 or newer)

**Comment by ot-i-to** [comment]
> Have you tried booting to an SDCard image?
> It is not a Banana Pi, it may be a 'clone', but I do not see support for it specifically in the BootRoot supported boards. It says it supports an older Ubuntu. Does it support an Ubuntu newer than 12? (Preferably 16.04 or newer)

Armbian 21.05.1 Focal with Linux 5.10.34-sunxi
# uname -a
Linux lime2 5.10.34-sunxi #21.05.1 SMP Thu May 6 20:13:21 UTC 2021 armv7l armv7l armv7l GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
--- ok ---

**Comment by starbasessd** [comment]
Try to install motionEye on Ubuntu 20.04 following these instructions:
https://github.com/ccrisan/motioneye/wiki/%28Install-On-Ubuntu-%2820.04-or-Newer%29
