### ISSUE TITLE
MotionEyeOS: Raspberry PI3B vs. PI4B8GB (PI3B works, not PI4B8GB)

### ISSUE THREAD

**Issue by we-do-it-lu** [ccrisan/motioneyeos#2801]
Discovering MotionEyeOS today, 1st post on this GitHub, I hope you'll be kind to me.
I have installed MotionEyeOS on a Raspberry **PI3B** and managed to follow the (very clear) procedure and run the software (very easy, well done). 
Now I am trying to install MotionEyeOS on a Raspberry Pi4B 8GB using exactly the same procedure (making sure that I download the correct image for PI4 instead of P3) but this time it does not work: I slid the memory card, turn the PI on and ... nothing: the AKT led (the green one) continuously blinks   _ _ _ _   . . . .     
I am not a champion with computers and unfortunately don't have a HDMI monitor to plug in for it to maybe display info that would help me "debug" if only I'd be able too.
I was thinking maybe one of you came across the same issue // maybe PI 4B 8GB specifically is not supported (I red very old articles concerning PI 4 so probably not relevant to **PI4B 8GB**.
I tried different things, with webcam plugged and unplugged, flashed the memory a few time, tried a different memory card; went back to **PI3B** where it works well. 
My **PI4B 8GB** is brand new and to test it I installed Raspberry standard OS it, no issues with the board.
Thank you in advance.

**Comment by starbasessd** [comment]
1) the questions are there for a reason. 
2) Pi4-8GB must have the latest rpi-eeprom update (4/29/2021)
3) Pi4-8GB only works with dev20201026 here: https://github.com/ccrisan/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz

**Comment by we-do-it-lu** [comment]
100 thanks. And I will get more familiar with / follow-up the project and the documentation obviously.

**Comment by starbasessd** [comment]
If it is resolved, please close.

**Comment by we-do-it-lu** [comment]
It works like a charm :-)

**Comment by we-do-it-lu** [comment]
Closed
