### ISSUE TITLE
No remote motionEye Camera found

### ISSUE THREAD

**Issue by wawawa15** [ccrisan/motioneyeos#2817]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606

### Board Model

I am using the following board/model: Raspberry PI 3B+

### Camera

I am using the following type of camera:  Fast Network Camera and Simple MJPEG Camera.

My camera model is: Rpi camera v2.1 8mpx

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:
-

### Log Files

I consider the following log files relevant to this issue:

[motioneye.log](https://github.com/ccrisan/motioneyeos/files/7315560/motioneye.log)

[boot.log](https://github.com/ccrisan/motioneyeos/files/7315559/boot.log)

### Text
 Hi Guys! I have a project for my University, connecting 4 Rpi with camera to a Rpi Hub and send the video to a ssd and after that I will process the image. It's kind of, a dvr for car, I want to analize driver reaction on certain condition on Romanian Roads :))) but I have a little problem: Whne I try to add a Remote motionEye Camera with the correct ip adress and I get "no cameras" window
![Screenshot 2021-10-09 153127](https://user-images.githubusercontent.com/53373038/136657992-7211bc08-08d7-45c1-a2d5-2c5697615130.png)
Yes, all of Rpis are conected to same wifi. For now, two of them are configured as a fast network camera and a hub with local camera. What can I do?

Thanks, Have a nice day,
Rares

**Comment by starbasessd** [comment]
Is the camera you are trying to add set as a 'normal' motionEyeOS camera or as a Fast Network Camera? If FNC, use 'MJpeg' or Network.

**Comment by wawawa15** [comment]
> Is the camera you are trying to add set as a 'normal' motionEyeOS camera or as a Fast Network Camera? If FNC, use 'MJpeg' or Network.

It's set as a Fast Network Camera, when I try to use MJPEG or Network I get "not a supported network camera":
![Screenshot 2021-10-09 155925](https://user-images.githubusercontent.com/53373038/136658812-f9bcd4c9-a02c-4c0b-8ac4-aaf281bcd680.png)
![Screenshot 2021-10-09 155941](https://user-images.githubusercontent.com/53373038/136658815-34d2a01e-2fb6-48fa-8c5f-4351ea8c8928.png)
![Screenshot 2021-10-09 160016](https://user-images.githubusercontent.com/53373038/136658816-1747ab00-4424-4e91-81a9-9d9cdb06e029.png)

**Comment by starbasessd** [comment]
Are you using the URL: http://ip_address:8081? or switch the protocol in the FNC to rtsp and use the rtsp URL.

**Comment by wawawa15** [comment]
> Are you using the URL: http://ip_address:8081? or switch the protocol in the FNC to rtsp and use the rtsp URL.

Well, I try with port but with 8080 instead of 8081. It's work with 8081 :))) Thanks for help

**Comment by starbasessd** [comment]
Don't forget to close if fixed. You're welcome.
