### ISSUE TITLE
Cannot connect via RTSP

### ISSUE THREAD

**Issue by mlittle408** [ccrisan/motioneyeos#2822]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

Yes.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

Yes.

### motionEyeOS Version

I am running motionEyeOS version: 20200606

### Board Model

I am using the following board/model: Raspberry Pi Zero W.

### Camera

I am using the following type of camera: PI Camera v2.

My camera model is: V2

### Network Connection

My motionEyeOS unit is connected to the network via: WIFI

### Peripherals

None

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

None

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 
I am running MotionEyeOS in Fast Network Camera mode. I am not able to connect via rtsp://192.168.1.154:554/ or rtsp://192.168.1.154:554/1 or rtsp://192.168.1.154:554/Camera1. I have tried with VLC running on Windows 10

As a point of reference, I am able to connect via HTTP when not running Fast Network Camera so I know the camera is working. 

Did I miss a step somewhere?

[messages.log](https://github.com/ccrisan/motioneyeos/files/7365889/messages.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/7365890/boot.log)
[dmesg.log](https://github.com/ccrisan/motioneyeos/files/7365891/dmesg.log)
[streameye.log](https://github.com/ccrisan/motioneyeos/files/7365892/streameye.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/7365893/motioneye.log)

**Comment by starbasessd** [comment]
Did you enable:
Settings, Video Streaming, Streaming Protocol: rtsp?

**Comment by mlittle408** [comment]
> Did you enable: Settings, Video Streaming, Streaming Protocol: rtsp?

Yes. I'm sorry, I should have mentioned that. It's enabled and on port 554

**Comment by starbasessd** [comment]
There are a number of issues with motionEyeOS 20200606. Can you please try dev20201026?

**Comment by mlittle408** [comment]
> There are a number of issues with motionEyeOS 20200606. Can you please try dev20201026?

I'll try it right now. Which build should I run on the Zero W? Looks like there's 4 for the pi

**Comment by mlittle408** [comment]
Sorry, I didn't realize I could upgrade to a dev version. I am doing it now.

**Comment by starbasessd** [comment]
Also, the correct URL would be http://ip_address:8081/h264 for VLC, web browser, or motionEye server

**Comment by starbasessd** [comment]
PiZero is equivalent to the Pi1 so you would use the image for Pi, not Pi2, Pi3, or Pi4.

**Comment by mlittle408** [comment]
I did the update, rebooted and now the left admin panel is all greyed out. 

Also, this is the URL for RTPS? http://ip_address:8081/h264

**Comment by starbasessd** [comment]
At the top left, click on the head bust icon, and log in as admin.

Yes, the RTSP URL is http://ip_address:8081/h264

**Comment by mlittle408** [comment]
Ok. I did log in and everything is greyed out. I'll try rebooting. Thanks for your help. That URL works too, btw.

**Comment by gerolori** [comment]
Just for future reference, the correct rtsp link is rtsp://ip_address:554/h264
The one suggested above is a mjpeg stream, so mjpeg settings of motioneye will apply.
