### ISSUE TITLE
Camera grayed out

### ISSUE THREAD

**Issue by peterd550** [ccrisan/motioneyeos#2826]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.
Yes I have
I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.
Yes I have
### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).
0.42.1
### Board Model
Raspberry PI 4 - 4GB

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

### Camera
Network Camera
D-Link dcs-5020L - but with a lag
Tapo camera c100 - not working with grayed out

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).
Network Camera

My camera model is: (insert your camera model, e.g. Logitech C290).
D-Link dcs-5020L - but with a lag
Tapo camera c100 - not working
### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).
WIFI
### Peripherals

I am using the following peripherals that I consider relevant to this issue:
Nope
 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/7406493/boot.log)
[motioneye.log](https://github.com/ccrisan/mo
[motion.log](https://github.com/ccrisan/motioneyeos/files/7406496/motion.log)
tioneyeos/files/7406495/motioneye.log)
 
![Capture](https://user-images.githubusercontent.com/15135115/138619072-e043950f-112b-4d72-9aa7-8ea810ff42ec.JPG)

**Comment by starbasessd** [comment]
What URLs are you using for the d-link and tapo?
The version of motionEyeOS you are using is 20200606. Recommended for Pi4B is dev20201026 (https://github.com/ccrisan/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz)
What kind of 'lag' do you have with the d-link? I have 3 in my production system, and do not have more than 2-3 seconds lag (in a 6 camera system)

**Comment by starbasessd** [comment]
URL for the Tapo C100 cameras according to iSpyConnect should be either:
rtsp://ip_address/stream1
or
rtsp://ip_address/stream2
and for Camera I would try RTSP/UDP also (default when adding is RTSP/TCP)
I have 2 Foscam rtsp cameras one prefers RTSP/TCP and the other prefers RTSP/UDP...

**Comment by peterd550** [comment]
Thanks for the response.
I have tried both settings and still have the issue with grey box :(
Any idea what can cause this?

**Comment by starbasessd** [comment]
The version of motionEyeOS you are using is 20200606. Recommended for Pi4B is dev20201026 (https://github.com/ccrisan/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz)

**Comment by peterd550** [comment]
yes I have changed the build and re configured my camera but still get the Gray box.

**Comment by starbasessd** [comment]
If you ssh into the Pi, or use the console, can you ping the camera?
Do you have a user and password set on the camera itself?

**Comment by peterd550** [comment]
Yes I can SSH into the motion eye box and ping my tapo camera

**Comment by starbasessd** [comment]
Did you  try the RTSP/UDP setting?

**Comment by peterd550** [comment]
Yes I have tried both sdttingd

**Comment by starbasessd** [comment]
Does the camera work with the URL in VLC?

**Comment by peterd550** [comment]
Resolved issue. Don't know how just start working
I now have 2 more all working as expected

**Comment by peterd550** [comment]
Resolved issue. Don't know how just start working
I now have 2 more all working as expected

**Comment by starbasessd** [comment]
It happens. Sometimes it's the phase of the moon, or whether someone is holding their tongue 'just right'...

**Comment by peterd550** [comment]
Hahaha yep I know that feeling.
Thanks for all the support and knowledge
