### ISSUE TITLE
How to access stand alone pi ?

### ISSUE THREAD

**Issue by qxotic** [ccrisan/motioneyeos#2828]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version
motionEye Version 0.42.1       Motion Version 4.2.2  working fine

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

### Board Model
Pi4 8GB  Raspbian 10  working fine
I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

### Camera
Pi camera MMAL - working fine
I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: (insert your camera model, e.g. Logitech C290).

### Network Connection
Want to be able to use no etho connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).

### Peripherals

I am using the following peripherals that I consider relevant to this issue:
Internal pi wifi
 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 

I have wlan0 on  my pi set up as a wireless server.  I can ssh into it with my laptop through the wireless connection.  When i have the pi at the office, and it is also connected to the lan network I can connect to the pi wi fi with my laptop and bring up the webpage for motioneye fine.  I am not able to bring it up when I disconnect from the lan network.  

eth0 on the pi has a static IP

I want to be able to take the pi offsite where it has no ethernet/internet connection and have the camera recording and be able to bring the laptop, log in through my wireless connection. which works.. and bring up the motioneye in the browswer (currently it only works when also connected to the LAN.)   

Since the pi eth0 has a static IP I thought motioneye would keep the same address and I would be able to connect.. but no luck.  Any idea how this can be done?  How can you view the camera when the pi is not connected to a network?  When I ssh in and run top I can see motion is running.. so is there a way to get motioneye to show in the browswer when the pi is not connected to the internet?

**Comment by starbasessd** [comment]
If you are running motionEyeOS (you don't say which version, 20200606 or dev20201026)
there are instructions here:
https://github.com/ccrisan/motioneyeos/wiki/WiFi-Access-Point
to turn your Pi into an Wifi Access Point. 
I attached a set of instructions and files to include in a clean install of 
motionEyeOS 20200606 or newer, unzip the files into the /boot partition
after creating the image, and before first run
[ConfigFiles(20200606-or-newer).zip](https://github.com/ccrisan/motioneyeos/files/7436932/ConfigFiles.20200606-or-newer.zip)

**Comment by qxotic** [comment]
Thank you for the information.  I am running Raspian 10 as the OS and running motioneye as a program.

________________________________

**Comment by starbasessd** [comment]
This is the motionEyeOS github, the motionEye on other OSs is at:
https://github.com/ccrisan/motioneye/wiki
And that functionality is based on the underlying OS
There are MANY youtube videos and instruction sets out there to set
up the Pi as an Access Point using Raspberry Pi OS.

**Comment by qxotic** [comment]
Thanks for pointing me in the right direction.  I didn't realize motioneye had two seperate sites.  I did go through a lot of youtube videos setting it up.. I'll try searching for Access Point and see if I can find it.

Thank you.

________________________________

**Comment by starbasessd** [comment]
If you are having issues finding links / sites try:
https://learn.adafruit.com/setting-up-a-raspberry-pi-as-a-wifi-access-point

**Comment by qxotic** [comment]
I've been trying this on a Pi 4 gets past Preparing AP interaces: "apo"  then configuring wired network lists "no link" for wired network and panic reboots.  I did copy the four files over to the boot folder.

Any suggestions?  I am using the 20200606 pi4 image for motioneyeOS

________________________________

**Comment by starbasessd** [comment]
For a Pi4 you should run dev20201026, as there are a number of issues with the 20200606 image and Pi4s.

**Comment by qxotic** [comment]
I have tried it on a 4G and an 8G pi with same result.  8G pi is up to date on eeprom.. not sure on the 4.. they can both boot raspian by usb, but am using sd card for motioneyeOS


________________________________

**Comment by starbasessd** [comment]
You can use dev20201026 on SDCard as well...

**Comment by qxotic** [comment]
I did... can it be used on USB?
I made some progress... I edited the /etc/os.conf file.. networkless from false to true, then it booted and my attached lcd shows meye... login.

I don't see my wifi showing up for log in though.  May have to bring a keyboard to connect to the pi to try and find out why.

________________________________

**Comment by starbasessd** [comment]
Will test and confirm in a bit, wrapping up another issue (documentation of installing motionEye on Debian 11 Bullseye).

**Comment by starbasessd** [comment]
Do you want me to test SDCard or USB first? 
4GB or 8GB first?
Anything else in your particular setup?

**Comment by qxotic** [comment]
8GB... also have a pizero w but no way to display what's going on with it.  ordered cable to be able to connect to my little lcd

on the 8GB I did find a keyboard.. hostname -i just gives 127.0.0.1    and cat /var/lib/misc/dnsmasq.leases  returns No such file or directory

I'm in no big rush, just appreciate the help and the program.

________________________________

**Comment by starbasessd** [comment]
Pi4-4GB, motionEyeOS dev20201026, 2GB USB stick Files from attached zip
[ConfigFiles(20200606-or-newer).zip](https://github.com/ccrisan/motioneyeos/files/7463491/ConfigFiles.20200606-or-newer.zip)
Changed cmdline.txt from root=/dev/mmcblk0p2 to root=/dev/sda2
booted correctly, showed up in android phone as picam access point as expected.
shutdown, moved to Pi4-8GB
Same result.
Do you want me to test SDCard?

**Comment by qxotic** [comment]
I'm heading out for the day, will try the usb tomorrow.

Thanks
Daniel

________________________________

**Comment by starbasessd** [comment]
I don't have access to my Pi4-8GB SDCard slot on my test machine (it's in an Argon40 ArgonOne V2 case) but I just repeated with a Pi4-4GB, 8GB microSDCard, the above files, (don't need the cmdline.txt change)
 Set up and running as expected.
Be sure to use CURRENT files, as they are different (using AP0 instead of WLAN0, etc...)

**Comment by qxotic** [comment]
Ok.. here's what I did.  Downloaded the pi4 development image... unzipped.  I run linux mint 19.  I used Disks to format 2 G 2.0 usb drive and  restore disk image using the pi4 image.  Then I mount the partition, open boot folder as root, copy the 20200606 or newer config files into the boot folder.  It contains the 4 .conf files.  I then unmount and put into the 8GB pi and booted with the usb, power, display and keyboard attached..as well as a picam.
The 2.0 2G usb only flashed a color screen and hung on a flashing cursor.

I then did the same steps with a PNY 64GB 3.0 USB and get flashing cursor then also.  Where do you edit the command line text for sd instead of mmblk?

I did the same to a 32 G sd card.. and got the panic reboot for no network link.

I also have a Pi zero wireless... used the dev pi2 image... is that the right one?  The light flashes briefly but it does not appear to go anywhere after that.. thinking that is not the right dev image for the zero?

What do you suggest I try next?  I have the Zero and a couple of 8G Pi4s I can tinker with today.




________________________________

**Comment by starbasessd** [comment]
Boot the Pi4 with raspbian, make sure the rpi-eeprom is dated for 2021 (any version) and if not, update it to current:
rpi-eeprom-update [enter]
If current will report:
pi@raspi1:~ $ rpi-eeprom-update
BOOTLOADER: up to date
   CURRENT: Thu 29 Apr 2021 04:11:25 PM UTC (1619712685)
    LATEST: Thu 29 Apr 2021 04:11:25 PM UTC (1619712685)
   RELEASE: default (/lib/firmware/raspberrypi/bootloader/default)
            Use raspi-config to change the release.

  VL805_FW: Dedicated VL805 EEPROM
     VL805: version unknown. Try sudo rpi-eeprom-update
   CURRENT:
    LATEST: 000138a1
If it reports a 2020 date, update it:
sudo rpi-eeprom-update -a
- - - - -
When you image the dev20201026 to either USB or SDCard copy the files (unzip them first, of course) to the /boot partition.
ONLY If you are using USB for the Pi4, edit the file cmdline.txt in the folder where you just copied the files. Change the part where it says:
root=/dev/mmcblk0p2
to
root=/dev/sda2
Do NOT make any other changes. It needs to be ONE long line.
Then you can eject it and use it.
- - - - -
The image you need for RPiZero is the one labeled:
motioneyeos-raspberrypi-20200606.img.xz
https://github.com/ccrisan/motioneyeos/releases/download/20200606/motioneyeos-raspberrypi-20200606.img.xz

**Comment by qxotic** [comment]
The bootloader is the current 29 Apr 2021


I need to be clear on the /boot partition.  When I put the card into my computer, it mounts 3 partitions  (this is after it has been booted on the pi)  There is not a cmdline.txt file... should i create it when using a USB?  and does it belong in the same /boot folder in this partition as the other files?   (I do have show hidden files checked)

Partition 1 is 31 MB it does not have a boot folder
Partition 2 is 231 MB and has the boot folder where I copied the config files into.  (is this where they should have gone?)
  If I edit the /etc/os.conf file to true it will boot to prompt.. otherwise it will panic reboot due to no network.


partition 3 is 31 GB and does not have a boot folder.

I tried the image on the zero but no wifi log in.. just a slow flashing green light.  I don't have the cable I need yet to hook it up to a screen.


________________________________

**Comment by qxotic** [comment]
I did find the cmdline.txt file and can boot on the usb

It panic rebooted due to network also.. until I edited the /etc/os.conf file to true.. it boots to login now but still no wifi ID on my search list.

________________________________

**Comment by starbasessd** [comment]
You're not using the files from the zip file I uploaded.
https://github.com/ccrisan/motioneyeos/files/7463491/ConfigFiles.20200606-or-newer.zip
 
The file os.conf already has the correct setting, and some adjustments in other files that are needed for the latest images.

Start clean (fresh image)
Copy the extracted files to the first partition (also called the /boot partition)
If using USB, edit the cmdline.txt file as in:
https://github.com/ccrisan/motioneyeos/issues/2828#issuecomment-959617411
THEN eject the USB or SDCard and insert into the Pi and power up.

**Comment by qxotic** [comment]
Yes I used those files... the os.conf file from that zip has the setting to true but it does not prevent the panic reboot due to network

here is a paste from the file - OS_NETWORKLESS="true"
________________________________

**Comment by qxotic** [comment]
Attaching screen shot of /boot folder
the dns and hostapd files both use ap0 instead of wlan0

________________________________

**Comment by starbasessd** [comment]
I just imaged a 2GB USB drive with 
https://github.com/ccrisan/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz
Copied the unzipped files to the /boot partition.
Edited the cmdline.txt file change
ejected the drive, inserted into my test Pi4-8GB Pi, without ethernet, and it booted as expected, showing up as AP: picam on my android phone. I connected, and used Chrome browser to go to 192.168.42.1 and got the WebGUI of motionEye.

**Comment by starbasessd** [comment]
I just imaged a 8GB Micro SDCard drive with
https://github.com/ccrisan/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi-dev20201026.img.xz
Copied the unzipped files to the /boot partition.
ejected the drive, inserted into my test PiZeroW Pi, without ethernet, and it booted as expected, showing up as AP: picam on my android phone. I connected, and used Chrome browser to go to 192.168.42.1 and got the WebGUI of motionEye.

**Comment by qxotic** [comment]
I got it... I had the files in the wrong place.. the /boot was throwing me off... I looked for and found the /boot folder.. on the second partion, but you were meaning to put them in the root of the bootable partition.  I think I am up and running now.. was able to connect and bring up the webpage for motioneye on the pi4.. going to make the corrections for the zero now.

Thank you,  sorry for the trouble.


________________________________

**Comment by starbasessd** [comment]
Any further issues, please open a new issue.
