### ISSUE TITLE
Open/Copy last motion triggered Snapshot

### ISSUE THREAD

**Issue by Hunte060708** [ccrisan/motioneyeos#283]
Hello,
Is there any way to view the last Snapshot taken by a motion? I read that there was a link oder file called lastsnap.jpg in older versions but did not find that on my motioneyeos. 

I´m using pushover to get a notification to my smart-phone when a motion is detected and the i can connect to the raspberry and look whats happening - BUT if i get a notification and look 5 minutes later i just see the live-picture oder video so my idea is to go to the last picture that is saved because of an detected motion.

I am using MotionEyeOS version 20160410 on my Raspberry Pi 1. Pictures and videos are saved to an 64GB-USB-Stick.

**Comment by bortek** [comment]
If still unsolved please post your question on the forum page
