### ISSUE TITLE
Schedule for normal recording

### ISSUE THREAD

**Issue by peterd550** [ccrisan/motioneyeos#2835]
Can I request a feature the I can Continuous record on a schedule.
I can see it under motion detection.

**Comment by starbasessd** [comment]
Continuous Record on a schedule? Like, what kind of schedule? Do you want 'normal motion detection when not recording continuous?
If a 'simple schedule' you should be able to turn on Working Schedule, and pick hours. If they go over midnight  then you would pick 'outside working hours. For example:
If you wanted 8a-5p you would select During working hours, with the 8a and 5p selected.
If you wanted to record 6p-6a you would select Outside Working Hours, and set the times at 6a and 6p.

**Comment by peterd550** [comment]
So my cameras are recording 24/7
I would like to schedule no recording between 10 pm to 7 am. When my baby is asleep and not in the lounge

**Comment by starbasessd** [comment]
So you would set Working Hours to 7a to 10p in Working Hours below Motion Detection.

**Comment by peterd550** [comment]
Without motion detection

**Comment by starbasessd** [comment]
In the list of Settings on the left, Working Hours is below Motion Detection and Motion Notification.
![image](https://user-images.githubusercontent.com/20134429/140786675-d67e905a-221e-49ce-9b03-fd122c583f4f.png)

**Comment by peterd550** [comment]
Sorry mate
Miss read the wiki
Thanks again for your help

Now I have the cameras and my Pi is wired it's a good app with plenty of features

**Comment by starbasessd** [comment]
Don't forget to close when you confirm it's working as expected.

**Comment by peterd550** [comment]
:( can’t close issue via the app
All working as expected
