### ISSUE TITLE
Email options wont save

### ISSUE THREAD

**Issue by andy6149** [ccrisan/motioneyeos#285]
Hi,
hopefully minor, just installed the latest release 20160410. When I turn on 'Send an Email' and input my gmail settings (which worked previously) and click 'apply' I get 'An error occurred. refreshing is recommended' - any thoughts?

thanks

**Comment by Phesten** [comment]
Gmail requires a device-specific password that can be generated from your Gmail account privacy settings. Try that password instead of your usual Gmail password.

**Comment by andy6149** [comment]
Couple of reboots seem to have resolved it - thanks for commenting
