### ISSUE TITLE
Grey Screen on Reolink RLC-810A

### ISSUE THREAD

**Issue by uwe72** [ccrisan/motioneyeos#2855]
I tried many many variations of links, e.g.
rtsp://192.168.178.89:554/h264Preview_01_main

But either it is a grey screen (unable to display video device) or it is black. Just the jpg stream is working.

![image](https://user-images.githubusercontent.com/61848539/147777442-2fbbc1a4-afe8-4034-8d3a-fa308142e85c.png)

Can anybody help me please? In VLC Player it works well

**Comment by starbasessd** [comment]
Did you try without the :554 in the URL?
rtsp://192.168.178.89/h264Preview_01_main
which is what iSpy database suggests.

**Comment by starbasessd** [comment]
If you want any further assistance, you need to answer the questions presented when you opened the issue at a minimum.
