### ISSUE TITLE
Grey Screen on Reolink RLC-810A

### ISSUE THREAD

**Issue by uwe72** [ccrisan/motioneyeos#2856]
### motionEyeOS Version

I am running motionEyeOS version: 
motionEye Version | 0.42.1
Motion Version | 4.3.2

### Board Model
I am using the following board/model: Laptop Linux OS Version | Ubuntu 21.10. Intel i5

### Camera
Reolink RLC-810A

### Network Connection
My motionEyeOS unit is connected to the network via: Ethernet

### Log Files
I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 [motioneye.zip](https://github.com/ccrisan/motioneyeos/files/7794155/motioneye.zip)

I tried many many variations of links, e.g.
rtsp://192.168.178.89:554/h264Preview_01_main
rtsp://192.168.178.89/h264Preview_01_main

But either it is a grey screen (unable to display video device) or it is black. Just the jpg stream is working.

**Comment by starbasessd** [comment]
You're not running motionEyeOS, you're running motionEye
https://github.com/ccrisan/motioneye/issues
https://github.com/ccrisan/motioneye/wiki/%28Install-On-Ubuntu-%2820.04-or-Newer%29
VLC is more flexible as to RTSP, than motionEye. motionEye, ffmpeg and motion are much stricter on the standards.
Do you have the latest firmware in the camera?
https://www.reddit.com/r/reolinkcam/comments/l5difs/firmware_update_for_reolink_810a820a510a520a/
https://reolink.com/download-center/ Select PoE IP Cameras & NVRs, Scroll down to Reolink RLC-810a, Firmware.
