### ISSUE TITLE
I have been trying to map my network share from a Synology NAS

### ISSUE THREAD

**Issue by mstewart81** [ccrisan/motioneyeos#2863]
Hi 
I have been trying to map my network share from a Synology NAS the location of the folder is /volume1/surveillance
i seem to have tried everything but the correct path, 
i have attached the motioneye.log 
please can you advise

[motioneye.log](https://github.com/ccrisan/motioneyeos/files/7875796/motioneye.log)

**Comment by starbasessd** [comment]
Your log indicates you have a bad path.

If up are using motionEyeOS, then:
If you are trying to save via Settings, File Storage, Storage Device, Network Share, the 
Network Server is the IP address of the SMB Server
SMB Protocol Version is whichever version your NAS supports.
Share name would be (probably) /surveillance but might be /volume1/surveillance
Username and Password as appropriate
Root Directory is usually /

If you are using Upload Media Files, then you need the FTP or SFTP settings for your NAS.
Similar as above.

If you are using motionEye on another OS, then look at how to map drives using fstab for your particular OS.

**Comment by mstewart81** [comment]
tried changing to as stated /surveillance & as per image i have rooted to Guest so it doesn't need a username, although i have tried both does it come from the camera IP or the Motioneye IP for the Guest to the NAS?
i have updated the log 
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/7875877/motioneye.log)
![image](https://user-images.githubusercontent.com/43047240/149637025-fa39f791-83ab-4fce-97c7-118962657f26.png)

**Comment by starbasessd** [comment]
motionEye IP address.

**Comment by starbasessd** [comment]
It's not https:// it has to be smb://
for a Samba/SMB/CIFS Share

**Comment by starbasessd** [comment]
motionEye prefers using JUST the IP address for the server.

**Comment by mstewart81** [comment]
still having the issue can't map network share any other ideas?
![image](https://user-images.githubusercontent.com/43047240/149637984-ae539a48-ea2d-466c-b531-dcb45078082f.png)

**Comment by starbasessd** [comment]
JUST the ip address. 
Username and password
motionEye doesn't understand guest with no password...

**Comment by mstewart81** [comment]
have updated username & password now but still not, have given full access to the user surveillannce including applications
but still same error
![image](https://user-images.githubusercontent.com/43047240/149638306-4405842e-c31b-465b-9b82-90f58285fe8d.png)

**Comment by mstewart81** [comment]
changed to a custom path and got it working

**Comment by mykgroup** [comment]
Hi  masterwart81 couldyou share a picture of that custom path? I'm having the same issue storing recordings in my Synology using smb. Nothing works imusing a pi zero with Motioneye OS

**Comment by starbasessd** [comment]
![image](https://user-images.githubusercontent.com/20134429/152087267-ae473d5f-03fd-4678-9e56-db0002fe45ab.png)
I use motionEyeOS dev20201026 for my PiZeroWs.
You may need to adjust SMB Protocol Version depending on your Synology NAS. Start at 1.0, Click Apply, then test, Repeat by increasing Version until you get Success.
![image](https://user-images.githubusercontent.com/20134429/152087632-61fcffdb-8225-4fa5-b988-d188dab59557.png)
I also suggest you start at the Base of the Share, and slowly move up. As above, the Base name of the share is 'Share_Drive1', then the next folder is 'motioneye' on my NAS. Both work fine, with the above settings.

**Comment by mstewart81** [comment]
i find Synology Surveillance Station better to use for my situation so no longer using Motioneye, it was a toss up for me i had 2 cameras on both but Synology clipped the post

**Comment by mykgroup** [comment]
It worked. thanks. Although I might use Synology surveillance It looks better initially.
