### ISSUE TITLE
NoIR Camera Interference after IR Blasters turn on

### ISSUE THREAD

**Issue by Xadro3** [ccrisan/motioneyeos#2864]
### Preliminary Docs
I have read all the docs

I am running motionEyeOS version: 20200606

### Board Model

I am using the following board/model: RPI 0 with the camera ribbon, i think thats 1.3
### Camera

I am using the following type of camera: MMAL

My camera model is: Generic IR camera with IR LEDS and a OV5647 sensor in the middle

My motionEyeOS unit is connected to the network via:Wifi Dongle

I am using the following peripherals that I consider relevant to this issue:

NETGEAR WG111 GR wifi dongle
2.5A HTC charger as PSU

### Issue
My issue arises after the IR LEDs are turning on, after a few minutes i get horrible interference on my stream, i have reseated the cables multiple times, but as the camera ribbon connector on my Pi is damaged i can not rule it out 100%.
While the IR LEDs are off i have no issues whatsoever.
![image](https://user-images.githubusercontent.com/22886138/149801431-19c203d3-8256-40a3-8db7-cdedb732a32b.png) 
![image](https://user-images.githubusercontent.com/22886138/149801528-8efbddf4-3047-43e0-bb4e-5c214cbe9415.png)

### Log Files

I consider the following log files relevant to this issue:
 
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/7883109/motioneye.txt)
[boot.txt](https://github.com/ccrisan/motioneyeos/files/7883110/boot.txt)
[messages.txt](https://github.com/ccrisan/motioneyeos/files/7883111/messages.txt)
[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/7883112/dmesg.txt)
[motion.txt](https://github.com/ccrisan/motioneyeos/files/7883115/motion.txt)

**Comment by starbasessd** [comment]
Your messages log cuts off just before the time shown in the snapshot above. Can you either extend the log, or give another time that it happened to compare the log?

**Comment by Xadro3** [comment]
It happened yeterday after 16:30 or 17:00 until sunrise, no exact time for that though, there  should be a  bunch of restarts in the log at that time as i tried to troubleshoot it, couldnt find anything camera related going through the message log myself 

1.3, camera no wifi, confirmed

**Comment by starbasessd** [comment]
RPi0 v1.3 is camera but no wifi. V1.1 is camera with wifi. Version is on the back.

**Comment by starbasessd** [comment]
1st I'd try to get a power supply, not a cell phone charger.
I'm not sure what all you have connected, but if your setup works with the IR lights off, but has issues with the IR lights on. If you have WiFi dongle, GPS (getting time from GPS indicated in messages) Camera, and IR Lights, you are probably having power issues. If you can SSH in to console when having the issue, run the command:
> vcgencmd get_throttled

and report the number here. You aren't overheating, so that's good.
2nd you might try the dev20201026 version of motionEyeOS, but I doubt that will resolve your issue.

**Comment by Xadro3** [comment]
throttled=0x0

is what i get, i have the WiFi Dongle and the camera connected, the camera comes with IR LEDs so those are not seperate, operated by sensores on the board, no GPS, can i update the FW without flashing? because i mounted it real final.... (very smart yes...)

EDIT: I forgot to add i have a super long USB cable, like 2-3 Meters at least, if thats relevant

**Comment by starbasessd** [comment]
It can have issues, but if you want to try:
Settings, Expert Settings, Enable Prereleases
Apply at the top
Settings, General, Software Update, Check.
Should prompt you to update to dev20201026

**Comment by Xadro3** [comment]
I've been updating for the last 1.5h, should it take that long? i dont have webserver access anymore but ssh is still fine 
Edit: Top reporting, not much 
![image](https://user-images.githubusercontent.com/22886138/149821606-8f7a811c-cd7a-430e-b3cd-3d836a7f6f33.png)
am rebooting

**Comment by starbasessd** [comment]
No, it should have rebooted after a few minutes. You might try command
> reboot

but I'll bet something got corrupted.

**Comment by Xadro3** [comment]
reboot aint doing much :D
pulling sd card, wish me luck on my ladder
Updated it, didnt change anything with my issue
![motioneye](https://user-images.githubusercontent.com/22886138/149824733-25a392f5-f38a-4242-8f3f-db916e07920e.gif)

also cant seem to access settings anymore <-- Fixed it <-- Nope still broken

**Comment by Xadro3** [comment]
Rolled back to latest stable version and changed over to a different usb cable, now working as intended.
