### ISSUE TITLE
Does Motioneyeos work on the Raspberry Pi Zero 2 W?

### ISSUE THREAD

**Issue by MrAppAndCrap** [ccrisan/motioneyeos#2867]
Hi there,

Does the Motioneyeos work on the Raspberry Pi Zero 2 W? If so, which os version do I download for it?

Thank you

**Comment by starbasessd** [comment]
Jawsper has contributed a build that works on PiZero2W [here](https://github.com/ccrisan/motioneyeos/issues/2827#issuecomment-967737252) but there is no "Official" build, yet.
