### ISSUE TITLE
I can't connect to wifi using Raspberry Pi Zero W2 - Resolved

### ISSUE THREAD

**Issue by MrAppAndCrap** [ccrisan/motioneyeos#2876]
Issue fixed: Thanks @starbasessd 

Solution: https://github.com/ccrisan/motioneyeos/issues/2876#issuecomment-1023596728

Hey there,

So i'm using the the latest modified version of MotioneyeOS for RPI Zero W2 modified by @jawsper. 
I am trying to connect it to set up my wifi preconfiguration files but it will not connect. 

I have tried:

Connecting to my home wifi router (talk talk one).
Connecting to my Phone Hotspot.

With no luck. 

My old RPI zero w orginal connected fine to my home wifi and phone without a problem. 
(The sdcarder port broke so I can't use it anymore) 

Any tips? 

Can you see anything wrong with my config file? (I'm uk based)

       country=GB
        update_config=1
        ctrl_interface=/var/run/wpa_supplicant
        
        network={
            scan_ssid=1
            ssid="AndroidAP"
            psk="Mypassword"
        }

I save it using notepad++ and encode it. It still gets seen as a text file - is that ok? 

Any help?

**Comment by starbasessd** [comment]
Missing part of a line and a whole line:

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GB

network={
&nbsp; &nbsp; &nbsp; ssid="AndroidAP"
&nbsp; &nbsp; &nbsp; psk="Mypassword"
&nbsp; &nbsp; &nbsp; key_mgmt=WPA-PSK
}

**Comment by MrAppAndCrap** [comment]
I'm using the config template suggested in the EyemotionOS wiki [](https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration) So I'd hope nothings missing.

Just tried your version - still no luck

**Comment by starbasessd** [comment]
Do you have a monitor & keyboard attached, or another Pi you can put the SDCard in?

**Comment by starbasessd** [comment]
Unfortunately, that link points into the ThingOS Wiki, is somewhat out of date, and I don't have access to change it there. RPi Foundation [recommendations](https://www.raspberrypi.com/documentation/computers/configuration.html#adding-the-network-details-to-your-raspberry-pi) is in the format I posted here.

**Comment by starbasessd** [comment]
Make sure there isn't a .txt extension (wpa_supplicant.conf.txt) in the filename, too.

**Comment by MrAppAndCrap** [comment]
> Make sure there isn't a .txt extension (wpa_supplicant.conf.txt) in the filename, too.

Nope there isn't .txt in the name but is still showing as a text file.

Nope, my mini hdmi cable has gone missing. Just went looking round the house for it. I have a feeling a family member got to it so it's basicially as good as gone now lol. 

The only way I'll be able to access it it via wifi. 


![Screenshot 2022-01-27 200026](https://user-images.githubusercontent.com/26773315/151435227-0163fef3-d5ae-4ba2-94b3-fbdf3c7a71c4.png)

**Comment by starbasessd** [comment]
It IS saving as a .conf.txt file. Look at the tab where you are editing it.
In Windows File Explorer Go To View at the top, and towards the right , check the box for File Name Extensions. Then take the .txt off the filename.

**Comment by MrAppAndCrap** [comment]
Oh FFS, yes that was the problem, embarrassing lol. 

That worked, amazing, thank you so much @starbasessd d :) saved the day. 

They should update the wiki to include a screen shot and the updated code really.

**Comment by starbasessd** [comment]
Like I said, I wish I could. If @ccrisan gives me access to ThingOS I will, otherwise I may break that link and write a whole 'nuther page for it. If you are working, please close it.
