### ISSUE TITLE
Is this still being worked on

### ISSUE THREAD

**Issue by Steeleshh** [ccrisan/motioneyeos#2895]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (motionEyeOS dev20201026).

### Board Model

I am using the following board/model: (Raspberry pi 4).

###question

I was wondering if this project was still being worked on or is it not?

**Comment by starbasessd** [comment]
Not currently, there is a new group of developers working on motionEye, but not motionEyeOS.

**Comment by starbasessd** [comment]
See: https://github.com/ccrisan/motioneyeos#readme

**Comment by Steeleshh** [comment]
Thank you, we currently use your program for our business so were just wondering
