### ISSUE TITLE
Raspberry Pi rev2 is too slow

### ISSUE THREAD

**Issue by mouatte** [ccrisan/motioneyeos#29]
Hi,

motionEyeOS is great, but i have a Rasberry PI rev2 (512mo de ram) and in motion detection mode, the CPU is up to 90% and is too slow to detect, send mail ...

This device is the lower speed of the devices compatibles. But for the motionEyeOS, what is the best card ?

Thanks

**Comment by ccrisan** [comment]
I would use the RPi2, if you want streaming, motion detection and notifications on the same board.
