### ISSUE TITLE
IR lighting

### ISSUE THREAD

**Issue by dmarkscouk** [ccrisan/motioneyeos#290]
Is it possible to activate an IR light such as BrightPi, when motion is detected?

Also having just got this up and running, this is awesome! :)

I'm about to try and link a few together :)

**Comment by andreacampanella** [comment]
Why you want to do something like that? You need the light on to let the camera see in the dark otherwise you will never have motion detection...

**Comment by dmarkscouk** [comment]
@andreacampanella - Good point! Thankyou.
