### ISSUE TITLE
Hello, I have make a mistake with the port numbers and no I don't have access to web interface of my camera...

### ISSUE THREAD

**Issue by acroch** [ccrisan/motioneyeos#2915]
Hello I have make a mistake and no i don't have access anymore to my camera via the web interface...
I could stream with IPadress:8081 but that's all
Somebody now if there is an alternative methods than flashing the SD card.

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: not sure but

### Board Model

I am using the following board/model: Raspberry PI 3B+.

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: RPi 2 NoIR.

### Network Connection

My motionEyeOS unit is connected to the network via: WIFI.

### Peripherals

none

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by starbasessd** [comment]
You can SSH into the motionEyeOS, you can use keyboard and monitor, and edit the /data/etc/motioneye.conf file
You would want to change the 'port' line from whatever you changed it to, back to 80.
The normal port for motionEyeOS WebGUI though is port 80 (just http://ip_address without a port number)
motionEye on another OS like RaspberryPiOS WebGUI is port 8765

**Comment by starbasessd** [comment]
Any word?

**Comment by acroch** [comment]
Hello,
Thanks for your answer, i was in vacations for few days.
I have try to connect via SSH I have a negative answer... Network error Connection refused...
I can access to the rpi via FTP but not SSH, I probably didn't open the access.

I will reflash the card tanks for your help.
