### ISSUE TITLE
BUG: Videopreview in Webinterface not working

### ISSUE THREAD

**Issue by invisan** [ccrisan/motioneyeos#293]
Hi Crisan,

i changed a few settings in the Webinterface of motioneyeos.
When i changed the Streaming Port the page stopped to show me the Preview Stream.
In the Streaming URL window above the Port the old port is still located.
This is the issue for the Preview Stream as well. 
According to the Sourcecode when viewing with firefox the Port seems to be hardcoded.
This happens only if i choose to use the fastcam.

If i disable the fast webcam though there are some other issues.
I am not able to flip the video image horizontal or vertical anymore.
Plus the authentication for the stream is not working. 
It does not matter if i choose Basic or Digest. Nothing is happening.
I can access the stream without the need of a login.

Would be great if you could fix that or tell me where the Webinterface is located so i could fix it myself.

**Comment by bortek** [comment]
please post your question on forum page if this is still intreresting
