### ISSUE TITLE
Uploading to google drive stops once admin password is set

### ISSUE THREAD

**Issue by juntek** [ccrisan/motioneyeos#294]
Uploading captured movies to google drive works only when admin password has not been set.
Once I set the password motioneye stops uploading movies. I use RPI3

**Comment by ccrisan** [comment]
Please attach your `moitioneye.log` file.

**Comment by juntek** [comment]
Sorry for delay, log attached. Pretty much normal, reboot at 21:09:33 relates to admin password setting.

[motioneye.log.zip](https://github.com/ccrisan/motioneyeos/files/268978/motioneye.log.zip)

**Comment by ccrisan** [comment]
There's nothing suspicious in your log file. If you change your admin password back to what it was before, do your media files get uploaded to Google Drive?

**Comment by juntek** [comment]
Yes, upload to Google Drive is resumed once I bring empty admin password back.

**Comment by ccrisan** [comment]
Can you please enable Debugging in Expert Settings, change your password again so that it won't work, leave it running as much as needed for some media files to be created and send me the motioneye.log file again?

**Comment by juntek** [comment]
I think I've found the culprit. Upload to Google Drive doesn't work if admin password contains a $ sign. I've tested it with the two passwords: admin1234 and admin$1234

**Comment by ccrisan** [comment]
Good to know. I'll look into it and get back to you asap.

**Comment by ccrisan** [comment]
Fixed with https://github.com/ccrisan/motioneye/commit/2890653304c1e5dedd2d1c4b64cb92903d0a7fbc.

**Comment by rushless** [comment]
Hi, 

I had this issue also, this thread helped me thank you. In my case I had an @ sign that was causing the issue not a $. Thought it might help you troubleshoot.

**Comment by ccrisan** [comment]
The issue was valid for all special characters.
