### ISSUE TITLE
Can't seem to correct the Mirror Image

### ISSUE THREAD

**Issue by ryanpwest** [ccrisan/motioneyeos#297]
I have the Raspberry Pi 3 and the Camera Module V2 and the image is appearing mirrored.
I cannot find an option in the settings to enable/disable mirrored image.

I came across the following thread about putting a command in rc.local but rc.local never appears to run on its own.
https://github.com/ccrisan/motioneyeos/issues/278

**Comment by b0rnwr0ng** [comment]
I've been having this problem, too and came across this--  following the last two posts on that thread worked for me (adding to the S99showinfo file)

**Comment by gavros** [comment]
If you are using the motioneyeos image, you can fix this by doing the following:

ssh into your device
create this file using the nano command:
nano /data/etc/userinit.sh
add the below line into the userinit.sh file
v4l2-ctl --set-ctrl horizontal_flip=1
save and reboot your device.
