### ISSUE TITLE
Lastest Raspberry Pi 4 Model B build says it is to old for Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by Ryu945** [ccrisan/motioneyeos#2983]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606

### Board Model

I am using the following board/model: Raspberry PI 4B

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

Mentions the software is to old to run on the board.

For some reason, the latest software will not boot  on Raspberry Pi 4 Model B.  It says the software is to old for the board.

**Comment by mr-dhakal** [comment]
Yes I am also facing the same problem. And I am not able to do my school project because of this.

**Comment by starbasessd** [comment]
In this thread https://github.com/motioneye-project/motioneyeos/issues/2772 there is a discussion for the EEPROM issue. Good eeprom dates are from 9/2020 through 4/2021 
Here's another thread: https://github.com/motioneye-project/motioneyeos/issues/2892

**Comment by starbasessd** [comment]
BTW, you HAVE TO USE dev20201026 for Pi4s.
https://github.com/ccrisan/motioneyeos/releases
[Pi4 dev20201026 official](https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz)

**Comment by mr-dhakal** [comment]
when I download and extract the file for raspberry pi 4 it says windows.iso file rather than image file

**Comment by starbasessd** [comment]
I just downloaded it and extracted with 7zip, and the file name is:
motioneyeos-raspberrypi4-dev20201026.img
You may have that file extension (img) associated with ISO files in windows.

**Comment by mr-dhakal** [comment]
yeah the extension is .img but the file type is windows.iso

**Comment by mr-dhakal** [comment]
In the process I downloaded the file
-then write it on my sd card
-made the hardware connection of the raspberry pi
-then to find the ip address i went to the command prompt and run the command arp -a
but I was not able to get the ip address for my raspberry pi

**Comment by mr-dhakal** [comment]
I don't know what is the major reason for that

**Comment by mr-dhakal** [comment]
![image](https://user-images.githubusercontent.com/127873755/225078729-2594ac4a-09e7-4e53-ba68-7bf2060b6d3d.png)

**Comment by starbasessd** [comment]
For the IP address you can use (at the command line prompt on the Pi)
> ip a

or

>ifconfig

**Comment by Ryu945** [comment]
> BTW, you HAVE TO USE dev20201026 for Pi4s. https://github.com/ccrisan/motioneyeos/releases [Pi4 dev20201026 official](https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz)

I tried that version and I still get the same problem.  Do I have to flash firmware on the Pi as well?

edit:  Apparently the answer is yes.

> The older bootloaders can be found [here](https://github.com/raspberrypi/rpi-eeprom/tree/master/firmware/old)
> Depending on how far you want to go back, they are also found in the folder tree:
> /usr/lib/firmware/raspberrypi/bootloader/ in the stable, beta, and critical folders

**Comment by starbasessd** [comment]
You do if the bootloader is reported older than 9/2020 or newer than 4/2021.
run command:
>vcgencmd bootloader_version

What do you have?

**Comment by Ryu945** [comment]
> You do if the bootloader is reported older than 9/2020 or newer than 4/2021. run command:
> 
> > vcgencmd bootloader_version
> 
> What do you have?

I think I just flashed the bootloader. to 4/29/2021 and it still gives me that problem.  I am guessing it was meant to be newer then April.  April is not included.

**Comment by starbasessd** [comment]
If it was already newer than 04/29/2021 then there are reports of not being able to flash back to earlier versions correctly, and have it recognize motionEyeOS dev20201026. At that point, you would have to use motionEye on Raspberry Pi OS Buster (Legacy) if you want to use a CSI (ribbon cable) camera, or you can use Raspberry Pi OS Bullseye if you only need USB or Network cameras.

**Comment by Ryu945** [comment]
> If it was already newer than 04/29/2021 then there are reports of not being able to flash back to earlier versions correctly, and have it recognize motionEyeOS dev20201026. At that point, you would have to use motionEye on Raspberry Pi OS Buster (Legacy) if you want to use a CSI (ribbon cable) camera, or you can use Raspberry Pi OS Bullseye if you only need USB or Network cameras.

I was going to try the March version.   That download doesn't have an image file.   It is just a folder.   Do I just use DD to write the folder to the SD card?

**Comment by starbasessd** [comment]
pieeprom-2021-04-29.bin (Apr 29 2021) file is here: 

> /lib/firmware/raspberrypi/bootloader/stable 

in a clean image. (not the motionEyeOS image)
To apply it:

> sudo rpi-eeprom-update -d -f /lib/firmware/raspberrypi/bootloader/stable/pieeprom-2021-04-29.bin

and reboot

**Comment by Ryu945** [comment]
> pieeprom-2021-04-29.bin (Apr 29 2021) file is here:
> 
> > /lib/firmware/raspberrypi/bootloader/stable
> 
> in a clean image. (not the motionEyeOS image) To apply it:
> 
> > sudo rpi-eeprom-update -d -f /lib/firmware/raspberrypi/bootloader/stable/pieeprom-2021-04-29.bin
> 
> and reboot

I used the SD card version of the 04/29/2021 image:   [rpi-boot-eeprom-recovery-2021-04-29-vl805-000138a1-sd.zip](https://github.com/raspberrypi/rpi-eeprom/releases/download/v2021.04.29-138a1/rpi-boot-eeprom-recovery-2021-04-29-vl805-000138a1-sd.zip)

Using no commands and just powering on the device seems to apply it.

It didn't work so I am trying to figure out how to apply March's version since that is also a compatible version.   The problem is March's version was never prepared in an image file.  I am trying to figure out how to write that to the SD card.

**Comment by starbasessd** [comment]
You need a current RPiOS image to boot from, then run the 2 commands from above to see what is currently in the eeprom and apply the specific rpi-eeprom. Then rebbot, and run the first command again.

**Comment by starbasessd** [comment]
pi@raspi5:~ $ vcgencmd bootloader_version
Apr 29 2021 17:11:25
version c2f8c388c4ee37ad709ace403467d163e8dd91ce (release)
timestamp 1619712685
update-time 1621697261
capabilities 0x0000001f

Mine boots motionEyeOS appropriately, from SDCard and USB memory stick...

**Comment by Ryu945** [comment]
> pi@raspi5:~ $ vcgencmd bootloader_version Apr 29 2021 17:11:25 version c2f8c388c4ee37ad709ace403467d163e8dd91ce (release) timestamp 1619712685 update-time 1621697261 capabilities 0x0000001f
> 
> Mine boots motionEyeOS appropriately, from SDCard and USB memory stick...

Thankyou. That at least tells me to stop trying to get the March version working.  On my own Pi, I notice that even though I have the 4-29-21 bootloader, it says I have the 2019 firmware.   Does that need to be updated?

**Comment by Ryu945** [comment]
> sudo rpi-eeprom-update -d -f /lib/firmware/raspberrypi/bootloader/stable/pieeprom-2021-04-29.bin

I assume this is a command you apply in a linux terminal while you have the board connected via USB?  Where do I install this tool?  How do I open the terminal into updating a Raspberry Pi 4B?

edit:  Apparently, that command is not typed on a seperate computer.  it is typed on the Pi's terminal

**Comment by Ryu945** [comment]
> If it was already newer than 04/29/2021 then there are reports of not being able to flash back to earlier versions correctly, and have it recognize motionEyeOS dev20201026. At that point, you would have to use motionEye on Raspberry Pi OS Buster (Legacy) if you want to use a CSI (ribbon cable) camera, or you can use Raspberry Pi OS Bullseye if you only need USB or Network cameras.

It is not possible to use Bullseye I assume for the CSI cable camera?

**Comment by starbasessd** [comment]
Buster Legacy is only 32 bit. They (RPi Foundation) made a number of changes when they upgraded from Buster to Bullseye, breaking a number of functions in Python and other system calls preventing a lot of applications from working like they used to with CSI cameras. If you do not need CSI camera functions, you can use Buster Legacy, or either of the Bullseye (32 bit or 64 bit) images.

**Comment by Ryu945** [comment]
> pi@raspi5:~ $ vcgencmd bootloader_version Apr 29 2021 17:11:25 version c2f8c388c4ee37ad709ace403467d163e8dd91ce (release) timestamp 1619712685 update-time 1621697261 capabilities 0x0000001f
> 
> Mine boots motionEyeOS appropriately, from SDCard and USB memory stick...

I tried to boot Buster and I just get a color palette screen.

**Comment by Ryu945** [comment]
I may be wrong on some things.   I noticed I was working with microsd cards that worked well enough to give the illusion that there was no problems but the microsd cards have some problems.  This caused MotionEyeOS to not boot and I suspect caused other issues with Raspbian OS (both legacy and new).   Changing the microsd cards fixed the problem.  I don't know what is a software issue and what is a microsd card issue so I will be closing this because I don't know what actually caused which problems.
