### ISSUE TITLE
RPi Zero W hangs on *Starting motion eye:

### ISSUE THREAD

**Issue by ThunderClap86** [ccrisan/motioneyeos#2987]
I was following the wiki and pulled the image from there. Used raspberry pi imager and fixed the first problem with the wpa_supplicant.conf, now it gets to the starting motioneye line and hangs for a couple minutes then initiates the shutdown as imaged in the attached picture. 
![E38BC753-9552-4267-849F-58B000D51911](https://user-images.githubusercontent.com/105729168/230655621-0c15ea09-a180-4bec-b3ab-129ebd3d5163.jpeg)

This is a fresh install and has never been operational before. I was just hoping to have some fun with this RPi 0w, but I am stubborn and want to make this work. Can anyone help?

**Comment by MichaIng** [comment]
It is probably not the issue, but be careful when changing something via RPi Imager on any other image than official RPi OS. Probably better to use a flasher which has not even the capability to touch anything within the image file, like Rufus or balenaEtcher.

**Comment by ThunderClap86** [comment]
Okay, Ill try to give the image file to Rufus and see if that corrects my issue.

**Comment by ThunderClap86** [comment]
> It is probably not the issue, but be careful when changing something via RPi Imager on any other image than official RPi OS. Probably better to use a flasher which has not even the capability to touch anything within the image file, like Rufus or balenaEtcher.

![image](https://user-images.githubusercontent.com/105729168/230695884-54b8dcb7-1666-447a-b9f4-b2ce3c4838bc.jpeg)

Formatted and re-imaged using unmodified file through Rufus. 

Needed wpa_supplicant.conf to get past the first hangup with wired configuration. It made it to the same hang. Not sure what to try next.

**Comment by starbasessd** [comment]
I recommend [dev20201026 for RPiZero](https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi-dev20201026.img.xz)

**Comment by ThunderClap86** [comment]
> I recommend [dev20201026 for RPiZero](https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi-dev20201026.img.xz)

I am re-imaging with rufus now. Ill update in a few when it's done and powered on.

**Comment by ThunderClap86** [comment]
> I recommend [dev20201026 for RPiZero](https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi-dev20201026.img.xz)

This image seems to have fixed the issue. Thank you!
