### ISSUE TITLE
After changing admin password motioneye always asks for login credentials twice.

### ISSUE THREAD

**Issue by juntek** [ccrisan/motioneyeos#300]
Scenario:
1. Change admin password
2. Reset
3. Login

**Comment by ccrisan** [comment]
It does, but this only happens right after you change your password. Or does it happen thereafter all the time?

**Comment by juntek** [comment]
Only once after I change my password.

**Comment by ccrisan** [comment]
That's normal and it wouldn't be easy to fix it. Sorry.
