### ISSUE TITLE
Can't access motioneye IP

### ISSUE THREAD

**Issue by githupandgo** [ccrisan/motioneyeos#3017]
### Preliminary Docs
I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.
I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version
How do i check?

### Board Model
OrangePi Zero 2W
Running Ubuntu 22.04.3 LTS

### Camera
USB Logi 720P

### Network Connection
Both Lan and Wif

### Peripherals
USB keyboard/mouse

### Log Files
Where do i find the log file?
journalctl -u motioneye > motioneye.log = no response
find . -name motioneye.log = no result

### Issue:
Install via this link without issue: https://github.com/motioneye-project/motioneye/wiki/%28Install-On-Ubuntu-%2820.04-or-Newer%29

Can't access IP while on LAN or WAN.
Ping just fine
SSH in just fine with putty.

**Comment by starbasessd** [comment]
Use the same IP in:
http://ip_address:8765

**Comment by githupandgo** [comment]
> http://ip_address:8765

Thank you, that did it!!!

**Comment by starbasessd** [comment]
Nice and simple.

**Comment by Boba1980Fet** [comment]
Hello. I have the same issue with my raspberry pi 4. The ip address doesn't appear. What do you mean by saying to use the same ip???

**Comment by starbasessd** [comment]
Use the IP address of the Pi. If the Pi gets the ip address 192.168.1.23, you would use the web url http://192.168.1.23:8765. If you are using motionEyeOS instead of motionEye on another OS, you would use just the web url http://192.168.1.23

**Comment by Boba1980Fet** [comment]
Yes but the issue is that the raspberry doesn't give any ip. When I start the device I get no ip.

**Comment by starbasessd** [comment]
Hook up a monitor to the Pi if running motionEyeOS, it gives you the ip address during the last of the boot up.
Hook up a monitor and keyboard if running motionEye on another OS, log in, and enter 
> ip a

in a terminal window and it will show you the IP addresses.
Look in your router's DHCP leases. Most Pi mac addresses begin with dc:a6:32 or b8:27:eb but it may show the meye-xxxxxx name.
Run a program like AngryIP or AdvancedIP scanner if running windows
There are MANY different ways to find the ip address.

**Comment by Boba1980Fet** [comment]
Well I did it. I hooked a monitor to raspberry but it doesn't start. I installed in another card the Raspberry pi os and everything worked fine. I was able to see my ip and the screen worked fine.
I reinstalled the motioneye os to an empty card following all the github motioneyeos  instructions and again same issue. 
No screen no ip. The pi  is booting and the screen is empty,black and I try to scan the ip but nothing. 
It's weird. The os img is not the proper or I am doing a mistake...

**Comment by starbasessd** [comment]
At the beginning, you post it as an OrangePi Zero 2W, then we started talking Raspberry Pi.
The OrangePi Zero 2W was released around Oct 2021, more than a year after the last images were created. There isn't a valid image for it. I would load a valid OS (Buster or Bullseye version of Debian or Ubuntu) and build/install motionEye from [here](https://github.com/motioneye-project/motioneye/wiki/Installation)

**Comment by githupandgo** [comment]
Yea I started it with orangepi and he NOT me added Rpi.

> At the beginning, you post it as an OrangePi Zero 2W, then we started talking Raspberry Pi. The OrangePi Zero 2W was released around Oct 2021, more than a year after the last images were created. There isn't a valid image for it. I would load a valid OS (Buster or Bullseye version of Debian or Ubuntu) and build/install motionEye from [here](https://github.com/motioneye-project/motioneye/wiki/Installation)

**Comment by githupandgo** [comment]
Question answered for my thread.
