### ISSUE TITLE
Not able to change Dropbox credentials

### ISSUE THREAD

**Issue by konraaad** [ccrisan/motioneyeos#302]
At one time I had Dropbox enabled and it was working fine. For a brief time I used Google Drive, but as it is impossible to enable subfolders I wanted to switch to Dropbox again.

I already had the cancelled the MotionEyeOs permissions on my Dropbox and therefore tried to obtain a new authorization code. But whenever I enter it and test the service I get an error message saying: 
"Accessing the upload service failed: 'Dropbox' object has no attribute '_refresh_credentials!"

How can I fix this and enable my Dropbox account again.

![screen shot 2016-05-22 at 13 51 51](https://cloud.githubusercontent.com/assets/12102085/15453851/3f33f1f0-2025-11e6-930a-54b447979703.png)

**Comment by ccrisan** [comment]
It's been fixed upstream. It'll be available with the next release.
