### ISSUE TITLE
WiFi Config Panic

### ISSUE THREAD

**Issue by MrWxlfz** [ccrisan/motioneyeos#3032]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running the latest motionEyeOS version.

### Board Model

I am using the following board/model: Raspberry Pi Zero W

### Camera

I am using the following type of camera: Logitech Webcam
My camera model is: Logitech G290 PRO (same as example)

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:
None

### What the prob is:

So I have a Raspberry Pi Zero and I correctly setup the configuration for Wireless because it does not have a ethernet port but when I boot it up it says this;

"Configuring wired network: no device"
"panic: rebooting in 110 seconds (caused by network)

I don't no exactly what this is because I have basically no experience with Linux because this is my first time using well.. Linux.

Can someone help?

**Comment by starbasessd** [comment]
Which version of motionEyeOS did you use, specifically? I suggest using dev20201026
How did you configure WiFi on the PiZeroW?
Which version of PiZeroW are you using? There is a line on the bqack o9f it that starts with Raspberry Pi Zero. What is the rest of that line?
Does your wpa_supplicant.conf file look like:
= = = = =
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="your_SSID"
    psk="your_password"
}
= = = = =
If you created it on a Windows machine, is the file name wpa_supplicant.conf or wpa_supplicant.conf.txt ???
