### ISSUE TITLE
No computer name in Samba

### ISSUE THREAD

**Issue by Petreleslie** [ccrisan/motioneyeos#304]
Finally got the Motioneyeos camera working with my network storage. thanks for all your good work and for continuing support. (Made a donation today)

The network storage works with my second Raspberry Pi as a NAS but only with its IP address. I would like to be able to use the NAS computer's name. Windows computers on the network see it but the Motioneyeos Raspberry doesn't work with the name only the IP address.

Does samba need some addition config to make this work? 

![motioneyeos](https://cloud.githubusercontent.com/assets/14812294/15456429/45a25d82-2035-11e6-8aa7-02f042f65886.jpg)

And is there a way to make the a larger camera preview on the right pane?

Thanks for sending this newbie in the right direction.

**Comment by ccrisan** [comment]
It should work with the name as well. How do you know it doesn't work with the NetBIOS name?

P.S. Check the preferences/layout in order to adjust the frame size.

**Comment by Petreleslie** [comment]
Preferences! Who knew? Thanks. 
BTW the help files must not be installed correctly for me. Clicking on any question mark shows nothing.....
The screenshot shows what happens with the NetBios name. This is the name in the Windows machine and from running nbtstat at a Windows command line. I've tried adding a forward backslash and also leaving it off, giving the same result. 

![name](https://cloud.githubusercontent.com/assets/14812294/15474702/9a1f177e-20cb-11e6-8121-c751ee28211f.jpg)
