### ISSUE TITLE
Support for Pi Camera V2 Module?

### ISSUE THREAD

**Issue by Mariusmssj** [ccrisan/motioneyeos#306]
I could not find any information if the current Motioneyeos supports the new Pi Camera V2 Module which is the 8 megapixel camera?

I don't want to buy the new camera module if it's not supported.

Thank you

**Comment by ccrisan** [comment]
It will be 100% supported by the next version (soon to be released).

**Comment by Mariusmssj** [comment]
That's lovely to hear :) I will buy the module today.
