### ISSUE TITLE
Idea: network sniffing for devices for auto-on/off instead of schedule

### ISSUE THREAD

**Issue by petermolnar** [ccrisan/motioneyeos#308]
I have an idea, but being entirely new to motioneyeos, I don't know where to start implementing it. 
In short: a tcpdump sniffing or querying the router for connected devices could reveal what MAC addresses are present on the network. This would be useful to automatically turn the camera on or off depending if certain devices (mobile phones, mostly) are present on the network or not. This way there might be no need for schedules for some.

So the questions: are they any ways to script motion detection, recording and camera states from the command line?

**Comment by felixgr** [comment]
@petermolnar - did you work on this? I plan to work on this.

@ccrisan any comments from your side?

**Comment by ccrisan** [comment]
Nobody is working on this as far as I know, given the fact that motionEye currently lacks a way to programmatically control motion detection and I'd need to implement it myself.

**Comment by felixgr** [comment]
Thanks for the reply. Indeed, if there is no command line utility, that makes such a feature harder to implement. I might give it a try and report back in case of success.
