### ISSUE TITLE
Possible add ODROID-W distro/instructions

### ISSUE THREAD

**Issue by x893** [ccrisan/motioneyeos#310]
Hello,
can you add instruction (and distro) for [ODROID-W](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G140610189490) ?

**Comment by ccrisan** [comment]
I don't own one of those but in theory they should work with the RPI 1 OS. Don't they?

**Comment by x893** [comment]
Some changes (additions) in power management.
Sources for additional devices available on github.
But in general compatible with RPi.

**Comment by ccrisan** [comment]
I'd need to get my hands on such a device first.
