### ISSUE TITLE
Raspberry Pi Zero reboot loop.

### ISSUE THREAD

**Issue by SpaceDoge** [ccrisan/motioneyeos#313]
I'm using a CanaKit wireless dongle to get internet since the RPI0 doesn't have a wired connection. MotionEye won't detect it and stops at "Configuring wired network: no device". Is there any way around this?

**Comment by ccrisan** [comment]
The next version will have the up-to-date Raspbian kernel. Assuming the new Raspbian kernel supports your device, the next motionEyeOS release will support it as well.

**Comment by SpaceDoge** [comment]
Good to know. Thanks!
