### ISSUE TITLE
Wireless Issue

### ISSUE THREAD

**Issue by likozhang** [ccrisan/motioneyeos#314]
Driver Tplink TL-WN725N cannt connect
not support ?

**Comment by likozhang** [comment]
starting wpa_suplicant : failed (r8188eu)

**Comment by kieranc** [comment]
I would test it using Raspbian. If it works in Raspbian but not Motioneyeos, it might be a bug. If it doesn't work in either, it's probably not supported.

**Comment by likozhang** [comment]
@kieranc yea, i try to install driver R8188EU but many syntax cannt used
thankyou for try helping
