### ISSUE TITLE
Compatible 802.11AC drivers

### ISSUE THREAD

**Issue by mehtaman** [ccrisan/motioneyeos#315]
Hi,

Please could someone let me know which WiFi drivers are pre-loaded into MotionEyeOS?

My Pi3 works fine with its built in wireless N.
My Pi2 needs a hard reset everyday so I can reconnect over web.

I am currently using a 802.11n TP-Link dongle but I think due to location signal might be week.

I am looking for an AC dongle that will work out the box and does not require a powered hub to operate.

Thanks

**Comment by bortek** [comment]
if stil interested please post your question in the forum page.
