### ISSUE TITLE
Odroid C1 latest version: 20151103 not for Odroid, for RPi???

### ISSUE THREAD

**Issue by mitchsfm** [ccrisan/motioneyeos#32]
Please check the latest version: 20151103 for Odroid C1, it appears to be for the RPi. The image does not work with an Odroid C1.

Thanks,
F Mitchell

**Comment by ccrisan** [comment]
I updated the link. Thanks for letting me know about the problem.

**Comment by mitchsfm** [comment]
Thank you! I'm setting up a spare Odroid C1 as a security camera, so thanks
for the update.

And I really appreciate your efforts, the motionpie/motioneyeos software is
outstanding!

F. Mitchell
Opelika, AL


On Thu, Nov 19, 2015 at 3:59 PM, Calin Crisan <notifications@github.com>
wrote:

> I updated the link. Thanks for letting me know about the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrisan/motioneyeos/issues/32#issuecomment-158211218>.
>



-- 
"There is a rank due to the United States, among nations, which will be
withheld, if not absolutely lost, by the reputation of weakness. If we
desire to avoid insult, we must be able to repel it; if we desire to secure
peace, one of the most powerful instruments of our rising prosperity, it
must be known that we are at all times ready for war."
George Washington, 1793
