### ISSUE TITLE
No wifi on motioneye Pi 3

### ISSUE THREAD

**Issue by Galaxyflyer** [ccrisan/motioneyeos#320]
I just bought a Pi3, installed the latest motioneye OS and configured the wifi details. When unplugging the cable and rebooting, motioneye doesn't detect the wifimodule of the Pi3, so it loops into reboot.

**Comment by ccrisan** [comment]
Can I see your boot.log file?

**Comment by Galaxyflyer** [comment]
[boot.log.txt](https://github.com/ccrisan/motioneyeos/files/292944/boot.log.txt)

**Comment by ccrisan** [comment]
Are you absolutely sure your device is a Raspberry PI 3 and the OS image you have downloaded is the Raspberry PI 3 version?

**Comment by Galaxyflyer** [comment]
It is a raspberry Pi3... I might have used the same version as the on my Pi2's... I'll reinstall and let you know... thanks! Any ideas on the #319 issue?

**Comment by Galaxyflyer** [comment]
Problem solved! Thanks for the swift reply!
