### ISSUE TITLE
Is it possible to run rpi as wifi AP?

### ISSUE THREAD

**Issue by cone63** [ccrisan/motioneyeos#322]
Scenario: 2-3 webcam attached to rpi 2 with wifi adapter. Using motioneyeos. Rpi serves as wifi access point (no external router). Connect to wifi from smartphone/tablet to view images. Setup is driven by power bank and is easy to move around.

Is that possible with motioneyeos ?

Regards Claus

**Comment by ccrisan** [comment]
There's no support for AP in motionEyeOS and there are no plans to add and maintain such a feature. Sorry.

**Comment by cone63** [comment]
Ok I will figure out something else.
Thanks for the answer
