### ISSUE TITLE
Email and drive/ dropbox issues

### ISSUE THREAD

**Issue by graphicted** [ccrisan/motioneyeos#323]
Hello seems like i'm unable to receive email notifications and unable to upload the motion movies to Dropbox or Google drive.

checked in the motioneye.log and saw this error 🎱 

2016-06-04 13:33:34: [sendmail]    ERROR: failed to send mail: timed out
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 208, in on_message
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 52, in send_mail
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
timeout: timed out

No idea which is the log for the network sharing.
thanx a lot!

**Comment by Gordon-1** [comment]
I don't know if this is related but I just upgraded to 20160410 and discovered that M-OS stopped sending email.. I found that the contents of the fields for the email settings were shifted one place.  I re-entered my email settings and it is OK now.

**Comment by ccrisan** [comment]
There were some changes to the email parameters but I had hoped they were backwards compatible (it turns out they are not).

**Comment by barkingdoggy** [comment]
I'm running 20160605.  Here's what I'm getting trying to email to smtp.gmail.com using TLS on port 587...

2016-06-10 17:34:35: [sendmail]    ERROR: failed to send mail: [Errno -2] Name or s
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 208, in on_me
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 52, in send_m
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
gaierror: [Errno -2] Name or service not known

**Comment by ccrisan** [comment]
Your DNS server is misconfigured.

**Comment by barkingdoggy** [comment]
I don't think so.  When I ssh to the device I can ping google.com
successfully.

On Sat, Jun 11, 2016 at 11:12 AM, Calin Crisan <notifications@github.com>
wrote:

> Your DNS server is misconfigured.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ccrisan/motioneyeos/issues/323#issuecomment-225368775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF1waKNzwvY-f8i-rTHC-VmS6KHHT1uoks5qKtBjgaJpZM4IuHT5>
> .
>



-- 
John Redmond
Keystone Computer, LLC
Cell: 240-486-6370

**Comment by ccrisan** [comment]
Are you sure your SMTP server is correctly spelled (smtp.gmail.com)? If yes, can you ping smtp.gmail.com from via SSH?

**Comment by barkingdoggy** [comment]
D'oh!
I had smpt

On Mon, Jun 13, 2016 at 9:08 AM, Calin Crisan <notifications@github.com>
wrote:

> Are you sure your SMTP server is correctly spelled (smtp.gmail.com)? If
> yes, can you ping smtp.gmail.com from via SSH?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ccrisan/motioneyeos/issues/323#issuecomment-225575437>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF1waG9tXjTEr5HSwbfmStKLf4z9pNAiks5qLVY0gaJpZM4IuHT5>
> .
>



-- 
John Redmond
Keystone Computer, LLC
Cell: 240-486-6370

**Comment by ccrisan** [comment]
I'm glad you found the problem. I'll close the issue now.

**Comment by barkingdoggy** [comment]
Sorry to bother you.  Thank you for helping me see the problem.  Thank you
for your good work on Motioneye!

On Mon, Jun 13, 2016 at 3:33 PM, Calin Crisan <notifications@github.com>
wrote:

> I'm glad you found the problem. I'll close the issue now.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ccrisan/motioneyeos/issues/323#issuecomment-225684125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF1waBEujqokeVpmwGZX_Gw69APazJenks5qLbCWgaJpZM4IuHT5>
> .
>



-- 
John Redmond
Keystone Computer, LLC
Cell: 240-486-6370
