### ISSUE TITLE
Using both wifi and wired network connections with a fixed IP

### ISSUE THREAD

**Issue by AUSF** [ccrisan/motioneyeos#325]
I'm successfully running motionEye on an RPi and I can use both wireless and wired interfaces at the same time. I'd like to have a fixed IP on both interfaces, but with the current GUI it's possible to define only one address, assigned to wifi. Is there a way to set a fixed IP also for eth0 (using the SSH console)?

Thanks!

**Comment by ccrisan** [comment]
Static IP on both interfaces won't be possible with motionEyeOS. If you must have that, please use Raspbian + motionEye.

**Comment by AUSF** [comment]
Thank you!
