### ISSUE TITLE
Raspberry config.txt should not contain overclocking info by default

### ISSUE THREAD

**Issue by moritzmhmk** [ccrisan/motioneyeos#326]
When using the Pi zero the default overclocking settings ("none") make it run slower then its intended 1Ghz because config.txt sets the frequency to 700Mhz explicitly instead of having it commented when set to "none" (see http://raspberrypi.stackexchange.com/questions/38897/overclocking-capabilities-of-pizero).

**Comment by ccrisan** [comment]
I'll take care of that before the stable release.

**Comment by ccrisan** [comment]
fixed with ae439f579b376cd79a9acc36ace33e7ebfe1f23f
