### ISSUE TITLE
WIFI disconnect

### ISSUE THREAD

**Issue by drknstrmyknight** [ccrisan/motioneyeos#327]
I'm having trouble with falling off the WIFI network, tried a couple of AP's that other devices seem to stay connected to - what are the optimal settings to keep Motioeyeos connected and reconnect as necessary?

**Comment by ccrisan** [comment]
The reconnection should happen automatically. Make sure the signal is powerful enough. Also see [Wireless Connection Problems](https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems).
