### ISSUE TITLE
Where is the image for RPi Zero?

### ISSUE THREAD

**Issue by pmidhun** [ccrisan/motioneyeos#329]
Hello,

In the latest pre-release, I see that you have added support for RPi Zero. But I dont see an image for RPi Zero specifically. Does it mean that I can use any of the RPi 1 or 2 or 3 image for RPi Zero? Or am I missing anything here?

Thanks,
Midhun,

**Comment by ccrisan** [comment]
Pi Zero is a variant o RPI 1 A+ in fact. As soon as the I release the stable version I'll make sure to add this remark to the supported devices page.

**Comment by pmidhun** [comment]
Great! Thanks.
