### ISSUE TITLE
Raspberry PI USB WiFi dongle not supported

### ISSUE THREAD

**Issue by agassner** [ccrisan/motioneyeos#33]
Hi,

I'm getting an error running on a Raspberry Pi 2 Model B with the official WiFi dongle - https://www.raspberrypi.org/products/usb-wifi-dongle/
Error:
```
usb 1-1.3: Direct firmware load for brcm/brcmfmac43143.bin failed with error -2
```
It seems that the firmware is not there.

I tested on Raspbian and it works fine. The firmware is at /lib/firmware/brcm/

Can you help on this?

Thanks for the brilliant work, well done!

Arthur

**Comment by ccrisan** [comment]
I'll make sure to include the required firmware in the next release.

**Comment by agassner** [comment]
Nice one, thanks.

**Comment by ccrisan** [comment]
The firmware has been added to the OS. It will be available with the next release.
