### ISSUE TITLE
Control robotized network camera

### ISSUE THREAD

**Issue by KKWait** [ccrisan/motioneyeos#330]
Hi Calin,

First, let me congratulate you for your hard and nice work ! 
I'm using motionEye with an USB web cam and it works like a charm, but now I'd like to upgrade with an IR IP robotized cam (like a Foscam). Is there a way (or is it planned) to let motionEye control the IP cam moves ?
Thanks !

**Comment by ccrisan** [comment]
There are no plans to add support for pan/tilt controls in the near future.

**Comment by KKWait** [comment]
Ok Calin thanks for your answer.
Keep moving forward, thanks again for your work
