### ISSUE TITLE
motion still running

### ISSUE THREAD

**Issue by Mayday171** [ccrisan/motioneyeos#332]
I disabled motion detection in the web GUI and reboot the system. After that there is still a progress called motion-mrdave. This progress should be stopped because it uses 12-14 % of the cpu.

System: Pi 3 with pi cam v2

**Comment by Mayday171** [comment]
btw movie recording is enabled in continuous mode and streaming, image recording and motion keep alive disabled

**Comment by bortek** [comment]
if stil interested please post your question in the forum page.
