### ISSUE TITLE
Feature Request: Trim Capture Area

### ISSUE THREAD

**Issue by Telain** [ccrisan/motioneyeos#334]
I'm using a Raspberry Pi B with the camera module for a peephole camera on my door. A large portion of the image is black by necessity. If possible, I'd like to capture a larger resolution image of just the active area.
![download](https://cloud.githubusercontent.com/assets/1679073/15944967/b3c50200-2e55-11e6-9048-ca0c959c5cbd.jpg)

**Comment by bortek** [comment]
Please post this request to Motioneye instead since AFAIK it is motionene not motioneyeos that hanled that part.
