### ISSUE TITLE
Update to 20160605 fails

### ISSUE THREAD

**Issue by greenlee** [ccrisan/motioneyeos#341]
When updating from 20160410 to 20160605 I immediately receive "The update process has failed!"
http://s000.tinyupload.com/?file_id=00680982196819884566

**Comment by greenlee** [comment]
Ah, I looks like i'm out of storage. testing now.

**Comment by greenlee** [comment]
Well apparently I lost access. I deleted the capture files using SAMBA, did a reboot and the system is not responding to http,smb, or ssh requests.
Guess Ill bring it inside and reimage the SD card.

**Comment by ccrisan** [comment]
A partial upgrade could have messed up things there.
