### ISSUE TITLE
Running Motion Eye OS w/o Ethernet Connection

### ISSUE THREAD

**Issue by lyounkins57** [ccrisan/motioneyeos#345]
Is this possible?
I've disabled the Network Link Watch and the Connectivity Watch under Expert Settings, but the OS continuously reboots. I'd like to run a Raspberry Pi 2 remotely w/o Ethernet and then recover it to view the collected images. Thanks in advance!

**Comment by ccrisan** [comment]
Nope, motionEyeOS is not designed to run w/o a network connection. Sorry about that.
