### ISSUE TITLE
AWB Off gives a green image

### ISSUE THREAD

**Issue by AlBaum** [ccrisan/motioneyeos#349]
Hi,
Completely new here, but discovered motioneyeos and starting to like it !
1. I was wondering whether there is a document somewhere explaining all the setting options. The question mark on the web interface does not work.
2. as the subject says, I am trying to disable the AWB, but when I turn it off I get a green image. Anything I am doing wrong ? I am using a NoIR PiCam on a PI3, with Fast Network Camera enabled.
   Thanks
   Alain

**Comment by cuddylier** [comment]
The question mark beside every option works fine for me on Chrome, you have to hover over it, don't click on it or anything else.

I'll leave 2. for someone else to answer.

**Comment by AlBaum** [comment]
Hi cuddylier, thank you for your reply !
 I will check maybe it's due to my browsers configuration.
