### ISSUE TITLE
Add remote motioneye cam

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#35]
I have tried to add second MotionEyeOS / RPi2 to the first MotionEyeOS / RPi2. Unfortunately, I receive an connection error. Is it because it is not possible to add Remote MotionEyeOS units to a unit already using its egt camera. 

To be used in a stand alone MotionEyeOS RPi2 in order to function as a hub MotionEye? Maybe it's just my URL syntax is wrong, but the device tries to connect, so I must believe it is correct. 

Can you briefly describe the requirements for a MotionEyeOS hub / RPi2. 
How many cameras will be able to handle? 
Being shown streaming tumbs from each camera? 

It's a great fine piece of software you have developed here. Great respect and gratitude for it. 

Craving someone design a 3D printable waterproof encloure to house it all.

Kind regards
Sune Bielefeldt
Denmark

**Comment by ccrisan** [comment]
What is the URL that you're using to add the first motionEye to the second motionEye? Normally everything should work fine as long as the versions of the two units are the same.

**Comment by SuneBielefeldt** [comment]
I use the following url: http://192.168.1.108:8081 and get connection error: request time out

Before that i have remove all other camera connections.

Se picture at dropbox link:
https://www.dropbox.com/sh/ouuryr2bta0zken/AABwbKLNbDY1zu_CJdkPBAgla?dl=0

**Comment by ccrisan** [comment]
Use the port 80, as that's where motionEye lives (http://192.168.1.108). Port 8081 is associated with the MJPEG streaming, which, when requested, never ends the response (thus giving a timeout when used as you did).

**Comment by SuneBielefeldt** [comment]
Dear Calin Crisan 

Have tried your instructions to connect a MotionEyeOs Remote Camera with http://192.168.1.108:80, but here too, the following error: Fail to connect to 192.168.1.108 port 80, no host to route. 

During connection is shown an example of the screen which is suggested as follows: 
Example: http: //examble.com: 8080/cam ... also here given an error: connection refused. 

See my dropbox link for screenshots from my experiments.
(https://www.dropbox.com/sh/ouuryr2bta0zken/AABwbKLNbDY1zu_CJdkPBAgla?dl=0)

**Comment by SuneBielefeldt** [comment]
Hello Calin Crisan 

Sorry, I had used a large H in the Http: // and it was evidently here the fault lay. 

Now everything works as it should and I'm glad and happy. 

Thinking that you might want to correct the example to show that to be used port 80 instead of 8080. 

Thank you for your amazing work with MotionEyeOs, it is a super project and the great work you put into it.

See my dropbox link for latest screenshots from my experiments with succes.
(https://www.dropbox.com/sh/ouuryr2bta0zken/AABwbKLNbDY1zu_CJdkPBAgla?dl=0)

**Comment by SuneBielefeldt** [comment]
Thanks a lot

**Comment by ccrisan** [comment]
Where exactly do you think I should correct the example?

**Comment by SuneBielefeldt** [comment]
Dear Calin Crisan.

On the screen "add camera" which indicate url to Remote MotionEye Camera says
"http://example.com: 8080/cams. The correct must be "http://example.com:80". 

I think it could be a great help when you, as inexperienced in MotionEyeOs first time trying to add a remote cam.

Sune

**Comment by ccrisan** [comment]
Yes, you're right. Thanks.

**Comment by SuneBielefeldt** [comment]
You are welcome 😊

**Comment by ioquatix** [comment]
This is a good suggestion and I was confused by it too.

**Comment by spyda96** [comment]
The easy way to add the other motion eye cam was just to copy the ip address from the other cam and past it into the gui. This works everything for me.
