### ISSUE TITLE
Raspbian Kernel Jessie ? ?

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#350]
Hello Calin Crisan

>> # 313
The next version will have the up-to-date Raspbian kernel. Assuming the new Raspbian kernel supports your device, the next motionEyeOS release will support it as well.

You write that the next version of MotionEyeOs will use a Raspbian kernel. Does that mean MotionEyeOs say goodbye to Buildroot and future uses Raspbian Jessie, or perhaps Raspbian Jessie Light without Desktop?

**Comment by ccrisan** [comment]
None of the above. The current version of motionEyeOS uses the exact same kernel configuration as Raspbian, for Raspberry PI boards. It's still based on BuildRoot.
