### ISSUE TITLE
Wifi hotspot

### ISSUE THREAD

**Issue by yar0d** [ccrisan/motioneyeos#353]
Hello, do you have planned an option to make a WiFi hotspot?

PS: MotionEyeOs is really awesome - thank you !

**Comment by ccrisan** [comment]
Not in the near future. Sorry.

**Comment by latexink** [comment]
Can you point one to a guide to configure such a feature?

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
