### ISSUE TITLE
Different frame rate on still images / movies?

### ISSUE THREAD

**Issue by on9kim** [ccrisan/motioneyeos#354]
Hello, thanks for this great software from my heart.

i'm building a home security system with network camera looking at the door.
and I set motioneye, takes movie whenever motion is detected.
I feel at least 7fps to make a movie good to me.
But on the other side, i would like to set email notify me when motion detected as well.
and I found the pictures used to send email, are actually from Still images.
I would like 10 seconds of pictures , one per second. so total 10. in my email.
But now. if i input 10 in "attached pictures time span", it probably gives me 70 pictures isn't it?

Hope you understand what i mean, any suggestions?

Thanks very much.

**Comment by ccrisan** [comment]
You'll get at most 70 pictures in your email. In reality the number of pictures is considerably smaller since during a motion event the cpu is under a lot of stress and most likely won't be able to create that many photos.

Anyways there's no way around this that i know of.
