### ISSUE TITLE
no Web interface!! No login button!!

### ISSUE THREAD

**Issue by xDGameStudios** [ccrisan/motioneyeos#355]
When I reach for the IP of the Raspberry with MotionEyeOS, it loads the page with motionEye on the top right corner... but theres is no button on the top left corner. The camera is a HP HD 2300... and it worked (without motion detection in MotionPie) don't know what the problem might be! Some ideas?!

**Comment by ccrisan** [comment]
Try a ctrl+f5 to clear the browser's cache as you might have been using an older version of motionEye before.

**Comment by xDGameStudios** [comment]
Problem solves thank you very much
