### ISSUE TITLE
Was working fine, now shows grey "no-camera" image on web interface and ECONNREFUSED in motioneye.log

### ISSUE THREAD

**Issue by lenkawamoto** [ccrisan/motioneyeos#356]
I've had MotionEyeOS running on a Raspberry Pi 3 (using a PiNoir v1) for several months.  However, earlier this week, I noticed there were no motion capture movies stored on my network storage since about a week ago.  I logged in successfully to the web interface and initiated a reboot (via the web interface) just thinking that perhaps the RasPi lost its network connection to the share when I rebooted the server at around that time.  I logged back in to the web interface and everything looked fine, but after about 5 minutes of just watching the live view, I noticed at that it disappeared and the grey "no camera" image was displayed instead.  After poking around a bit (changing the video resolution, turning off and then back on the video device) with no affect, I noticed in my motioneye.log file a ton of lines that might be relevant:

2016-06-22 13:47:28: [motioneye]  WARNING: Connect error on fd 15: ECONNREFUSED

The above line is repeated about every second and is filling my log file.  It also seemed to start right about the time that my live video disappeared while I was watching it.

I then upgraded to the latest 20160605 image (from the previous version) using the built in upgrade mechanism hoping this problem would be fixed, but upon rebooting (following the successful upgrade to 20160605) the live video disappeared again after a few minutes.  Again, my log file (motioneye.log) shows the ECONNREFUSED messages starting about the time the live video disappeared.

Any suggestions on what might be the problem, how to fix it, and/or what additional information to provide?

Thanks!

**Comment by lenkawamoto** [comment]
I've determined that this is most likely a duplicate of #275.

However, I don't know why the symptoms started showing up recently when it was working well for several months.  Perhaps it was due to a recent package update to my Samba server.

I *do* notice many entries in motioneye.log like this:
2016-06-28 13:07:56: [motioneye]    ERROR: failed to unmount smb share "//r2d2/g2-9t" from "/data/media/motioneye_r2d2_g2_9t_g2"

though it's not as frequent as the "ECONNREFUSED" message I indicated earlier.


My file server information:
AMD64
Debian 8.5
samba 2:4.2.10+dfsg-0+deb8u3

smb.conf:
[global]
interfaces = xxx.xxx.xxx.xxx/24
bind interfaces only = yes
log file = /var/log/samba/log.%m
max log size = 1000
syslog = 0
panic action = /usr/share/samba/panic-action %d
server role = standalone server
passdb backend = tdbsam
obey pam restrictions = yes
unix password sync = yes
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
map to guest = bad user
usershare allow guests = yes

# Share for Raspberry Pi MotionEyeOS
[g2-9t]
path = /mnt/Data/g2-9t
force group = users
browsable = yes
write list = g2-9t
create mask = 0664
directory mask = 0775
# end of smb.conf

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
