### ISSUE TITLE
Sabrent Usb Capture Device showing grey camera icon

### ISSUE THREAD

**Issue by Hamburgler101** [ccrisan/motioneyeos#357]
so i got a usb video grabber at frys and pluged it into a rpi2 and it showed up as stk1160 so i added the camera and it connected but it doesnt show any feed just a grey camera logo and i know its not the video grabber of camera itself cause i can plug it into my laptp and it shows feed. please help! Thx!

**Comment by Tamps** [comment]
Got the same card and have the same problem. the picture is just white.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
