### ISSUE TITLE
New camera Model (USB)

### ISSUE THREAD

**Issue by Spectre1968** [ccrisan/motioneyeos#366]
Hi!

You would be connected via a USB camera ? the camera model is this : HQL5II (monocrome)
http://www.qhyccd.com/QHY5II.html

BestRegards

**Comment by ccrisan** [comment]
(assuming you're on Raspberry PI) if it works with Raspbian, it will work with motionEyeOS. If it doesn't then there's nothing I can do about it.

**Comment by Spectre1968** [comment]
HI!

Is the work there are several programs that use it in particular that :

https://sourceforge.net/projects/linguider/

The camera is for astronomical use .
