### ISSUE TITLE
RTSP 401 erroneous response

### ISSUE THREAD

**Issue by tvb** [ccrisan/motioneyeos#368]
I receive the following error:
<img width="440" alt="screen shot 2016-06-28 at 22 03 27" src="https://cloud.githubusercontent.com/assets/1263414/16430482/2eecd702-3d7c-11e6-8ed1-6d36b0645b95.png">

while I am sure the details are correct since I can connect to the cam via RTSP with VLC. 

I am running MotionEyeOs 20160605 on a raspberrypi2

**Comment by tvb** [comment]
Does anyone has an idea? Running MJPEG isnt the prettiest.

**Comment by ghostyroasty** [comment]
I have the same issue using an Amcrest prohd outdoor wifi bulletcam.

**Comment by ccrisan** [comment]
There have been a few users complaining about authentication issues with RTSP. However I have never been able to reproduce the problem. Would any of you be so kind and temporarily forward a port to such a RTSP camera with authentication enabled, so I can run some tests and see how credentials are passed?

**Comment by ghostyroasty** [comment]
E-mail sent to your gmail address.

**Comment by ccrisan** [comment]
Fixed with https://github.com/ccrisan/motioneye/commit/c3f900a1412698568c13f81cee3ed24a18070e19.
