### ISSUE TITLE
Can't upload pictures and movies to ownlcoud

### ISSUE THREAD

**Issue by Tobus** [ccrisan/motioneyeos#369]
Hello,
I'd like to know, if there is a possibility to upload instead of google drive/dropbox to a owncloud.

Best regards
Tobus

**Comment by parth15041995** [comment]
https://github.com/odeke-em/drive
I want to do the same thing 
this link might help
I didnt integrate but if you can let me know the steps

**Comment by ccrisan** [comment]
There are no plans to implement OwnCloud media file upload support. Sorry about that.

**Comment by dg1sek** [comment]
Could it work if I use the MotionEyeOS on raspberry as an external FTP storage (https://docs.nextcloud.com/server/9/admin_manual/configuration_files/external_storage_configuration_gui.html#storage-configuration) in nextcloud?
