### ISSUE TITLE
Multi Email addresses

### ISSUE THREAD

**Issue by vdyo** [ccrisan/motioneyeos#37]
Hi

It would be nice to have the ability to add more than one email for the alert to go to.

Regards

Damian

**Comment by ccrisan** [comment]
Well, you should already be able to do so. Have you tried adding multiple addresses separated by comma?

**Comment by vdyo** [comment]
I did before but not in this build. I will try now and report back.

**Comment by vdyo** [comment]
Ok, I did the comma and it now accepted the address, Thanks.
