### ISSUE TITLE
Workaround for faster recording framerate when motion is detected

### ISSUE THREAD

**Issue by fredericcollin** [ccrisan/motioneyeos#372]
As you know the recording framerate drops to about 2 FPS when motion has been detected, and ccrisan has acknoledged that it's an encoding bottleneck. Allocating more memory to GPU or overclocking the RPI doesn't help either. 
I have found a workaround which might benefit some of you guys, so here is how:
Instead of using one RPI for both capture and recording, I devide the task on 2 RPIs.
The first one with the camera module is used in "Fast Network Camera" mode. The second one in regular mode imports that (fast) camera stream as a "network camera" and processes motion detection, records images and movies. Now I can capture with 10FPS.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
