### ISSUE TITLE
Can't disable local images and movies

### ISSUE THREAD

**Issue by Tobus** [ccrisan/motioneyeos#374]
Hello,
is there any option to disable dropping images or movies to the local memory card?
When using a cloud service, may it is better to disable local images.

Best regards
Tobus

**Comment by ccrisan** [comment]
You can't do that given the way uploading to cloud is designed: images are first saved to the SD card and then they are asynchronously uploaded wherever they need to be uploaded.

**Comment by Tobus** [comment]
Hi Crisan,
ok that makes sense.

Thanks a lot
Tobus
