### ISSUE TITLE
Pi Zero v1.3, 20160605: libpython2.7.so.1.0 invalid ELF header

### ISSUE THREAD

**Issue by bhardie** [ccrisan/motioneyeos#377]
```
$ /etc/init.d/S85motioneye start
 * Starting motioneye: /usr/bin/python: error while loading shared libraries: /usr/lib/libpython2.7.so.1.0: invalid ELF header
```

Looks like the python build doesn't support the latest version of the pi zero (v1.3 with camera connector). The build does recognize the camera correctly though.  `raspistill` works.

**Comment by ccrisan** [comment]
Rewrite the OS image from scratch. Your SD card partition seems corrupted.

**Comment by bhardie** [comment]
(facepalm)
Thanks!
