### ISSUE TITLE
Unable to Obtain Autentication Keys

### ISSUE THREAD

**Issue by leeford** [ccrisan/motioneyeos#378]
Hi,

I've got the latest build running on a Pi 2. All working well, except when I select "Upload Media Files", select "Dropbox", click "Obtain Key" I get an error on the newly opened page:

{"error": "unknown upload service dropbox"}

Let me know if you need anything further.

Thanks.

**Comment by leeford** [comment]
Just to add, with "Google Drive" I get:

{"error": "unknown upload service gdrive"}

Thanks.

**Comment by ccrisan** [comment]
Is this 20160703?

**Comment by jeancazes** [comment]
I have the same problem 
same message 
v : 20160703

try with chrome and firefox.(just in case)

**Comment by ccrisan** [comment]
It's a known bug. I have already fixed it upstream with https://github.com/ccrisan/motioneye/commit/5def02069cc8c8818fc6e322561e542e592724a4. Thanks for reporting it though.

**Comment by leeford** [comment]
OK thank you.
