### ISSUE TITLE
Use motionEyeOS  behind proxy

### ISSUE THREAD

**Issue by nextgen1979** [ccrisan/motioneyeos#381]
Hi,  it's possible to set proxy setting in motioneyeos ? 

Thanks in advance 

Nicolas

**Comment by ccrisan** [comment]
Nope. There is no proxy support in motionEyeOS and there are no plans to add one.

**Comment by dazzag24** [comment]
+1 for http_proxy support.

**Comment by shanester64** [comment]
Why does base path setting exist (although it does not work)?

![image](https://cloud.githubusercontent.com/assets/10452329/16721552/c43ac05c-4705-11e6-8989-972d492ebc6f.png)

**Comment by ccrisan** [comment]
@shanester64 what do you mean it doesn't work? Have you tried it? By the way, it's meant for *reverse proxy* usage and has nothing to do with internal motionEye clients using a normal HTTP proxy (which is indeed not supported).

**Comment by shanester64** [comment]
I understand it is for reverse proxy. I have tried it on both stable and current pre-release on rp2.For example, upon changing the base path to /cams and rebooting I would get an error message not found (http://IP:port/cams).  Thanks,Ken Shane

**Comment by ccrisan** [comment]
You actually need to use a reverse proxy. Did you use Apache or Nginx or anything of that sort? Of course nothing will work anymore if you're just appending /cams to your motionEyeOS machine URL. motionEyeOS will still be accessed internally by your reverse proxy with its root URL / but all the static resources (images, scripts and so on) will be expected to be found at e.g. /cams.

I have been using it this way for a year now so I know for a fact that it works.

**Comment by shanester64** [comment]
Thanks for your input. I do use nginx, however I never configured it due to the errors (via internal). I will configure and test. Being somewhat new to nginx, based upon your input, can you access both internally and externally (nginx)?

Thank you,
Ken Shane

**Comment by ccrisan** [comment]
Nope, unless you use no base URL.

**Comment by shanester64** [comment]
So your confirming that changing the base url/path does not work.  Thanks,Ken Shane

**Comment by ccrisan** [comment]
I do not confirm that. I believe you have misunderstood how it works and how reverse proxies work in general.

**Comment by MiGeppert** [comment]
Hi ccrisan

Would you share your nginx configuration file part concerning the motioneyeos-proxy (and "special settings" in motioneye if necessary)?

I tried to proxy https://"myservername"/webcam on nginx to http://"webcamip"/ but I thinks I'm too stupid for this. I spent hours searching the internet without success!
The "best" thing I got is a white background with parts of the left side menu and no chance to login (instead of the dark background with login window). When I enter "/webcam" to the "Base Path" in the expert settings, I get the "white background" thing even when entering http://"webcamip"/ and have to log in via ssh to correct/delete the "Base Path" line in /data/etc/motioneye.conf to get http access to my camera.

Can you help me please?

Many thanks for making that great motioneye(os) software.

Best regards
MiGeppert

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.

**Comment by hiphophurray** [comment]
Hi, 

I've just tried to configure MotionEyeOS (Odroid XU4) and NGINX/Let'sEncrypt/DynamicDNS (Raspberry Pi 3B+) within my environment, internally (http://10.1.1.2:80) I can access the MEOS system perfectly and view my cameras however when I go to my external domain (https://sub.mydomain.com) address over port 443 (I do have 443>80 redirect on via CertBot/NGINX) I cannot see the MEOS web page correctly. I have looked and looked online for an answer for this but cannot find the answer. The last question above from MiGeppert seems to be quite close to what i'm looking to do. 

Can anyone please assist? I'm not willing to open port 80 to my server VLAN from the outside world hence the reasoning for NGINX.

I must also mention i want to access the MEOS web page from the base URL (/).

<img width="522" alt="screen shot 2018-12-28 at 14 42 34" src="https://user-images.githubusercontent.com/46223741/50518705-e55a5300-0aae-11e9-85d9-516847254fe7.png">

Thanks for any answers that may come.
Frank

**Comment by ccrisan** [comment]
@hiphophurray can we see your nginx config (at least the relevant part)?

**Comment by shanester64** [comment]
Here is my partial config..replace IP with your IP address 

location /cams/ {
        proxy_pass http://IP:8765/;
        proxy_read_timeout 120s;
        #access_log off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # SSL proxying headers
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_set_header    X-Forwarded-Ssl     on;        }

        location /mjpeg {
        proxy_pass http://IP:5888/;
        proxy_read_timeout 86400;
        #access_log off;
        proxy_set_header Host $host;  
        proxy_set_header X-Forwarded-Host $server_name;  
        proxy_set_header X-Real-IP $remote_addr;  
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        # SSL proxying headers
        proxy_set_header    X-Forwarded-Proto   $scheme; 
        proxy_set_header    X-Forwarded-Ssl     on; 
        }

Thank you,
Ken Shane

**Comment by MiGeppert** [comment]
Hi Ken Shane
Thanks for your config file - this works as long as I use the unsecure http:// connection (http://"myserveraddress.com"/xwebcam/), but when I use the secure connection (https://"myserveraddress.com"/xwebcam/) I got only a white page with four lines:
1. an empty pull down menu,
2. "Apply" (no link)
3. "webcam" (I think the name of my Motioneye-Cam)
4 "motionEye" (link to https://"myserveraddress.com"/xwebcam/)

I don't want to use my user:password with http :-(.

Note: both config files for Nginx were modified ("default" and "ssl-default")

Best regards
MiGeppert

**Comment by shanester64** [comment]
Here is the 1st part of my default config (replace mydomain.com with yours).

# Redirect http to https.    server {        listen 80;        server_name mydomain.com;        return 301 https://$host$request_uri;    }
# HTTPS Server    server {        listen 443 ssl;        server_name mydomain.com;
#        root /var/www/mydomain.com/html;        root /usr/share/nginx/html;        index index.html index.htm;
        ssl on;        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        ssl_session_timeout 1d;        ssl_session_cache shared:SSL:50m;        ssl_stapling on;        ssl_stapling_verify on;        add_header Strict-Transport-Security max-age=15768000;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';        ssl_prefer_server_ciphers on;        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        location ~ /.well-known {                allow all;       }
#       redirect server error pages to the static page /50x.html        error_page 500 502 503 504 /50x.html;        location = /50x.html {               root /var/www/mydomain.com/html;      }



 

Thanks,

Ken Shane

 
 

    On Thursday, January 3, 2019, 7:57:50 AM CST, MiGeppert <notifications@github.com> wrote:  
 
 
Hi Ken Shane
Thanks for your config file - this works as long as I use the unsecure http:// connection (http://"myserveraddress.com"/xwebcam/), but when I use the secure connection (https://"myserveraddress.com"/xwebcam/) I got only a white page with four lines:
   
   - an empty pull down menu,
   - "Apply" (no link)
   - "webcam" (I think the name of my Motioneye-Cam)   
4 "motionEye" (link to https://"myserveraddress.com"/xwebcam/)

I don't want to use my user:password with http :-(.

Note: both config files for Nginx were modified ("default" and "ssl-default")

Best regards
MiGeppert
