### ISSUE TITLE
Failed to Create Zip File?

### ISSUE THREAD

**Issue by micky2171** [ccrisan/motioneyeos#388]
![image](https://cloud.githubusercontent.com/assets/7550213/16710242/ae4cca56-461f-11e6-8351-07e871d4386f.png)

**Comment by ccrisan** [comment]
Please attach your motioneye.log file.

**Comment by itsMig** [comment]
Just in case one also searches for this issue.
I had a similar issue, the accompanying log resolved this case:

`ERROR: failed to create zip file "/data/output/.zip-1589633408": ZIP does not support timestamps before 1980`
