### ISSUE TITLE
request for rsync

### ISSUE THREAD

**Issue by mmmmmrob** [ccrisan/motioneyeos#39]
Great distro, working really great for me :)

I'd really like to configure rsync as a post-motion command but I can't see rsync in the build.

Could rsync be included? Or is there an alternative approach to pushing files up online?

Thanks

**Comment by ccrisan** [comment]
rsync is not part of motionEyeOS and will not be. Files can be stored on a network share. Google Drive, Dropbox, FTP, SFTP and generic HTTP support are on the way.

**Comment by ccrisan** [comment]
8a28d2c97adc3bcb7241b70751cd9000b77bcb0a adds the rsync binary to the image.
