### ISSUE TITLE
Feature request: user defined motion detection region

### ISSUE THREAD

**Issue by adriankwil** [ccrisan/motioneyeos#390]
Would you be able to add a feature where you are able to select a region in which motion is detected? So that any amount of motion is allowed outside the region, but recording is only triggered inside the region? This would be a very useful feature! Or is this already an option?

**Comment by ccrisan** [comment]
It's in the works.

**Comment by adriankwil** [comment]
Fantastic! Thanks.

**Comment by fredericcollin** [comment]
I approve 100%!

**Comment by timdonovanuk** [comment]
Request for useful title ;)

This feature is implemented now.

**Comment by jasaw** [comment]
Duplicate of issue #89.
Feature already implemented.
