### ISSUE TITLE
Adding external USB hard drive

### ISSUE THREAD

**Issue by surfexplorer** [ccrisan/motioneyeos#393]
I added a external usb hard drive to my motioneyeos.  When I choose the file storage / storage device pulldown menu I see the new hard drive but when I select it its still writing files to my SD card.  Do I need to do anything else?

**Comment by ccrisan** [comment]
Normally not. Can you please attach your config files (saved using the Backup button), after having removed any sensitive data?

**Comment by surfexplorer** [comment]
Which files contain sensitive data?  Thanks

**Comment by surfexplorer** [comment]
re-formatted my sdcard/motioneye os and I’m good to go now.  Files saving to external drive.

**Comment by ccrisan** [comment]
Well I'm glad you sorted it out.
