### ISSUE TITLE
Heartbeat - watchdog timer

### ISSUE THREAD

**Issue by veames** [ccrisan/motioneyeos#394]
Hi Caylen,

Was hoping you could tell me how to enable/add the watchdog timer feature as was in motionpi?

I am looking for the device to reboot every time it is unable to connect with the backend router/file repository. This fixes the situation where the pi looses wifi and has to be powered off manually.

thanks

**Comment by ccrisan** [comment]
It's enabled by default.

**Comment by TheKitro** [comment]
Hi 
When I stop the Server with:
meyectl stopserver -b -c /etc/motioneye.conf

after 120 sek I got an reboot.
How can i deactivate the autoreboot, when motioneye is manually forced offline.

thanks

**Comment by veames** [comment]
Why not use systemd? #systemctl stop motioneye

**Comment by TheKitro** [comment]
I got following results:

[root@meye-40 startstop]# systemctl stop motioneye.service
-sh: systemctl: command not found
[root@meye-40 startstop]# sh systemctl stop motioneye.service
sh: systemctl: No such file or directory
[root@meye-40 startstop]# systemctl stop motioneye
-sh: systemctl: command not found
[root@meye-40 startstop]# sh systemctl stop motioneye
sh: systemctl: No such file or directory
[root@meye-40 startstop]#

seems not working.

**Comment by ccrisan** [comment]
If you're on motionEyeOS you don't have systemctl, and you probably shouldn't stop motionEye or any other services manually :) However, if you must do that, add `meyewatch_disable="true"` to your `/data/etc/watch.conf`.
