### ISSUE TITLE
Ability to add SSL/TLS certificate through the UI

### ISSUE THREAD

**Issue by dmelliott0311** [ccrisan/motioneyeos#402]
Can you add a feature to enable a user to add a certificate to enable HTTPS connections to the Web UI? It feels a little insecure to log into the admin console using a password passed through HTTP.

**Comment by stllunatic** [comment]
I wonder if you could change the HTTP Port in the GUI to 443 to help achieve this? I was thinking the same  @dmelliott0311 

>  It feels a little insecure to log into the admin console using a password passed through HTTP.

>

**Comment by ccrisan** [comment]
I totally agree. However, the only way to go is to setup an HTTPS reverse proxy (such as nginx) on a separate machine. That server should handle all the SSL stuff. Changing the port to 443 is not enough, as the traffic would still be clear text HTTP.

**Comment by blah4-5078** [comment]
Definitely feels unsafe...
