### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by noxx2015** [ccrisan/motioneyeos#404]
Hello

today i try motioneyeos. 

i use a creative hd 720p (usb), motioneye detect the camera,
but i get a grey screen.

any idea?

regard

http://www.bilder-upload.eu/show.php?file=929eb5-1468945739.png

**Comment by noxx2015** [comment]
here my log files



[motion.log.txt](https://github.com/ccrisan/motioneyeos/files/372067/motion.log.txt)
[dmesg.log.txt](https://github.com/ccrisan/motioneyeos/files/372068/dmesg.log.txt)
[boot.log.txt](https://github.com/ccrisan/motioneyeos/files/372071/boot.log.txt)
[messages.log.txt](https://github.com/ccrisan/motioneyeos/files/372070/messages.log.txt)
[motioneye.log.txt](https://github.com/ccrisan/motioneyeos/files/372069/motioneye.log.txt)

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
