### ISSUE TITLE
update the installation for motioneyeos

### ISSUE THREAD

**Issue by freddii** [ccrisan/motioneyeos#408]
change the line from:
./writeimage.sh -d /dev/mmcblk0 -i "/path/to/motioneyeos.img" -n "yournet:yourkey"
to:
./writeimage.sh -d /dev/mmcblk0 -i "/path/to/motioneyeos.img" -n 'yournet:yourkey'

so you simply use ' instead of " for yournet:yourkey

cause otherwise you will not be able to use passwords with a "!" in it.

maybe also use a "sudo" at the beginning of the bash command.

**Comment by ccrisan** [comment]
You're right. Fixed.
