### ISSUE TITLE
Extra Motion Options incorrect after reboot

### ISSUE THREAD

**Issue by menrath** [ccrisan/motioneyeos#41]
Hi,

first off all thank you for the great support.
Unfortunately after every reboot the values in the Extra Motion Options changes from "on" to "true" or "off" to "false".

For example "output_secondary_pictures on" changes after reboot to "output_secondary_pictures true".
So motion doesn't understand the option and uses the default.

**Comment by ccrisan** [comment]
I'll look into it.

**Comment by ccrisan** [comment]
You were right. I fixed the problem and the fix will come with the next release. Thanks for reporting the issue.
