### ISSUE TITLE
Master / Client ?

### ISSUE THREAD

**Issue by noxx2015** [ccrisan/motioneyeos#410]
Hello

i want to use 3 Camera.

CAM1 is my "master", CAM2 and CAM3 my "client".

If CAM1 detect a motion, all 3 CAMs should record
a movie or make a picture...

is this possible (?), if not, set this to my wishlist.

:-)

regard

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
