### ISSUE TITLE
attached usb storage

### ISSUE THREAD

**Issue by rickmoua** [ccrisan/motioneyeos#414]
I have a 15G usb plugged in.  Is there a setting to just record over the old data when the drive is full or does it do that automatically.  I don't want to manually delete the files/folders out.  I just wanted it to remove older files when the drive runs out of space.

**Comment by Just-Incase** [comment]
I am also wondering about this.  I do not see any options to control this, or to store video to the USB.  Sorry if I am missing something.

**Comment by ccrisan** [comment]
I'll close the issue then :)
