### ISSUE TITLE
Failing to Update from 20160605

### ISSUE THREAD

**Issue by stllunatic** [ccrisan/motioneyeos#420]
I am using a Raspberry Pi 3 and would like to update to 20160705 from 0605. When I click Check for software update in the GUI it tells me that "MotionEye is up to date (current version: 20160605). Is there another method of manually updating? I'd like to avoid writing a new image and using the restore button if possible.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-noticed-a-new-version-has-been-released-why-does-my-motioneyeos-say-its-up-to-date.
