### ISSUE TITLE
TOR question

### ISSUE THREAD

**Issue by bre75** [ccrisan/motioneyeos#421]
Hello,

I'd like my Raspberr PI/MotionEyeOS to use TOR.
Little bit the same way as they are doing there : [https://home-assistant.io/cookbook/tor_configuration/](url) 

In MotionEyeOS source code, here [https://github.com/ccrisan/motioneyeos/blob/master/package/Config.in](url), i can see a reference to TOR :  source "package/tor/Config.in"

Does it mean MotionEyeOS already use TOR network ?

Else how could i achieve this ?

Thanks for your help.

Regards,

**Comment by ccrisan** [comment]
You can't use TOR with motionEyeOS. I recommend using Raspbian + motionEye instead if you need TOR.

**Comment by bre75** [comment]
Hi Calin,

Thanks for your answser.
Just for my curiosity what is the tor package in the MotionEyeOS source code ?

Instead of Raspbian + MotionEye, does a "Onion Pi" [https://learn.adafruit.com/onion-pi/overview](url) could do the job as well ?
