### ISSUE TITLE
RaspiCam v1.3 - Set max resolution ?

### ISSUE THREAD

**Issue by noxx2015** [ccrisan/motioneyeos#424]
Hello

in the datasheet i found the max resolution of the cam is 1920x1080.

how can i set this? the max of motioneyeos is 1600x1200

**Comment by PicoPi** [comment]
I have the same exact problem.
Also, when it records at 1270x720, the playback is speeded up!
version 20160801

**Comment by ccrisan** [comment]
Fixed with https://github.com/ccrisan/motioneye/commit/f1298c012312aee69e231d2831abab2c3d76a0a6 and https://github.com/ccrisan/motioneye/commit/d61858b0ad47a13428e850ee475619ac57e0af62.
