### ISSUE TITLE
IUK 5 A1 IP Camera

### ISSUE THREAD

**Issue by sakfus** [ccrisan/motioneyeos#426]
Hello  Ccrisan
Thank you for your project.
Is it possible connect IUK 5A1 IP camera ?

**Comment by ccrisan** [comment]
As long as it's an IP camera that supports MJPEG or RTSP and you enter the correct MJPEG/RTSP URL in the motionEye UI, yes.

**Comment by sakfus** [comment]
@ccrisan 
My computer is raspberrypi 3. 
URL is correct: `http://admin:passssw4@192.168.0.3:81/videostream.cgi?rate=11`
I dont see camera
[photo](https://1drv.ms/i/s!AqUy0DtEhbk8k3reRJVGryY90qOD)

**Comment by ccrisan** [comment]
Don't include credentials in the URL; use the username/password input boxes instead.

**Comment by sakfus** [comment]
It's working!
Thank you very much.
