### ISSUE TITLE
Software Update 20160320 don't update

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#427]
I have a new PRiV3 not update to the next release.
The current version is 20160320, and I have tried to activate the pre-release, but without success.

Is there something I've missed, or should I just put a new version manually?

The unit has been unstable and there are numerous outages streaming.
It has otherwise been running fine for a few months at up to 10 fps

![image](https://cloud.githubusercontent.com/assets/9556987/17271042/4be1d624-5671-11e6-8e23-5018c483ef89.png)

**Comment by ccrisan** [comment]
I cannot seem to reproduce your problem. Can you please attach your motioneye.log file here?

**Comment by SuneBielefeldt** [comment]
I think that WiFi connection was too weak. Moved device to my workshop, and here I could fine update it. The device is also stable here.

case Closed
