### ISSUE TITLE
Boot reloop eth has no IP address

### ISSUE THREAD

**Issue by thundergreen** [ccrisan/motioneyeos#428]
Hi 

After booting it shows the login screen. Everything seems to be fine, but then it says eth0 has no IP address. THe strange thing is that it shows up when it boots. I have a PI1 here with PiCam 2.1

anyone facing the same problem?

**Comment by ccrisan** [comment]
What ethernet adapter do you use? Are you by any change on the PI Zero with a USB ethernet adapter? If yes, it may be a known issue.

**Comment by thundergreen** [comment]
hi.. solved issue by taking a 2.1 A adapter.. it was not enough power on the pi .. thanks anyway... i close this issue.

GREAT work!

I use this with home assistant .. do u use it maybe also with home assistant?
