### ISSUE TITLE
Cannot use POST

### ISSUE THREAD

**Issue by mneumark** [ccrisan/motioneyeos#43]
I tried to create a Web Hook Notification, but whenever I change the HTTP Method from GET to POST, it fails to change anything. It looks like it went through but when I go back to the settings it says GET again.

**Comment by ccrisan** [comment]
The bug has been fixed in upstream motionEye and the fix will be included with the next motionEyeOS version. Thanks for reporting, though.

**Comment by mneumark** [comment]
Just for those who do encounter it, I worked around the issue by having motion trigger a command instead and using it to call `curl`.
