### ISSUE TITLE
cant configure wifi - Starting wpa_supplicant: failed (brcmfmac)

### ISSUE THREAD

**Issue by aristosv** [ccrisan/motioneyeos#430]
I am running motioneyeos 20160705 on a raspberry pi 3. When connected to Ethernet everything is OK. When I configure it for WiFi I get the below during boot. Its a fresh installation. How can I fix this?

---- booting motionEyeOS 20160705----
- Mounting filesystems: done
- Loading kernel modules: done
- Setting hostname: done
- Starting syslogd: done
- Configuring CPU frequency: done
- Starting watchdog: done
- Starting eudev: done
- Setting root password: done
- Starting wpa_supplicant: failed (brcmfmac)
- Configuring wireless network: no link
- Configuring wired network: 192.168.7.23/24
- Setting static gateway to 192.168.7.1: done
- Setting static DNS server to 8.8.8.8: done
- Setting current date using http: Mon Aug 1 13:23:30 EEST 2016
- Starting http date updater: done
- Starting crond: done
- Starting sshd: done
- Starting streameye: done
- Starting motioneye: done
  # Interface eth0 has IP address 192.168.7.23/24
  # Default gateway is 192.168.7.1
  # DNS server address is 8.8.8.8

**Comment by ccrisan** [comment]
Have you checked all the items from [here](https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems)?

**Comment by navigonic** [comment]
Same issue here, have checked all the items..

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
