### ISSUE TITLE
"An error occurred. Refreshing is recommended"

### ISSUE THREAD

**Issue by BenBelatrix** [ccrisan/motioneyeos#432]
Hi. I got this error message on my Android device (browser Chrome) after update to version 20160705. No problem prior to this update. No such an error on any desktop browser. Update to pre-release 20160801 doesnt help..

**Comment by ccrisan** [comment]
Try refreshing a few times the page on your android browser. I'm fairly sure this has to do with browser's cache.

**Comment by BenBelatrix** [comment]
Thanks for quick reply - was really local application problem (proxy) - sorry.
