### ISSUE TITLE
is the tcp/ip stack on motioneyeos compatible with ipv6?

### ISSUE THREAD

**Issue by ivr588** [ccrisan/motioneyeos#434]
Hi, 

Is the motioneyeos tcp/ip stack ipv6 capable?

thanks,

**Comment by ivr588** [comment]
also is it either ipv4 or ipv6 or is it dual-stack?

**Comment by ccrisan** [comment]
There's no ipv6 support in motionEyeOS.

**Comment by ivr588** [comment]
ok. thanks again for the prompt response.
