### ISSUE TITLE
Normal user only sees rotating circle, but no pic

### ISSUE THREAD

**Issue by maxl95** [ccrisan/motioneyeos#435]
Hello,

suddenly no "normal" user can view the images from the various Webcams, which I have configured. 
A "normal" user only sees the rotating circle but no pictures. 
When I log in as "admin" user, everything seems to be normal. 
I haven't changed anything. It occurred suddenly.

Of course I have tried to reboot, but that had no effect.

I attached the log files and two pictures for better understanding

Thanks

[boot.txt](https://github.com/ccrisan/motioneyeos/files/397171/boot.txt)
[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/397169/dmesg.txt)
[messages.txt](https://github.com/ccrisan/motioneyeos/files/397173/messages.txt)
[motion.txt](https://github.com/ccrisan/motioneyeos/files/397170/motion.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/397172/motioneye.txt)

Here i'am logged in as admin user:
![admin_user_view](https://cloud.githubusercontent.com/assets/15520385/17331666/34542a68-58cc-11e6-87e8-d962256d3af8.jpg)

and this is an normal user:
![normal_user_view](https://cloud.githubusercontent.com/assets/15520385/17331667/347cef70-58cc-11e6-8247-fadc8cd4b714.jpg)

**Comment by ccrisan** [comment]
I'm sorry I cannot seem to reproduce this problem. Can you please attach your configuration files (you can recover them using the Backup function), after *removing sensitive data* from them?

**Comment by ccrisan** [comment]
@maxl95 if you open the settings panel (after you have logged in with the normal surveillance user), what is the Preferences > Frame Rate Dimmer option set to?

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
