### ISSUE TITLE
size of the page?

### ISSUE THREAD

**Issue by coME973** [ccrisan/motioneyeos#436]
Hello,

How can I adjust the size of videos to the size of the page?

As when configuring.

Thank you

**Comment by ccrisan** [comment]
I'm not sure I understand what you want. Can you try to describe this on a screenshot (you could draw stuff on it)?

**Comment by coME973** [comment]
I would like to see all the camera (4).
But when I put 2x2. We see nothing.
![2x2](https://cloud.githubusercontent.com/assets/20799241/17345724/ca87012a-58dd-11e6-8f03-d1bcb153970f.png)
If I put it 4x1 are too small.
![4x1](https://cloud.githubusercontent.com/assets/20799241/17345718/c073743e-58dd-11e6-90c4-b14167d91afb.png)
I would like the 2x2 grid adapts to the size of the window.

In the configuration menu is always good.
![setting](https://cloud.githubusercontent.com/assets/20799241/17345720/c5b31dfa-58dd-11e6-9647-7cdb87fa6e66.png)
You understand?

**Comment by coME973** [comment]
Anyway your system very nicely on a raspberry2.
I perform tests to see possibilities for professional projects.
Currently project but I hope to convince, if I manage to run the Action Buttons, particularly movement.

Can we get you a gift.

**Comment by ccrisan** [comment]
Well it's quite hard to fit all frame sizes on all screens, preserving the *aspect ratio* of each frame (otherwise the image would look distorted). Ideally the "Fit Frames Vertically" could be a number (from 1 to 4) indicating how many frames to fit vertically within a window. In your case, it could be 2 (2x2). I'll take this into consideration for the next release.

**Comment by coME973** [comment]
It is not possible to change the size of the video with the parameters in /etc/motioneyes/thread-1.conf ?
Extra Motion Options:
width 160
height 120


I have changed but nothing to do, only the size of the text changes.

![taille](https://cloud.githubusercontent.com/assets/20799241/17463299/1181dcc6-5c99-11e6-902e-b48d80c34091.png)

**Comment by ccrisan** [comment]
Commit https://github.com/ccrisan/motioneye/commit/bd90ce107622bd2b961765468613972afcd4266b should help out with this issue. The next release will include this fix.
