### ISSUE TITLE
Stand-alone Video Recorder usage scenario

### ISSUE THREAD

**Issue by andrei-volkau** [ccrisan/motioneyeos#437]
Is It possible to make with help of motioneyeos a stand alone video recorder with the next features:
1) automatic restart of video recording after a power outage;
2) logging video to local usb HDD?

If It possible, say please few words about how to do It.

**Comment by ccrisan** [comment]
1) Yes - it happens automatically; just enable movies and choose how you like movies to be recorded (motion-triggered or continuously).
2) Yes - just choose your USB storage device in File Storage.

**Comment by andrei-volkau** [comment]
Without a wired connection on-board computer have endless reboot loop.
![1](https://cloud.githubusercontent.com/assets/12778567/17362491/f5b69784-597d-11e6-82c8-c852abc596fa.jpg)

I just want to preconfigure motioneyeos with help of motioneye. And after this, I want to use a single board computer with attached camera as a stand-alone dashcam without network connection.

**Comment by ccrisan** [comment]
Hi,

You can't do that with motionEyeOS. However if you must have that, manually edit `/etc/init.d/S40network`, look for the line that says `"no network connection available"` and remove the following `reboot` command.

For more details on how to edit files on the system partition, see [Tweaks](https://github.com/ccrisan/motioneyeos/wiki/Tweaks).
