### ISSUE TITLE
Can't View Feed From Web Configurator

### ISSUE THREAD

**Issue by AMP648** [ccrisan/motioneyeos#438]
When I go to the :8081 I can view the stream but not when I go to the Configuration page on :80. I don't know why this is. The Pi is setup over Wi-Fi. Also I have authentication on for the Stream page on :8081. I don't know if that makes a difference. This is what I see:

In the Configuration Page(80):
<img width="1024" alt="screen shot 2016-08-02 at 4 48 46 pm" src="https://cloud.githubusercontent.com/assets/9892074/17346712/b413e0e0-58d1-11e6-937a-972c0daf63bc.png">
In the Stream Page (8081)
<img width="1024" alt="screen shot 2016-08-02 at 4 49 11 pm" src="https://cloud.githubusercontent.com/assets/9892074/17346713/b4221598-58d1-11e6-9106-0be921ce83a7.png">

Log Files:
[raspimjpeg.txt](https://github.com/ccrisan/motioneyeos/files/398222/raspimjpeg.txt)
[streameye.txt](https://github.com/ccrisan/motioneyeos/files/398223/streameye.txt)
[boot.txt](https://github.com/ccrisan/motioneyeos/files/398224/boot.txt)
[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/398228/dmesg.txt)
[messages.txt](https://github.com/ccrisan/motioneyeos/files/398225/messages.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/398226/motioneye.txt)
[motion.txt](https://github.com/ccrisan/motioneyeos/files/398227/motion.txt)

If someone could please help me figure out a way to view the stream from the configuration page that would be awesome. Thank you.

**Comment by ccrisan** [comment]
I assume you have enabled Fast Network Camera. That's alright for streaming, but your browser might not be very happy with previewing mjpg streams. What browser are you on?

**Comment by AMP648** [comment]
I was using Safari for Mac

**Comment by ccrisan** [comment]
Have you tried another browser?

**Comment by AMP648** [comment]
Yes, It works with Chrome. Thank you for your help. I love this software.
