### ISSUE TITLE
New Camera added but motion is blurry

### ISSUE THREAD

**Issue by surfexplorer** [ccrisan/motioneyeos#439]
Just added a new ip camera to my motioneye (uokoo 720P IP Camera) but for some reason video playback and recording on motion eye is all blurry when capturing movement.  If I use the native web url the video is very clear and crisp and quality does not change when recording motion.  Any idea what I'm doing wrong?  Motioneye captures high quality video but just the movement is blurred.  My 10 year old USB camera works better and I just don't get it.

Thanks

**Comment by ccrisan** [comment]
What version is this? What video codec and quality have you chosen?

**Comment by surfexplorer** [comment]
version 20160705.  Not sure how to check video codec.  For recording quality I’ve tried 50% & 100% with same results.  Thanks

**Comment by ccrisan** [comment]
Hmm can we see a screenshot of how blurry your video is? 20160705 won't let you choose the codec so that can't be a problem.

**Comment by surfexplorer** [comment]
Very blurry as you can see here.  Still video and motion is crystal clear
when viewed using the built in camera web server.  Only blurry when used on
motioneye.  My USB camera on same system works just fine.  Thanks


[image: Inline image 1]

**Comment by ccrisan** [comment]
Please attach a screenshot (here, on github, not via email).

**Comment by surfexplorer** [comment]
[blurry.pdf](https://github.com/ccrisan/motioneyeos/files/413200/blurry.pdf)

**Comment by ccrisan** [comment]
Well this is definitely not something related to motionEye but rather motion itself or the v4l2 camera driver (or the camera itself). I wouldn't know how to fix this.
