### ISSUE TITLE
Still images don't attach to emails

### ISSUE THREAD

**Issue by cuddylier** [ccrisan/motioneyeos#441]
Hi

Still images refuse to attach to the notification emails and I've even had the notification emails stop sending altogether after a few days although that was on a slightly older motioneyeos version a few days ago. Here is part of my motioneye.log where I think the problem is: http://pastebin.com/raw/Hu55JdRL

I have tried various values for 'Attached Pictures Time Span' including '1' with no luck. Opening the image/video viewing interface in the web interface is quite slow which is probably linked to the email attachment issue I'm guessing. Browsing via samba or FTP is perfectly fine. SD card isn't a rubbish one so speed of it shouldn't be an issue.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
