### ISSUE TITLE
Path entry field for images and movies does not persist when toggled on/off

### ISSUE THREAD

**Issue by giac0m0** [ccrisan/motioneyeos#444]
It would be beneficial for the gui to retain a custom path when it is toggled on and off.

I change the default to:

```
%Y-%m-%d/Images/%Y-%m-%d_%H-%M-%S
%Y-%m-%d/Movies/%Y-%m-%d_%H-%M-%S
```

I like to clear the images every 48 hours (so the images can be attached to emails but don't fill the storage).   Movies clear out every week.

Each time I toggle the on /off selection, the path field resets to default.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
