### ISSUE TITLE
Motion Detection Doesn't Stop

### ISSUE THREAD

**Issue by cuddylier** [ccrisan/motioneyeos#449]
Hi

After a few days after rebooting motioneyeOS, it refuses to stop motion detecting when there is no motion after a while and therefore doesn't record/take pictures anything anymore. Screenshot attached.

![](http://i.spartanhost.net/kA7hsb7j.png)

motioneyeos.log: http://pastebin.com/raw/N1jt8m1h

**Comment by cuddylier** [comment]
Motion detection stopped working earlier today, it still showed as black in the web interface, it didn't show the red surround like the above image. I had to reboot for it to start detecting and recording again.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
