### ISSUE TITLE
File Storage Settings Not Showing Up

### ISSUE THREAD

**Issue by AMP648** [ccrisan/motioneyeos#453]
The file storage settings aren't showing up. The last section in my configuration page is video streaming.  Is this because of some of my settings?

[raspimjpeg.txt](https://github.com/ccrisan/motioneyeos/files/406222/raspimjpeg.txt)
[streameye.txt](https://github.com/ccrisan/motioneyeos/files/406225/streameye.txt)
[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/406227/dmesg.txt)
[boot.txt](https://github.com/ccrisan/motioneyeos/files/406223/boot.txt)
[messages.txt](https://github.com/ccrisan/motioneyeos/files/406226/messages.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/406224/motioneye.txt)
[motion.txt](https://github.com/ccrisan/motioneyeos/files/406228/motion.txt)

Sorry if this issue is due to ignorance on my part. I'm still new to this scene.

**Comment by AMP648** [comment]
This might be just because I've enabled Fast Network Camera. I didn't know you couldn't save stuff while on Fast Network Mode.

**Comment by AMP648** [comment]
Is there ever going to be a way to save files while using fast network camera?

**Comment by ccrisan** [comment]
Nope. That will be impossible given the fact that FNC doesn't use motion as backend.
