### ISSUE TITLE
Use without Internet

### ISSUE THREAD

**Issue by Just-Incase** [ccrisan/motioneyeos#455]
Hello,

I love this OS.  How can I use without a internet connection.  I want to use as a dashcam, but being it needs network to boot, I cannot.  How can I turn this off?

Thank you.

**Comment by Just-Incase** [comment]
I would pay to have this option.  I really want it.

**Comment by PiB4Dinner** [comment]
Ok you owe me Bitcoins! lol 

https://github.com/pageauc/pi-timolo
Look in the script of pi-timolo and compile the two or use pi-timolo only...
Time-lapse and motion recording. It works very well.
I have a 32GB card in mine and it is in a birdhouse; not for birds but for surveillance.  Bird hole covered by plexiglass and camera is inside the beast along with a DHT-22 Temp Humidity sensor. It has run non stop for a month and my card is not near full! 

-Wiz-of-OZ
Bitcoin, Cash, or Thanks is fine.

**Comment by PiB4Dinner** [comment]
NO INTERNET NEEDED

**Comment by Just-Incase** [comment]
@PiB4Dinner, how? Upon star up its looking for a network. How do you start the OS with a network? Thank you and have a great day.

**Comment by Just-Incase** [comment]
@PiB4Dinner

I just watched the You Tub videos- awesome. I look forward to trying this. Looks intense. Will report back.

**Comment by ccrisan** [comment]
Commit 16f67c02e056e2b7e9d6a4515ad580b3c959536c adds support for networkless configurations. Setting `link_watch="no"` in `/data/etc/watch.conf` will disable rebooting in case a network connection is not/no longer available.
