### ISSUE TITLE
Using noip client

### ISSUE THREAD

**Issue by karter2000** [ccrisan/motioneyeos#456]
Hello,

I need to use noip, as I need the port-forwarding feature.  Is it possible to setup the noip client with motioneyeos (using a pi)?

Thanks!

**Comment by cramaboule** [comment]
I agree with karter2000: can you add ddclient?
https://github.com/wimpunk/ddclient

Greetings!
Cr.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
