### ISSUE TITLE
notification in motion eye error

### ISSUE THREAD

**Issue by vm29** [ccrisan/motioneyeos#458]
hello?
we have an issue to set up the motion notification for our google account (gmail).
the error keep saying :

" Notification email failed:[Errno 97] Address family not supported by protocol! "

![capture](https://cloud.githubusercontent.com/assets/20984319/17613920/ab5c431e-6094-11e6-9b3e-8e27a55ea97e.PNG)

**Comment by ccrisan** [comment]
Does that happen when you press "Test Email"? Have you entered your SMTP password correctly? (it doesn't look so from the screenshot).

**Comment by vm29** [comment]
We already entered the smtp port but it still same. It cant be conduct
clearly as we enterted 587 for the port with gmail email..
should us have a try with another port or use another email account such as
yahoo?

On Aug 12, 2016 2:36 PM, "Calin Crisan" <notifications@github.com> wrote:
>
> Does that happen when you press "Test Email"? Have you entered your SMTP
password correctly? (it doesn't look so from the screenshot).

**Comment by vm29** [comment]
Oopps, my bad sir, I'll try to configure it again...if the problem still the same I will refer again with you..thank you

**Comment by kgestrich** [comment]
Hello,
I have get the same error message: " Notification email failed:[Errno 97] Address family not supported by protocol! " when I try the email connection with "Test Mail"
![motioneye_email_error](https://cloud.githubusercontent.com/assets/14964987/18557052/e49f2582-7b5c-11e6-8173-08f2a807dc8f.png)

Ich try to connect to a myname@gmail.com account. So far I have tried several variations to send out a notification mail - unfortunatly without any success...
- I changed the password to only contain small and capital letters and numbers. 
- the 2 step verification is turned off
- Less secure apps are allowed: https://www.google.com/settings/security/lesssecureapps
- signing in a new device https://accounts.google.com/DisplayUnlockCaptcha 
- I have no problem with the internet connection - I can ping the smtp.gmail.com server
- the password and username / email is working fine in the web-interface.

What should I change / try now? Have you got any idear or can I send you more information?

Thank you very much for your help in advance.
Greetings
Klaus (kgestrich)

**Comment by ccrisan** [comment]
See if port 587 works

**Comment by kgestrich** [comment]
:-D great it is working!
Thanks a lot!!! - and it was such a small stupid thing ...

**Comment by psycoppp** [comment]
Have the same problem and dont understand why.
I verify my adresse and pw, it's ok.
i used MotionPie (version 20150719) since a month, with the same mail, and it's work.
Yesterday, i install MotionEye, and it's dont work  :'(
The same Raspi, the same IP and the same mail.
Any idea ?
![mail_error](https://cloud.githubusercontent.com/assets/24374490/20868504/aa5b9104-ba5d-11e6-81fc-68b9ee84f373.jpg)
