### ISSUE TITLE
hostname with dot not supported

### ISSUE THREAD

**Issue by auban** [ccrisan/motioneyeos#461]
Hello,
I would like enter a hostname with dot but it not supported by the frontend.
Is there a reason?

Thank you

Auban le Grelle

**Comment by ccrisan** [comment]
What version do you use?

**Comment by auban** [comment]
I have install the last release.
motioneyeos-raspberrypi3-20160801.img

![network](https://cloud.githubusercontent.com/assets/13569836/17659012/0347cdae-62d0-11e6-9822-a6bf6de5afd1.JPG)

**Comment by ccrisan** [comment]
Ah, hostname changing is supported, but don't use special characters (remove the dot).

**Comment by auban** [comment]
I would like use a domain name

**Comment by ccrisan** [comment]
On a second thought, I believe there's nothing wrong with allowing dots in hostname. I'll make sure that the next version will allow dots in hostnames.

**Comment by auban** [comment]
Great many thanks

**Comment by kcranley1** [comment]
Continuing on from the Facebook conversation, I can assign a Surveillance Username of . (dot) with a blank Surveillance Password, but when I try to log in with those details, the rotating icons start, but just keep on rotating (ie it doesn't get any further).  My version is Current Version	20160801  What I really want to do is allow the video to be displayed on a web page without the need for viewers to log in.  I greatly appreciate your attention in this matter.

**Comment by ccrisan** [comment]
Normally the correct way to have a passwordless surveillance system is by simply clearing out the surveillance password while leaving the surveillance username to whatever it is (e.g. "user").

However I can see that in your case it doesn't work that way. Does the system still ask for credentials or it simply goes to the camera frames view where the actual video streams never show up?

**Comment by kcranley1** [comment]
It simply goes to the camera frames view where the actual video streams never show up

**Comment by ccrisan** [comment]
Alright. Could you please try opening the UI webpage in Chrome and then open the Developer Tools (Ctrl + Shift + J). After that, a printscreen of the Developer Tools window could be revealing :)

**Comment by kcranley1** [comment]
Is this what you mean?
![motioneyescreenshot](https://cloud.githubusercontent.com/assets/6755705/17701784/10d5141a-63c3-11e6-9562-da2fea9e529b.jpg)

**Comment by ccrisan** [comment]
I found the problem. Somehow the Frame Rate Dimmer preference is set to 0%. This means that frames will never refresh.

**Comment by ccrisan** [comment]
Also please remove the screenshot now (or at least blur the IP address) or otherwise unwanted users may visit your website.

**Comment by kcranley1** [comment]
Thanks - have you fixed something?  It's just the same here.

**Comment by ccrisan** [comment]
I haven't touched it. Just open the settings panel and increase the Frame Rate Dimmer (set it to 100%, preferrably). Then hit refresh and you should be fine.

**Comment by kcranley1** [comment]
I did that, but the problem's just the same.

**Comment by ccrisan** [comment]
I changed it myself now to 40% and it appeared to have been fixed.

**Comment by kcranley1** [comment]
Yes that works.  Thank you so much for your considerable help with this amazing software.  Now can you tell me how I should be displaying the video without a security risk?

**Comment by ccrisan** [comment]
Fixed with 88c76e9504e8bc0c05dca0fac65a9d991faf5a55.
