### ISSUE TITLE
No sign of Action Buttons

### ISSUE THREAD

**Issue by mcastaneda83** [ccrisan/motioneyeos#463]
Hi,
I have been using 20160705 and 20160801 images on a Rpi Zero which is using a Raspi Cam V2.1, everything works great but I don't get to make the action buttons appear on top of the camera frame.
I have followed the steps described on the Action Buttons wiki article, the "light_on" example to be more specific.  On the other hand, my gpio wiring seems to be ok.
Any clue of what could I be doing wrong? 

Thank you and congralutations for this awesome project.

**Comment by ccrisan** [comment]
Have you made them executable?

**Comment by mcastaneda83** [comment]
Yes I forgot to mention that, I made "chmod +x" on the created bash script.

**Comment by ccrisan** [comment]
Where did you place them and what are their names?

**Comment by mcastaneda83** [comment]
I put them in /data/etc
They are called "light_on_cam1" and "light_off_cam2"

**Comment by ccrisan** [comment]
Just rename them to "light_on_1" and "light_off_2". I assume you have two cameras; one of them will have a "light on" button and the other one a "light off"

**Comment by mcastaneda83** [comment]
It works! Thank you so much.
