### ISSUE TITLE
unable to open picture browser via UI

### ISSUE THREAD

**Issue by sroettgermann** [ccrisan/motioneyeos#466]
I'm unable to open the picture browser via the webinterface. The system seems to load, but after a while I get back to the start screen and nothing happens. 
Further I want to upload the still images to my Fritz!Nas or my Dropbox. But it seems not to work, too.

**Comment by ccrisan** [comment]
You probably have too many media files. Please try cleaning up your media files folder, making sure that there are no more than a few hundred photos in that folder. On a Raspberry PI with a standard SD card, it's understandable to have such performance issues.

**Comment by sroettgermann** [comment]
Thanks for the quick answer. That might be a reason. How do I cleanup the files properly?

**Comment by ccrisan** [comment]
Using ftp, sftp or smb (network shares).
