### ISSUE TITLE
motioneye and mypi

### ISSUE THREAD

**Issue by sunnymike** [ccrisan/motioneyeos#468]
Rather than use WebIOPi I would like to use MyPi as my GPIO interface. If I do not have motioneye embedded into Raspberry Pi, can I embed MyPi somehow into motioneye? I am not a programmer so cut and paste pretty much is what I need. Or it needs to be part of a bootable image for raspberry pi.

**Comment by ccrisan** [comment]
Use motionEye on Raspbian then.

**Comment by sunnymike** [comment]
I have tried to put motionEye on Raspbian using this:


http://www.howtoembed.com/projects/raspberry-pi/95-motioneye-with-raspberry-pi#comments

as the method.


When I try to install this I get an error message:




sudo aptitude install python-tornado python-jinja2 python-imaging motion ffmpeg v4l-utils




The error message basically says it cannot find a suitable ffmpeg package then doesn't install any of the packages so motioneye will not work without this.




Michael Sundgaard
mgsundgaard@verizon.net




-----Original Message-----

**Comment by ccrisan** [comment]
How about the instructions described [here](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian)?

**Comment by sunnymike** [comment]
I'll try it.
Thanks
