### ISSUE TITLE
web update

### ISSUE THREAD

**Issue by funtomas** [ccrisan/motioneyeos#47]
Software update can't find new version 
"motionEye is up to date (current version: 20151103)"

**Comment by scoobyd00** [comment]
It's probably because it's a pre release and not the full update.
Think there's an option to select beta releases if you want to  try it

**Comment by funtomas** [comment]
Ithanks i found "PRERELEASES" option

**Comment by funtomas** [comment]
in FF update proces failed 
then i have used IE and it was successful

**Comment by ccrisan** [comment]
I'd like to see the logs.

**Comment by tokodude** [comment]
Mine won't update ether.
I put on the Pre-Release option and rebooted, but it still say's I have the latest version installed.

**Comment by ccrisan** [comment]
What version do you currently run @tokodude?

**Comment by tokodude** [comment]
Current Version	20151103

**Comment by ccrisan** [comment]
Could you please also enable debugging, reboot, try to update again and, if it still says it's up to date, please send me the motioneye.log file.

**Comment by tokodude** [comment]
Here:



[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/49736/motioneye.txt)

**Comment by ccrisan** [comment]
Your board doesn't seem to have access to the internet (at least to to a DNS server that works):

    1970-01-01 01:00:49: [motioneye]    DEBUG: fetching https://api.github.com/repos/ccrisan/motioneyeos/releases?_=49...
    1970-01-01 01:01:09: [motioneye]    ERROR: could not get versions: <urlopen error [Errno -3] Temporary failure in name resolution>
