### ISSUE TITLE
CIPCAMPTIWL

### ISSUE THREAD

**Issue by mesofranico** [ccrisan/motioneyeos#473]
I have this camera, but cant connect!

Supported?

http://www.conceptronic.net/download_list.php?back=1&stype=1&search=CIPCAMPTIWL

**Comment by ccrisan** [comment]
No idea. Look for a JPEG/MJPEG/RTSP URL for this camera.

**Comment by mesofranico** [comment]
![ipcam](https://cloud.githubusercontent.com/assets/8009556/17892927/8365eac2-693b-11e6-8145-2a90871cd2a3.png)

iSpy - Working

**Comment by mesofranico** [comment]
Fixed, tks

PS: Connected direct to my HUB solved
