### ISSUE TITLE
Areas in motion detection

### ISSUE THREAD

**Issue by xxllo** [ccrisan/motioneyeos#483]
translated with Google
Is it possible in the next update to divide the motion detection to certain areas ? for example a certain grid in which there is the movement and it only monitors this area ? I have some trees that serves in my picture for monitoring and therefore at each wind impact a motion . would be great if you could divide the picture plane parts to nine to zwöf

**Comment by joshlukas** [comment]
Hi. This seems to be possible, however I do not have experience with that. Look at https://github.com/ccrisan/motioneyeos/issues/89 and http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigOptionMaskFile.

**Comment by ccrisan** [comment]
It's in the works.

**Comment by jimuhall** [comment]
This would be great - constantly getting motion detection trigger from a tree in one quadrant.  Would love to test the beta.

**Comment by xxllo** [comment]
Translated with Google
Then only the field of motion detection recording or the whole picture ? The whole picture would be better because I monitor my garden and then all would see .

**Comment by sapcons** [comment]
This is in my opinion the no. 1 missing feature of this program. Especially during this time of the year when it is getting windy you receive a lot of alerts from moving trees etc. You can reduce the sensitivity, but this may result in a situation that a real situation is not detected. 
Don't get me wrong: MotionEye is from my perspective a great program. This feature would just make the difference between 'great' and 'leading edge program'.

**Comment by ccrisan** [comment]
I am working these days on this feature and it will hopefully be ready within 1-2 weeks.

**Comment by xxllo** [comment]
Motioneyeos is the best program in the surveillance sector. Search and experimenting a long time with such programs and can only recommend motioneye

**Comment by tremichl** [comment]
I would also appreciate this feature since area_detect in Extra Motion Options doesn't work now for me. Overall great job ccrisan! Thank you very much!

**Comment by ccrisan** [comment]
Added in https://github.com/ccrisan/motioneyeos/releases/tag/20160919.
