### ISSUE TITLE
'protocol rtsp not supported' with motion 3.4.1~rc01 and meye 0.33.2

### ISSUE THREAD

**Issue by Microcentillion** [ccrisan/motioneyeos#491]
Attempting to add an RTSP network camera in MotionEye throws an error 'protocol rtsp not supported'. 

I installed Motion from the packages at https://github.com/Motion-Project/motion/releases - specifically xenialrc01_amd64. Is there any additional configuration needed to support RTSP with MotionEye, or any workaround for adding one?

Thanks in advance!
![root 0b856e487674 -var-log_053](https://cloud.githubusercontent.com/assets/143415/18233586/b113c4d2-72a8-11e6-856d-71afea4ba84f.png)

**Comment by Microcentillion** [comment]
Sorry, I just realized I posted this to meyeos instead of the meye repo.

**Comment by ccrisan** [comment]
No worries. The bug has been recently fixed upstream motionEye. If you feel like testing it you can try using the latest commit.
