### ISSUE TITLE
Data display with MotionEye - IrCut filter motorized

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#494]
hey Calin

**1) Creative use of MotionEyeOs :-)**

I have a desire to use a field of Motioneye system to display data from different sources. In and outside temperature, temperature of pellet boiler, day high and low temperature, sunrise, sunset e.t.c.
It's okay that it costs an extra RPI without camera, but it is possible to let Motioneye post data as a web page rather than a video stream?

Can you give some ideas on how it can be created?

![13 x cam 05-09-2016a](https://cloud.githubusercontent.com/assets/9556987/18254541/f8959abe-739e-11e6-9656-7fb3a812f7c1.JPG)

**2) Motorized Ir Cut filter**
I've seen that www.arducam.com soon deliver a IR cut filter along with their own version of a Raspberry Pi Cam. They write to me that the camera costs more than an original because they have to pay a license fee, so the price of the camera is around $ 50. There can then be fitted with optional lenses too. But if it can be acquired with IRcut filter motorized as possible. could be controlled from a GPIO pin, then it would be something I think many would demand.

If I can get one, is it possible to persuade you to assist with an implementation?

I'm thinking of using an astro library to find sunrise and sunset to handle the activation.

![image](https://cloud.githubusercontent.com/assets/9556987/18254535/e48fbe78-739e-11e6-9fc9-29789c7d1e3a.png)

See the link below:
http://www.arducam.com/category/camera-module-demonstration/

Best wishes from Denmark

**Comment by ccrisan** [comment]
Hi,

1. I'm not really sure what you mean. Everything motionEye displays ia a webpage. The "streams" are in fact mjpeg series of images served at a certain location.

2. I see what you need but I honestly don't have too much time these days to take care of such a task. I'm sorry about that.
