### ISSUE TITLE
More possibilities for timelapse planed?

### ISSUE THREAD

**Issue by Oberlandix** [ccrisan/motioneyeos#496]
Dear all, Dear @ccrisan ,
I allowed me to put this topic in a own issue.

"Would it be possible in a next version to "group" more photos for a timelapse then just from one day? That would be nice for lager (longer!) projects f.e. building up a house.

-> Example: Over the period of one year, just 3 photos at one day, taken by daylight, f.e. at 9, 12 and 3 (am) o clock.

Now that arrangement must be done manually out of thousands photos...

Sorry - I am new with motioneyeos (with a lots of questions at the beginn), but I am yet a fan :-) 
Thank you very much!
Oberlandix"

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
