### ISSUE TITLE
Login Attempt Log

### ISSUE THREAD

**Issue by stllunatic** [ccrisan/motioneyeos#500]
I love the motionEyeOS. I am a huge fan and it works great on the Rpi 3 with newest update! Really appreciate the work you’ve done with it Calin.

Does anyone know if there is a running log anywhere on the OS that would show login attempts? I checked the main error logs listed in the UI, but didn't find anything or didn't know what I was looking for exactly.

It would be a nice feature to be notified after a failed login attempt. Especially if you don't want to go down the road of a VPN, but still want more security than a simple password. 

Most routers can notify you upon firewall attacks, but is there additional security that can be setup for ports that are forwarded?  

References:

https://github.com/StarshipEngineer/OpenVPN-Setup
https://github.com/ccrisan/motioneyeos/issues/194
https://github.com/ccrisan/motioneyeos/issues/223

Thanks!

**Comment by ccrisan** [comment]
You could always read the motioneye.log file which will tell you about failed login attempts. The problem with it is that when you open yourself the web UI, you are prompted for credentials, which happens as a consequence to an initial failed authentication that happens in the background, and which will also generate such a line in the log file. I know this is not exactly what you were looking for but this is what we have for now.
