### ISSUE TITLE
Cant add a android camera through the app "Ip webcam"

### ISSUE THREAD

**Issue by seven01** [ccrisan/motioneyeos#504]
Is it possible to add a android phone camera to motioneyeos?
I have tried the app "ip webcam" but no sucess 
https://play.google.com/store/apps/details?id=com.pas.webcam

**Comment by katutxakurra** [comment]
I'm also interested on this. Is a motioneyeOS device automatically able to act as a central server?
https://github.com/ccrisan/motioneyeos/wiki/Usage-Scenarios

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
