### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by tokodude** [ccrisan/motioneyeos#51]
I would find it very useful if there is more possibility of setting up your camera.
It would be very useful if we could change this :
Sharpness
ISO
Video FPS
Image RES
Video Res

I hope if its possible to set Max resolution to 1920x1080 for video recording, 
and for taking pictures 2592×1944 and the possibility to change the ratio of width to height (different aspect ratio's)

It also seems very cool and useful to add image effects / color effects.
For example, night vision , cloudy , sunrise , etc ... Some good configuration what is best for these conditions.

sorry if I post in the wrong sector . I 'm new to gfthub

**Comment by ccrisan** [comment]
The "sector" for posting these is alright. The answer, on the other hand, is no, the main reason being the relatively low processing power on boards targeted by motionEyeOS, as well as the fact that most of them would require changes to the motion daemon, which is out of the scope of this project.
