### ISSUE TITLE
Constrain Motion Dimensions

### ISSUE THREAD

**Issue by tekgeek1** [ccrisan/motioneyeos#511]
Great job on the software!  I am looking to constrain the dimensions which will trip the motion alerts.  Are the dimensions of the motion detect area configurable?

Thanks!

**Comment by ccrisan** [comment]
It's in the works :) It's basically the next major upcoming feature.

**Comment by tekgeek1** [comment]
Excellent!! Estimated release time?

**Comment by tekgeek1** [comment]
Can I use the *area_detect* config in the options field?

**Comment by ccrisan** [comment]
Added in https://github.com/ccrisan/motioneyeos/releases/tag/20160919.
