### ISSUE TITLE
Not be able to reach the raspberry pi 2 after reboot

### ISSUE THREAD

**Issue by Eschtia** [ccrisan/motioneyeos#512]
Hello! 

After a reboot of my raspberry pi connected only via ethernet it isn't reacheble my router does not show my raspberry.

Raspberry Pi 2 with a Microsoft Webcam and connected via ethernet
The problem persists after a fresh install too.

I can't send a log file because it is not reacheble via web and via ssh

I hope someone can help me

---sorry for my bad english--- :(

**Comment by ccrisan** [comment]
What version is this? Have you tried other OSes on the same Raspberry PI unit? Can you connect a monitor on the HDMI output and see what's going on?

**Comment by Eschtia** [comment]
I tried many different builds. The problem was the SD card i changed to an other one and now its ok

thank you

**Comment by ccrisan** [comment]
Alright I'll close the issue now.
