### ISSUE TITLE
Higher video resolution supported with Raspberry Pi Camera Board V2

### ISSUE THREAD

**Issue by Shineson1001** [ccrisan/motioneyeos#513]
Video resolution 1920x1440 works fine with the Raspberry Pi Camera Board V2 (https://www.modmypi.com/raspberry-pi/camera/raspberry-pi-camera-board-v2-8mp1080p)
Would be nice, if you provide this video resolution in the web frontend.

**Comment by ArmandH** [comment]
Also streameye you can't set higher then 1080

raspimjpeg.py: error: option height: must be between 64 and 1080

**Comment by SkyByte** [comment]
It would at least be nice to be able to select the video resolution for the still images separately from the video streaming resolution, incl. the 3280x2464 resolution for the new Raspberry Pi Camera Board V2.

In my personal case, i would like to take some still images with the highest resolution as possible, but i don't need a high video stream resolution (even not simultaneously). How about a additional menu entry at 'Still Images' to select the 'Still Image Resolution'?

**Comment by jbthoma** [comment]
Yes, I also have the V2 camera and agree -- it would be nice to take still images at the full 3280x2464 resolution.

**Comment by ccrisan** [comment]
Fixed with https://github.com/ccrisan/motioneye/commit/f1298c012312aee69e231d2831abab2c3d76a0a6 and https://github.com/ccrisan/motioneye/commit/d61858b0ad47a13428e850ee475619ac57e0af62.
