### ISSUE TITLE
Not getting feed from remote camera

### ISSUE THREAD

**Issue by Dazzathedrummer** [ccrisan/motioneyeos#515]
HI again,

So, I now have a working Pi3 hub and a remote Pi Zero camera. For some reason, I'm not getting a consistent feed from the Zero - If I browse directly to the Zero, I get a perfect feed - but if I go to the hub, very often, the camera is not visible - I'm not sure why this is? is there anything in the settings that I need to tweak?

Pi Zero feed from 192.168.1.80
<img width="1280" alt="screen shot 2016-09-19 at 13 57 55" src="https://cloud.githubusercontent.com/assets/660243/18632810/3b319f76-7e71-11e6-8645-b28e844cad36.png">

Pi3 Hub at 192.168.1.69
<img width="1280" alt="screen shot 2016-09-19 at 13 53 42" src="https://cloud.githubusercontent.com/assets/660243/18632849/66f057d8-7e71-11e6-91d7-bb2ebeac2369.png">

**Comment by ccrisan** [comment]
Please attach the motioneye.log file.

**Comment by Dazzathedrummer** [comment]
File attached...
[motioneye.log.zip](https://github.com/ccrisan/motioneyeos/files/480191/motioneye.log.zip)

**Comment by ccrisan** [comment]
Well it seems there's a communication problem between the two:

    ERROR: failed to get current picture for remote camera 1 on http://192.168.1.80/config/1: request timed out

Most likely the network bandwidth between the two is not enough for the selected resolution and framerate. I recommend reducing the framerate and/or the resolution.

**Comment by Dazzathedrummer** [comment]
Ok, thanks - I'll give that a go.
