### ISSUE TITLE
How to enable motion sensing remotely

### ISSUE THREAD

**Issue by pi-pi-pi** [ccrisan/motioneyeos#518]
This is a fantastic program. Exactly what I need.

Is there a way via python script that I can enable motion detection? I have a trigger in a text file on an NFS drive and I have a script to read it. How can I turn the motion sensing on and off on the local camera pi? Any guidance appreciated.

Thanks,
pi-pi-pi

**Comment by dev67** [comment]
Total shot in the dark:
https://eltechs.com/run-teamviewer-on-raspberry-pi/

Has headless options on there I believe too.

**Comment by jasaw** [comment]
See issue #842 . You already have a script that reads your trigger, have the script send signals to the motion program.
