### ISSUE TITLE
The list of days are out of focus!

### ISSUE THREAD

**Issue by breakthecode** [ccrisan/motioneyeos#52]
Hi!
Using OS X El Capitan on my iMac 27" with 5K res. with latest Firefox and as you can see, I can only see todays date, and just above that I can see the beginning of the last days box. Edit: I found the problem, the code is not suitable for high res. screens like my 5K".

This is the view when I have the browser near fullscreen.
<img width="2560" alt="screen shot 2015-12-02 at 16 26 58" src="https://cloud.githubusercontent.com/assets/9256550/11534930/b8ec7882-9911-11e5-85dd-7ce7aacef6e2.png">

This is the view when I resize the browser to a small screen!
<img width="997" alt="screen shot 2015-12-02 at 16 30 56" src="https://cloud.githubusercontent.com/assets/9256550/11535041/4fe33f64-9912-11e5-8561-64f6275bd7ce.png">

Any change to make the code or box responsible for 5K screens? :+1: 

Best
Pontus

**Comment by ccrisan** [comment]
What version of motionEyeOS are you using?

**Comment by breakthecode** [comment]
I´m using the 20151103 running on my Raspberry Pi 2 model B.

**Comment by ccrisan** [comment]
The issue has been fixed in 20151129, which is a prerelease. Please enable pre-releases to be able to upgrade.
