### ISSUE TITLE
Integrated browser

### ISSUE THREAD

**Issue by chrisglitz** [ccrisan/motioneyeos#522]
Is there anyway I can use the same device motioneyeOS is installed on (rasp pi 1 model B) to access a browser on? I dont want to access the UI from any other location than the monitor attached to the pi that the OS is installed On. thanks

IP CAM---->Local Router (no internet access)----->Raspberry pi 1 with attached monitor.

**Comment by ektus** [comment]
That's not the use case motioneyeos is designed for. Use standard Raspbian with motioneye instead. Without internet access, you'd have to add a rtc if you want to have the PI display the correct time.

**Comment by ccrisan** [comment]
Everything that @ektus said is correct.
