### ISSUE TITLE
Mask in latest pre-release

### ISSUE THREAD

**Issue by andy6149** [ccrisan/motioneyeos#524]
Hi, great work on this, can i ask a question about the masking? When you set an editable area the live feed is covered with opaque tiles which can be added or removed as needed but do you want the area to be included to be covered with the opaque tiles or the darker ones?

**Comment by jeanfbrito** [comment]
The darker area is the "rejected" area, and the other is where the system will "see".

**Comment by andy6149** [comment]
Great thanks
