### ISSUE TITLE
is it possible to post the pictures to whatsapp? 

### ISSUE THREAD

**Issue by dbirlase** [ccrisan/motioneyeos#525]
hi,

i am working on a small experiment with bird watching.  I wanted to post it to facebook/whatsapp.  Is this been done before?  

In the cmd 

Run A Command, has anyone interfaced this with 

https://github.com/tgalal/yowsup/tree/master/yowsup?

**Comment by arghasarkar** [comment]
I'm not sure how it'll be interface but I can look into a Facebook messenger bot where it sends you the URL of the image that has been uploaded to dropbox or google drive. What do you think?

**Comment by raspdealer** [comment]
WhatsApp is a awesome idea!

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
