### ISSUE TITLE
xconfig raspberry pi 3 selected a7 by default 

### ISSUE THREAD

**Issue by parth15041995** [ccrisan/motioneyeos#526]
@ccrisan  while running "./build.sh raspberrypi3 xconfig" setting default set to arm a7 but raspberry pi 3 has armv8 a53 so it is intentionally put to that settings because there is no a53!!
what should I select to get multi threaded best performance? 
Thanks and Regards 
Nice Work

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
