### ISSUE TITLE
ftp

### ISSUE THREAD

**Issue by andy6149** [ccrisan/motioneyeos#527]
im finding the framerate to be very slow from my ipcam and was wondering if i get the camera to ftp into the raspberry pie into the folder used by the camera setup on motioneye will the ftp'd video be sent to dropbox?

**Comment by andy6149** [comment]
Ok so tested and yes it ftps to the right place but is not uploading to dropbox - is the dropbox upload a cron type job or could i make motioneye upload the new folder?

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
