### ISSUE TITLE
Configuring wireless adapter

### ISSUE THREAD

**Issue by Nokia95638** [ccrisan/motioneyeos#532]
hi,
How do i configure my wifi adapter for raspberry pi 3 to run on motioneyeos. I tried enabling wireless network from motioneyeos but it never seems to establish a wireless connection. i am using a tp-link wireless adapter, Model no. TL-WN725N

**Comment by kennynapalm** [comment]
Not sure if this helps. but I had the same issue.  Having the Ethernet cable seems to override the wireless.  I had to unplug the cable before I had it connect successfully to the wireless.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
