### ISSUE TITLE
cpu usage test

### ISSUE THREAD

**Issue by francescobragagna** [ccrisan/motioneyeos#538]
Hi,

this is not exactly an issue, but I hope this data could be useful for other people.
I'm using Rasberry PI 3, with release 20160919 and 7 FOSCAM FI9816P where rtsp stream is enabled with 720p resolution.
On motion eye I configured the 7 cameras one by one, and I tracked the cpu usage, with top command issued by ssh.
Foscam cameras allows to set up some streaming configuration, like resolution, bit rate, frame rate.
Using different configuration of stream I saw very different values of cpu usage.

Stream config: 720p, 2M bitrate, 10fps
cpu usage  (num cameras: %cpu)  1: 8%,  2: 16%,  3: 32%,  4: 53%,  5: 69% 

Stream config: 720p, 1M bitrate, 6fps
1: 8%,  2: 15%,  3: 18%,  4: 23%,  5: 33%  6: 37%   7: 43%

Using a very low resolution (QVGA with 200K bitrate and 15fps) the cpu usage is about 3% for each cameras (e.g 4 cameras consume 15%)

The defaulf foscam configuration gives for main stream 720p, 2M bitrate and 15fps: Adding 6 of these streams the 100% of rasberry cpu is quickly reached. It works bad, and becomes hot. 

My rasberry is connected via lan to an access point, and cameras area reached by wifi.
The recording speed looks like 2fps.
The cpu almost is used by /urs/bin/motion-mrdave process

**Comment by alainvc67** [comment]
Hello , 
Maybe you can help me .
I try to connect my fi9816p with motion eye but can make a connection .
I use this command : http://192.168.0.172:88/video.cgi 
But this will not work .
Any idee ?
Thanks for helping.
Best regards.
