### ISSUE TITLE
adjust shutter speed/exposure?

### ISSUE THREAD

**Issue by newalbanytom** [ccrisan/motioneyeos#543]
I have seen this asked before but never saw an answer.

is it possible to adjust shutter speed/exposure on a Pi camera ver. 1.3? I know it can be done with streameye, but I'd like to do it with stills, at night. Most stills are too dark to detect motion.

**Comment by ccrisan** [comment]
"stills" mode is not supported by motionEyeOS. If you must use stills mode, I recommend playing with Raspbian + streamEye + raspimjpeg.py (--stills).
