### ISSUE TITLE
i2c not working on RPi2 

### ISSUE THREAD

**Issue by milo3** [ccrisan/motioneyeos#549]
I am trying to use RTC DS1307 on RPi2 board (latest motioneyeos build). But I don't see i2c-1 on /sys/class/i2c-adapter/  I wasn't facing this problem on motioneyeos-raspberrypi2-20160109.img. 
Any idea?

**Comment by ekdrishta** [comment]
what!!
you have described the method at #61 is not working now I just bought DS1307 for my pi3. Do you know any way to correct time and date manually because my system is offline and there is no text-box in HTML page saying that enter your current date & time here.

**Comment by milo3** [comment]
I need to have working system tomorrow, so I return back to 20160109 version, which works fine. If the newest version contains a bug I hope it will be fixed soon.

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
