### ISSUE TITLE
[SOLVED] foscam fi8904w

### ISSUE THREAD

**Issue by zorrotenai** [ccrisan/motioneyeos#55]
Hi all; I bought a foscam fi8904w because I read it's a motion compatible device, but I get "not a supported network camera"
![motioneyeos](https://cloud.githubusercontent.com/assets/16159467/11604097/b7e676f8-9ae8-11e5-9700-dd7ca789b36f.png)

**Comment by psts** [comment]
Try this url instead: rtsp://192.168.1.101:88/videoMain

Taken from: http://www.ispyconnect.com/man.aspx?n=foscam

**Comment by zorrotenai** [comment]
Thanks first off all...
a little step: now the problem is "authentication failed"
 I reseted from factory my camera, so I'm sure user is admin whit no password, but nothing: 
![authentication failed](https://cloud.githubusercontent.com/assets/16159467/11610612/e276738a-9ba8-11e5-91c8-68cac6a49cb9.png)

**Comment by zorrotenai** [comment]
OK, this work:  http://<ip>:<port>/videostream.cgi?user=<user>&pwd=<password> from https://bitbucket.org/ccrisan/motioneye/issues/190/foscam-camera-is-not-working
Thank you very much

**Comment by zorrotenai** [comment]
I found this working:  http://<ip>:<port>/videostream.cgi?user=<user>&pwd=<password> from https://bitbucket.org/ccrisan/motioneye/issues/190/foscam-camera-is-not-working
Thank you very much
