### ISSUE TITLE
Pictures and Videos

### ISSUE THREAD

**Issue by flatustube** [ccrisan/motioneyeos#550]
I have MotioeyeOS setup and have everything working.

I am probably being stupid but I cannot see where to access pictures and videos from the GUI as shown in the screenshots from the installation guide.

Could you give me a clue?

Cheers

**Comment by ekdrishta** [comment]
click on the streaming video there is four action button and you should be clicking on 2nd and 3rd button.

**Comment by flatustube** [comment]
Thanks. Will check when I get home.
