### ISSUE TITLE
automatically timelaps every day

### ISSUE THREAD

**Issue by thundergreen** [ccrisan/motioneyeos#551]
Hey guzs,
absolutely great software what u created here.

Just an enhancement for the timelapse.

Would it be possible to integrate a schedule for automatically create timelaps every day with the poossibility to configure with the same options like actual.

would be nice. like this i could check in the evening what happened over the day.

Higly appreciate a resopnse

Greety

Thunder

**Comment by thundergreen** [comment]
Hi all again. Is this feature not wished here?

**Comment by Snille** [comment]
Hi! I'm also very interested in a timelapse function. It is already possible with motion. I have used when setting it up manually (for my 3D-printer). Would be very nice to be able to set it in the GUI as well! :)

**Comment by ccrisan** [comment]
If you configure your motionEyeOS to take still pictures (snapshots) at regular intervals (e.g. 60 seconds), you can download a timelapse movie made of them from the media browser.
