### ISSUE TITLE
motion boxes becoming current?

### ISSUE THREAD

**Issue by fundean** [ccrisan/motioneyeos#569]
Hey there CCrisian
Any chance you know when you will make the current version the one with the masks?
it works amazing but I don't want to pull the cameras down to update... Hoping to be able to just use the apps update feature and the current one doesnt have the boxes yet...

Thank you again its awesome
Dean

**Comment by ccrisan** [comment]
There still are a few minor issues to be dealt with. I believe the stable release will be out within 2 weeks or so.

**Comment by fundean** [comment]
Thank you!!

**Comment by scoobyd00** [comment]
Looking forward to this feature on the stable release :)

**Comment by ccrisan** [comment]
If by "motion boxes" you guys understand mask support, then it's gone stable already: https://github.com/ccrisan/motioneyeos/releases/tag/20161027
