### ISSUE TITLE
sound recording?

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#57]
hi. is it possible to add audio sources? like usb sound card or some board have mic in. and assosiate it with video sources so record video with sound?

**Comment by ccrisan** [comment]
No.

**Comment by shinji2009** [comment]
thanks for answer. thats a bummer ( it will be realy useful ((

**Comment by mitchelldavis44** [comment]
+1 on the sound issue.

**Comment by Mugiwara75** [comment]
+1 for sound ;-)

**Comment by Mayday171** [comment]
+1 mic support would be great

**Comment by spyrotsk** [comment]
+1 for sound support!
Thanks! ;-)

**Comment by hellyberry** [comment]
Sound and universal sensor action support would be great, for monitoring PIR, Temperature, Moisture, ...

**Comment by bortek** [comment]
This is duplicate of #57

**Comment by shinji2009** [comment]
it is #742 is duplicate of this request, it is 25 days old, mine is more than a year

**Comment by bortek** [comment]
Does not matter really which Issue we will be driving since it is the same feature request. Lets keep #742 ac active and keep this one closed. Thanks!
