### ISSUE TITLE
Error Unable to open video device with two different cam

### ISSUE THREAD

**Issue by robcop2000** [ccrisan/motioneyeos#571]
I have installed tree IP Cam:
-nr 1 - SRI SP0009
-nr 2 of this model (, One works and the other no
As software I have installed Motioneye os versione motioneyeos-raspberrypi2-20160919.img.gz
As you can see in t 
![schermata 2016-10-27 alle 14 33 56](https://cloud.githubusercontent.com/assets/6071909/19768765/1cbe259a-9c59-11e6-8d6c-6de191f7c9ba.png)
![schermata 2016-10-27 alle 14 33 56](https://cloud.githubusercontent.com/assets/6071909/19768778/264f4f44-9c59-11e6-9c30-67a5210cef78.png)

he attached image I have the Unable to open device error.
I have seen previous issue that talk about mrdrive but is for raspian version.
Here un abstract of the log

Jan 1 01:04:57 LDAhome user.alert motion-mrdave: [2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.52:554/)
Jan 1 01:04:57 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.229:554/)
Jan 1 01:04:57 LDAhome user.alert motion-mrdave: [3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.230/)
Jan 1 01:04:57 LDAhome user.err motion-mrdave: [3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam2:101968@192.168.2.230:554/): Server returned 400 Bad Request
Jan 1 01:04:57 LDAhome user.warn motion-mrdave: [3] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1 01:04:58 LDAhome user.err motion-mrdave: [2] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam02:rc1068@192.168.2.52:554/): Server returned 400 Bad Request
Jan 1 01:04:58 LDAhome user.warn motion-mrdave: [2] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1 01:04:59 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_handler_loop: Camera handler thread [5] started
Jan 1 01:05:00 LDAhome user.warn motion-mrdave: [2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
Jan 1 01:05:00 LDAhome user.alert motion-mrdave: [2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.52:554/)
Jan 1 01:05:00 LDAhome user.err motion-mrdave: [2] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam02:rc1068@192.168.2.52:554/): Server returned 400 Bad Request
Jan 1 01:05:00 LDAhome user.warn motion-mrdave: [3] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
Jan 1 01:05:00 LDAhome user.alert motion-mrdave: [3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.230/)
Jan 1 01:05:00 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_handler_loop: netcam camera handler: finish set, exiting
Jan 1 01:05:00 LDAhome user.err motion-mrdave: [3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam2:101968@192.168.2.230:554/): Server returned 400 Bad Request
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] conf_load: Processing thread 0 - config file /data/etc/motion.conf
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-1.conf
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-2.conf
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-3.conf
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Motion Unofficial-Git-UNKNOWN Started
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Logging to syslog
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Using default log type (ALL)
Jan 1 01:05:02 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
Jan 1 01:05:02 LDAhome user.err motion-mrdave: [0] [ERR] [ALL] start_motion_thread: Stream port number 8081 for thread 1 conflicts with thread 0
Jan 1 01:05:02 LDAhome user.warn motion-mrdave: [0] [WRN] [ALL] start_motion_thread: Stream feature for thread 1 is disabled.
Jan 1 01:05:02 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.229:554/)
Jan 1 01:05:02 LDAhome user.alert motion-mrdave: [2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.52:554/)
Jan 1 01:05:02 LDAhome user.alert motion-mrdave: [3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.230/)
Jan 1 01:05:03 LDAhome user.err motion-mrdave: [2] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam02:rc1068@192.168.2.52:554/): Server returned 400 Bad Request
Jan 1 01:05:03 LDAhome user.warn motion-mrdave: [2] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1 01:05:03 LDAhome user.err motion-mrdave: [3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam2:101968@192.168.2.230:554/): Server returned 400 Bad Request
Jan 1 01:05:03 LDAhome user.warn motion-mrdave: [3] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1 01:05:05 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_handler_loop: Camera handler thread [5] started
Jan 1 01:05:05 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_handler_loop: netcam camera handler: finish set, exiting
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] conf_load: Processing thread 0 - config file /data/etc/motion.conf
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-1.conf
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-2.conf
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] config_thread: Processing config file thread-3.conf
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Motion Unofficial-Git-UNKNOWN Started
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Logging to syslog
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Using default log type (ALL)
Jan 1 01:05:08 LDAhome user.notice motion-mrdave: [0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
Jan 1 01:05:08 LDAhome user.err motion-mrdave: [0] [ERR] [ALL] start_motion_thread: Stream port number 8081 for thread 1 conflicts with thread 0
Jan 1 01:05:08 LDAhome user.warn motion-mrdave: [0] [WRN] [ALL] start_motion_thread: Stream feature for thread 1 is disabled.
Jan 1 01:05:08 LDAhome user.alert motion-mrdave: [1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.229:554/)
Jan 1 01:05:08 LDAhome user.alert motion-mrdave: [2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.52:554/)
Jan 1 01:05:08 LDAhome user.alert motion-mrdave: [3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.2.230/)
Jan 1 01:05:08 LDAhome user.err motion-mrdave: [2] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam02:rc1068@192.168.2.52:554/): Server returned 400 Bad Request
Jan 1 01:05:08 LDAhome user.warn motion-mrdave: [2] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1 01:05:08 LDAhome user.err motion-mrdave: [3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam2:101968@192.168.2.230:554/): Server returned 400 Bad Request
Jan 1 01:05:08 LDAhome user.warn motion-mrdave: [3] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jan 1

Any suggestion?
Thanks in advance

**Comment by skinnyjay** [comment]
```
Jan 1 01:04:57 LDAhome user.err motion-mrdave: [3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://ldacam2:101968@192.168.2.230:554/): Server returned 400 Bad Request

Jan 1 01:04:57 LDAhome user.warn motion-mrdave: [3] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
```

I would check the address of your cameras to see if they changed, and the settings for the resolution given these two lines here.
