### ISSUE TITLE
Dirty Cow vulnerability

### ISSUE THREAD

**Issue by j-shaffer** [ccrisan/motioneyeos#572]
Is motioneyeos susceptible to the Linux Dirty Cow vulnerability?
If so, do you plan a patch for it?

**Comment by ccrisan** [comment]
No idea. To be honest, I didn't have the time to investigate it. The next release will have the updated Raspbian kernel, so it's pretty much up to them.

**Comment by Mikiya83** [comment]
https://www.raspberrypi.org/blog/fix-dirty-cow-raspberry-pi/
The latest kernel version (since 25th Oct) has been patched so if the next release use it, it should be fine 👍
