### ISSUE TITLE
Sharing working IP Cam

### ISSUE THREAD

**Issue by robcop2000** [ccrisan/motioneyeos#581]
I' have buyed three different IP Cam an I have been able only one to make it work. So two of them I have to send it back.
I think should be great if the users can share their experience on their working confuguration. 
So one can buy IP cam that centarnly works

**Comment by xxllo** [comment]
Translated with Google
Try this site. If it does not work I have other pages. Just do not give it up already.
http://skjm.com/icam/mjpeg.php
