### ISSUE TITLE
fails to build  - 

### ISSUE THREAD

**Issue by rabarar** [ccrisan/motioneyeos#589]
Looks like there's a missing dependency in the Kconfig for the driver/media/i2c/ov2659.c

it should be:
```
depends on MEDIA_CAMERA_SUPPORT && VIDEO_V4L2_SUBDEV_API
```
rather than
```
depends on MEDIA_CAMERA_SUPPORT
```

see:
https://patchwork.kernel.org/patch/6436761/

**Comment by ccrisan** [comment]
What kernel, what board, what version?

**Comment by rabarar** [comment]
i attempted to build the motionpie repo for raspberry3 - cloned it and 

make raspberry3_defconfig
make

**Comment by ccrisan** [comment]
1. Don't use motionPie. Use motionEyeOS instead.
2. Follow [these](https://github.com/ccrisan/motioneyeos/wiki/Building-From-Source) instructions to build your OS.

**Comment by rabarar** [comment]
Cool - thanks!
