### ISSUE TITLE
System status and remote monitoring

### ISSUE THREAD

**Issue by flyingclimber** [ccrisan/motioneyeos#592]
Curious with how 'System status in UI (CPU, memory, network, disk, temperature, etc)' is going from the Roadmap. Given that most items are in /proc and https://pypi.python.org/pypi/proc/0.9.1 exists, it should be do-able. For me personally, I'd love to be able to ship some of these metrics to central server for logging. Happy to help.

**Comment by shinji2009** [comment]
ccrisan can you tell please in which units cpu usage are displayed?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
