### ISSUE TITLE
Fast network camera snapshot url

### ISSUE THREAD

**Issue by jmai444** [ccrisan/motioneyeos#593]
A snapshot url does not appear anywhere in the configuration panel when the fast network camera option is enabled.

I'd like to use an http request to trigger a snapshot.  Possible?

**Comment by ccrisan** [comment]
The current FNC implementation (based on streamEye) does not allow serving a single snapshot. I have opened an [issue](https://github.com/ccrisan/streameye/issues/8) on this matter but this is not a priority so don't expect it to be done any time soon.

**Comment by davimas** [comment]
Hey, any solution after 2 years?
I need a jpg snapshot url, an not will use a another System. Motioneyeos is great, and a read only System in the sdhc card > this is very importend for the life of the card......

**Comment by bsvedin** [comment]
This still remains an issue
I would like to see this fixed

**Comment by starbasessd** [comment]
I doubt it will be. Calin gave control over to new devs a year ago, and very little has gone forward. This ticket was opened 7 years ago and closed 5 years ago. There hasn't been any activity on the streameye in several years, either.
