### ISSUE TITLE
Pixelated movies

### ISSUE THREAD

**Issue by Oreron** [ccrisan/motioneyeos#601]
Hi

I have a strange problem running MotionEyeOS on a Raspberry Pi 2. Whatever resolution/framerate/quality I set, the movies become very pixelated. See attached image. Still images looks fine.

I have another camera running off an old Raspberry Pi 1 (manually configured with "motion"). The movies produced with this are all OK (not pixelated).

Both setups use the official Raspberry Pi cameras.

Both produce .ogg files (I need to play them from a web page). I have noticed that the MotionEyeOS produce very small .ogg files (under 20k) files compared to the manually configured camera (about 100k).

Also, I have tried to add custom parameters to "Extra motion options", but some of them will not save and are gone after "Apply"...

Any ideas?

![pixelated](https://cloud.githubusercontent.com/assets/23232319/20381225/cb98c40a-aca6-11e6-9363-e3c6d59c7eb0.png)

**Comment by ccrisan** [comment]
What's your movie quality setting?

**Comment by Oreron** [comment]
Right now 100% with framerate 5.

**Comment by ccrisan** [comment]
What version?

**Comment by Oreron** [comment]
20161027 - The latest?

**Comment by ccrisan** [comment]
Could you please try the prerelease 20161114?

**Comment by Oreron** [comment]
Absolutely. Is it possible to install it from motionEyeOS or do I need to download and create a new SD card?

**Comment by Oreron** [comment]
Never mind. Installing now...

**Comment by Oreron** [comment]
The install worked well. Two new issues after installation:

1. The output file is .avi, even if I selected .ogg
2. The movie starts all black, then there is the same frame playing the entire movie

**Comment by ccrisan** [comment]
Please attach your config files here, after *removing any sensitive data*. I'm not sure about ogg videos but I remember seeing a post saying that it's been deprecated and no longer supported by motion. Not sure, though.

**Comment by Oreron** [comment]
OK, then we can disregard .ogg. I changed to .mp4 and it seems to work fine for now. Pixelation gone :-) and it plays fairly smooth from my webpage.

Thanks for your help, and thanks for creating this fantastic OS :-)
