### ISSUE TITLE
Stream Authentication

### ISSUE THREAD

**Issue by moonguar** [ccrisan/motioneyeos#602]
When setting the Surveillance User and Password from the motioneyeOS server to a camera on the motioneye system, the stream_authentication username and password is not written to the thread-X.conf file in the /etc/motioneye directory on the motioneye system.  Is this a known issue with the latest version?  Also, when enabling the basic or digest authentication on the motioneyeOS server, logging into any streams of remote motioneye systems doesn't work.

**Comment by ccrisan** [comment]
Yes, this is how it's supposed to work. The authentication options should never be altered remotely, via a motionEye master. If you need to adjust your auth options, please do them locally, directly on your "slave" motionEye system.

**Comment by moonguar** [comment]
Roger that.  Thank you Calin
