### ISSUE TITLE
Highlight issue

### ISSUE THREAD

**Issue by moonguar** [ccrisan/motioneyeos#603]
I have noticed that after I highlighted the "Snapshot URL" value from the motioneyeOS web interface for copying and pasting into another window, the text in the "Snapshot URL" box will scroll all the way to the right and will remain there.  There is no way to scroll back to the left in the value box to see the full path in the "Snapshot URL" value box.  Logging out and then back in or refreshing the page (which requires authentication if enabled) fixes the problem.

**Comment by ccrisan** [comment]
How about clicking and dragging the selection to the left?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
