### ISSUE TITLE
Video lag

### ISSUE THREAD

**Issue by lodgemoorlad** [ccrisan/motioneyeos#604]
Hi 
I've just got my ME up and working on wifi and when I'm within a meter or two away from my router  it's perfect

However When I position my camera an Pi in the garage or garden, 7 - 10 meters away it won't even load a full screen. I know this particular Pi 3 works well at this distance using the Pi cam web interface software ( at very low res) but the ME is really struggling so I was wondering is ME running or accessing anything in the background I might be able to turn off allowing more processing power just to deal with what the camera is looking at?  
Hope someone can advise
Thanks 
Ps I have the latest software running

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
