### ISSUE TITLE
Custom video resolution crops image

### ISSUE THREAD

**Issue by mitchf** [ccrisan/motioneyeos#607]
I love the addition of custom video resolutions to the version 20161114 software. Prior to motioneyeos, I was capturing stills near the max raspi camera resolution of 2592x1936, so 1600x1200 was a big downgrade. However, when setting the custom video resolution in the "Video Device" section, the resulting image appears cropped, with only the middle part of the video displayed. The cropped image is getting displaying at the set custom resolution, though. (RasPi3)

**Comment by ccrisan** [comment]
I'm afraid this is not something motionEye(OS) can fix. Cropping the image is something the v4l2 driver (or the MMAL libraries or so) does. You need to seek help on the Raspberry PI forums. If there's a workaround or a proper fix for this problem, I'd be happy to consider integrating it into motionEyeOS.
