### ISSUE TITLE
NexGadget Mini Cam - Authentication failed

### ISSUE THREAD

**Issue by gioluca2** [ccrisan/motioneyeos#608]
I use motioneyeos-20161114 on my raspberry pi 2 and I have this issue with NexGadget Mini Cam (https://www.amazon.it/gp/product/B01LPJZVZS/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1):
when I insert the link (192.168.1.101), username and password I have "authentication failed" error message:
![add_camera](https://cloud.githubusercontent.com/assets/23580113/20455850/eed68cc0-ae65-11e6-87b3-69277452aee6.png)

When I open http://192.168.1.101/ into browser I have this screen:
![screen](https://cloud.githubusercontent.com/assets/23580113/20455830/88d77484-ae65-11e6-81b2-53c64afef718.png)

I also try to add the two direct links (http://192.168.1.101/main.html?id=1&playtype=iv and http://192.168.1.101/main.html?id=1&playtype=fv) but without success.
It doesn't work http://192.168.1.101:554 (RTSP port with and without authentication request) either.

Please help me

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.

**Comment by thesatishk** [comment]
@gioluca2 did you manage to get this camera work with the pi?

**Comment by thesatishk** [comment]
https://www.ispyconnect.com/man.aspx?n=iSmartViewPro#

Here's the info about the rtsp stream for this camera.
