### ISSUE TITLE
Using motioneyeos with Raspberry Pi Zero

### ISSUE THREAD

**Issue by mpeill** [ccrisan/motioneyeos#609]
Apologies that this is very basic, but I'm just finding my feet using the Rpi.
Is the motioneyeos compatible with the pi zero, and if so, which of the Rpi files would be appropriate?

**Comment by dkelley810** [comment]
Raspberry PI (A, B, A+, B+, Compute Module and Zero models)

    board home page
    latest version: 20161027
    kernel: 4.4 (raspbian)

[Download Files](https://github.com/ccrisan/motioneyeos/releases/tag/20161027)

**Comment by mpeill** [comment]
Excellent, thanks for the advice.
