### ISSUE TITLE
Motion detection border and email

### ISSUE THREAD

**Issue by axum202** [ccrisan/motioneyeos#615]
Hello, 

Im trying to figure out why..
1.) There is no type of 'motion detection border' around the objects being detected....And
2.) Is this the reason why im not receiving email notifications with a attached snapshot of the object being detected? Even though the test emails DO work. 

Raspberry Pi 3, Raspbian Jessie. 

Great App by the way. Awesome .

**Comment by axum202** [comment]
ps. i think its called the mask. Im not able to see a mask in my video. it is set to smart.

**Comment by axum202** [comment]
I dont think its detecting motion. No red frame.

**Comment by axum202** [comment]
I have hovered over the question marks and looked through the issues on this page. I hope its not a big problem. Any ideas? Thanks

**Comment by ccrisan** [comment]
1. Does it detect any motion at all?
2. Do you receive notification emails at all?

**Comment by axum202** [comment]
No.
No.

But when i sent a test email, it does work.

**Comment by ccrisan** [comment]
What does your motion detection settings look like? A screenshot would help.

**Comment by axum202** [comment]
Here are my motion detection settings.
Frame Change Threshold
0%-5%

Auto Noise Detection on
Light Switch Detection on
0%

Despeckle Filter on
Motion Gap 20 seconds
Captured Before 3 frames
Captured After 3 frames
Minimum Motion Frames 20 frames
Mask on
Mask Type smart
Smart Mask Sluggishness
5

Show Frame Changes off
Create Debug Media Files off

**Comment by ccrisan** [comment]
What is your video device (capturing) framerate?

**Comment by ccrisan** [comment]
Have you enabled working schedule?

**Comment by axum202** [comment]
Yes , it is enabled to detect during working hours

**Comment by ccrisan** [comment]
Try disabling the working schedule and see if motion is detected.

**Comment by axum202** [comment]
framerate is at 2, I tried disabling work schedule and nothing

**Comment by ccrisan** [comment]
With a framerate of 2 and a minimum motion frames set to 20, you'll need to generate at least 10 seconds of motion. Have you done that *after* disabling the working schedule?

**Comment by axum202** [comment]
Yes, i just did that. Still nothing.

**Comment by ccrisan** [comment]
Then please attach your configuration files (downloadable using the Backup button) *after* removing sensitive data from them. In need to see `motion.conf` and `thread-1.conf`.

**Comment by axum202** [comment]
motion.conf 


# @enabled on
# @show_advanced on
# @normal_password 
# @admin_username admin
# @admin_password 
# @normal_username user


thread thread-1.conf
webcontrol_html_output on
webcontrol_port 7999
setup_mode off
webcontrol_localhost on

**Comment by ccrisan** [comment]
Please attach them, don't paste them!

**Comment by axum202** [comment]
[motion.txt](https://github.com/ccrisan/motioneyeos/files/619829/motion.txt)
[thread-1.txt](https://github.com/ccrisan/motioneyeos/files/619831/thread-1.txt)

**Comment by ccrisan** [comment]
Your camera doesn't appear in your motion.conf. Please remove and re-add it.

**Comment by axum202** [comment]
Ok I just removed and readded. Still nothing. After re-adding, should I change any settings? What should I see in motion.conf if my camera was added correctly?

**Comment by ccrisan** [comment]
A line saying "thread thread-1.conf"

**Comment by axum202** [comment]
I can see that line now. It is the last line of the file.

**Comment by ccrisan** [comment]
Well, does the camera frame turn red when motion is detected now?

**Comment by axum202** [comment]
No it doesnt. The camera is always focusing in and out, idk if that is a problem .

**Comment by axum202** [comment]
Im also using this in my room , do i need to have much more space?

**Comment by ccrisan** [comment]
set Show Frame Changes to on, to at least see that it does some detection and reduce the frame change threshold to something around 1%.

**Comment by axum202** [comment]
Just changed those settings. Still nothing. By setting show frame rate to on, where would i find out that it is detecting motion?

**Comment by ccrisan** [comment]
In the top right corner of the camera frame you should see a number. That's the number of motion pixels detected.

**Comment by axum202** [comment]
all  see is frames per second in bottom left and timestamp in bottom right. camera name top left, and setting icons in top right.

**Comment by axum202** [comment]
show frame changes is ON

**Comment by axum202** [comment]
i have opencv installed on my pi. hope is has nothing to do with that.

**Comment by ccrisan** [comment]
OpenCV shouldn't affect motion.

It's not on the overlay. You'll need to click on the camera frame once to make the overlay disappear. Then you'll see the clear camera image. On top of that you should see (in white) the number of frames changed in the top right corner.

**Comment by ccrisan** [comment]
If that's not the case, please send me a screenshot of how your camera frame looks like.

**Comment by axum202** [comment]
![2016-11-27-060243_1246x737_scrot](https://cloud.githubusercontent.com/assets/22774733/20725380/a0bfbd90-b63f-11e6-97aa-f2925fac8f22.png)

**Comment by ccrisan** [comment]
This is odd. Please attach your two config files as they are now.

**Comment by ccrisan** [comment]
Also what version of motion and motionEye do you use?

**Comment by axum202** [comment]
[motion.txt](https://github.com/ccrisan/motioneyeos/files/620028/motion.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/620029/motioneye.txt)
[thread-1.txt](https://github.com/ccrisan/motioneyeos/files/620030/thread-1.txt)

**Comment by axum202** [comment]
motionEye Version	  0.35.1
Motion Version	4.0.1

**Comment by ccrisan** [comment]
I'm sorry but things look a lot different here. It's like you weren't using motion 4.x. Can you please attach your motioneye log file (journactl -u motioneye > motioneye.log)?

**Comment by axum202** [comment]
pi@raspberrypi:~ $ journalctl -u motioneye > motioneye.log
No journal files were found.

let me try to find the log file.

**Comment by axum202** [comment]
nano motioneye.log file is empty

**Comment by ccrisan** [comment]
How do you run motionEye?

**Comment by axum202** [comment]
by going to my raspberry pi ip address:8765

**Comment by axum202** [comment]
how should i run it?

**Comment by ccrisan** [comment]
I meant how you *start* it, not how you open the user interface. Did you use the systemd unit and enabled it with systemctl? Did you use the init script?

**Comment by axum202** [comment]
sudo systelctl start motioneye

**Comment by ccrisan** [comment]
Then I cannot explain why you have no motioneye log. Could you give me temporary remote SSH access on your motionEye system, so I can see what's going on/

**Comment by axum202** [comment]
yes, 192.168.116.130
pi@raspberrypi:~$

**Comment by axum202** [comment]
there is no sensitive info in this device

**Comment by axum202** [comment]
user : pi
password : raspberry

i will delete this info later

**Comment by ccrisan** [comment]
That's your private IP address. You need to (1) set up port forwarding on your router and (2) give me your public IP address.

**Comment by axum202** [comment]
I literally JUST figured it out....cant run motion and motioneyeos at the same time.

**Comment by ccrisan** [comment]
I'm glad you sorted it out :)
