### ISSUE TITLE
Camera not detected by motioneyeOS on RPi 2

### ISSUE THREAD

**Issue by mholland21** [ccrisan/motioneyeos#616]
So I flashed motioneyeOS to an SD card everything seems to be working (Wifi, etc) except the automatic camera detection for the on-board camera...

I know the camera works because I checked with raspistill before flashing motioneye to the SD card. I also tried using the Raspian + MotionEye method and could not get it to work (I'm a very novice coder) so I reflashed the OS. 

bcm2835_v412 shows up in lsmod but shows that it isn't being used by any other modules

![rpi](https://cloud.githubusercontent.com/assets/24248362/20710669/1302b252-b601-11e6-867c-bd1ff47ce2ae.jpg)

I'm going to retry the raspbian method but I would still love some insight about my issue with the OS.

Thank you!

**Comment by ccrisan** [comment]
What do you mean by "automatic camera detection". How do you know it doesn't work? Can you exemplify it with some screenshots?

**Comment by mholland21** [comment]
In "local cameras" the camera doesn't show up. I'm currently double checking if the camera works in case something happened to the hardware. I'll post screenshots if I run into the same issue. Thanks for your quick response!

**Comment by mholland21** [comment]
It seems as though my camera crapped out on me in my recent move as raspistill isnt detecting it anymore either (I last checked when i bought it a few months ago). Thanks again for your help, I guess I'll  have to buy a new camera and try again.

**Comment by gitgoldberg** [comment]
I've several times had the tiny connector on the Raspberry Pi camera board pop open.  It can carefully be snapped closed again - but take anti-static precautions when doing so.
Sometimes just flexing the board when handling it is enough to un-pop the connector.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
