### ISSUE TITLE
Notification & Upload after reestablishing internet connection

### ISSUE THREAD

**Issue by eteran23** [ccrisan/motioneyeos#619]
When motion is detected while there is no internet connection then none of the notifications are sent and the video is not uploaded to cloud storage. I would appreciate if motionEyeOS could check for connectivity before trying to send notifications/upload and retry regularly if there was no connectivity initially.

I will use motionEyeOS in an environment where the internet connection is very unstable and will likely fail often for several minutes. Sadly there is no way to fix that. Notifications are very important to react in time.

**Comment by ccrisan** [comment]
Unfortunately there's no easy way to implement this. The motion daemon is responsible of generating the events and they are processed on the fly. Without an internet connection, motion(Eye) would have to queue these events and process them eventually, when the internet is back on. This is not something easy to implement and honestly, not a priority.
