### ISSUE TITLE
Working Schedule

### ISSUE THREAD

**Issue by moonguar** [ccrisan/motioneyeos#621]
Calin, I have noticed weirdness with the scheduler not working correctly by sending motion notifications when it not suppose to because it's out of schedule. I noticed in some other issue reports that you can't have the times set in the scheduler to span between two days. I have my scheduler set for 20:00 to 00:00 everyday day. Is 00:00 considered the next day therefore spanning days which won't work?  I'm thinking the problem is this.

**Comment by ccrisan** [comment]
00:00 is considered the beginning of the day. The interval 20:00 to 00:00 is not valid as the start is greater than the stop; hence the "weirdness" in your working schedule setup.

Unfortunately there's no way working schedule can span more than a day.
