### ISSUE TITLE
Real Time Clock for Raspberry PI?

### ISSUE THREAD

**Issue by svoket** [ccrisan/motioneyeos#622]
A RTC would be good for a stand alone, no network installation.

**Comment by ektus** [comment]
This has been asked before and is WIP. https://github.com/ccrisan/motioneyeos/issues/61

**Comment by ccrisan** [comment]
In theory this should work, as indicated in #61. I can't say for sure as I don't own such a module, but the required binaries and modules are included, so it should work.

Please report back any problems you encounter so we can get this working. If it is working, I'll put together a wiki article on this matter.

**Comment by ccrisan** [comment]
See [Adding A RTC Module](https://github.com/ccrisan/motioneyeos/wiki/Tweaks#adding-a-rtc-module).
