### ISSUE TITLE
Cannot access login page anymore - direct to full screen streaming

### ISSUE THREAD

**Issue by markvanhaze** [ccrisan/motioneyeos#627]
Strangely, after changing the port to 8081, using the browser I now do not get a login prompt anymore and instead a full screen stream of my webcam. How do I get back to the login page?

**Comment by ccrisan** [comment]
Do not use port 8081 for the web frontend, as it's already used for the video streaming (which is what you see when you're accessing that port).

**Comment by markvanhaze** [comment]
Is there a way of changing the web frontend port without having to re-install the image?

**Comment by ccrisan** [comment]
The web frontend doesn't start anymore due to the port conflict. You'll need to rewrite the OS image or login with SSH and manually edit the port in `/data/etc/motioneye.conf`.

**Comment by markvanhaze** [comment]
SSH did it. Thank you for your help!
