### ISSUE TITLE
Can i use and external usb hard drive?

### ISSUE THREAD

**Issue by TheMightyInferno** [ccrisan/motioneyeos#63]
I'm wanting to connect my external hard drive to store my media files but im having trouble finding the relevant information. Any ideas?

**Comment by ektus** [comment]
Sure you can. Just ensure the hard drive has it's own power supply (or a powered hub). Then it will be mounted automatically and you can select it in the "file storage" section in the GUI.

**Comment by Lukas1990** [comment]
if you have 2,5-inch HDD in RPi USB, go into folder boot a add this "safe_mode_gpio=4
max_usb_current=1" but usb Ampers output is to low default, even when you have god power supply. 2,5-inch HDD do not need own power supply.
