### ISSUE TITLE
Unable To Open Video Device Error message

### ISSUE THREAD

**Issue by chenselman** [ccrisan/motioneyeos#631]
Hello,
I'm running into the gray screen in motioneye with the error message "unable to open video device" (shown in the following screenshot.)
![screenshot 40](https://cloud.githubusercontent.com/assets/21174984/21022855/be6c573a-bd43-11e6-91bc-3509ee015e85.png)
I'm currently using one microSD card with the image for raspberry pi 3 motioneyeOS and it works perfectly with both of the raspberry pi 3's I am testing, and I can view one of my Raspberry Pi v4l2 cameras by searching the IP address in my browser in real time.  (that camera works perfectly with both raspberry pi's)  However, I run into the "unable to open video device" error message in motioneye whenever I try to use my other v4l2 camera (I get the error message with both raspberry Pi's).  
Is this error caused by trying to use only one microSD card, or is something else causing this?  Is there a setting or command I need to execute/change in order to fix this problem with my second camera?  
Thanks :)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
