### ISSUE TITLE
Failed to load the motioneyeos in my Raspberry Pi 3 device

### ISSUE THREAD

**Issue by Ahmedmud** [ccrisan/motioneyeos#632]
I failed to load the motioneyeos in my Raspberry Pi 3 device. I recent downloaded and mounted the image using windows Win32 Disk Imager. 

can you help please?

Note: I am just a starter on IT world and I am seeking to learn with you pros :)

Linked is the error message:
http://pictub.club/image/s7If0L

BR
Ahmed

**Comment by ccrisan** [comment]
You'll need to rewrite the OS image from scratch on your SD card. Somehow the data partition got corrupted. Possible causes include a bad power supply, a faulty SD card or too much overclocking.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
