### ISSUE TITLE
Stream h264 in Fast Network Camera mode

### ISSUE THREAD

**Issue by tafryn** [ccrisan/motioneyeos#636]
The MJPEG stream supported in Fast Network Camera mode is very bandwidth intensive. Raspberry Pis can output a less bandwidth intensive h264 stream without a heavy CPU load using raspivid. Can streamEye be adapted to serve up this h264 stream?

**Comment by Mikiya83** [comment]
In the same aspect, it should be perfect if h264 stream can be output even if not in "fast mode", when motion is on (as you said, MJPEG is very intensive for network)

**Comment by ccrisan** [comment]
Adding a backend such as streamEye for h264 is definitely a good idea. However having motion stream h264 (i.e. "not fast mode") is not something I see happening anytime soon.

**Comment by Mikiya83** [comment]
Ok, not a problem, it's already very good, thanks for your constant work 👍

**Comment by mrgnou** [comment]
Adding h264 output to fast mode is a real need feature as it would allow support of high fps / definition video streaming which can't be done with mjpeg.

**Comment by jasaw** [comment]
There are 2 different issues here:
1. Fast Network Camera mode stream H264, which can be implemented via uv4l and uv4l-raspicam.
2. Motion stream H264 (not in fast mode), which requires changes to motion software. This is difficult to implement and requires support from motion developers.

**Comment by Mikiya83** [comment]
The first point could be very useful if it's possible to implement it quite easily !

**Comment by jasaw** [comment]
@ccrisan Any thoughts on marking this issue as an enhancement request? The first point looks possible.

**Comment by ccrisan** [comment]
I don't see any problem with it but I personally don't have time to take care of it. Pull requests are welcome, though :)

**Comment by jasaw** [comment]
Alright, making this issue as an enhancement and anyone can submit a pull request if they want to.

**Comment by d-faure** [comment]
According to https://www.raspberrypi.org/forums/viewtopic.php?t=51476#p449922,
or even https://chriscarey.com/blog/2017/04/30/achieving-high-frame-rate-with-a-raspberry-pi-camera-system/comment-page-1/
this should be doable combining `raspivid` and command-line `vlc`.

While the MotioneyeOS architecture is really nice as a camera firmware, this could be nice to embed `vlc` and provide a way to customize the streaming server to something else than `streameye` and/or `raspimjpeg.py`.

**Comment by yonailo** [comment]
+1 to have this feature at least in fast-mode !!

**Comment by Goeks1** [comment]
I am waiting also for a stream in h264 !!

**Comment by jasaw** [comment]
See https://github.com/ccrisan/motioneyeos/pull/1764 and https://github.com/ccrisan/motioneyeos/issues/1259

**Comment by jasaw** [comment]
If anyone is willing to be a guinea pig to test h264 stream in fast network cam mode, please go to PR #1764. There's a link to my pre-built image that supports this feature, but web UI hasn't been implemented yet, so it requires editing a couple of config files. Instructions are in the PR.
Any positive or negative feedback is welcomed.

**Comment by Spacemarine2018** [comment]
I will try in the next days if possible. Finally one elegant way to watch my 3D-printer in high-res high FPS over low(er) bandwidth connection! Thanks!

**Comment by jasaw** [comment]
Basic RTSP support has been implemented in dev branch.
