### ISSUE TITLE
Unable to open video device 

### ISSUE THREAD

**Issue by SgtNobbyNobbs** [ccrisan/motioneyeos#637]
Hi,

I just installed the latest motioneyeOS image (20161211) on my brand new RPI3 but am unable to get video feed from the connected picamera v2; I see the camera in the viewer but the feed is gray and it says 'unable to open video device'. The camera works correctly, I tested that on vanilla Raspbian before installing motioneyeOS. 

I found a similar issue on this forum (https://github.com/ccrisan/motioneyeos/issues/147), but I think that was another problem, caused by connecting a non-compatible camera.

The 'motion' command causes a sort of loop, seemingly due to an issue with the camera: I see messages like 'device doesn't support VIDIOC_G_STD', 'error setting pixel format', 'VIDIOC_S_FMT: device or resource busy', and 'motion_loop: video device fatal error - closing video device'.

Could it be that PIcam v2 is not yet supported by motioneyeOS?

Any help is greatly appreciated.

Thanks!

**Comment by ccrisan** [comment]
All RPi cameras should be supported by motionEyeOS. Could you please try this with a previous, stable release? It might be a RPi firmware issue.

**Comment by SgtNobbyNobbs** [comment]
Thank you for your very quick answer!

Which stable version do you recommend?


On 11 Dec 2016, at 20:31, Calin Crisan <notifications@github.com<mailto:notifications@github.com>> wrote:


All RPi cameras should be supported by motionEyeOS. Could you please try this with a previous, stable release? It might be a RPi firmware issue.

-

**Comment by ccrisan** [comment]
20161125

**Comment by SgtNobbyNobbs** [comment]
I just tried the 20161125 build but got the same error message unfortunately.  Do you have another suggestion for me?

**Comment by ccrisan** [comment]
At this point I'd recommend getting back to Raspbian and making sure it still works. The camera might have gotten damaged in the meantime.

**Comment by SgtNobbyNobbs** [comment]
thanks for the answer! It turned out that my camera was indeed not working anymore. Issue solved!
