### ISSUE TITLE
Login Credentials do not appear to apply

### ISSUE THREAD

**Issue by SmallConcern** [ccrisan/motioneyeos#638]
Hi

First off, thank you for all of your work on MotionEyeOS. It's fantastic. I'm setting it up on a Raspberry Pi 3, running the latest version (20161211)

I'm having an issue applying login credentials. I've set a password for admin and configured a surveillance login. However, upon applying and the pi rebooting, it will not accept my configured credentials with a password. It recognizes my change from 'user' to my new username for surveillance but accepts the login with no password. Same thing with admin, the password I set will not work, but empty still works.

I do see a message regarding Samba password on bootup, I'm unsure of its significance though:

> Setting smb admin password: Mismatch - password unchanged.

Thank you for any help

**Comment by SmallConcern** [comment]
These debug messages are at the beginning of messages.log:

> Jan  1 00:00:27 meye-d89c43ec auth.err passwd: /etc/passwd: Read-only file system
Jan  1 00:00:27 meye-d89c43ec auth.err passwd: can't update password file /etc/passwd
Jan  1 00:00:27 meye-d89c43ec auth.err passwd: /etc/passwd: Read-only file system
Jan  1 00:00:27 meye-d89c43ec auth.err passwd: can't update password file /etc/passwd

**Comment by ccrisan** [comment]
Things have changed a bit with regards to authentication in 20161211, indeed. The smb-related error is problematic. Those from messages.log, however, are normal.

1. Have you updated from a previous version? If yes, could you please try the new version from scratch?
2. Please clear your browser's cache, refresh and retry updating the password.

**Comment by SmallConcern** [comment]
For each:
1. This was a fresh install today to 20161211. I have reformatted the SD card a few times trying earlier versions (20161125, 20161114). Interestingly enough, maybe related, maybe unrelated - after downgrading versions it would not let me login with the default credentials (admin/empty). It would not accept what I thought I changed the password to in 20161211 as well. When formatting up to the earliest version from the old, I did make sure to format the disc to empty before re-writing the latest image.
2. I tried clearing cache and trying a different browser on desktop and on my phone with the same results.

Would any logs be beneficial for debugging support?

**Comment by koenig-dro** [comment]
Maybe Interesting to know:
After writing the image i could login as admin with no password after startup. Then nothing changed just reboot and it dosnt accept login as admin...

**Comment by stefanoqredo** [comment]
same issue. very annoying. just a fresh install,  nothing else.
both admin and user works without password, I've tried to change (and rebooted) multiple times.

**Comment by ccrisan** [comment]
This is indeed a nasty bug and needs to be addressed asap. I can reproduce it myself. Thanks for reporting it; I'll keep you posted.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/releases/tag/20161212 fixes this.

**Comment by SmallConcern** [comment]
Thank you!

**Comment by plauria** [comment]
Hi ccrisan,

Whatever is 'fixed' about this release (20161212) doesn't apply to the Raspi2 at least. I get the same behavior; changing passwd does nothing. Reboot and it's back to 'blank.'

Can someone else confirm?

**Comment by plauria** [comment]
Sorry, my mistake. It appears that one cannot use 'passwd' with this OS but most go through the app. THis might be worth mentioning on the FAQ. Thanks
