### ISSUE TITLE
camera ip compatible list

### ISSUE THREAD

**Issue by kiki51** [ccrisan/motioneyeos#639]
Hi.

I use motion eye on my old raspberry b+.
Its perfect but i would like to use one camera ip.
I have not find a list of compatible device.
If you have this it can be fine.
Thanks
Eric

**Comment by ccrisan** [comment]
There's no such list, unfortunately.

**Comment by kiki51** [comment]
Hi,

Thanks for your answer.
It's not easy cause you have a lot of camera IP on the market, with all the prices!
I'm searching for a cheap camera IP, compatible with rpi..., with basic quality
