### ISSUE TITLE
New config options in motion

### ISSUE THREAD

**Issue by Chiny91** [ccrisan/motioneyeos#642]
Idly perusing /var/log/messages to see what I have broken recently, I see:

> user.warn motion: [0:motion] [WRN] [ALL] thread config option deprecated use camera
> user.notice motion: [0:motion] [NTC] [ALL] config_camera: Processing camera config file thread-2.conf
> user.warn motion: [0:motion] [WRN] [ALL] thread config option deprecated use camera
> user.notice motion: [0:motion] [NTC] [ALL] config_camera: Processing camera config file thread-4.conf
> user.warn motion: [0:motion] [WRN] [ALL] thread config option deprecated use camera
> user.notice motion: [0:motion] [NTC] [ALL] config_camera: Processing camera config file thread-5.conf

In conjunction with the _motion_ release 4.0 release notes:
```
New configuration options:
mmalcam_name
mmalcam_control_params
camera_name
camera_id
camera_dir
```

It looks like the old _thread-n_ config option is being phased out, although I have not managed to find the 4.0 documentation yet to find out details of the new versions.

**Comment by ccrisan** [comment]
It's a known "issue". For compatibility reasons, the old option names are still used. Moreover, the camera id concept also exists in motionEye and has a slightly different meaning.
