### ISSUE TITLE
Camera ID field error after update to 20161125

### ISSUE THREAD

**Issue by nighty2k7** [ccrisan/motioneyeos#643]
Hi,
after the auto update to 20161125 the field Camera ID is empty with a red mark next to it. I cannot enter any value in the field. I also cannot change any other setting and apply them as the interface wants me to fill in the field (which I cannot).
Marco

**Comment by nighty2k7** [comment]
Camera is working though!

**Comment by ccrisan** [comment]
Please clear your browser's cache, refresh and see if the problem persists.

**Comment by PieterGit** [comment]
I also had this with 20170212 which was upgraded today. 
A simple press on CTRL-F5 (refresh all) fixed the problem
