### ISSUE TITLE
Network camera password bug upon changed settings

### ISSUE THREAD

**Issue by eteran23** [ccrisan/motioneyeos#644]
MotionEyeOS adds a space before a dash to the password when applying saved settings.

To access my network camera a username and password is required. The password for the camera contains a "#", as in "my#Password". Initial setup works fine and the camera connects as expected. Once I edit some settings for the camera in the motionEyeOS interface and apply them the camera stops working. thread-*.conf shows that motionEyeOS added a space before the dash character. "my#Password" becomes "my #Password".

motion produces a rather inconclusive error in motion.log
[2:ml2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (...)
[2:ml2] [CRT] [NET] netcam_start: libjpeg decompression failure on first frame - giving up!
[2:ml2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
(just for future reference)

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/8c8b0b4b4c2c2fd9716fa108cbc54d01678ce83b fixes this problem.
