### ISSUE TITLE
SSH Port Number

### ISSUE THREAD

**Issue by gocursor** [ccrisan/motioneyeos#648]
Is it possible to change the SSH port number for MotionEysOS?

**Comment by Rouzic6666** [comment]
1) log in MotionEysOS
2) make / rw
   # mount -o remount,rw /
3) change port in /etc/sshd_config
4) reboot
   # sync ; shutdown -r now
5) test ...

**Comment by ccrisan** [comment]
Unfortunately that's the only way to do it and it won't survive upgrades. Sorry about that.

**Comment by gocursor** [comment]
Thank you!

But maybe you can leave this ticket open as a future wish... Maybe you can provide SSH port number as a input field in user interface in the future (like HTTP port number and video streaming port number)...
