### ISSUE TITLE
Working Schedule

### ISSUE THREAD

**Issue by Rouzic6666** [ccrisan/motioneyeos#650]
Hi Calin,
I use the "Working Schedule" option. It works perfectly when range is included in a single day.
But when I try to define a period straddling two days at night to capture the event from 18:00 Monday to Tuesday at 09:00 it does nothing.
My configuration :
![capture du 2016-12-16 12 09 20](https://cloud.githubusercontent.com/assets/16211981/21261186/2af12434-c38a-11e6-9f5d-2461c6267349.png)
Thanks you for motioneyeos

Regards,
Jean Louis
motionEye Version 20161125
Motion Version 4.0.1+git37b3595

**Comment by ccrisan** [comment]
It doesn't work that way. You cannot span working schedule across two days. The *from* field must always be smaller than the *to* field. Sorry about that.

**Comment by Rouzic6666** [comment]
thanks you,
I found the solution using complement...
![capture du 2016-12-16 13 55 24](https://cloud.githubusercontent.com/assets/16211981/21263497/79bbc1e8-c397-11e6-8e33-17169878638c.png)
