### ISSUE TITLE
All Pictures twice...

### ISSUE THREAD

**Issue by Dobi29** [ccrisan/motioneyeos#655]
Hi,
i have all pictures twice in my folder.
These are my settings:
![grafik](https://cloud.githubusercontent.com/assets/16850445/21294131/692fbea6-c536-11e6-8af1-5f254b0a3f31.png)
![grafik](https://cloud.githubusercontent.com/assets/16850445/21294140/8a7cd56c-c536-11e6-9a5e-e39556b9f12b.png)
![grafik](https://cloud.githubusercontent.com/assets/16850445/21294145/9af03db2-c536-11e6-9673-b7630dd326c1.png)
What's wrong ?
Thx
Klaus

**Comment by ccrisan** [comment]
How can you have the pictures twice? Duplicate filenames are not allowed.

**Comment by Dobi29** [comment]
i have them twice uploaded on my google drive
![grafik](https://cloud.githubusercontent.com/assets/16850445/21294708/d2b7fa84-c543-11e6-9b78-cc4d51a8732e.png)

**Comment by ccrisan** [comment]
Please add a -%q at the end of the still images filename pattern and see if the problem persists.

**Comment by Dobi29** [comment]
-->
![grafik](https://cloud.githubusercontent.com/assets/16850445/21303255/66f668d8-c5bd-11e6-9de6-bde73372e228.png)

**Comment by Chiny91** [comment]
It looks as though you have the video device (camera) set at Frame Rate 2 (per second).   Google and motion are correctly storing both pictures, although with a slightly different file naming mechanism.   If you want only 1 pic/sec, you'll need to drop the frame rate.

**Comment by ccrisan** [comment]
That is correct, your motion is configured to store more than one picture per second. While that is not something I'd recommend, it is possible, but you'll have to make sure the filename pattern allows it (which is what you did by adding %q to it).

**Comment by Dobi29** [comment]
...but it is the same picture.

**Comment by Chiny91** [comment]
How do you know it is the same (what is your "Frame Change Threshold") ?   Try enabling "Show Frame Changes" in "Motion Detection" and then look at 2 pictures of the same second.
