### ISSUE TITLE
Read-only file system?

### ISSUE THREAD

**Issue by rainkinz** [ccrisan/motioneyeos#656]
Just flashed a 16Gb SD card for a raspberry pi 2 B. When I login via SSH and try to create a file I get an error about the FS being readonly:

```
[root@meye-fc06aa29 ~]# touch testing
touch: testing: Read-only file system
```

Is this expected? 
Thanks

**Comment by zoocey** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file

**Comment by rainkinz** [comment]
Ugh, sorry I thought I'd read through the FAQ, but I guess not!
