### ISSUE TITLE
Version 20161125 Video Streaming enable/disable problem

### ISSUE THREAD

**Issue by Gotland** [ccrisan/motioneyeos#658]
The ON/OFF switch to enable/disable Video Streaming seems to be missing...

![clip](https://cloud.githubusercontent.com/assets/24679430/21353434/31652e7a-c6c6-11e6-8081-c5f4087b2826.jpg)

**Comment by ccrisan** [comment]
Make sure you (1) don't have Fast Network Camera mode enabled in Expert Settings and (2) you did not add your camera as a Simple MJPEG Network Camera.

**Comment by Gotland** [comment]
OK, I missed the Fast Network Camera Mode in Expert Settings... Thank 
you for helping, Merry Xmas!

Den 2016-12-21 kl. 12:19, skrev Calin Crisan:

**Comment by Gotland** [comment]
OK, I missed the Fast Network Camera Mode in Expert Settings...
Thank you for helping, Merry Xmas!
