### ISSUE TITLE
Email Notification Setting Up

### ISSUE THREAD

**Issue by MaxfieldXie** [ccrisan/motioneyeos#660]
Hello everyone.  When trying to set up email notification for motion detection. it kept failing. Please help! Thank you in advance!
![screen shot 2016-12-21 at 2 04 45 am](https://cloud.githubusercontent.com/assets/24695580/21385253/a7f9b270-c722-11e6-89e1-33d81fc91ffa.png)

I have avoided special characters in my password, it is a new gmail account 
![image](https://cloud.githubusercontent.com/assets/24695580/21385303/cfc2f352-c722-11e6-867b-bd9a740f6019.png)
This is the message after hitting the "Test Email" 

 I have enable Still Images 
 
![image](https://cloud.githubusercontent.com/assets/24695580/21385365/13af1320-c723-11e6-826d-3beff01acb1e.png)

Thank you for any help!

**Comment by ccrisan** [comment]
Are you sure gmail's SMTP allows you to use a different account than your email address?

**Comment by ccrisan** [comment]
Also, I believe that Google's SMTP uses port 587 by default with TLS.

**Comment by MaxfieldXie** [comment]
Sorry, Can you help me understand a lit more when you said " gmail's SMTP allows you to use a different account than your email address?" True be told told, I don't know how to set it up. 

after I changed the port number new error message 
![image](https://cloud.githubusercontent.com/assets/24695580/21400887/ffeb3f8c-c766-11e6-81d3-a7521998cbb3.png)
Than you for the quick response !

**Comment by BillSmith68** [comment]
That feature doesn't work with Gmail. There is always some sort of error.
