### ISSUE TITLE
TP-LINK Mini N300 USB Wireless Adaptor

### ISSUE THREAD

**Issue by smudge-o-tron** [ccrisan/motioneyeos#662]
I have tried a few wireless adaptors with the Pi zero and all work fine, however when i tried the TP-LINK Mini N300 USB Wireless Adaptor the adaptor doesn't seem to work or be recognised by the zero.

I believe this to be a driver fault.

**Comment by ccrisan** [comment]
Does it work with Raspbian?

**Comment by smudge-o-tron** [comment]
yes ive had it working on OSMC and raspbian, also on a pi 2 and 3.

It may be a power issue with the zero

**Comment by ccrisan** [comment]
Can you try it with Raspbian on the Pi Zero? Also, when running Raspbian, please post the `lsusb` output here.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
