### ISSUE TITLE
First boot on Raspberry Pi 3 (connectivity issue)

### ISSUE THREAD

**Issue by Ikitissimo** [ccrisan/motioneyeos#666]
Hi there,
i was booting for the first time but at the very beginning i got stucked during the configuration of "wired networks" because the system finds no connections available. I think it's just a matter of plugging in an ethernet cable but i was wondering if there is a way to bypass this step and just configure a wifi connection since RbP3 has wifi capabilities.

thank you in advance, i can't wait to make some tests!

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-%28Plus%29-And-Zero.
