### ISSUE TITLE
Feature Request - integrate with ALPR?

### ISSUE THREAD

**Issue by birukun** [ccrisan/motioneyeos#67]
Anyone messing with this and see a possible option for this project?
http://www.openalpr.com/features.html

I would love a menu item for a camera that allows you to configure the functionality to read license plates.

This would be for your cameras facing your driveway, private lane, etc.

Love this project! I am getting more people to use MotionEyeOS. :-)

**Comment by bortek** [comment]
Closing due to lack of Interest from the developers.
