### ISSUE TITLE
Cannot apply new settings

### ISSUE THREAD

**Issue by Skrappjaw** [ccrisan/motioneyeos#673]
Clicking the Apply button tells me an error occurred and to refresh the page but refreshing does not seem to resolve. Fresh install on raspbian with 1 camera. Logitech c910.

**Comment by ccrisan** [comment]
Please try clearing the browser cache and refresh. If that doesn't work, please send me your motioneye.log file.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
