### ISSUE TITLE
Not an "Issue". More of a "is this possible?"

### ISSUE THREAD

**Issue by Budman1758** [ccrisan/motioneyeos#675]
Great project you have here.  Just what the doc ordered for what I'm trying to set up.  I am making several cameras using Raspberry Pi Zeros.  Using dummy surveillance cameras as the housing for the components.  Because these will be outdoors and in the sun I'm thinking they will need a small fan inside to promote airflow through the housing.

What I would like to do is control the fan using the Pi's GPIO to turn the fan on or off based on internal temp.  Wiring a temp sensor and running the fan is easy and coming up with a script to control this is probably no big deal.  My question is can this be done using motioneyeos or do I need to use motioneye on top of a standard Jessie-lite OS?  I also want to control an IR LED array in a similar fashion. The dummy camera comes with red leds that I am replacing with IR LED's.  Using the Raspberry NIOR camera module.  Not sure if the IR LED array will be on when dark or triggered on when motion is detected.

I like the idea of using motioneyeos because of the lower overhead.  But if not possible then I will try the other way.  Thanks for any pointers.

**Comment by ccrisan** [comment]
Well reading the temperature and controlling the GPIO can definitely be done via the sysfs interface in motionEyeOS, just as you would do it on Raspbian. It's a matter of writing a bash script and leaving it run in the background.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
