### ISSUE TITLE
Native support for RTSP 

### ISSUE THREAD

**Issue by cl0udb0y** [ccrisan/motioneyeos#679]
Hi ... do you have any plans to support any other protocols other than HTTP for camera streams? RTSP would be a personal preference...

**Comment by ccrisan** [comment]
RTSP is already supported for more than one year now.

**Comment by cl0udb0y** [comment]
is there a doc/readme you can point me to as using rstp://.... in the URL just gives 'RTSP' not supported... is it only supported on the MotioneEyeOS as I have the MotionEye on a separate ubuntu server and just using RPi as the cameras along with Panasonic and Hikvision for others?

**Comment by ccrisan** [comment]
Well, then you're on the wrong project. This is motionEyeOS. For motionEye, you must make sure you have [motion 4.0](https://github.com/Motion-Project/motion/releases) installed.

**Comment by cl0udb0y** [comment]
Thanks.. I'm using both, thanks for the pointer Calin. Rgds John
