### ISSUE TITLE
unable to see Raspberry Pi NoIR Camera Module V2

### ISSUE THREAD

**Issue by seanlee77** [ccrisan/motioneyeos#682]
hey,

happy new year!

I've installed your latest motion image  on my Pi2. I'm unable to see any local cam's. I've installed it on 2 different Pi 2, so I have ruled out hardware. Also, I can take the pic using raspcstill with no issues.  Do you know if this cam works with this motion. (Raspberry Pi NoIR Camera Module V2)

Do you have any idea what I can do to resolve the issue.

Also to you know if the xbox 360 kinetic will work with this image.

![screenshot from 2017-01-04 23-29-38](https://cloud.githubusercontent.com/assets/8616914/21663524/a4a81a0a-d2d8-11e6-8687-998028c6ef04.png)

Thanks for your help

S

**Comment by sylvaindc** [comment]
I had the same issue. Turns out i had the cable in backwards...

**Comment by seanlee77** [comment]
Hi, 

I checked that and it's plugged in correctly.  Shame I was hoping it was something simple. 

Take care 
S

**Comment by sylvaindc** [comment]
Too bad, could the camera or the ribbon cable be broken?

**Comment by sylvaindc** [comment]
It all works fine on my setup, I've tried with a PI2 (with NoIR1) and a PI3 (with NoIR2). Did it ever work?

**Comment by bortek** [comment]
I have NOIR camera and it is working fine. Please try to google for your problem somewhere else .
