### ISSUE TITLE
Feature request: Block IP after failed logon-attempts?

### ISSUE THREAD

**Issue by Goudtik** [ccrisan/motioneyeos#683]
Is there a possibility to block a incoming IP-address after a few failed login attempts on MotioneyeOS?
Maybe by using fail2ban or something? It would really improve security!

**Comment by skinnyjay** [comment]
Just tested and done, found using google already written out in an article and packaged into Raspbian. Works just fine: https://dvpizone.wordpress.com/2014/03/02/how-to-install-fail2ban-on-a-raspberry-pi/

**Comment by Goudtik** [comment]
but will this work under MotioneyeOS? (currently i'm using Motioneye under raspbian but i'm considering to abandon this and install the OS version)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.

**Comment by rotrials** [comment]
@jarednthomas but the configuration from the link is for ssh not for motioneye login...
