### ISSUE TITLE
Feature Req: Remote Arm / Disarm (motion capture enable / disable) 

### ISSUE THREAD

**Issue by sylvaindc** [ccrisan/motioneyeos#684]
First of all, What a great project! exactly what I am looking for to setup my home security.

I am working on a setup where I install cameras in and outside of my house, each a single PI with Noir camera in a dummy housing. I am looking at probably about 10 cams in total.

As I am fond of my privacy and I dont like false alarms I would like to disable the "interior" (in the house) cameras when anyone is home. The easiest way would be to have a nice traditional key-pad or other electronic lock and send a message to each of the PI's running in the house to disable / enable the motion recording. 

I searched for this, but I cannot find any reference to this (If I missed, then please accept my apologies). It would be cool to have build in functionality for this, but I am equally happy with a hack (e.g. enable / disable motion recording via the command prompt, as I can then just abuse SSH to do it for me).

Would this be possible in the current setup?

Many thanks in advance

Sylvain

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
