### ISSUE TITLE
Clarification: Editable Mask

### ISSUE THREAD

**Issue by gtr33m** [ccrisan/motioneyeos#685]
Great new feature!  I never could get mask images to work properly.

Can you please clarify, the grey or lighter boxes are the areas watched for motion detection, and the black or darker boxes are the ignored area?

**Comment by ccrisan** [comment]
You start with an empty mask (no dark boxes), which is the default. You click and drag to add dark boxes which will *mask out* the frames. So yes, the darker boxes represent the ignored area.
