### ISSUE TITLE
Question-Remote admin + camera hub

### ISSUE THREAD

**Issue by i1own0u** [ccrisan/motioneyeos#686]
Haven't seen the ability in the settings to be able to log into the camera to change settings from the admin side remotely.  Am I missing something? 

Also,

If I have 2 or more cameras set up that I want to view outside of my network, do I need to have 2 ports assigned to them or is there a way to have them viewed as a hub (like you can view them as admin)
(if we're able to remote into the admin side, then I guess that's a solution to this question)

**Comment by ccrisan** [comment]
If you have added your motionEye cameras to your hub as *remote motionEye cameras*, then you should be able to change their settings directly from the hub's UI.

See https://github.com/ccrisan/motioneyeos/wiki/Usage-Scenarios.
