### ISSUE TITLE
Recording alot of False Positives

### ISSUE THREAD

**Issue by championc** [ccrisan/motioneyeos#691]
Hi there

This is a fantastic piece of software and I'm having a lot of fun with it, but with a small amount of frustration.

I have an IP camera indoors, pointing out my window, across the street.  I have left the option for "Show Frame Changes" to ON.  I am getting many instances every day where the recording is triggered but there is nobody about.  When I review the still images, they show large sections of the photo in a red box.  However, I have "Light Switch Detection" now set at 35% and I am still getting these False Positives.  My understanding of this setting is that if the photo changes by more than 35%, then the recording will NOT be triggered - correct ?

It's just that I am chomping up vast amounts of disk space, with nothing happening on them.

I am running with Motion 4.0.1 rather than the original 3.4 ??  since I was trying to get my local USB cam working without success

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
