### ISSUE TITLE
Lib crypto python

### ISSUE THREAD

**Issue by Mikiya83** [ccrisan/motioneyeos#692]
Hello
I try to use a python lib (https://github.com/mjg59/python-broadlink) to start/stop some domotic equipments according to camera detection, but i cannot use AES in python. 
I get `File "/home/ftp/storage/broadlink/broadlink/__init__.py", line 4, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher` . 
I thougt pycrypto lib is included in 2.6.1 because there are references to it in package, but i'm not that sure now ...
If anybody can help, i'm not a python-master ...
Thank you !

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
