### ISSUE TITLE
Feature Request: Programmatically change Text Overlay Custom Text.

### ISSUE THREAD

**Issue by cooleyandy** [ccrisan/motioneyeos#694]
Is there a possible way to use code to change the custom text in the Text Overlay for the video feed?
I see there is a way to change it in the web UI, but I have no clue how to do it using Python code or Bash Script.

I wanted to attach a temperature probe to the Motioneyeos RPi. I was able to read the temperature off the DS18B20 temperature probe, but how to set the text overlay custom text still eludes me.

I have tried using the line of code but it didn't work for some reason:
wget -q --delete-after "http://localhost:8080/0/config/set?text_right=$TEXT"

I found this line of code from an older feature request at:
https://github.com/ccrisan/motioneyeos/issues/76

**Comment by bortek** [comment]
I will close this one. Lets keep #76 as a main thread. Thanks!
