### ISSUE TITLE
Lan Network

### ISSUE THREAD

**Issue by lapajarita** [ccrisan/motioneyeos#698]
Hello, I have configured Static IP and No wireless network, however always the raspberry needs a patchcord connected to LAN when the patchcord is disconnected from raspberry appear the messsage "Ethernet disconnected" and reboot the raspberry every time until the patchcord is connected again, can you please say me how can I proceed for no need a patchcord connected?
Thank you

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#how-can-i-run-motioneyeos-without-a-network-connection
