### ISSUE TITLE
Proble with login

### ISSUE THREAD

**Issue by kytcoin** [ccrisan/motioneyeos#700]
Hi i have the trouble with login vrsion  "motioneyeos-raspberrypi2-20161125"  invalid credetial??
<img width="445" alt="screen shot 2017-01-15 at 01 56 11" src="https://cloud.githubusercontent.com/assets/10095970/21957344/d3b66b8a-dac6-11e6-84d7-84cbdc350c53.png">
wht is that??   :-0
Please Help! can get access ((

**Comment by kytcoin** [comment]
ADMIN password not working

**Comment by johtho** [comment]
Hi
I have the same problem when i try to login from my iphone, but works when using the anroide tablet.
Have tried to login from  diffrent computers?

**Comment by kytcoin** [comment]
i try every time connect from MAC OS X

**Comment by pescadou999** [comment]
i just can say no problem for password admin and user with : RPI3 and motioneyeos-raspberrypi3-20160320.img

**Comment by ccrisan** [comment]
@pescadou999 does that mean you have login problems with recent versions? If yes, which ones have you tried?

**Comment by pescadou999** [comment]
@ccrisan . No sorry i speak French. I have no problem , i think it is a other guy , i have no problem no it is the top with your soft and i make the update direct in the soft and it work goed, great job ccrisan

**Comment by johtho** [comment]
Hi, 
yes i cant login with my iphone, but works fine when I'm using anroide tablet.
Installed version 20161125   4.0.1+git37b3595

**Comment by johtho** [comment]
Tried using W10 and it also works to login. For me it seems that its only iOS device how have the problem to login.

**Comment by ccrisan** [comment]
@johtho try clearing the browser cache on your iOS (if that is even possible).

**Comment by johtho** [comment]
Hi, 
I have know cleared the cache.
And I can login again from my Iphone.

Tank you Crisan.
regards /Thomas
