### ISSUE TITLE
Issue with IMG 20161212 for raspberry

### ISSUE THREAD

**Issue by jsvalderrama** [ccrisan/motioneyeos#702]
Hello, 
I have tried to deploy the motioneyeos-raspberrypi-20161212.img.gz and raspberrypi2-20161212.img.gz but when I power on my raspbperry I just have the screen with several colors (see the picture attached)
![20170115_000653_hdr](https://cloud.githubusercontent.com/assets/6882573/21958807/d463420c-dab6-11e6-9c49-8e64380c385c.jpg)
And nothing happens. I have the same issue with the release motioneyeos-raspberrypi2-20161211.img.gz
The only release that I was able to launch at this time  is the release motioneyeos-raspberrypi2-20161125.img.gz that shows up and setting up.
Could you please tell me how to make the other releases work?
Thanks for your help

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
