### ISSUE TITLE
samba share

### ISSUE THREAD

**Issue by sgiannulli** [ccrisan/motioneyeos#706]
Hi Calin,
any change to do on some config files apart to activate samba on webUI to let it work?
I'm trying latest pre-release on RPi2 and no shares on my Win7 machine
Thanks

**Comment by sgiannulli** [comment]
.......maybe workgroup=MOTIONEY in smb.conf does not help

**Comment by 48296** [comment]
Hi, I'm using a Raspberry Pi 3 and the options in the gui are on. 
I really need the samba share, how do i activate then 
@sgiannulli : did you get the share working? if yes ,how?

**Comment by sgiannulli** [comment]
yes I got it
mount -o remount,rw / to make root partition writable
then changed  workgroup=MOTIONEYE in smb.conf to
workgroup=WORKGROUP

**Comment by 48296** [comment]
I changed the workgroup. now it shows up in the network but is is giving an error when i try to enter it.

**Comment by sgiannulli** [comment]
are you using admin credentials to access the share from windows?
the steps I described above were enough for me on Win7

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
