### ISSUE TITLE
Motioneyeos with Xiaofang Wifi Camera

### ISSUE THREAD

**Issue by hgelpke** [ccrisan/motioneyeos#707]
Through hacks here:
https://github.com/samtap/fang-hacks

I have been able to get a RTSP server up and running that works with VLC using this address:
rtsp://IP:554/unicode

When I input this URL into mOS, it says there is an error and recommends a refresh. There is no username or password to the camera, FYI.

**Comment by ccrisan** [comment]
Please attach your motioneye.log file here.

**Comment by tobilap** [comment]
This camera works fine for me. Did you select TCP/IP when you added the camera?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.

**Comment by sushenmathur** [comment]
@bortek 
the xiaofang cam with fang-hack do not have a username and password for the rtsp stream. Do you leave it blank in the motion eye set up ?

**Comment by bortek** [comment]
No idea actually. I don't own that cam and can't test it, sorry. But i suggest testing it. Leave it blank and test it.
