### ISSUE TITLE
Choppy Video

### ISSUE THREAD

**Issue by djjayrock** [ccrisan/motioneyeos#710]
I get choppy/shaky video in every resolution except 1024/768

I have a Raspberry Pi3 2 of these cameras
https://www.amazon.com/gp/product/B01N3YTNN7/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

Thanks for your Help!!!

**Comment by djjayrock** [comment]
I would love to be able to use 1280x720

**Comment by s0rent** [comment]
I get max 10fps when recording in 1024x768 on a Pi 2 and 3. If you need more then i think you should record on a larger computer and let the PIs stream only.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
