### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by jcfain** [ccrisan/motioneyeos#715]
I noticed in the source here
[https://github.com/ccrisan/motioneyeos/blob/master/package/opencv/opencv.mk](https://github.com/ccrisan/motioneyeos/blob/master/package/opencv/opencv.mk)

That OpenCV may be integrated with motioneyeos somehow.

If this is correct, how would one go by configuring it in to the motion detection?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
