### ISSUE TITLE
Still images almost look inverse, not clear, indistinguishable, incorrect file name

### ISSUE THREAD

**Issue by pgbc** [ccrisan/motioneyeos#716]
motionEye Version 	20161212
Motion Version 	4.0.1+git37b3595
Raspberry Pi 3
When pictures are indistinguishable, the file name is followed by an "m". 
Attached are two files with close time stamps
![camera1_11-47-09m](https://cloud.githubusercontent.com/assets/25236229/22131466/7573af4c-de68-11e6-91c9-0dcaa008f147.jpg)
![camera1_11-47-08](https://cloud.githubusercontent.com/assets/25236229/22131467/757bf9ae-de68-11e6-97e7-4c812cf7e650.jpg)

**Comment by ccrisan** [comment]
Have you enabled Create Debug Media Files option?

**Comment by pgbc** [comment]
I have now, what file should I be looking at for info on my problem?

**Comment by ccrisan** [comment]
Make sure the *Create Debug Media Files* us disabled.

**Comment by pgbc** [comment]
Okay, I misinterpreted your first reply to thinking that I should turn it on?
So it was off when I first posted my problem of the "inverse" or incomplete images.

**Comment by ccrisan** [comment]
Yes, that option should be normally off. The first of your images looks somewhat like the option was on. However the second looks fine to me.

**Comment by pgbc** [comment]
The system had worked fine on a B+, but then I got a Pi 3 and moved the camera to it, and that is when my problems started? I just noticed there is a new update out now, so I will try that and see if it makes a difference?

**Comment by pgbc** [comment]
Cailin.  I upgraded to 20170212 on the 20th of February, and the problem was solved with the upgrade.
All images look normal since the upgrade.
Thanks for your time.
