### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Shrirammc55** [ccrisan/motioneyeos#718]
hi , im new to the motioneyeos , i'd be greatful if someone could tell what would happen if the storage space for writing the captured video get filled, will it overwrite the old files or will it wont store the video when the storage runs out?

**Comment by sylvaindc** [comment]
I remember seeing in an earlier report that it would not automatically
remove old stuff.

**Comment by Shrirammc55** [comment]
thanks for the info. But i would appreciate if someone could be sure about it
