### ISSUE TITLE
Wifi booting isssues

### ISSUE THREAD

**Issue by maurbeck** [ccrisan/motioneyeos#720]
I just added wireless information to the settings and let it restart. Now I'm in a loop saying:

<13> Jan 1 00:00:25 wifi: disconnected

it keeps doing that until it restarts. How do get back into the pi to take off those wireless credentials so it doesn't get stuck in a boot cycle like this? I plugged the ethernet in and out but it wont pick that up.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
