### ISSUE TITLE
Feature request: Get (web hook) notification when motion stops

### ISSUE THREAD

**Issue by CatoAntonsen** [ccrisan/motioneyeos#722]
Hi,

I've made a [plugin](https://github.com/CatoAntonsen/MMM-MotionEye) to [MagicMirror²](https://magicmirror.builders/) for displaying the streaming image from Motion Eye. One of my features is to automatically show the stream when motion is detected. I've implemented this using the web hook from MotionEye.

At the moment I have no way of telling when to hide the stream, except from time. 

Request: Would it be possible to add a (web hook) notification when MotionEye stops recording the motion?

Edit: If it matters, I just donated... ;-)

Sincerely,
Cato Antonsen

**Comment by hellyberry** [comment]
You could use in motion(eye)
'on_movie_end'
to do exactly what you want!
