### ISSUE TITLE
ONVIF IP cameras with MotionEye

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#723]
Is it possible to integrate IP cameras as follows ONVIF standard into the Motion Eye ecosystem as an external camera ?

**Comment by ccrisan** [comment]
As long as your camera has a JPEG (snapshot), MJPEG or RTSP URL, it can work just fine with motionEye(OS).

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.

**Comment by SuneBielefeldt** [comment]
It is possible to buy dual stream cameras with ONVIF and mjpeg support. Here is an example of such a camera. I will try it in the near future.

Hikvision® DS-2CD2142FWD-I 
4MP WDR Dome Network Camera with DC12V & PoE
(Waterproof Day Night Motion Detection PoE)
30m IR

http://www.lightinthebox.com/hikvision-4mp-wdr-fixed-dome-network-camera-with-dc12v-poe-waterproof-day-night-motion-detection-poe-dual-stream-remote-access-plug-and-play-30m-ir_p5546865.html
 
![1496320996684](https://cloud.githubusercontent.com/assets/9556987/26680509/9de8f64a-46d1-11e7-9bb3-6ca9de7bbe75.png)
Ü
![zafxun1490752209794](https://cloud.githubusercontent.com/assets/9556987/26680562/d3e56828-46d1-11e7-8f01-cc666c5dcbd9.jpg)

**Comment by waitfor1t** [comment]
I find more cameras with ONVIF without an RTSP stream (that I can find)... not sure how that happens.. I will try a port scan to see what ports it may be using. Basically I think better ONVIF support would be very helpful.
