### ISSUE TITLE
Video length 0 secs with extremely high frame rate

### ISSUE THREAD

**Issue by akashskypatel** [ccrisan/motioneyeos#724]
All of the videos generated are 0 secs long and have extremely high frame rate.

Is this an issue with motion dameon?
I have tried searching for similar issues on both motioneye and motion and have not seen anyone reporting this issue. I have also tried this at the lowest settings but i get the same exact results.

I am running this on Raspberry Pi 2 Model B with a NoIR Camera module

![image](https://cloud.githubusercontent.com/assets/8129618/22184317/3a516c88-e09d-11e6-865a-0bc5f40d29a2.png)

My settings:
![image](https://cloud.githubusercontent.com/assets/8129618/22184340/c68e45e0-e09d-11e6-99c8-12eb373638b6.png)

![image](https://cloud.githubusercontent.com/assets/8129618/22184300/f05652ba-e09c-11e6-8e62-e09a35cf783d.png)

![image](https://cloud.githubusercontent.com/assets/8129618/22184311/243b5c06-e09d-11e6-8d68-bbe326979431.png)

**Comment by cgpgh** [comment]
I faced a similar issue today. 0 Sec video.

**Comment by chevyman142000** [comment]
I believe I am facing a simliar issue as well. I have a brand new setup with a Raspberry Pi 3 and a Foscam camera. Only difference I'm seeing is that I have mine set to record movie continuously as I have a 3tb external hard drive connected. When I download the video so that I can watch it, it downloads a zero kb file that I am unable to play back. When looking at the interface though, it says the file is like 6 or so gb in size.

**Comment by ccrisan** [comment]
I can't say anything about the other cases, but @chevyman142000 in your case you're trying to download a relatively large file via motionEye which is unfortunately problematic (things aren't optimized enough there and a lot of CPU is required). Timeouts or incomplete files may be retrieved.

**Comment by chevyman142000** [comment]
Thanks for the reply. Is this something you are working on for future updates? What is your recommendation for continuous recording? Right now I have them at 4 hours in length. Maybe do a shorter time so they are smaller files?

**Comment by ccrisan** [comment]
@chevyman142000 I'm not currently working on this problem and frankly I don't have any ideas on how to optimize it. I'm sorry about that.
