### ISSUE TITLE
Can`t add OV5647 camera module to RPI3 motionEye

### ISSUE THREAD

**Issue by svizc** [ccrisan/motioneyeos#725]
Hello,

i am new in motionEye OS.

Few days ago i bought new RPI 3.  Reason of buying it is i would like to run motionEyeOS on it with a few cameras (wifi and cable connected). So with win32diskimager i installed motionEye on sd card and started it. Changed admin password, added everything but when it comes to the point when i want to add [THIS CAMERA](http://www.ebay.com/itm/261582953144) i cant find it on the list. Where option Local Camera is, under there i cant chose nothing (it say`s no cameras). 

motionEyeOS is up to date, it`s latest one "motioneyeos-raspberrypi3-20161212".

PS. in november 2k16 i was trying this system with another RPI 3(i am ussing that one now for TV) and it worked perfectly. Version was 20160919 and  i could add camera with no problem.

![screenshot_20170122-181601](https://cloud.githubusercontent.com/assets/25281975/22197490/83b03692-e152-11e6-8e2c-a6a518f02657.png)
![screenshot_20170122-181623](https://cloud.githubusercontent.com/assets/25281975/22197493/869f0946-e152-11e6-9ef9-e5b739d1bc63.png)
![img_20170122_181113](https://cloud.githubusercontent.com/assets/25281975/22197502/8ecb97ce-e152-11e6-8ef7-ca18472eead4.jpg)

Pictures added and sorry for my english :)

**Comment by sylvaindc** [comment]
Are you sure the camera connector is attached correctly?

**Comment by vikingscania** [comment]
The cable is attached to wrong connector. Use the other one between hdmi and headphones.

**Comment by svizc** [comment]
Hello,

it doesnt work on that one either... just removed IR modules and it also doesnt work...

**Comment by vikingscania** [comment]
Hi again,
It could also be that the connector on the backside of the camera is loose.
Happend for me once.

**Comment by svizc** [comment]
Ok, will try that at home and report what happened... Thanks

**Comment by svizc** [comment]
Its the same, i cant add camera...

**Comment by sylvaindc** [comment]
Can you send another picture of your setup

**Comment by VincentvanDuijn** [comment]
i am having the same issue

**Comment by svizc** [comment]
Did you already figured out where is the problem? I will try one more time now with newest version of the OS and the i will report what happened...

**Comment by VincentvanDuijn** [comment]
my fix was 

sudo nano /etc/modules

and place bcm2835-v4l2 keep in mind it is an L at 4l2

**Comment by svizc** [comment]
@VincentvanDuijn and on the end this complitely fixed the problem for you, no more problems?. Few day ago i had a little time and once again i tried to add camera module. This time in RPI1 model and RPI3 model, they are both on latest OS 20180101. I added line bcm2835-v4l2 in modules, but this time i get this on both models of Raspberry Pi...
![camera](https://user-images.githubusercontent.com/25281975/35498439-8b8199a6-04ce-11e8-81a6-c486b7566995.JPG)

Any ideas?

**Comment by svizc** [comment]
One stupid question, looking all over, how do i edit, actually on the end save file modules file when i put "bcm2835-v4l2" in there. It says that file modules is unwritable, hot to set all the permisions to that file? I am root, but still... tried chmod 777 and nothing?

**Comment by ccrisan** [comment]
@svizc https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file

Also, if you want to load a module, see https://github.com/ccrisan/motioneyeos/wiki/modules. However, on a Raspberry Pi, `bcm2835-v4l2` is already present in the modules file. I don't see why you would readd it.

**Comment by svizc** [comment]
Still didn`t figure out where is the problem that camera doesn`t work. On both models, RPI 1 and RPI 3 i can`t add camera. I tried, camera works perfectly, but not with motioneye. 

ccrisan can you help me?

**Comment by ccrisan** [comment]
Can you try and make a screencast or series of screenshots showing what you exactly do from the very beginning to when the camera doesn't work?

**Comment by cablegunmaster** [comment]
I had an similar issue and it all comes down to me to wiggling the cable and rebooting a few times and it will find it.

Basically its a reinsert the cable. make sure its tight.  Reboot the raspberry pi and see if the camera is found kind of operation. 
If not ?
Retry, and recheck both side of the connection even if you are sure. Only after 15 times you could say for sure its not the wire/cable issue. (after six times for me).
