### ISSUE TITLE
[Request] Webmin/Linux-Dashboard or similar administration/monitoring software

### ISSUE THREAD

**Issue by Bluscream** [ccrisan/motioneyeos#726]
I wish there would be a quick way to check things like cpu/ram/network usage etc. preferably in the webpanel itself but third party software would be ok too

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneye/wiki/Monitoring-Commands. In motionEyeOS on RPi you get some monitoring info out-of-the-box by enabling it in Expert Settings.

**Comment by Bluscream** [comment]
That seems pretty 'advanced users only' :(

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
