### ISSUE TITLE
starting wpa_supplicant: done (brcmfmac)

### ISSUE THREAD

**Issue by wouter0702** [ccrisan/motioneyeos#727]
i've installed the latest version of motioneye. when i boot up my rsb pi 3 i couldn't connect using my ip address. a few times later i could connect. now i am stuck in a infinte loop of rebooting my rsb. when it worked i used ethernet. i get starting wpa_supplicant: done (brcmfmac) and then i get disconnected a few times. then the rsb is rebooting. what can i do to stop the infinte loop? why does it sometimes let me connect and sometimes not?

**Comment by bortek** [comment]
check your power and google for power issues, this has nothing to do with mnotioneyeos
