### ISSUE TITLE
Auto updater to 20161212 not working?

### ISSUE THREAD

**Issue by silversword411** [ccrisan/motioneyeos#729]
I see there's a 20161212 release but software check button reporting up to date?

![2017-01-23 11_53_18-meye-2dcfc336](https://cloud.githubusercontent.com/assets/13395348/22213569/a78fe3a4-e162-11e6-9d9d-aa6dbeeda6ae.png)

**Comment by Chiny91** [comment]
I suspect you have not checked _Enable Prereleases_ under _Expert Settings_.    You may not want to do that for less well tested versions, although 20161212 has been in pre-release for a while.

I trust you have blanked out (for your post) your passwords and have not really left them blank for the default users 😱

**Comment by silversword411** [comment]
Didn't know it was in prerelease status since it was on the main download page, that's definitely the difficulty!

No passwords, because local LAN access only. Would certainly change if I every put it internet facing :)
