### ISSUE TITLE
Any plans to support the Tinker Box?

### ISSUE THREAD

**Issue by mehtaman** [ccrisan/motioneyeos#730]
You can now pre-order the ASUS Tinker Box - with 4K output:
http://cpc.farnell.com/asus/90mb0qy1-m0eay0/tinker-board-2gb-1-8ghz-4k-gb/dp/SC14363

Would you consider porting a Pi build over to the ASUS board?

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-motioneyeos-be-ported-to-insert-your-board-here
