### ISSUE TITLE
Enabling Fast Camera removes motion capture options.

### ISSUE THREAD

**Issue by hbar98** [ccrisan/motioneyeos#731]
Pi Zero with Pi Camera V2, using motioneyeos 4.0.1+git37b3595.

When I enable fast camera and restart the pi, I lose all motion capture options. All my custom settings (day and times) reappear if I disable fast camera.
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/725525/motioneye.txt)
[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/725526/dmesg.txt)

**Comment by sylvaindc** [comment]
Fast camera turns it into a simple (fast) ip camera and disables the
capture functionality.
