### ISSUE TITLE
Can Motioneye begin recording immediately from RiPi power on?

### ISSUE THREAD

**Issue by dorkygrin** [ccrisan/motioneyeos#735]
I'd like RiPi to be off until an external trigger powers it up. Can motioneyeOS be set to record video as soon as the RiPi is booted? I don't see any way to do it in Motion Options. 

Thanks!

**Comment by Shrirammc55** [comment]
Yeah, by default if u set the setting for the movies to be 'ON', it would automatically start recording once the raspberry pi is on. I've tested it recently
