### ISSUE TITLE
Motioneyeos with Compute Module IO board V3 ?

### ISSUE THREAD

**Issue by willbird** [ccrisan/motioneyeos#739]
https://www.raspberrypi.org/products/compute-module-io-board-v3/

This might be a nice way to add two cameras, and the compute modules come with or without eMMC flash.

https://www.element14.com/community/docs/DOC-83926/l/raspberry-pi-compute-module-3

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
