### ISSUE TITLE
wpa_supplicant: failed (8192cu)

### ISSUE THREAD

**Issue by dpradaro** [ccrisan/motioneyeos#740]
Hi there. I have been a user of motioned OS for a couple of weeks on a RPi3 and I love it! Now, trying to use it on a RPi0 has been a huge pain in the neck. Initially, I was utilizing the wrong WIFI dongle and only realized it once I installed Raspbian on the Pi and tried using it. Went and purchased a new dongle (Edimax n150) which works just fine in Raspbian but will not connect to motioneye OS no matter what I do. I have read every post and done every recommendation but nothing works.

Ultimately I am getting a wpa_supplicant: failed (8192cu) message. What does that mean and how can I fix it? Please HELP!
![img_1117 jpg](https://cloud.githubusercontent.com/assets/22361683/22401408/c98df9f0-e586-11e6-90bc-ef1088ee7d2b.jpeg)

**Comment by strofse** [comment]
I have this problem too.

**Comment by sylvaindc** [comment]
Just thinking out loud, but have you tried adding a kernel mod for the
specific network chip?

I seem to remember the wiki saying something about that,  but I'm not sure

**Comment by ccrisan** [comment]
@dpradaro does this happen with various versions of motionEyeOS or is it just the latest?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
