### ISSUE TITLE
Feature Request: Boot Loop Detection and Action

### ISSUE THREAD

**Issue by hellyberry** [ccrisan/motioneyeos#746]
I had serious boot looping problem after having switched from Pi 2 to Pi3. I had no WIFI configured, as I am using wired access but it was trying to use Wireless nevertheless. So it constanly rebooted writing to data-partition, creating some truncated files and filesystem errors. 

Can you include a configurable Boots per time interval (e.g. max 10x per hour?) And an action when this is detected each boot during the interval? And what to do when the limit is reached. Deep sleep for increasing intervals? Extensive logging automatically activated?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
