### ISSUE TITLE
Raspi UPS HAT Board support?

### ISSUE THREAD

**Issue by bbead** [ccrisan/motioneyeos#750]
Hi,

I got a Raspi UPS HAT Board (http://www.raspberrypiwiki.com/index.php/Raspi_UPS_HAT_Board). Does Motioneyeos support something like this or do you plan future support? It would be great to have ups support on our cameras when the power goes down.

Thanks.

**Comment by bortek** [comment]
What kind of support you think is needed? Isn't it enough to follow the instructions on the HAT board wiki and install the drivers?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
