### ISSUE TITLE
Feature: storage client rather than server

### ISSUE THREAD

**Issue by george-vieira** [ccrisan/motioneyeos#752]
I see there's ftp/smb server and I could potentially run motionEye on the central server but it could be good if the rasp pis could upload via nfs mount or some other network method (seen it has SMB at least) avoiding storing on sd card or having additional storage added locally (ie big temp buffer USB stick, or disk, etc).

I have a linux server with raid etc, so makes sense to just push to upstream if possible, but I'll might try installing a central server instance, just preferred not to.

**Comment by hellyberry** [comment]
SMB or NFS is not the best from a security-appliance perspective.

If NFS would suit your use-case, why not use SSHFS (or alternatively SFTP/SCP)?

**Comment by george-vieira** [comment]
I'm fine with anything. You could let the OS take care of the security perspective as anyone can simply setup IPSEC or openvpn so there would be no need to secure at the application layer.
I'm just trying to avoid having the central server having to rsync from remote multiple motioneye instances whereas if they all mount or remote send images to a central system would be better.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
