### ISSUE TITLE
Layer 7 Firewall

### ISSUE THREAD

**Issue by impressio** [ccrisan/motioneyeos#759]
Hi ccrisan

Some functions are not working when layer 7 firewall is active. I don't know if Layer 7 Firewall actually blocks ports. Any ideas?

Thanks

**Comment by ccrisan** [comment]
Given the relatively large number of users asking this question (or similar), I have added [this](https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-ports-do-i-have-to-open-in-my-firewall) FAQ entry.

**Comment by impressio** [comment]
found out that I had blocked all video applications in layer 7 firewall
