### ISSUE TITLE
Unable to add remote camera

### ISSUE THREAD

**Issue by emosbek** [ccrisan/motioneyeos#760]
Hello,

When i try to add a remote camera as my first cam i get an error saying `An error occurred. Refreshing is recommended.`
Remote cam is checked and working and i'm confident that the username and password is correct.

_Remote MotionEyeOS:_
motionEye Version	20161125
Motion Version	4.0.1+git37b3595

_Local MotionEyeOS:_
motionEye Version	20161212
Motion Version	4.0.1+git37b3595

Logfiles:
[messages.txt](https://github.com/ccrisan/motioneyeos/files/766425/messages.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/766426/motioneye.txt)

**Comment by ccrisan** [comment]
What camera(s) do you have configured on your remote motionEyeOS?

**Comment by emosbek** [comment]
local Wideangle CSI cam

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
