### ISSUE TITLE
Individual stream not working/available

### ISSUE THREAD

**Issue by emosbek** [ccrisan/motioneyeos#761]
i got two camera added to my MotionEyeOS. Both are powerd by CSI r.pi MotionEye.
The local on i got the possibility for livestream via http://MotionEyeIP:8081 stream, but for the remote cam this is not an option :/

under video streaming > Useful URLs its not even listed (left one in the picture).

any guesses?

![motioneye setup](https://cloud.githubusercontent.com/assets/11929143/22828158/13258852-ef9c-11e6-9ece-25c565b4cea2.jpg)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
