### ISSUE TITLE
Installing ffmpeg on Raspbian

### ISSUE THREAD

**Issue by coproc79** [ccrisan/motioneyeos#762]
I am currently trying to build a RPi2 using the Rasbian Jessie Lite with the most updated packages (as of Feb 6, 2017.)
I am attempting to follow the posted instructions to install MotionEye on top of that following the instructions found on [https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian](url)
The problem I run into is in step 1 where I need to install ffmpeg. 
This package is not found at the location, nor was I able to find it anywhere else when searching.
(Consequently, Google search pointed to that vary same solution.)

I use the command (as sudo) `dkpkg -I ffmpeg_3.1.1-1.deb` I get the following error message:
```
dkpg-deb: error: 'ffmpeg_3.1.1-1.deb' is not a debian format archive
dpkg: error processing archive ffmpeg_3.1.1-1.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 ffmpeg_3.1.1-1.deb
```
I'm not sure where I could get the source code or how to compile it if I had it.
I have also attempted to search the GitHub for any other information as well and have not been able to find anything.

Thanks in advance.

**Comment by cephasiii** [comment]
Do you need to install ffmpeg? I have never had to installing it when installing motioneyeos ontop of raspbian.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
