### ISSUE TITLE
Cannot send notification  

### ISSUE THREAD

**Issue by peternsomerset** [ccrisan/motioneyeos#763]
Hi,

I have two emails accounts (gmail.com and virginmedia.com).  when I set up either smtp configurations motioneyeos gets timed out with " Notification email failed: Connection unexpectedly closed: timed out!".
I do not have any "special characters" in the password,  but I can send mail from the same PC via Thunderbird when using each of the smtp servers as "default".
Any ideas as what is causing this and or how to diagnose how it is failing? 
I am happy to just use my gmail account if its easier to diagnose.

Thanks

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
