### ISSUE TITLE
Feature Request: Capture Best Image

### ISSUE THREAD

**Issue by anthony82** [ccrisan/motioneyeos#767]
Using motion or even motioneyeos, there is a built in ability to have motion capture the best image of the series instead of X number of pictures per second. This is very convenient for reviewing the images for activity and then if need be, watching the corresponding recorded video. This is enabled in motioneyeos for example by editing the thread-1.conf (or whichever camera you want to edit it on) and changing the line "output_pictures on" or "output_pictures off" to "output_pictures best". My question is, would it be possible to implement this in to the GUI as check box when "output_pictures" is enabled. As stated, I can manually change it, but every time any other changes are made and applied, it overwrites it and I have to go back and manually edit it and restart motion again. Thought it would be a nice addition, let me know your  thoughts.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
