### ISSUE TITLE
Ov51x (Ominivision drivers) ???

### ISSUE THREAD

**Issue by bwente** [ccrisan/motioneyeos#772]
Install went smooth. Great job.

I wanted to use an old usb web cam I had in the junk drawer. A Hawking USB web cam.

Any chance of adding the drivers?

**Comment by ccrisan** [comment]
Are you on the RPi? If yes, is it supported by Raspbian? If yes, it will be supported by motionEyeOS as well.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
