### ISSUE TITLE
Feature Request: VNC Connect Integration

### ISSUE THREAD

**Issue by ajayjosepaul** [ccrisan/motioneyeos#773]
Please integrate support for VNC Connect

https://www.raspberrypi.org/blog/get-back-to-my-pi-from-anywhere-with-vnc-connect/

**Comment by ccrisan** [comment]
VNC requires a UI (normally the X server) to be present on the Linux machine. This is is not the case with motionEyeOS and will never be. Sorry.

**Comment by ajayjosepaul** [comment]
That's right, completely forgot, no worries. Thanks for all maintaining this project.
