### ISSUE TITLE
trigger on one camera triggers them all | the grand scheme

### ISSUE THREAD

**Issue by molly78** [ccrisan/motioneyeos#774]
Hey, trying to setup my camera array & this scheme is what I think will work for me:

Pi Zero's all are Fast Network Cameras with piv2 cam's - will be 3 or 4 of them. Max resolution streaming out here. At ~2 fps is fine with me.

I then have an Odroid XU4 for the hub, doing the motion control and writing the images out.

At the end of the day, ie 12:01am I plan on running ffmpeg to make an mp4 of the previous day's images:

ffmpeg -framerate 24 -pattern_type glob -i '*.jpg' -c:v libx264 -pix_fmt yuv420p ..\2017-02-16-Cam1.mp4
for each of the cameras.

This will combine the images into a movie & tests have shown I can get about 2000 images into a movie in about 30 seconds of processing time, at about 15-20MB .

I'd then like to combine them into a lesser (less resolution) mosaic per day
https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos

---- upload to daily mosaic dropbox videos

End of the week, combine the daily mosaic's

---- upload to weekly mosaic dropbox videos

End of the month, combine the daily mosaic's and delete the daily's & the previous month's weekly's

---- upload to monthly mosaic dropbox videos

But always tuck away the original jpeg's...

So to do this and have it make sense, I'd need the timestamps of the pix to all be somewhat lined up. Plus or minus a second. Otherwise say Camera A is busy and takes lots of shots but B doesn't see much and therefore isn't  taking snaps...

**So any way the camera's triggers can be shared?**

Ie, only one cam is triggered but all take shots?

If not I think we can fudge it with the concat demuxer and some wizardry...

- Scan in all the image folder times
- Do a comparison to line up timestamps
- Pad the frames so they line up with each other
- Generate the video for each camera.

http://trac.ffmpeg.org/wiki/Slideshow

> 
> Concat demuxer
> 
> You can use the concat demuxer to manually order images and to provide a specific duration for each image.
> 
> First, make a text file with the appropriate info:
> 
> file '/path/to/dog.png'
> duration 5
> file '/path/to/cat.png'
> duration 1
> file '/path/to/rat.png'
> duration 3
> file '/path/to/tapeworm.png'
> duration 2
> file '/path/to/tapeworm.png'
> 
> (Due to a quirk, the last image has to be specified twice - the 2nd time without any duration directive)
> 
> Then run the ffmpeg command:
> 
> ffmpeg -f concat -i input.txt -vsync vfr -pix_fmt yuv420p output.mp4
> 

Any input is appreciated as this seems like an scheme that makes sense and requires minimal processing time, at a quiet hour....

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
