### ISSUE TITLE
How do we add PiEye M-JPEG and, or RTSP streams/cameras?

### ISSUE THREAD

**Issue by bdheeman** [ccrisan/motioneyeos#775]
How do we add PiEye (https://github.com/jacksonliam/mjpg-streamer) M-JPEG and, or RTSP streams/cameras?

Add possibly c++rtmp-server's (https://github.com/dreamsxin/crtmp) rtmp streams?

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
