### ISSUE TITLE
Lan LED's

### ISSUE THREAD

**Issue by duckietm** [ccrisan/motioneyeos#778]
Hello, 

Is there a way to disable the LAN lights in motioneyeos, i see this can be done : https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=72070
This would be super cool to have this 🥇

**Comment by pimuser** [comment]
Yes there ist a way. Just look at Wiki and then howto. But I,ve tried it with my Raspberry Pi 3 and it does't work. Bothe LED still on. :-(

**Comment by m4rky-m4rk** [comment]
In the How To's it tells you how to change the config file to do this.

https://github.com/ccrisan/motioneyeos/wiki/Turn-Off-LEDs

As the file is write protect you also need to mount and remount as rw

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
