### ISSUE TITLE
Browser doesn't show camera output in main viewing window

### ISSUE THREAD

**Issue by wallclimber21** [ccrisan/motioneyeos#78]
After playing with various configuration settings, the web interface doesn't show any images. However, the camera is recording pictures and video.

Rebooting doesn't fix it.

I did the following:
- Save configuration of failing case
- Reinstall completely
- Save configuration of passing case.
- Restore failing case

After restoring the failing case, everything failed again. Good! :-)

Find in attachment the thread-1.conf file (with .txt extension to make github happy) that has the failing case.

Thanks!
Tom

[thread-1.conf.txt](https://github.com/ccrisan/motioneyeos/files/70298/thread-1.conf.txt)

**Comment by ccrisan** [comment]
It might have to do with the streaming authentication. It's a known bug that has been fixed in upstream motionEye but hasn't been yet integrated into motionEyeOS. Could you please try disabling authentication for streaming and see if the problem goes away?
