### ISSUE TITLE
no picture with movie on

### ISSUE THREAD

**Issue by Philippe-M** [ccrisan/motioneyeos#780]
With the latest version, when video recording is activated when detecting a motion there are no more attached images in the notification mail.

**Comment by ccrisan** [comment]
Please attach your motioneye.log file.

**Comment by Philippe-M** [comment]
[motioneye.log.txt](https://github.com/ccrisan/motioneyeos/files/789405/motioneye.log.txt)

**Comment by ccrisan** [comment]
`ERROR: timeout waiting for the media listing process to finish` indicates you have too many pictures and it takes too much time to look through them and select those to be attached. Clean up your media files folder.
