### ISSUE TITLE
Continuous Recording with usb camera's

### ISSUE THREAD

**Issue by Loscarones** [ccrisan/motioneyeos#781]
Hi ccrisan,

Thanks for the good work! 
Although i have an issue. My setup is:
1x Raspberry pi 2
2x USB camera
network cable
network share saving

The issue is when i set one of the camera's to continuous recording the memory of the pi will slowly get full. I've set the video memory to 650mb. It looks like a memory leak, but i'm not the best at programming so i don't know. I hope you can fix this! (PS it gets really hot while recording?)
![knipsel](https://cloud.githubusercontent.com/assets/18003621/23165463/7b57c3ec-f83c-11e6-964f-469ae74c8d46.PNG)

**Comment by bortek** [comment]
@Loscarones Can you elaborate a little bit. What do you mean by "memory of the pi will slowly get full". Are you using any specific tools?

**Comment by shinji2009** [comment]
same here. pri3. everything was fine but then i swich to network share. sometimes it's looks loke memory leaked, sometimes it's don't. some network queue share problem maybe? help please

![1981](https://cloud.githubusercontent.com/assets/6340606/23338625/64b18736-fc42-11e6-944b-33ba7a45525d.JPG)

![1979](https://cloud.githubusercontent.com/assets/6340606/23338613/1801b8ca-fc42-11e6-8bd1-e776952a293f.JPG)

**Comment by shinji2009** [comment]
oh noes now its something with local storage too. 
![1983](https://cloud.githubusercontent.com/assets/6340606/23338966/6fc734d8-fc4a-11e6-8009-98a44b6b17d7.JPG)
why git wont accept my logs or zip? i was able to get a 5 log files from expert settings. is there any sensative data in them?

**Comment by bortek** [comment]
Honestly I dont know what your issue is. This is definitely  not a motioneyeos issue.  If still interested please post your question in the forum page. I will close this issue.
