### ISSUE TITLE
Feature Request: ui improvements

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#789]
hi.  ok.
"Network Link Timeout" and "Date Updating Interval" 	 have no units.
maybe it will be useful to have "restore defaults" button in the ui. after pressing on it everything become like just installed from image. it is much simpler than install from image again.
video device fps changes video streaming fps fo no reason. for example if streaming fps is 5 and i change video device fps to 10, streaming become 10 too.
no popup tip above system monitoring info. (cpu temp|5min? cpu load average|total network speed).
.ogg format actually saves as .avi files.
it is very hard to set Frame Change Threshold and Light Switch Detection to 0.1. it will be nice if such a exact value can be set by typing numbers in the field. actually set to 0.1 like this: set it to 0 and then press Right key on keyboard once, and i think this will be 0.1, but i am not sure because i can't pick it with mouse without move it.
thank you.

**Comment by ccrisan** [comment]
Too many ideas into a single request. Please consider opening one issue per problem. I'm closing this as it's impossible to keep track of everything you've mentioned here.
