### ISSUE TITLE
strange .motioneye1488 folders in the network share

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#790]
hi
![1968](https://cloud.githubusercontent.com/assets/6340606/23345273/0ba17d8c-fcbe-11e6-9715-596f5d89b619.GIF)
what's the purpose of them? is it possible to not to create them? because they are distracting. can't find any settings related. 
thank you

**Comment by ccrisan** [comment]
Those are folders used to test the write access to your SMB share. Normally they get removed automatically unless there are some permission problems. It's safe to delete them. If they keep reappearing, please attach your motioneye.log file.
