### ISSUE TITLE
"Network Link Timeout" and "Date Updating Interval" have no units.

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#791]
hi. 
"Network Link Timeout" and "Date Updating Interval" have no units.
thank you.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.

**Comment by ccrisan** [comment]
a6b5fcc6c27ec2ab2358325883eae9e2666de68c and https://github.com/ccrisan/motioneye/commit/46627c6734d5cc7809083a041e9f12b5e2a28589 should fix this issue.
