### ISSUE TITLE
feature request: system monitoring info popup or tip

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#794]
hi. 
no popup tip above system monitoring info. (cpu temp|5min? cpu load average|total network speed) or under the "?" symbol in the expert settings.
thank you.

**Comment by ccrisan** [comment]
The text displayed as monitoring is configurable. It defaults to something simple when using motionEyeOS on the Raspberry PI, but generally speaking you can write a script to output whatever you want there. Hardcoding a tooltip there wouldn't make sense.
