### ISSUE TITLE
.ogg format actually save .avi files.

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#796]
hi. 
.ogg format actually saves as .avi files.
rpi3
thank you.

**Comment by ccrisan** [comment]
What version is this? What board?

**Comment by shinji2009** [comment]
motionEye Version 	20170212
Motion Version 	4.0.1+git37b3595
rpi3

**Comment by ccrisan** [comment]
I'll look into it.

**Comment by ccrisan** [comment]
It seems that the ogg container is no longer supported. The next version of motionEye(OS) will have this option removed.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/3c5e6f1d33227fabea0dde37b606f8656840fecb removes the no-longer-supported ogg format.
