### ISSUE TITLE
feature request: Show Frame Changes in percents

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#797]
hi
Show Frame Changes in   percents make  Frame Change Threshold and Light Switch Detection adjustment much easier than in pixels, because  Frame Change Threshold and Light Switch Detection are in percents. 
rpi3
thank you

**Comment by ccrisan** [comment]
motionEye(OS) can't do anything about this. It's generated internally by motion.

**Comment by shinji2009** [comment]
but Frame Change Threshold and Light Switch Detection are in percents :(
how motion compare percents with pixels? it is different units. there should be Frame Changes in percents somewhere
