### ISSUE TITLE
video darker than still images

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#799]
hi
video for some reason much darker tnan pictures or Desktop View  in the web ui.
here is a still image
![23-30-43](https://cloud.githubusercontent.com/assets/6340606/23370840/94fc2b56-fd48-11e6-9f9b-bca3b798caba.jpg)
here is a video snapshot taken from same time video without any brightness/contrast adjustmets 
![grab00122](https://cloud.githubusercontent.com/assets/6340606/23370912/d3255cb8-fd48-11e6-9249-27089749375f.JPG)
rpi3 20170212 V4L2 Camera

**Comment by ccrisan** [comment]
Which pictures?

**Comment by shinji2009** [comment]
pictures that a taken by still Images setting.  and that are on a desktop.  as i understand it is fast changing pictures on a desktop as a camera preview, not a video feed

**Comment by ccrisan** [comment]
If this is a Raspberry PI CSI camera, it may have to do with video vs stills mode. And then it's not a motionEye-related issue.

**Comment by shinji2009** [comment]
well if raspberry PI CSI camera can output two streams at the same time - still image and video. i was thinking that camera produce only series of still images, and motioneye make a jpegs and/or video of them using gpu.
it is still pity that desktop feed does not show as video is recorded in the darkness. on the desktop there is something but in actual video file there is nothing.
sorry

**Comment by shinji2009** [comment]
try this with old 320*240 usb camera, i think it can't do two streams at a time - same thing. looks like still images and desktop are +0.2 gamma.

**Comment by shinji2009** [comment]
@ccrisan can you please consider once more #797 ?
is there a problem for motionos to convert pixels into percents by itself? it's os О_о

**Comment by ccrisan** [comment]
@shinji2009 motionEye does not handle the overlay, nor those settings. motionEye exposes the threshold setting as a percent (it's easier for most users than having to deal with a big number) but internally it transforms it to the threshold number required by motion.

**Comment by shinji2009** [comment]
this issue is not about percents, are you close it by mistake?

**Comment by ccrisan** [comment]
I closed it because I have no idea what to do about it.

**Comment by shinji2009** [comment]
@ccrisan is there any chance that  somewhere used a key -optimize_dark_images for the jpeg library or -gamma-minus-0.2 for video encoder?
