### ISSUE TITLE
cannot add a camera

### ISSUE THREAD

**Issue by karma007** [ccrisan/motioneyeos#8]
hello, my rpi cam was not connected properly when i installed motioneyeos.
now i cannot add or remove a camera.
here are the logs : https://dl.dropboxusercontent.com/u/18722948/motioneye.log
![motioneyeos](https://cloud.githubusercontent.com/assets/11249071/10637155/4465a1d8-7804-11e5-80db-a35d3a7eced2.png)
thanks

**Comment by ccrisan** [comment]
I suggest rewritting the OS image from scratch, as things appear to have gone wrong at first boot.

**Comment by karma007** [comment]
arf ok. Can i do a clean install without network and configure Wifi later ?
thanks

**Comment by karma007** [comment]
problem solved rewritting image. thanks

**Comment by ccrisan** [comment]
Alright, I'm glad you solved it.
