### ISSUE TITLE
Cannot Download motioneyeos-raspberrypi3-20170212.img.gz page not found...

### ISSUE THREAD

**Issue by Osirus126** [ccrisan/motioneyeos#801]
Trying to download motioneyeos-raspberrypi3-20170212.img.gz but i keep getting timed out or page not found.. if you could help me that would be great!

**Comment by mcjohnffs** [comment]
Same problem here. Even the earlier releases wont download

**Comment by fersingb** [comment]
Looks like there are currently some issues with amazon S3

**Comment by ccrisan** [comment]
Yeap, they seem to have some serious problems. I'll close this issue now as it's not ours.
