### ISSUE TITLE
how to use usb wifi dongle on a rpi3?

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#803]
hi
how to use usb wifi dongle on a rpi3 with motioneyeos? onboard wifi is weak, i'd like to use usb wifi dongle with big antenna, but i can't find any info how. please help

**Comment by ccrisan** [comment]
You could blacklist the on-board module, which is called `brcmfmac` IIRC. See [modprobe.conf](https://github.com/ccrisan/motioneyeos/wiki/modprobe.conf) for more details.
