### ISSUE TITLE
using physical motion sensor to control power

### ISSUE THREAD

**Issue by molly78** [ccrisan/motioneyeos#808]
I read that the motioneyeos boot partition is read-only

How bad would it be if the power supply to my pi zero was running off a physical motion sensing switched outlet?

**Comment by ccrisan** [comment]
Having two of the three partitions read-only significantly reduces the chances of filesystem corruption upon power loss. However I definitely do not recommend cutting the power automatically on a regular basis, which is what I believe your use case would consist of.

**Comment by molly78** [comment]
Right, and i would be saving to a network share, so that should help alleviate any chance of corruption
