### ISSUE TITLE
MotionEyeOS compatibility with PaspberryPi Zero - W

### ISSUE THREAD

**Issue by jspee** [ccrisan/motioneyeos#809]
Hi.
First off, great software project, kudos. I've used MotionEyeOS on a pi zero and think it's fantastic. 
The question:
Should motionpiOS work on a Pi Zero - W. I can't get the pi camera to work. In fact, it's as if it's just not connected. On the add camera dialogue, I get:
Camera Type: Local Camera
Camera: (no camera)

Have you had chance to test on this hardware, do I just need to keep an eye out for a future update?

Thanks for all your efforts,

John

**Comment by ccrisan** [comment]
Duplicate of #804. Fixed in https://github.com/ccrisan/motioneyeos/releases/tag/20170326.
