### ISSUE TITLE
Odroid2  will not boot

### ISSUE THREAD

**Issue by superpat999** [ccrisan/motioneyeos#810]
Hi,
As others have found Odroid C2 will not boot.
However  Odroid C2 download is labelled:- motioneyeos-odroidc1-20170212.img
(Same as Odroid C1 download)    
Do the Odroid downloads actually test to see which cpu  is being installed on or is this an error?

Cheers  P

**Comment by superpat999** [comment]
HI, 
Just found correct download  :-motioneyeos-odroidc2-20170212.img.gz   Works fine

Problem is link in Wiki under "Supported Devices"  Odroid C2  20170212  is pointing to Odroid C1 download !!

cheers

Patrick

**Comment by ccrisan** [comment]
Oups. Fixed. Thanks for reporting.
