### ISSUE TITLE
Web UI can't be opened from 3G

### ISSUE THREAD

**Issue by toothGandalf** [ccrisan/motioneyeos#814]
I have this issue for almost year, with different motioneyeos versions. Each time when i'm trying to connect to web interface from 3G internet i'm getting this message "An error occured. Refreshing is recommended". If my phone is connected to any kind of WiFi network everything works fine. After successful login i can use web ui on any network while browser tab not closed. I've tried clearing cache, opening in incognito mode even in different browsers, results are the same.

**Comment by ccrisan** [comment]
First off, motionEyeOS does not support 3G modems. There's some kind of preliminary work in this direction, but has never been tested.

Secondly, I'd like to see your motioneye.log file after such an error occurs.

**Comment by toothGandalf** [comment]
Hi, thanks for your reply and sorry for my English. I was trying to say that this issue occurs when my phone is on 3G network and is trying to access web ui from my phone. When phone is connected to wifi everything works fine.
This is what i see when i'm trying to connect trough 3G
![screenshot_2017-03-07-12-31-41-737_com android chrome](https://cloud.githubusercontent.com/assets/24443896/23652592/30f89f6e-0332-11e7-9b3f-4ec0e339c3f2.png)

This is my recent events in motioneye.log (46.211.155.205 and 46.211.155.199 is my mobile phone on 3G):

**Comment by ccrisan** [comment]
When your phone is connected to the mobile network, it can't also be connected to your wifi network. If you want your motionEyeOS to be accessible from the internet, in general, you'll need to set up port forwarding on your router. But that's beyond the scope of motionEyeOS.

**Comment by toothGandalf** [comment]
I've set my router port forwarding and i can connect to motioneye from any other place trough mobile browser but **only** when internet connection type is wifi

**Comment by ccrisan** [comment]
I'm sorry but your log file does not show any error that could be related to what you get on your mobile phone screen. I have no idea what could cause that problem.

**Comment by toothGandalf** [comment]
Okay, i've managed to figure out what is happening.
If it matters.
It's caused by custom 403 error responce from my cellular network provider.
Instead of getting plane json with error message, motioneye web ui is getting this page.
Because my provider decided that internet needs custom error pages :(
![85dc2a10c87e4e0893d8e6f3754d96f9](https://cloud.githubusercontent.com/assets/24443896/23657742/5910bbec-0348-11e7-92a4-925d90d7c2f3.png)

**Comment by ccrisan** [comment]
Thanks for keeping us posted. I'm really sorry about your provider but there's nothing I can do about it.
