### ISSUE TITLE
feature request: BMP180 support / enabling I2C interface

### ISSUE THREAD

**Issue by prutsky** [ccrisan/motioneyeos#815]
I would like to be able to add a BMP180 sensor to my webcam setup, so I can add the temperature/barometric pressure to the webcam feed/pictures.
Is there any change this is gonna happen?

**Comment by jtx99** [comment]
I agree.

**Comment by bortek** [comment]
Not at the moment.

**Comment by prutsky** [comment]
I installed the stand alone version of motion eye instead of the OS. Worked for me...
