### ISSUE TITLE
No motion

### ISSUE THREAD

**Issue by italianjoe69** [ccrisan/motioneyeos#816]
I am having an issue on 2 systems. Both are Raspberry Pi3 running motionEyeos with Logitech cameras. The motion was working fine when I first built the systems. I then went to edit the motion mask and now the frame change sits at 0 and nothing is triggered. I tried disabling the mask and put all settings to allow anything to be picked up as motion and no luck. Rebooted the systems many times and no luck.

motionEye Version	20170212
Motion Version	4.0.1+git37b3595

TIA

[Uploading motion.conf.txt…]()
[Uploading thread-1.conf.txt…]()

**Comment by italianjoe69** [comment]
The upload of log files seems to be hung on my initial post.

[thread-1.conf.txt](https://github.com/ccrisan/motioneyeos/files/825022/thread-1.conf.txt)
[motion.conf.txt](https://github.com/ccrisan/motioneyeos/files/825021/motion.conf.txt)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
