### ISSUE TITLE
Reboot on Download

### ISSUE THREAD

**Issue by shawnm5** [ccrisan/motioneyeos#817]
When i try and download videos that have been recorded from the camera.
When it doesn't reboot it does not do anything when i click download, or it will start the download but will do about 3MB and finish but its corrupted

**Comment by ccrisan** [comment]
How large are the movies? If they are too large, things may go south.

**Comment by shawnm5** [comment]
between 40Mb and 350Mb

**Comment by ccrisan** [comment]
Try reducing the size of your movie files, especially if you run on a Raspberry PI/.

**Comment by shawnm5** [comment]
its the reboot on no WiFi cause channel 9 is not working, and the length was 15 min which was way too long
