### ISSUE TITLE
Pi Zero Fast Network Camera performance?

### ISSUE THREAD

**Issue by MrGlasspoole** [ccrisan/motioneyeos#818]
Whats the maximum MP a Pi Zero can handle as Fast Network Camera?
Does 5 MP (2592 x 1944) or 8 MP (3280 x 2464) work?

**Comment by lexcyn** [comment]
I'm having problems with the PiZero W as a Fast Network Camera. It will work for a bit then freeze the camera output, then it will tell me cannot connect to camera. CPU usage is low (around ~7%) so I don't know what's going on. Changed the power supply too... so not sure if it's the SD card causing it.

**Comment by bortek** [comment]
you will have to test it yourself and find the figures you are looking for.

**Comment by StuartOswald** [comment]
@lexcyn having the same issue. Did you find a resolution?
