### ISSUE TITLE
Raspberry 2 is stuck onboot

### ISSUE THREAD

**Issue by visiongeist** [ccrisan/motioneyeos#819]
Hi,

I just installed the latest ("motioneyeos-raspberrypi2-20170212.img") on my raspberry but i cannot get it to boot beyond the rainbow screen (red led on). Since I do not have any logs, I was wonderin is there is any recommendation how to fix this. I already tried 2 different SDs in case of a card faulty.

Regards,
Damien

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#system-wont-boot.

**Comment by visiongeist** [comment]
@ccrisan i verified it again. Noobs is working with the same SD card. :-/ I tried several tools to setup the SD card, but no success so far

**Comment by ccrisan** [comment]
What is your exact board model, as written on the PCB?

**Comment by visiongeist** [comment]
rasp pi model b+ v1.2

**Comment by ccrisan** [comment]
I believe that speaks for itself :)

**Comment by visiongeist** [comment]
ah damn it :( ok sorry for the noise. i ll get new one

**Comment by visiongeist** [comment]
now it works... stupid me ;)
