### ISSUE TITLE
Slow refresh rate

### ISSUE THREAD

**Issue by Lordsauron** [ccrisan/motioneyeos#82]
Hi, love the project.

I am using this with the original Raspberry Pi B+ and a Raspberry Pi NoIR Version 1.3 Camera.
I have it running at a resolution of 1280x720 at 30fps, with Wifi. 

But the delay is horrible, every thing is like 4 second's behind. Is there any way that i am missing where i can speed this up?

**Comment by ccrisan** [comment]
Not really. The RPI1 is quite slow for such a resolution and framerate.

**Comment by Lordsauron** [comment]
Expecting that i have lowerd the resolution to 640x480, exact same behaviour

**Comment by ccrisan** [comment]
Even with 320x240 the actual refresh rate never went above 10 fps for me on a RPi1, so I wouldn't know how to improve this.
