### ISSUE TITLE
None of the normal Unix commands works while in putty connection

### ISSUE THREAD

**Issue by jtx99** [ccrisan/motioneyeos#820]
I'm not sure whats going on with this thing.

apt-get returns to a command not found

pico returns to a command not found

....am I doing something wrong here?  I am using a ROOT username login /password

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives

**Comment by jtx99** [comment]
Gotcha. Since theres no basic  FTP upload for images I'm going to need to install SSHFS.
