### ISSUE TITLE
Gdrive sync - same files uploaded multiple per second

### ISSUE THREAD

**Issue by wdawson001** [ccrisan/motioneyeos#822]
When frame rate is set to over 1 per second and google drive is active, the same image for that second is uploaded multiple times. 

So when I have it set to 10 frames per second, it will upload the exact same file 10 times. 

On the raspberry pi (in the folders), it only shows one frame per second. 

I know you have to add the %q to get the frames per second, but it seems inefficient not to have this auto added when the frame rate is over 1ps. Or even add %q in the default settings.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
