### ISSUE TITLE
Stream crashes when motion detected

### ISSUE THREAD

**Issue by mark0581** [ccrisan/motioneyeos#825]
Hey, 
at first thanks to the work you have spent to build that software!!

I wanted to get rid of the FPS problem when using the RPIs diretly as motion detected cams.

So I bought an Odroid XU3 which is working as MotioneyeOS-Hub now.
The cam itself is a Raspberry PI Zero V1.3 with original Raspi NoIR Cam module. 

It worked great for approx one day, then it started to stop the video stream as soon as motion is detected.

As I have adjusted the Minimum motion frames to 5 my inbox was full of messages without attachements.
Next try: Minimum motion frames to 20 helped a lot to define the problem. No notification messages anymore. I walked some seconds in front of the cam till the preview windoe in Motioneyeos got this red frame. As soon as that frame appeared, the stream broke again.

If I disable motion detection, I can view the live stream without any problems.

Does somebody have an idea what is wrong?

Many thanks in advance 

Mark
[boot.pdf](https://github.com/ccrisan/motioneyeos/files/839553/boot.pdf)
[dmesg.pdf](https://github.com/ccrisan/motioneyeos/files/839554/dmesg.pdf)
[messages.pdf](https://github.com/ccrisan/motioneyeos/files/839555/messages.pdf)
[motion.pdf](https://github.com/ccrisan/motioneyeos/files/839557/motion.pdf)
[motioneye.pdf](https://github.com/ccrisan/motioneyeos/files/839558/motioneye.pdf)

**Comment by ccrisan** [comment]
I must admit it's the first time I have to deal with PDF logs. They are readable, nevertheless :)

Anyways, I'm seeing the following line in your messages.log (along other similar messages):

    motion: [1:ml1] [ERR] [ALL] motion_loop: Video device fatal error - Closing video
device

I recommend that you report this issue to the [Motion Project](https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue).
