### ISSUE TITLE
Which IMG for Raspberry Pi Zero?

### ISSUE THREAD

**Issue by senadaruc** [ccrisan/motioneyeos#826]
Hi,

I tried the "motioneyeos-raspberrypi2-20170212.img" and "motioneyeos-raspberrypi3-20170212.img" on mu Pi Zero but the device is not booting?

Is there any workaround?

Thanks,

**Comment by ccrisan** [comment]
How about "motioneyeos-raspberrypi-20170212.img" which is the correct one, as listed [here](https://github.com/ccrisan/motioneyeos/wiki/Supported-Devices#raspberry-pi-a-b-a-b-compute-module-and-zero-models).

**Comment by senadaruc** [comment]
Ok thanks i will try now. 

Cheers.

**Comment by senadaruc** [comment]
The Pi Zero reboots after the Configure Wired Network message?
