### ISSUE TITLE
RPI3 Version B, -If possible, NVR with existing Wireless Foscam Cameras, Which is best and Secure, Motionpie or MotionEyeOS or other? 

### ISSUE THREAD

**Issue by celtiraspi** [ccrisan/motioneyeos#828]
Hi Calin,

- I desire for my **RPI3 Version B**, (If possible), to be a Dedicated NVR/DVR
-  (to record motion to USB or HDD) 
- with my existing 4 Wireless Foscam Cameras, (Fi9804w and Fi8918w) 
- and if it is possible, I was wondering Which is best and Secure, Motionpie or MotionEyeOS or some other?

Thank you in advance for any help you can share with my goals.

**Comment by ccrisan** [comment]
motionPie has been discontinued. motionEyeOS is the way to go.
