### ISSUE TITLE
What is the number in the Upper right corner ?

### ISSUE THREAD

**Issue by morbak** [ccrisan/motioneyeos#83]
What is the fluctuating number in the Upper Right corner of a camera streming?

**Comment by Chiny91** [comment]
I'll guess that somehow you have switched on the motion.conf *text_change* parameter, so you get displayed the number of pixels changed.   It might be useful during setup, otherwise perhaps tedious - your preference.

**Comment by morbak** [comment]
Oh, yes, indeed, i've checked ON :Show Frame Changes on motionEyeOs.
Thx,

**Comment by stryngs** [comment]
Does anyone know where this is listed in the code?  I'd like to take that integer and do things with it.
