### ISSUE TITLE
Add instructions to the wiki for turning off the ACT LED on RPi Zero

### ISSUE THREAD

**Issue by per1234** [ccrisan/motioneyeos#832]
Unlike the other RPi boards, the Raspberry Pi Zero's ACT LED is active low so following the instructions at https://github.com/ccrisan/motioneyeos/wiki/Turn-Off-LEDs causes the ACT LED on the RPi Zero to be permanently on. I suggest adding the following text to that page:

For Raspberry Pi Zero:
```
# Disable the ACT LED.
dtparam=act_led_trigger=none
dtparam=act_led_activelow=on
```

While I'm on the subject of that page I'd also like to suggest that if #184 is going to be mentioned there should be a link to that issue, which can be accomplished with the following markdown:
```markdown
As mentioned in [Issue #184](https://github.com/ccrisan/motioneyeos/issues/184).
```
renders as:
As mentioned in [Issue #184](https://github.com/ccrisan/motioneyeos/issues/184).

**Comment by bortek** [comment]
thanks for suggestion.  Wiki page updated.

**Comment by Jachimo** [comment]
Perhaps worth noting that I don't think the suggestions in the Wiki work on ThingOS currently?  I don't think it has a `/boot/config.txt` that is easily editable.  The same thing can be accomplished (if you don't mind the lights flashing momentarily on boot) by putting a couple of lines into `/data/etc/userinit.sh` instead. Perhaps not as thorough a solution...

**Comment by jasaw** [comment]
@Jachimo `boot` partition is mounted read-only by default. To remount it as read-write, run this command `mount -o remount,rw,noatime,sync /boot` and you should be able to edit `/boot/config.txt`.

**Comment by 5rzmz8odb** [comment]
for pi zero 2 w run: `echo 0 | tee /sys/class/leds/led0/brightness`
