### ISSUE TITLE
Installation page: please add a note on how to reference the SD card on Linux

### ISSUE THREAD

**Issue by akkana** [ccrisan/motioneyeos#833]
The installation instructions, https://github.com/ccrisan/motioneyeos/wiki/Installation were confusing on Linux, which uses /dev/sda, sdb, sdc etc. rather than something like /dev/mmcblk0. If the SD card is at sdb, the instructions give no hint of whether I should pass /dev/sdb1 or /dev/sdb to the installer. It turns out it's /dev/sdb; if I pass sdb1, it eventually fails but it takes a long time and the error message probably wouldn't be clear to someone not already aware of the sdb vs. sdb1 problem. Please either give /dev/sdb as an example, or add a sentence making it clear that the argument is the block device, not a partition on the block device, for people on platforms like Linux that don't use the /dev/mmcblk0 terminology.

**Comment by ccrisan** [comment]
This is not a motionEyeOS-specific thing. This is a common Linux thing and I'm not willing to do such an in-depth documentation in a few wiki pages. Sorry.
