### ISSUE TITLE
Can't change the timezone

### ISSUE THREAD

**Issue by kanere23** [ccrisan/motioneyeos#835]
i have the motioneyeos recently installed and i can't change the timezone

my timezone if you are wondering is gmt+1.00
![knipsel](https://cloud.githubusercontent.com/assets/25063515/24075601/0023f410-0c1f-11e7-9526-42f807f33b47.PNG)

can someone help me with this problem.

**Comment by wdawson001** [comment]
Change advanced settings to "on" - should find it then

**Comment by Lama81** [comment]
There is a bug in the 20170326 release with timezone. When you change it in GUI, it stay at UTC after reboot.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/commit/f57d036853660e38046882fe0ddddaec61244cc6 fixes the wrong date/timezone issue, although we might be talking about different issues.

**Comment by surak** [comment]
Where is the timezone supposed to appear? It's nowhere to be seen at the advanced settings. And it keeps saying that the most current release is from february...
