### ISSUE TITLE
Dropbox upload: "Accessing the upload service failed: Conflict!"

### ISSUE THREAD

**Issue by mwcz** [ccrisan/motioneyeos#837]
With the 20170212 build, I'm attempting to set up Dropbox upload.  Obtain key works fine, but Test Service causes:

    Accessing the upload service failed: Conflict!

![screenshot from 2017-03-19 20-00-54](https://cloud.githubusercontent.com/assets/364615/24086081/d06b9f32-0cde-11e7-82ec-9ae27ded74a5.png)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
