### ISSUE TITLE
Camera Image before desktop login 

### ISSUE THREAD

**Issue by Wanamingo77** [ccrisan/motioneyeos#838]
Hi everyone! First Congrats Calin for this very intuitive and cool system. 

I would like to know if this is a bug:
When you log in form a smartphone, first you see the log in screen, and after introducing the proper credentials, you can see the cameras.
But if you try the same procedure on a desktop, after entering the IP on the browser, the first that you will see is the camera stream, allowing everyone that knows the public IP, to see what's happening without login in first.
Is any tweak that I'm missing? 

Thanks again and excuse my English!

**Comment by ccrisan** [comment]
Just set a password for the normal (surveillance) user and never check the "remember me" option. You'll then always be prompted for password.
