### ISSUE TITLE
Feature Request : NFS Mounts

### ISSUE THREAD

**Issue by EdGetMeLink** [ccrisan/motioneyeos#84]
add feature to mount NFS drive

**Comment by MrJeromeV** [comment]
Would be very useful to me as I have no Windows computer in my network.

**Comment by wolfspyre** [comment]
+1 for this!

**Comment by pi-pi-pi** [comment]
I too would love to mount a local NFS share on my LAN. Is there a way this can be done by editing the fstab? I tried that but found the file system to be read only.

Thanks!

**Comment by tuxedo0801** [comment]
+1

**Comment by Chiny91** [comment]
Years ago, could be 10 years or more, when I last looked at NFS, it was considered horribly insecure and best avoided, although by now presumably there is suitable authentication and perhaps even encryption.   How about the already included ssh; either sftp with a nice GUI client, or rsync. 

-1 😄 

@pi-pi-pi  Have you tried making the file system writable ?   Info is in the motionEyeOE wiki, under tweaks.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
