### ISSUE TITLE
Request: Motion interval option

### ISSUE THREAD

**Issue by m4rky-m4rk** [ccrisan/motioneyeos#840]
Hi,
To improve performance and reduce the amount of emails and data could an alarm interval option be added for each motion action please.  This would be x number of seconds after email sending, image saving, FTP upload (if it gets added :-) ) before the any more motion actions are performed. eg 0 sec would be continuous actions during the motion event. 

This would limit the number of emails sent to just the initial motion trigger for an event. For Gmail I will get blocked when its hits 500 per day. It would also reduce the amount of images generated and save space. 

Thanks Mark,

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
