### ISSUE TITLE
Request: Periodic/interval actions AND motion actions

### ISSUE THREAD

**Issue by m4rky-m4rk** [ccrisan/motioneyeos#841]
Hi,
I would like to send emails and save images periodically. AND I would also like to save extra images and send emails if a motion event does occur. At the moment I have to choose one or the other and there is no choice for both. I would be great if I could do both :-)

Saving images and sending emails periodically is a useful check that everything is working OK and ready to work should any motion occur, Then if motion does occur I want to have motion alerts and images.

LG Mark.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
