### ISSUE TITLE
Connection refused SSH

### ISSUE THREAD

**Issue by breadfan13** [ccrisan/motioneyeos#845]
Hello,

Pi Zero here, cameras are working but I'm not able to SSH into them. I have errors at boot up no SSH keys. I am getting a connection refused on port 22 error

SSH It IS enabled in the UI 

I have disabled and re enabled it 

Error at boot reads "could not load host key: /data/etc/ssh_host..... then goes on to list all the hosts
rsa, dosa, ends, ed25519

"disabling protocol 2 could not load host key"

**Comment by wdawson001** [comment]
SSH doesn't seem to be working on the latest build. It's a known issue.

**Comment by nolan-m** [comment]
Any fixes for this?  How can I get files off my SD card?

**Comment by bortek** [comment]
Have you tried with the latest image ? Please test and report back.

**Comment by thibmaek** [comment]
Just tested and SSH works on the latest image on Pi B+

**Comment by jasaw** [comment]
There hasn't been any SSH problem in recent releases. Closing issue for now.
