### ISSUE TITLE
Half boot when usb camera attached

### ISSUE THREAD

**Issue by pilif-pilif** [ccrisan/motioneyeos#846]
HI, I have the following usb camera
uvcvideo: Found UVC 1.00 device A4 TECH HD PC Camera (0ac8:3500)
when attached motioneyeos - 20170212 on RPI 3 boots normal till eudev. Then eudev consumes more time to finish with 'done' (but does) and after that there is directly the login prompt. No 'setting root password', 'starting wpa..' etc. just directly  login prompt.
How can I debug this ? 

[dmesg_log_no_cam.txt](https://github.com/ccrisan/motioneyeos/files/864289/dmesg_log_no_cam.txt)
[dmesg_log_with_cam.txt](https://github.com/ccrisan/motioneyeos/files/864288/dmesg_log_with_cam.txt) 

Thanks. 
F.
p.s. if  the camera is connected after booting everything is working normally.

**Comment by pilif-pilif** [comment]
in S12udev in the start function putting (one more)
`test $? == 0 && msg_done || msg_fail`
after udevadm settle --timeout=30 fixes the boot. althou the message is 'failed'

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
