### ISSUE TITLE
Can connect to web page in IE but not Chrome

### ISSUE THREAD

**Issue by TechGiga** [ccrisan/motioneyeos#85]
So I put a fresh install of motioneyeos on the sd card on my RPi 2 yesterday, and it was working fine on Chrome. But today I cannot connect to it with Chrome but I can with Internet Explorer. What is up here?

If it won't work on Chrome, then I cannot view the live stream from a mobile device while I'm gone (we have Androids.)

**Comment by ccrisan** [comment]
Some screenshots and more details on "won't work" would help :)

**Comment by TechGiga** [comment]
Ah, well now that you reply, it works again in Chrome now... It's weird how sometimes it works and sometimes it doesn't. Won't work means it times out.

**Comment by ccrisan** [comment]
That's clearly not motionEye related as it makes no difference between browsers. I'll close the issue  now and should you have more details regarding this, feel free to get back to us.
