### ISSUE TITLE
Request : Shutter speed or iso setting (blurry picture in still images)

### ISSUE THREAD

**Issue by Lama81** [ccrisan/motioneyeos#852]
I just discovered motioneye and it's really a complete solution for video or picture surveillance.

For the moment, I run it on still imagesmode and it's working very welI. My problem is the blur when there is a mouvement on the picture. I would like to adjust shutter speed or ISO to avoid blurry picture. Is there any way to set it manually since it's not available on the webpage setting.

This option, if it's available or possible to set, will solve the only issue I have with motioneye.

Thanks you very much!

**Comment by silversword411** [comment]
Once you've checked the manual focus (that's what that round white piece of plastic was for) motion blur is tricky:
https://www.researchgate.net/post/What_are_ways_to_cleanup_motion_blur_in_an_image_stream

Not sure if this is/can be implemented with motioneyeos, but there is a sports mode: 
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=81718
