### ISSUE TITLE
How can "Show Frame Changes" help me adjusting motion detection settings?

### ISSUE THREAD

**Issue by tommy-rk** [ccrisan/motioneyeos#860]
I see a number in the top right corner, but I am having trouble to understand it.
I'm having trouble finding the docu that explains this setting.

**Comment by thomaskuczek** [comment]
I guess I found a guide:
http://www.lavrsen.dk/foswiki/bin/view/Motion/MotionGuideBasicFeatures

**Comment by ccrisan** [comment]
Yeap, that's the one. See also [this one](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html). The number is basically the amount of pixels changed.
