### ISSUE TITLE
Missing raspi-config?

### ISSUE THREAD

**Issue by mtwhitley** [ccrisan/motioneyeos#862]
Hi there,

Using a Pi ZeroW. Fresh install using the load from Mar 29. I am having difficulty turning on the Raspberry Pi Camera v2 (known to be working with Jessie) and found the [troubleshooting article](https://github.com/ccrisan/motioneye/wiki/Troubleshooting#raspberry-pi-camera-module-not-detected) on the wiki suggesting several steps. 

I was working my way through the list and became stumped on enabling the camera via raspi-config. When SSH-ing to the box with the admin/root user raspi-config is not found. 

I then tried adding start_x=1 to the config.txt under /boot. After adding this line the box refused to boot. Removing it boots the box normally. 

Any thoughts on why raspi-config would not be found on the system or how I can enable the camera?

Thanks,
Michael

**Comment by ccrisan** [comment]
The troubleshooting guide you mentioned is for motionEye. You appear to be running motionEyeOS. All those settings are already applied/active in motionEyeOS. motionEyeOS is not Raspbian and therefore you won't find many commands that you would normally find in Raspbian.
