### ISSUE TITLE
Auto brightness flashing

### ISSUE THREAD

**Issue by aptonline** [ccrisan/motioneyeos#864]
Not sure if this is a motioneyes or camera issue but when I enable auto brightness the image flashes from bright to dim continually.  I'm using the raspberry pi camera v 2 in the pi zero case.

**Comment by thomaskuczek** [comment]
I think that auto brightness as a setting is only for cameras which don't have auto brightness build in. Raspberry cam has auto brightness (in hardware), so there is no need to use it in software.

**Comment by ccrisan** [comment]
@tommy-rk is right. Don't use the autobrightness with a camera that already has a built-in autobrightness feature, as it will create some unwanted effects.
