### ISSUE TITLE
Raspberry Pi 1, 2 or 3?

### ISSUE THREAD

**Issue by tommy-rk** [ccrisan/motioneyeos#865]
Which Raspberry Pi is the best when using the Raspberry Cam? Are there difference in frame rate?

**Comment by SuneBielefeldt** [comment]
# **Best Raspberry Pi version to MotionEye**
As you can see on the picture below, there is a big difference in frame rate depending on the model you use. See frame rate by the red dots.

The camera I use, run in 1600 x 1200, except Cam6 which is a Logitech USB camera which can only handle 1024 x 786 pixels.

I use both Raspberry Pi 1.2 and 3, and version 3 provides at least twice the version first

I have no experience with P Zero W yet.

Version 3 is the best choice.

![motioneye](https://cloud.githubusercontent.com/assets/9556987/24579429/dea709bc-16f5-11e7-9bb2-e795b534f284.PNG)

**Comment by cephasiii** [comment]
What case do you use? Are your cameras located inside or outside?

**Comment by jezmck** [comment]
I have an original Pi (B 1.2), a Zero and a ZeroW, none are stable/reliable at more than 1024x768.

**Comment by jezmck** [comment]
@SuneBielefeldt What are the red dots on your camera feeds?

**Comment by SuneBielefeldt** [comment]
Best Raspberry Pi version to MotionEye

As you can see on the picture below, there is a big difference in frame rate depending on the model you use. **See frame rate by the red dots.**

**Comment by SuneBielefeldt** [comment]
All Cameras are placed inside

**Comment by SuneBielefeldt** [comment]
The last two Camera's are placed Remote (25 km away) by a frend

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
