### ISSUE TITLE
Unable to Record a Video

### ISSUE THREAD

**Issue by burnzbarbosa** [ccrisan/motioneyeos#868]
Hi,

I have setup the motioneye on my Raspberry Pi3 with motion Version 3.2.12 and a webcam Logitech C910.

When a video start recording in motion i am getting these error:
-------------------------------snip---------------------------------
[1] [ERR] [ENC] get_oformat: ffmpeg_video_codec option value mp4 is not supported
[1] [ERR] [EVT] event_ffmpeg_newfile: ffopen_open error creating (new) file [/var/lib/motioneye/Camera1/2017-04-03/08-22-09]:
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [ERR] [ENC] get_oformat: ffmpeg_video_codec option value mp4 is not supported
[1] [ERR] [EVT] event_ffmpeg_newfile: ffopen_open error creating (new) file [/var/lib/motioneye/Camera1/2017-04-03/08-22-23]:
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
-------------------------------snip---------------------------------
And the webpage will suddenly go down.

Below are the files content inside my /etc/motioneye/
thread-1.conf:
-----------------------------------snip--------------------------------------
# @webcam_resolution 100
# @upload_subfolders on
# @upload_server
# @enabled on
# @network_server
# @upload_username
# @motion_detection on
# @upload_port
# @upload_location
# @preserve_movies 0
# @network_username
# @upload_movie on
# @id 1
# @upload_password
# @upload_method post
# @upload_picture on
# @working_schedule_type during
# @network_password
# @upload_service gdrive
# @name Camera1
# @preserve_pictures 0
# @storage_device custom-path
# @network_share_name
# @upload_enabled off
# @webcam_server_resize off
# @working_schedule 06:00-23:00|06:00-23:00|06:00-23:00|06:00-23:00|06:00-23:00|06:00-23:00|06:00-23:00

ffmpeg_output_movies on
height 720
stream_quality 85
threshold 2000
quality 85
noise_level 31
ffmpeg_output_debug_movies off
pre_capture 1
noise_tune on
smart_mask_speed 0
stream_maxrate 5
output_pictures off
hue 0
saturation 0
stream_localhost off
ffmpeg_variable_bitrate 8192
ffmpeg_video_codec mp4
text_changes off
movie_filename %Y-%m-%d/%H-%M-%S
auto_brightness off
stream_port 8081
rotate 0
brightness 0
lightswitch 0
framerate 2
emulate_motion off
snapshot_filename
despeckle_filter
snapshot_interval 0
stream_auth_method 0
stream_motion off
target_dir /var/lib/motioneye/Camera1
text_double on
post_capture 1
stream_authentication user:
output_debug_pictures off
on_picture_save /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" picture_save %t %f
on_movie_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" movie_end %t %f
text_left Camera1
picture_filename
locate_motion_style redbox
locate_motion_mode off
contrast 0
videodevice /dev/v4l/by-id/usb-046d_0821_B1D373D0-video-index0
max_movie_time 0
on_event_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" stop %t
text_right %Y-%m-%d\n%T
on_event_start /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" start %t
event_gap 30
minimum_motion_frames 20
mask_file
width 1280
-----------------------------------end--------------------------------------

motioneye.conf
-----------------------------------snip--------------------------------------
# the base URL path at which motionEye lives
# change this if you run motionEye behind a reverse proxy (e.g. nginx),
# and you want to make motionEye accessible at a specific base path (e.g. /cams)
#base_path /cams

# path to the configuration directory (must be writable by motionEye)
conf_path /etc/motioneye

# path to the directory where pid files go (must be writable by motionEye)
run_path /var/run

# path to the directory where log files go (must be writable by motionEye)
log_path /var/log

# default output path for media files (must be writable by motionEye)
media_path /var/lib/motioneye

# the log level (use quiet, error, warning, info or debug)
log_level info

# the IP address to listen on
# (0.0.0.0 for all interfaces, 127.0.0.1 for localhost)
listen 0.0.0.0

# the TCP port to listen on
port 8765

# path to the motion binary to use (automatically detected if commented)
#motion_binary /usr/bin/motion

# whether motion HTTP control interface listens on
# localhost or on all interfaces
motion_control_localhost true

# the TCP port that motion HTTP control interface listens on
motion_control_port 7999

# interval in seconds at which motionEye checks if motion is running
motion_check_interval 10

# whether to restart the motion daemon when an error occurs while communicating with it
motion_restart_on_errors false

# interval in seconds at which motionEye checks the SMB mounts
mount_check_interval 300

# interval in seconds at which the janitor is called
# to remove old pictures and movies
cleanup_interval 43200

# timeout in seconds to wait for response from a remote motionEye server
remote_request_timeout 10

# timeout in seconds to wait for mjpg data from the motion daemon
mjpg_client_timeout 10

# timeout in seconds after which an idle mjpg client is removed
# (set to 0 to disable)
mjpg_client_idle_timeout 10

# enable SMB shares (requires motionEye to run as root)
smb_shares false

# the directory where the SMB mount points will be created
smb_mount_root /media

# path to the wpa_supplicant.conf file
# (enable this to configure wifi settings from the UI)
#wpa_supplicant_conf /etc/wpa_supplicant.conf

# path to the localtime file
# (enable this to configure the system time zone from the UI)
#local_time_file /etc/localtime

# enables shutdown and rebooting after changing system settings
# (such as wifi settings or time zone)
enable_reboot false

# timeout in seconds to use when talking to the SMTP server
smtp_timeout 60

# timeout in seconds to wait for media files list
list_media_timeout 120

# timeout in seconds to wait for media files list, when sending emails
list_media_timeout_email 10

# timeout in seconds to wait for zip file creation
zip_timeout 500

# timeout in seconds to wait for timelapse creation
timelapse_timeout 500

# enable adding and removing cameras from UI
add_remove_cameras true
-----------------------------------end-----------------------------------------

motion.conf
----------------------------------snip----------------------------------
# @enabled on
# @show_advanced off
# @normal_password
# @admin_username admin
# @admin_password
# @normal_username user

webcontrol_html_output on
webcontrol_port 7999
setup_mode off
webcontrol_localhost on

thread thread-1.conf
----------------------------------end----------------------------------

Hope you can help me resolve my issue.

Thank you!

Best regards,
Burnz

**Comment by bortek** [comment]
you are reporting to wrong place this is for motioneyeos not motioneye.
