### ISSUE TITLE
HUD Display? (NON ISSUE)

### ISSUE THREAD

**Issue by ramsesGIT** [ccrisan/motioneyeos#869]
I see in your screenshots Timestamp and different HUD features. How could I configure that as well? Thank you so much for this, it is great and I have learnt so much in configuring this OS. Thank you Calin.

**Comment by jezmck** [comment]
That's the Text Overlay settings.

**Comment by ramsesGIT** [comment]
motionEye Version	0.35.2
Motion Version	4.0.1+git37b3595
OS Version	motionEyeOS 20170329

I am not seeing that feature nor Movement, I am using PIcam, does this have anything to do with it? Thank you again for this OS

**Comment by ccrisan** [comment]
@ramsesGIT make sure you have Advanced Options enabled and that you don't use the Fast Network Camera mode (in Expert Settings).
