### ISSUE TITLE
Feature Request: Support for RaspberryPi Zero

### ISSUE THREAD

**Issue by endomorphismus** [ccrisan/motioneyeos#87]
Hi,

Are u planning to cook a build for the raspberry pi zero? I got a USB splitter to run a Wifi dongle and a USB webcam and it works with the motioneye os for the RPi one build but it's flaky. Getting this OS working with the zero will be killer since the zero is so cheap.

Thx!

**Comment by ccrisan** [comment]
As a matter of fact I'm planning to release a new version today. What exactly is not working right with Zero? Normally the RPi1 version should be fully compatible with the Zero.

**Comment by endomorphismus** [comment]
Running 20151206, added an USB web camera then got a spinning wheel, does spin forever. So i reboot and log in i get again "An error occurred. Refreshing is recommended" and "You have not configured any camera yet. Click here to add one...". When trying to add a camera i don't see the USB webcam anymore (but the light is on on the webcam).

**Comment by ccrisan** [comment]
Please attach your log files, @endomorphismus.

**Comment by bortek** [comment]
I am using this on Pi B+ and on pi zero with pi camera and it works great. Closing issue.
