### ISSUE TITLE
Can I save images to sd card and periodically dump to network share?

### ISSUE THREAD

**Issue by Billium28** [ccrisan/motioneyeos#870]
I want to save these images to a network nas but I do not want the nas to be constantly written to. I set it up to take an image every minute. I feel this constant data will not be good long term for my harddrives. Is there something I can do like tgis. Right now I save to dropbox and that works great but I'd rather not share data with them.

**Comment by spieiga** [comment]
you could periodically rsync a local folder to nas share with a cron job

**Comment by silversword411** [comment]
Answered
