### ISSUE TITLE
Can't connect to Wifi with Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Huhnovic** [ccrisan/motioneyeos#872]
Hey!

I connected my Pi Zero W with a Lad Adapter to my network and everything was working. But if i want to connect my Pi Zero W via WLAN to my network nothing happens... Can anybody help me? I thought last update had fixed the issue...

Huhnovic

**Comment by ccrisan** [comment]
Have you checked this article https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting#wireless-connection-problems?

**Comment by Huhnovic** [comment]
Yeah... everything works fine with the Pi 3.

**Comment by Huhnovic** [comment]
Haha! I connected it to another power socket and now it works! Don't ask me why!

Thanks for your really great project!


Huhnovic
