### ISSUE TITLE
motionEye is up to date (current version: 20170212)!

### ISSUE THREAD

**Issue by AnsuRio** [ccrisan/motioneyeos#881]
Hi!

Running motionEye Version	20170212 with Motion Version	4.0.1+git37b3595 but I can't update to the latest. It just tolds me that it's up to date as the topic.

Any clue?

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-noticed-a-new-version-has-been-released-why-does-my-motioneyeos-say-its-up-to-date.

**Comment by AnsuRio** [comment]
That's real odd, because the latest release is available for my board (Raspberry Pi 2).

**Comment by ccrisan** [comment]
Did you check what was indicated in the FAQ entry?

**Comment by AnsuRio** [comment]
Yeah, and that killed my camera... Forced to re-install all cameras. :/
