### ISSUE TITLE
Problem with motioneyeos gets stuck

### ISSUE THREAD

**Issue by lbrdv** [ccrisan/motioneyeos#882]
Hee guys, I love motioneyeOS, but it gets stuck all the time. I can't reach the IP-adress after a while. I already switched off Connectivity watch (or changed the waiting time), but it doesn't help.

When I plug it out and in everything works fine, sometimes for 30 minutes sometimes for a few days.

I don't know what is really happening. Here are all log files, maybe someone can help me? ;)

Today (apr 10) I restarted MotionEyeOS at 11h and approx 15.15
https://www.dropbox.com/sh/x3ojed764fo9gwt/AAD5r25CBvIOVWEFUCCtHzwma?dl=0

**Comment by ccrisan** [comment]
You have some connectivity issues that trigger all the various problems you're facing:

    user.notice wifi: disconnected for 20 seconds, rebooting

Make sure the wifi signal is good enough and the power supply does not go below 4.75V, where the wifi adapter may have problems.
