### ISSUE TITLE
when looking non-stop at the stream for 60 min. the video crashes - how to debug?

### ISSUE THREAD

**Issue by tommy-rk** [ccrisan/motioneyeos#883]
I have a tablet connected to the video stream on port 8081 to monitor constantly, but after about 1h it crashes.
When connecting to motioneye web interface I can't see a video anymore.
Rebooting helps and everything is normal again.
I have a Raspberry Pi 3. How can I help debugging this?

**Comment by bortek** [comment]
might be power issues. Closing this issue due to interest. If still interested please post your question in the forum page.
