### ISSUE TITLE
streameye: not running, respawning

### ISSUE THREAD

**Issue by prometrik** [ccrisan/motioneyeos#886]
i installed motioneye on my raspberrypi b+ by following the directions at https://pimylifeup.com/raspberry-pi-security-camera/. when i start it up, i can access the pi through firefox on my windows 10 pc, but there is no video showing. it recognizes the camera and shows it. i have it enabled and it still is not showing video. when i plug in my pi to a monitor it says "streameye: not running, respawning" over and over and i can not put anything into the console to make it run. i am using this camera https://www.element14.com/community/community/raspberry-pi/raspberry-pi-accessories/raspberry-pi-camera-board. thanks for the help in advance

**Comment by ccrisan** [comment]
1. What version of motionEyeOS is this? Please don't say "the last one".
2. Have you enabled Fast Network Camera?
3. Are you sure the camera is correctly connected and works as it should (i.e. have you tested it under Raspbian)?

**Comment by prometrik** [comment]
sorry i meant to say the latest version. 20170329. its is on a b+ model so
i am running the version for a pi 1. i have the camera enabled it shows up
on my windows pc as there but there is no video or pictures coming through.
i then get the message i stated on the issue over and over. i did test it
under raspbian and it worked

**Comment by ccrisan** [comment]
You never answered question number 2.

**Comment by prometrik** [comment]
it is enabled

On Apr 13, 2017 9:34 AM, "Calin Crisan" <notifications@github.com> wrote:

You never answered question number 2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ccrisan/motioneyeos/issues/886#issuecomment-293896737>,
or mute the thread

**Comment by ccrisan** [comment]
So what is the problem again then? You first said "i have it enabled and it still is not showing video". Then you said "i have the camera enabled it shows up on my windows pc as there but there is no video or pictures coming through".

Can you please clearly state what your problem is? Some screenshots would help.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
