### ISSUE TITLE
Request for Comments: Using H.264 Motion Estimation Vectors

### ISSUE THREAD

**Issue by hellyberry** [ccrisan/motioneyeos#889]
Hello,

this ticket is a request for comments and possible solutions about the way to handle motion detection and recording.

When using multiple IP- and USB-Cams connected to a Raspberry 3, there's the inefficiency with motion-detection. And drop of the framerate when recording.

Using the in relation quite powerful GPU-cores for this would be great. AFAIK there are multiple examples how the high-performance H.264-codec can be used for this. Additionally one can extract the motion estimation vectors this way for free. And work on these instead till motion is really detected and recorded. This way, there's no limit on the number of connected cameras to a single system. This problem could be solved that way. The next is the recording part which would also be solved with HW-supported H.264 VideoCore codec.

http://bits.citrusbyte.com/motion-detection-with-raspberry-pi/
https://www.raspberrypi.org/blog/vectors-from-coarse-motion-estimation/
https://wiki.matthiasbock.net/index.php/Logitech_C920,_streaming_H.264

In many setups only 1(-2) cam(s) will record at a time, so this should be possible.

Is this reasoning right? Has anyone explored this path or a solution to these problems?

**Comment by ccrisan** [comment]
This is not something for motionEye(OS) to take care of. This is "low level stuff" that's dealt with by [motion](https://github.com/Motion-Project/motion). Please open this issue on their issue tracker, if you think this is something that can be implemented by it or if you could contribute with code.
