### ISSUE TITLE
Record both stills images and movies?

### ISSUE THREAD

**Issue by Jasonb11** [ccrisan/motioneyeos#890]
Is this a limitation of the OS or am I missing something?

The ultimate goal is to have the motioneyeos record both still images at an interval of 300 seconds. 

Still images setting:
![2017-04-15 07_37_50-meye-c9827a30](https://cloud.githubusercontent.com/assets/14957568/25063313/eeb34dac-21ae-11e7-8c8e-3d14c27dc910.png)

Movies setting:
![2017-04-15 07_42_47-meye-c9827a30](https://cloud.githubusercontent.com/assets/14957568/25063319/34db8f88-21af-11e7-90dd-c28d177e1144.png)

The problem is when I apply the setting for either the still images or movies to record at continuous or interval it overwrites the other setting and I can't use my desired setting. I'm thinking that I should find the file that applies to these settings and manually update the settings that way. 

Issue:
![2017-04-15 07_50_25-meye-c9827a30](https://cloud.githubusercontent.com/assets/14957568/25063362/577f58ac-21b0-11e7-8c93-d84c6fd18675.png)
![2017-04-15 07_49_21-meye-c9827a30](https://cloud.githubusercontent.com/assets/14957568/25063361/577db7f4-21b0-11e7-9390-3d353334b592.png)

Currently, my settings are set to interval still images because I can create timelapse videos from them. But i would really like to have the continuous video too..

I am using a raspberry pi 3 and a 750gb 5400rpm HDD nas drive for storage.

Any help or feedback would be most excellent, thanks!

**Comment by ccrisan** [comment]
Unfortunately what you're trying to achieve is impossible using the available motion configuration options. That's why the UI automatically adapts the options for you. Sorry about that.

**Comment by Jasonb11** [comment]
:(
