### ISSUE TITLE
Can i install Debian system , not only single board computer ? 

### ISSUE THREAD

**Issue by joehk2017** [ccrisan/motioneyeos#891]
Hi , 

I finding motioneyeos install my debian system , but can't find , can you ask me where can find ?

Thank !

**Comment by ccrisan** [comment]
This is incomprehensible.

**Comment by joehk2017** [comment]
Sorry , my english is bad  i mean is where can find not single board computer package ?

i want to install debian , archlinux and other linux distribution

thank

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneye/wiki/Installation.
