### ISSUE TITLE
Logitech Webcam Image Funny

### ISSUE THREAD

**Issue by nagybal** [ccrisan/motioneyeos#892]
It is probably a linux/driver issue. But I do not know what to google for.
- funny colors
- funny resulution with little gray dots on the picture
![motioneye webcam](https://cloud.githubusercontent.com/assets/27618042/25070295/e463aeea-229a-11e7-92b5-3c798341b132.png)
![motioneye webcam2](https://cloud.githubusercontent.com/assets/27618042/25070367/472b64ae-229c-11e7-9f6b-e2f4ded354af.png)

please help

**Comment by ccrisan** [comment]
I'll leave the issue open just in case other users know a remedy for this. Anyways, I think it's best if you clearly state your camera model.

**Comment by davebdb** [comment]
What is the output of the dmesg at boot (or the snippet of dmesg.log containing the boot info), interested in knowing what Linux is detecting the camera as.  

Also what does the output of

/usr/bin/v4l2-ctl -d0 -L

Show for you?  if this is your only camera you can exclude the -d0 option, but if you have multiple cameras you need to figure out which device it is.  Had super-overexposure issues which I resolved and Calin was able to tell me what I needed to do to make my change persistent on reboots.  So if this is the only camera you just need to run

/usr/bin/v4l2-ctl -L

and copy/paste that output.  That should give all the camera settings you have set for the camera.  (even more than what is available on the WebUI [along with their ranges and defaults])

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
