### ISSUE TITLE
Lots of errors on first boot Raspberry Pi 1

### ISSUE THREAD

**Issue by Toontje** [ccrisan/motioneyeos#893]
I get a lot of errors on first boot using a Raspberry 1B. It looks like the /data directory is mounted correctly. Mounting /dev/mmcblk0p3 on /data failed: Invalid arguments.
![20170416_122556](https://cloud.githubusercontent.com/assets/4884243/25070489/1aae2426-22a0-11e7-9e2e-8008a3d04907.jpg)

**Comment by Toontje** [comment]
Downloaded the 20170212 version as mentioned on https://github.com/ccrisan/motioneyeos/wiki/Supported-Devices and this release doesn't have the issue.

**Comment by ccrisan** [comment]
You *can* and you *should* use the latest prerelease. It's proven to be stable enough so far. Just rewrite it again and boot it. It sometimes happens with first boots to fail like that and it has to do with the data partition on the SD card.
