### ISSUE TITLE
can't open /dev/ttylogin when booting up

### ISSUE THREAD

**Issue by Carson23** [ccrisan/motioneyeos#896]
![image](https://cloud.githubusercontent.com/assets/27700849/25100248/f8b4a824-2374-11e7-955f-8f9f003ef804.jpeg)
I'm using a raspberry pi 3 B with the motioneyeos-raspberrypi3-20170212.img
on a Kingston 16gb sd card with an Ethernet connected to my network
I have no idea how to fix this

**Comment by ccrisan** [comment]
Try rewriting the OS image from scratch. Something might have gone wrong at first write.

**Comment by Carson23** [comment]
I have actually tried to rewrite it several times and the same thing popped up I may just be doing it wrong

**Comment by Carson23** [comment]
I think it is worth mentioning that sometimes I get the reboot loop error when rewriting the card

**Comment by Carson23** [comment]
![image](https://cloud.githubusercontent.com/assets/27700849/25103102/d5e73b3e-2380-11e7-84f6-cd0958a48347.jpeg)
These are the files that are on my SD card 
![image](https://cloud.githubusercontent.com/assets/27700849/25103148/0855b4ba-2381-11e7-8e36-ab265e6ae6b9.jpeg)
And does it matter which extract option I use when extracting to an img file?

**Comment by Carson23** [comment]
Nvm I got it to work thanks for helping and responding quickly

**Comment by ccrisan** [comment]
How did you fix the problem?

**Comment by roelfsre** [comment]
I have the same issue. I have a PI Zero W, use the latest image and start from scratch. I only get to the point that it will ask for a login. But root, or admin does not work. No motioneye yet, looks like still booting, but ask for password.

**Comment by Carson23** [comment]
I just tried it again and it worked

**Comment by Carson23** [comment]
Do you have the right version?

**Comment by Carson23** [comment]
Wait if it pops up login prompt you don't put in the password in the pi itself if you see an ip address type that in to your browser then when it asks for login type in admin as password
