### ISSUE TITLE
Feature Request: Overlay-Icon for direct recording/screenshot

### ISSUE THREAD

**Issue by ozett** [ccrisan/motioneyeos#90]
action-buttons are wonderful since 0.30, but icons/buttons for some direct screenshot/recording  would  be wonderful too. i am used to this from other webcam solutions. 

By the way thanks for a great piece of software ..

**Comment by ccrisan** [comment]
The two action buttons are already there as a matter of fact. They are hidden however as I haven't yet figured out some issues with their actual implementation. To be more precise, interacting with the motion daemon is not always piece of cake.

**Comment by Samfox2** [comment]
It would be great to have a user defined action button that could start a script - I would use it to turn on my door light.

**Comment by ccrisan** [comment]
@Samfox2 it's already there as of 20151230: https://github.com/ccrisan/motioneyeos/wiki/Action-Buttons.

**Comment by Samfox2** [comment]
I don't know how I missed that. Tried it and It is working, thanks!
