### ISSUE TITLE
How do you adjust the hue or white balance of cameras in the UI?

### ISSUE THREAD

**Issue by hdfyusjnbkj** [ccrisan/motioneyeos#902]
I want to change the white balance of the camera I'm using.
I've tried adding 'hue \<some number\>' to the Extra Motion Options field, but nothing changed in the image. Is there a way to do this?
I'm using a Raspberry Pi 3 w/ a NoIR Pi Camera v2.

**Comment by silversword411** [comment]
That pink hue is because it's a NoIR camera, and why you got the blue filter in the box:
https://www.raspberrypi.org/blog/whats-that-blue-thing-doing-here/

Not sure how to software color correct, but there are hardware solutions:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=137403
