### ISSUE TITLE
Help, I can't download the recorded video files.

### ISSUE THREAD

**Issue by rynerlute159** [ccrisan/motioneyeos#903]
Hi i have a problem i start record continuous video and my sdCard got full but when im trying to download now the recorded video about 7GB i cant download it will start downloading and the size is 0byte how can i retrieve the recorded video ? can i just put it on my windows PC but the partition of the sdcard cannot be seen and cannot be mount also. so no chance of getting the recorded file ? sorry for bad english

**Comment by ccrisan** [comment]
Use FTP, SFTP or Samba (network sharing) to download the file from your running motionEyeOS.
