### ISSUE TITLE
Raspberry Pi B can't find USB video grabber camera

### ISSUE THREAD

**Issue by diarem** [ccrisan/motioneyeos#904]
Hi, my application is slightly different to the local camera thread but I am hoping someone will know straight away what I am doing wrong! I am using a Raspberry Pi B with a USB video grabber connected to a bird box camera. The software loaded first time, I can access the Pi easily and configure everything - except that it can't find a local camera! I am not trying to use wireless, I am happy with an Ethernet cable but I have tried the various suggestions about adding files without success.
 Can anyone point me in the right direction please?
Using the latest March Pi B image.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
