### ISSUE TITLE
No Menus available

### ISSUE THREAD

**Issue by mediastore93** [ccrisan/motioneyeos#906]
Everything was working fine on my Pi Zero W, I changed some of the settings (increased framerate etc) then next time I open the webpage I only see the camera image (which is streaming fine) and no menu panels. The webpage doesn't fully load (which is why I suspect I can't see the menus) but I can't change the setting to make the streaming image smaller as I suspect the stream is using too much bandwith. Can I change the settings by ssh'ing into a config file?

**Comment by ccrisan** [comment]
Screenshot?

**Comment by mediastore93** [comment]
Thanks for your help with this!

[grab1.pdf](https://github.com/ccrisan/motioneyeos/files/949061/grab1.pdf)

**Comment by mediastore93** [comment]
And the page never fully loads up. I've rebooted, tried different browsers etc.

**Comment by ccrisan** [comment]
Well the pdf doesn't say too much. What is the URL that you access when you open the UI?

**Comment by mediastore93** [comment]
I can watch the stream with 198.168.0.10:8080 etc in the browser fine just cant see any menu buttons to change settings.

**Comment by ccrisan** [comment]
Don't use port 8080 - that's for streaming only. Use port 80 (i.e. no port).
