### ISSUE TITLE
Compatible with NanoPi

### ISSUE THREAD

**Issue by escoand** [ccrisan/motioneyeos#907]
Is there a release for the NanoPi family, espacially for the NanoPi NEO Air?
http://nanopi.org/NanoPi-NEO-air_Feature.html

**Comment by ccrisan** [comment]
Nope, there's no NanoPi support. For your next question, see https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-motioneyeos-be-ported-to-insert-your-board-here.

**Comment by escoand** [comment]
Ok, I understand this. Do you have a short todo list what needs to be ported?

**Comment by ccrisan** [comment]
I'm currently waiting for a PINE A64 board which looks promising and which I hope will run motionEyeOS soon.

**Comment by escoand** [comment]
Kernel is probably the most important thing.

**Comment by ccrisan** [comment]
Indeed, once the boot loader (usually U-Boot) and the kernel work together, everything becomes piece of cake.

**Comment by escoand** [comment]
Ok, i'll have a look.

Off-topic, my reason for using NanoPi was the size and the huge amount of cheap actioncam outdoor cases. Usually too small for RaspiZero. Do you know a good alternative?
