### ISSUE TITLE
Looped Video Recording 

### ISSUE THREAD

**Issue by sheppy1** [ccrisan/motioneyeos#910]
Hi 😊 

I have motioneye on my Pi 3 and have it configured to continuously save video clips to the internal storage and then also to have it upload the clips to Google Drive. 

My question is, how do I have it auto overwrite the earlier clips or even auto delete all clips when the internal spread (32GB SD card) becomes full? I have it set to only keep clips for 30 days bit at present the card will become full within half a day. 

Thanks

**Comment by sheppy1** [comment]
I meant I have it set to store clips for 1 day, not 30.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
