### ISSUE TITLE
Request: Working Schedule "all day"

### ISSUE THREAD

**Issue by pascal2944** [ccrisan/motioneyeos#913]
Hello,

First, thank you for your great work on motionEyeOS.

I have a little request, when I leave home for few days I have to put from 00:00 to 23:59, it will be very helpfull if there is a check box that make detection from 00:00:00 to 23:59:59 or at least may be you can add 23:59 in your text box choice because there is only 23:00 and it isn't easy to set 23:59 from a smartphone for example.

So can you add a check box for each days in Working Schedule to select all the day please ?

Thanks a lot.

**Comment by ccrisan** [comment]
Yes, that makes sense. I'll take this into account when making changes to the Working Schedule configuration UI.
