### ISSUE TITLE
Can't login after I set manual IP

### ISSUE THREAD

**Issue by markdeblois** [ccrisan/motioneyeos#918]
Hi, I am having an issue that I cannot login to the webUI after I have set a manual IP address on my raspberrypi. I don't see how this should affect my login. Am I missing the obvious?

**Comment by ccrisan** [comment]
How can you not log in? Do you get any errors? Have you tried clearing the browser cache?

**Comment by davebdb** [comment]
Are you able to ping the address (old or the new one), and are you logging in from the same subnet or from a different routed network (gateway error/typo).

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
