### ISSUE TITLE
Raspberry Pi offline

### ISSUE THREAD

**Issue by gigawert** [ccrisan/motioneyeos#922]
I can't access my Raspberry Pi with motioneyeOS installed from a different PC on the network. I have not accessed it in a while but I do remember looking at the page a month or so ago. How can I do it now?

**Comment by redflag237** [comment]
rebooted?

**Comment by gigawert** [comment]
Yes, still not working

**Comment by redflag237** [comment]
Why don't you plug in a keyboard and a screen. Then check network connectivity from the terminal.
`ifconfig` or `iwconfig` might bring you the needed information.

**Comment by gigawert** [comment]
Oh, by looking at the console it said that it was expecting ethernet. Easy fix, I just plugged it into ethernet, accessed the page from another computer on the network, then configured the wireless network.
