### ISSUE TITLE
No network share available

### ISSUE THREAD

**Issue by snowman82** [ccrisan/motioneyeos#923]
Hi,

I dont have option to save files in a network share. Is there any option I should enable ? 

![image](https://cloud.githubusercontent.com/assets/9664011/25569035/82ef69e8-2e06-11e7-9e7f-3f4ea80748d8.png)

Thanks,

**Comment by ccrisan** [comment]
Are you sure this is motionEyeOS and not just motionEye? What version is this?

**Comment by snowman82** [comment]
Indeed it is. Posted in the wrong forum? Can you please point me to the right one?

Thanks

**Comment by ccrisan** [comment]
Well, motionEye lives here: https://github.com/ccrisan/motioneye. However if you want network shares, you just need to enable [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) and make sure you run motionEye as root.
