### ISSUE TITLE
Motion sensing trigger (Parking IOT project) HELP

### ISSUE THREAD

**Issue by AshrafRezk** [ccrisan/motioneyeos#925]
I need to sense car motion in a parking area and take "one" picture per car.
Issues I face:
--Inability to adjust the motion trigger to capture only one photo/or one video (any ideas to properly adjust the meters for one pic only?)
--Could I crop the picture... aka: dividing the camera into two cameras for two cars; hence two folders for two parking spots?
......
I'm currently using a usb webcam; sending to a folder in the network.
Afterwards a matlab program, takes on the image processing sending the data towards an excel csv that is later accessed with a matlab GUI as well.

**Comment by bortek** [comment]
sorry cannot be done.
