### ISSUE TITLE
motioneye hub recommendation

### ISSUE THREAD

**Issue by hibdude** [ccrisan/motioneyeos#926]
I've been using a RPi 3 for a hub for my four RPi fast network cameras.  It's started to get unreliable, so is there a recommendation for a cheap and stable hub that can handle about 5 fast network cameras?

**Comment by ccrisan** [comment]
OdroidXU4 is the board with the best performance that runs motionEyeOS. Otherwise, you could try installing Linux on a powerful PC and use it as a hub.
