### ISSUE TITLE
Total memory showing as 117MB on Raspberry Pi 3

### ISSUE THREAD

**Issue by cuddylier** [ccrisan/motioneyeos#932]
Hi

I'm on the latest version, 0.35.2, and having a lot of issues with uploading to Dropbox and emails no longer working after I believe the last few updates. The web interface and SSH also became very slow at times even after a reboot.

I checked 'free -m' and 'top' and they both show I only have 117MB RAM on my Raspberry Pi 3.

 free -m
             total       used       free     shared    buffers     cached
Mem:           117         78         38          2          0          8
-/+ buffers/cache:         69         47
Swap:            0          0          0

I only have 128MB assigned to the GPU.

I did a quick Google and found people reporting the same issue with other Pis, seems to maybe be a kernel issue?

Thanks

**Comment by ccrisan** [comment]
Is this motionEyeOS or Raspbian?

**Comment by cuddylier** [comment]
Motioneyeos.

**Comment by ccrisan** [comment]
@cuddylier what version? Don't say "the latest".

**Comment by cuddylier** [comment]
Already provided in the OP but here is the 'OS version' too: motionEyeOS 20170329

**Comment by ccrisan** [comment]
@cuddylier actually this is the first time you have disclosed the OS version. The other version you gave us was that of motionEye.

I couldn't find any reference online about people having their RPi3 reporting less than ~800MB. What do  `vcgencmd get_mem gpu` and `vcgencmd get_mem gpu` say?

**Comment by cuddylier** [comment]
`vcgencmd get_mem gpu`

gpu=128M

What should the 2nd command be? You said the same command twice.

**Comment by ccrisan** [comment]
My apologies. It's the same but with *arm* instead of *gpu*.

**Comment by cuddylier** [comment]
@ccrisan 

`vcgencmd get_mem arm`
arm=128M

**Comment by ccrisan** [comment]
Damn this beats me. What does cat/proc/cpuinfo say?

**Comment by cuddylier** [comment]
@ccrisan https://pastebin.com/raw/MSq6tRct

**Comment by ccrisan** [comment]
Have you tried Raspbian? Does it report the full amount of memory?

**Comment by cuddylier** [comment]
I haven't no as I'd prefer not having to wipe the Pi (got no other micro SD cards) as I've had it installed with motioneyeos for a long time, this  only occurred in one of the few recent updates I applied, I usually check for updates every 1 - 2 weeks.

**Comment by cuddylier** [comment]
The last day everything worked properly was the 29th April so an update on or before then.
