### ISSUE TITLE
Frame rate questions?

### ISSUE THREAD

**Issue by debevecc** [ccrisan/motioneyeos#936]
What are the two numbers listed at the bottom of the video in regards to frame rate? And is there any benefit in changing the frame rate under video device. This project is so close to being what I'm looking for but it it triggering when there is no perceived motion and not triggering when I walk in front of the camera.

**Comment by ccrisan** [comment]
If you hover them with the mouse, you'll see the tooltip saying "streaming/capture frame rate". So the first one is the frame rate perceived by the browser, while the latter is the one measured by the motionEye server, which on good hardware should be close to the one configured for the video device.
