### ISSUE TITLE
No Fast Network Camera

### ISSUE THREAD

**Issue by hplus28** [ccrisan/motioneyeos#937]
HI,
I am using a raspi zero (both W and without built in wifi, same behaviour with both versions ) and a csi camera. 
I don't see the fast network camera option in the expert settings.
Expert Settings is only showing Log Files et Enable system monitoring. Is this normal?
I am using latest motioneyeos version

Thanks

**Comment by ccrisan** [comment]
Screenshot please.

**Comment by hplus28** [comment]
![image](https://cloud.githubusercontent.com/assets/6792576/25991851/14719074-3705-11e7-83f9-470846e5fb43.png)

**Comment by ccrisan** [comment]
This is weird. Can you do a clear cache and a full refresh? If the issue persists, please attach your log files.

**Comment by hplus28** [comment]
I also don't see any network configuration in the interface.
I had to first boot with a screen and keyborad plugged in and manually edit the wpa_supplicant.conf in /data/etc in order to connect

**Comment by ccrisan** [comment]
You may need to rewrite your OS from scratch as things aren't alright there with your configuration.

**Comment by hplus28** [comment]
yeah... my only problem is thas i don't have a linux to use the writeimage.sh to set the ssid, that why i did it by hand

**Comment by ccrisan** [comment]
You don't need a Linux. Use your windows method to write the image and then use your windows to put the wpa_supplicant.conf file on the boot partition (which is a fat32). Just make sure to do this before the first boot.

**Comment by hplus28** [comment]
you mean i can put the correct wpa_supplicant.conf in the visible partition under windows before the first boot? i'll try this

**Comment by ccrisan** [comment]
Sure. See https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-%28Plus%29-And-Zero.

**Comment by hplus28** [comment]
I've just tried this using the same wpa_supplicant.conf that was on the raspi zero and i've copy it on a newly flashed sd card with the latested image. It keeps on rebooting trying to configure wired network and saying no device found....
The wpa_supplicant.conf is correctly written... no mistake its a real .conf file (not a .conf.txt )

**Comment by hplus28** [comment]
ok i made it work, i've first booted on a rasp B, it connected thru the wired network, then using the web interface, i first enabled the wireless network and configured the ssid and password.
I finally got all the options...
I think that something is wrong in the image, maybe wireless is not enabled by default?
