### ISSUE TITLE
Portfowarding/public ip

### ISSUE THREAD

**Issue by bdgtv** [ccrisan/motioneyeos#938]
Hi i am having some trouble finding my public IP address so I can portfoward is there any command to find your public ip?

**Comment by rynerlute159** [comment]
http://whatismyipaddress.com/ the  ip address show there is your public ip address

**Comment by silversword411** [comment]
Not really motioneyeos related, and you have the answer to determine from a browser. I use www.ipchicken.com as well.

If you need further port forwarding help try:
https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/
or google search: port forwarding tutorial.

Closing ticket.
