### ISSUE TITLE
how to configure motion ad timesheet for a camera?

### ISSUE THREAD

**Issue by Cosby86** [ccrisan/motioneyeos#944]
Hello all,
where i can find the configuration of motion detection and time sheet for a camera?? I'm only able to configure few parameters (using Simple MJPEG Camera)

**Comment by bgood4000** [comment]
Did you enable the "Fast Network Camera" option in the "Expert Settings"? If you did then motion detection goes away.

**Comment by Cosby86** [comment]
I finally found. I had to select the "network camera" and not MPEG Simple camera. Thank you
