### ISSUE TITLE
Guys how to have night vision ??

### ISSUE THREAD

**Issue by rynerlute159** [ccrisan/motioneyeos#946]
I purchase a NoIr v2 camera it said in the description its for night  vision. i see youtube it can see in night but when i turn off my lights i see only black ??? 

i mean do i  need some led like i see in the normal cctv ??? thank you so much :)

**Comment by silversword411** [comment]
Yes, you'll need IR lights in the appropriate wavelength like:
https://www.amazon.com/gp/product/B00M3O5ERK/

There's distant/narrow, and close/wide field types. Pick the one appropriate for your use case.
