### ISSUE TITLE
Im getting cannot create remote file Winscp

### ISSUE THREAD

**Issue by rynerlute159** [ccrisan/motioneyeos#950]
Hi, Ccrisan im trying to edit some pyc in the usr/lib/python2.7/site-package/motioneye but when i going to overwrite the file it saying that i cannot create remote file i'm using winscp thanks :)

**Comment by ccrisan** [comment]
1. I don't see how you'd edit a .pyc file.
2. https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file
