### ISSUE TITLE
Black Still Photos

### ISSUE THREAD

**Issue by oneweak7words** [ccrisan/motioneyeos#952]
I've recently developed a problem with two of my motioneye cameras where random stills  from motion events are black-washed. 
It first happened on a pi zero w board with usb cam. I figured maybe its an issue with the cheapo camera.
The next day, it occurred with my pi zero (w/ethernet) board with official pi cam. As  I watch the live stream, there is no black-wash. It seems to only be the saving of the stills. Screenshot below.
![image](https://cloud.githubusercontent.com/assets/20116365/26266430/447b4c52-3cb3-11e7-9017-75d73952567a.png)

Any suggestions you can give would be much appreciated.
Thank you for all of your hard work on this great project.

Ah, this is the special debug media, isn't it? It wasn't until posting the screenshot that I registered the "m" at the end of the file name.

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
