### ISSUE TITLE
raspberry pi camera led light stays on in newest motioneyeos

### ISSUE THREAD

**Issue by LanceSaintLuke** [ccrisan/motioneyeos#956]
Hello,

Wasn't there a button to disable the camera led in the expert settings section in the previous releases?

After re-loading the SD card with this newest version I searched through all the options and did not see any option to disable the LED light as there was in the previous version.

I greatly appreciate any ideas or workarounds.

Lance

**Comment by bgood4000** [comment]
The button is there:

motionEyeOS 20170329 > Expert Settings > Enable CSI Camera Led

**Comment by LanceSaintLuke** [comment]
Thank you Jean.  I was able to find it recently and I’m not sure why I overlooked it earlier.  I appreciate the reply.  Have a great weekend.
Lance
