### ISSUE TITLE
Set up RPi Zero for g_serial connection

### ISSUE THREAD

**Issue by tido-** [ccrisan/motioneyeos#958]
Make use of the RPi's USB OTG port.
Some awesome people on github sorted out that if you used the DWC2 USB driver, and patched a few files, you could get the Pi to act like a USB device (in linux-land this is called the USB Gadget system).
You can now set up a virtual network connection between your Raspberry Pi Zero and normal PC using a single USB cable in a matter of seconds, without the need for any extra hardware!
Login: ssh root@raspberrypi.local

As you already use the Raspbian-Kernel in MEYE, is it possible to add this functionality? It will make setup much easier.

Short description: https://gist.github.com/gbaman/975e2db164b3ca2b51ae11e45e8fd40a
A bit more in detail: http://blog.gbaman.info/?p=791

**Comment by bortek** [comment]
Not right now
