### ISSUE TITLE
WLAN and Eth0?

### ISSUE THREAD

**Issue by schmeckles22** [ccrisan/motioneyeos#959]
Hello,

I am using my RPi3 to connect the web interface over Wireless, I have a network camera setup to IP 10.0.0.40. I want to be able to connect the IP cameras Ethernet cable straight into the the RPi so there is no latency as at the minute I am using Power line adapters for the camera and it's not great.

**Comment by bortek** [comment]
sorry not possible

**Comment by forum999** [comment]
bit crap really if you want to create a stand alone unit, especially since when used on a pi the latency is terrible even at low resolution
