### ISSUE TITLE
How to make boot/startup as fast as possible?

### ISSUE THREAD

**Issue by worldburger** [ccrisan/motioneyeos#961]
My application is battery-oriented and has a Particle Photon in a sleep mode with a PIR sensor interrupt which turns on my RaspBerry Pi Zero W.

My problem is I cannot get the boot time below approx 35 seconds for motioneyeos on the Pi...which for capturing motion may or may not work.

What is the fastest attainable boot time?
If possible to speed this up, what are the best ways to accomplish this?

**Comment by ccrisan** [comment]
From my experience, 25 to 50% of the boot time is eaten up by network setup. The network setup itself is made up of bringing up WiFi and obtaining IP configuration via DHCP.

A considerable amount of boot time is taken by motionEye itself (starting the Python interpreter), as well as the motion daemon. You can't do anything about this, other than using a RPi3 which is considerably faster when it comes to running a Python interpreter.

If you really want to improve your boot time, i'd recommend setting a static IP and disable some startup services that you don't need (see Services settings menu). However, don't expect to obtain more than about 20% in terms of boot time reduction.

For reference, my RPi3 with a static IP boots in less than 10 seconds (to the point where it becomes 100% usable), which is more than I could expect.
