### ISSUE TITLE
Question: Run network if detected, Networkless if no network detected?

### ISSUE THREAD

**Issue by worldburger** [ccrisan/motioneyeos#962]
I see the option:
https://github.com/ccrisan/motioneyeos/wiki/FAQ#how-can-i-run-motioneyeos-without-a-network-connection

It says "Just edit /data/etc/os.conf and set the os_networkless variable to true. Your system will skip any network-dependent services at startup."

-Does this mean it will not run the services at startup?

-Can motioneyeos run the network-dependent services but continue the boot process if you don't have an available network?

**Comment by ccrisan** [comment]
Yes, it does mean that network-dependent services will *not* be started.

Nope, you can't have it both ways. Either you want a network connection or you don't want it at all. If motionEyeOS is told to expect a network connection, it will reboot until it has one. It's like in the microcontrollers world: the system is reset whenever a serious problem is encountered.
