### ISSUE TITLE
Wireless network dont Work.

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#966]
**I can not figure this out**

While setting up my MotionEyeOs number 11, I have network issues.
- Raspberry PI 3
- No  IR-cut  camera

I set up the system where the network cable is connected and everything works fine. I set up wireless network and restart still with the network cable connected. It now works from the new static IP address, but also via the DHCP assigned address. See the picture.

When I then remove the cable and restart, I can not access MotionEye on any of the IP addresses, it is completely unavailable.

I re-connect the network cable, and restart power off power supply and power on power supply, so work all over again from both IP addresses. What am I doing wrong ?

![motioneye_network2](https://cloud.githubusercontent.com/assets/9556987/26422395/fd5dda54-40c9-11e7-8013-dd5fe3b91883.JPG)

Motioneye.log
(https://www.dropbox.com/s/oqi1ajk16ss68zq/motioneye.log?dl=0)

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
