### ISSUE TITLE
nfs for kernel support

### ISSUE THREAD

**Issue by sidealice** [ccrisan/motioneyeos#968]
when i tried "modprobe nfs" i found out that the kernel didn't support that. could you add nfs support?

I can config it under linux environment without GUI. but if lack of kernel support i can do nothing.

Thanks a lot for the useful tool.

**Comment by ccrisan** [comment]
The kernel used is that of Raspbian (assuming you're on a Raspberry PI) and I believe it supports NFS. However adding NFS support (userspace tools and config frontend) is not on the list of priorities.
