### ISSUE TITLE
Feature/Request: Two Networkinterface Support

### ISSUE THREAD

**Issue by Noxigin** [ccrisan/motioneyeos#971]
Hello everybody,

i use RPI3 with MotionEyeOS and i have two networks.
 It would be great if i could configure the first Network on eth0 an the second on wlan0 to get full access from both networks. In the current version only one interface is used.

If this is already possible i would appreciate any help otherwise it would be great if this feature comes in future.

Thanks

**Comment by bortek** [comment]
sorry not possible.
