### ISSUE TITLE
Raspberry pi Zero/Zero W installation not working

### ISSUE THREAD

**Issue by adamideas** [ccrisan/motioneyeos#972]
Trying to setup wifi settings using Raspberry 3 to establish wifi and then use on Zero. But after using SD card with image for Zero/Zero W on Raspberry 3 doesn't work (on LCD only multicolor screen). Any ideas?

**Comment by lexcyn** [comment]
Why not just use wpa_supplicant.conf to setup WiFi - I'm pretty sure the first boot loads drivers for whatever hardware it's working on which could be messing up your install.

**Comment by adamideas** [comment]
thanks, i will try, i had a problem with adding that file on sd card - permission problems.
