### ISSUE TITLE
Pi Zero W + Camera Modul V2 - Fast Network Camera Problem

### ISSUE THREAD

**Issue by Noxigin** [ccrisan/motioneyeos#974]
Hello,

i got a Raspberry Pi Zero W with the camera module v2. I installed motioneyeos (20170329) on it and everything works fine. Love it.
Now i tried to switch to the "Fast Network Camera" and i got no preview anymore. There is only a grey screen with a camera symbol.
I read a lot of threads about similar problems and i tried a new Installation, a different power supply, with and without wifi and i changed the ports. Nothing helps.

If i deactivate Fast Network Camera everything works fine again.

Can someone help me? I don't got the skills to get some logs, so if it's necessary please tell me how.

Thanks a lot

**Comment by bortek** [comment]
Please post your question on the forum page instead of opening an issue.

**Comment by ccrisan** [comment]
@Noxigin this may be due to the fact that your browser doesn't render MJPEGs or that connections on port 8081 cannot be made.

**Comment by Noxigin** [comment]
I tried with IE11. I will try with another browser. The port i have changed, so that i think that this is not the reason.
I also found a thread in the forum with Problems with static ip and no video. I also have static ip configuration. I will check this, too.

Should i open a thread in the forum or is it here okay?

Thanks bortek for the tip with the forum and thank ccrisan for your response.

**Comment by ccrisan** [comment]
The forum is always a good idea. It has a wider visibility.

**Comment by Noxigin** [comment]
ok, if the problem persits i will post it there. 

Thank for your fast support.

**Comment by Noxigin** [comment]
Firefox works! :) Sometimes it can be so easy. Thank you!
