### ISSUE TITLE
Motioneyeos completely broken on Pi2

### ISSUE THREAD

**Issue by gigawert** [ccrisan/motioneyeos#975]
Not sure if it's something on my end but I've tried the setup procedure on two different Raspberry Pis and two different microSD cards, and I can't access it via ethernet and another computer. Just not too long ago it was working for me...

**Comment by bortek** [comment]
Please test the latest on pi zero if you have one.

**Comment by gigawert** [comment]
I do not have a pi zero, sorry

**Comment by falcondan** [comment]
I tried updating my pi2 to the motionEyeOS 20170329 through the updater within Motioneye. It,broke my configuration. Plugging in a monitor showed that it wouldn't even boot up again. I was able to re-image my sd card with the instructions here: "https://github.com/ccrisan/motioneyeos/wiki/Installation" and then load a backup configuration i had from a few months ago (even though it said it wasn't successful, it seems that it was). Can you ping the address that the board has?

**Comment by gigawert** [comment]
I can't find the address in my router page because it won't even show as online in the network.

**Comment by falcondan** [comment]
Can you plug a monitor and keyboard in to see what's happening? Does the board manage to boot at all when it gets power? Does it ever take you to a command line? If it does, run "ifconfig" that will show what kind of address the board has, if any.

**Comment by gigawert** [comment]
The screen is blank when I plug it in, even after rebooting the Pi.

**Comment by falcondan** [comment]
Would it be possible to try loading another OS on the Pi? Just to verify that the board is still functional? Maybe https://www.raspberrypi.org/downloads/raspbian/  If that doesn't load, then I think it has to be either the SD cards or the Pi. The 20170329 version of MotionEyeOS definitely worked on my Pi2...After I re-imaged my card.

**Comment by gigawert** [comment]
I wrote the image to the microSD card again and it works now. Thanks anyway for your time! :+1:

**Comment by falcondan** [comment]
Glad it's working! I had to check to see which version of Win32diskimager I have installed on my Windows 10 PC. It looks like version 0.9.5. Definitely something to keep in mind, I didn't even think about that being a possible culprit.

**Comment by jasaw** [comment]
Looks like a Win32diskimager problem. Closing issue.
