### ISSUE TITLE
Tried boot motioneyeOS on Rapsberry pi 3 B , onlly red lights on

### ISSUE THREAD

**Issue by Kishiro80** [ccrisan/motioneyeos#977]
I burned the image on empty SD card using Win32DiskImager on admin mode 
and the file is there 
but when i slot it inside the board , It just wont boot 
but it works if i put NOOBS 
and can you please enligthen me about what is noob and how to use it ? 
thank you in advance !

**Comment by bortek** [comment]
you are doing something wrong pal. Google is your friend. Try different sd card, different power supplies, differnt pi boards to find out where the problem is. nothing we can help you out.

**Comment by Kishiro80** [comment]
ehehe It worked now , THanks ~
