### ISSUE TITLE
Raspberry Pi Zero W wireless entry parameters not visible?

### ISSUE THREAD

**Issue by gustamucho** [ccrisan/motioneyeos#979]
I installed motioneyeos-raspberrypi-20170329.img on my Raspberry Pi Zero W today.  The settings panel will only display the Perferences tab.  Is this right? Just a noob asking.
[meye-882c5de9.pdf](https://github.com/ccrisan/motioneyeos/files/1045805/meye-882c5de9.pdf)

**Comment by ccrisan** [comment]
Your PDF screenshot doesn't make any sense. Sorry.
