### ISSUE TITLE
WiFi reconnect

### ISSUE THREAD

**Issue by AlquistArj** [ccrisan/motioneyeos#980]
I notice the WiFi does not attempt to reconnect if the connection has dropped. If we reset the WiFi router we need to reboot all the cameras. Is there any chance the WiFi could attempt to reconnect automatically>

**Comment by ccrisan** [comment]
Hmm, it's supposed to reconnect if the connection drops. Can you repeat the procedure and attach your log files (boot, dmesg, messages)?
