### ISSUE TITLE
Central server motion and capture

### ISSUE THREAD

**Issue by timdonovanuk** [ccrisan/motioneyeos#986]
I guess I'm majorly not understanding something, but in the [central server use case]()  you lose all motion and capture capability. Why can the central server not just run motion on the stream it receives from the network cameras, and record the frames appropriately? It especially makes sense as the server could be much more powerful than the remote camera. 

Thanks.

**Comment by ccrisan** [comment]
That's exactly what the central server does.

> The server can be motionEyeOS-based (preferably running on a multicore board) or it can be a regular Linux system that runs motionEye.

You don't lose motion/capture capabilities, you just move them from individual cameras to a central server and allow individual cameras to run other stuff than motionEye.

**Comment by timdonovanuk** [comment]
Ah my apologies! I think when I tried the motion option was not visible for some reason. I must have messed something up. Maybe add "offload motion processing" as an advantage to the Usage-Scenarios.

Cheers :)
