### ISSUE TITLE
Problem with VR CAM

### ISSUE THREAD

**Issue by Lakemast** [ccrisan/motioneyeos#988]
Hello,
I want to add a camera that gives me only plain jpeg images, but the motioneyeOs says that it is
a not supported camera

![1](https://user-images.githubusercontent.com/25143692/26890891-8d75ed10-4b89-11e7-9b32-fb54b0a394b4.png)

The URL for getting plain jpeg images is: "_http://192.168.1.112/snapshot.jpg?user=admin&pwd=admin&strm=1_"

This is the camera i want to add  [VR CAM P2](http://www.juancctv.com/productShow.asp?ArtID=660)

When I put this jpeg url  "_http://192.168.1.112/snapshot.jpg?user=admin&pwd=admin&strm=1_" in my web browser, I can download the jpeg image.

I also tried to add the camera to ispy software to see if the camera was really working and it worked

![2](https://user-images.githubusercontent.com/25143692/26891200-8bf24d0c-4b8a-11e7-9bfb-5ff74ea1f2ae.png)

What am I doing wrong ?

Thanks in advance!

**Comment by ccrisan** [comment]
If it says that's not a supported network camera, then the URL you're using does not render a simple JPEG but most likely some HTML page that wraps your JPEG. Make sure to use a URL that renders the final JPEG. It helps opening the URL with your browser and playing with the DOM inspection tools to identify the URL.

**Comment by Lakemast** [comment]
Sorry, but i guess i didn't explain in a right way.

When I put this in my web browser: "_http://192.168.1.112/snapshot.jpg?user=admin&pwd=admin&strm=1_"

I got only the picture, with no html view, like this:

![1](https://user-images.githubusercontent.com/25143692/26918726-851d9d54-4c09-11e7-9436-f72344fa8856.jpg)

**Comment by ccrisan** [comment]
Hmm so the camera does not directly serve the image but offers it for download. I'm not sure if that works with motion.

**Comment by Lakemast** [comment]
Thank you ccrisan for your quick answer!
Congratulations for making this great application.
I will try another camera instead.
Thank you!
