### ISSUE TITLE
No Networking Option - User Admin - RPi2

### ISSUE THREAD

**Issue by LexPoinrOh** [ccrisan/motioneyeos#991]
I formatted and installed the May 29th RPi2.img.gz file (I'm paraphrasing).

Everything else works but there's no option to add a network. Wi-Fi dongle if you will.

I did however install the RPi1 image on another pic I have (rpi 1) and it had the networking option.

Please help.
What didI do wrong.

**Comment by ccrisan** [comment]
Can I see a screenshot of your Settings Panel? I'm particularly interested in the Network section.

**Comment by jasaw** [comment]
Closing issue due to lack of follow up.
